### ISSUE TITLE
Selecting other tools after adding text, flameshot closes abruptly

### ISSUE THREAD

**Issue by Aster89** [flameshot-org/flameshot#2489] opened 2022-03-16 06:41 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.12-arch1-1
arch: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Archlinux (up-to-date at the time of writing)

### Description

Selecting a tool like arrow or rectangle or circle after some text has been inserted results in flameshot closing abruptly.

### Steps to reproduce

1. run flameshot (however you like)
2. use tools like arrow, circle, and stuff; all works fine
3. select text tool and write down something; all works fine
4. select the arrow, circle, rectangle (and more?): flameshot closes

### Screenshots or screen recordings

![flameshot](https://user-images.githubusercontent.com/20521900/158531475-761d3d1a-31bd-4fcb-b54e-6ea9a01623ea.gif)

### System Information

1. Archlinux, always up-to-date.

<details>
    <summary> 2. <code>xrandr</code>'s output</summary>
<code>
Screen 0: minimum 320 x 200, current 2560 x 1440, maximum 16384 x 16384
eDP-1 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +  59.97    59.96    59.93  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
HDMI-1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 725mm x 428mm
   2560x1440     59.95*+  74.97  
   1920x1080     60.00    50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1280x1440     59.91  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
DP-1 disconnected (normal left inverted right x axis y axis)
HDMI-2 disconnected (normal left inverted right x axis y axis)
</code>
</details>

3. Window manager: i3, Xorg

**Comment by mmahmoudian** [comment] 2022-03-16 07:22
Thank you for filing a bug report. Unfortunately it is duplicate of all the following:

- #2283
- #2353
- #2402
- #2407
- #2429
- #2434
- #2454
- #2458


Additionally, it has been already been fixed in the main branch and you can download the latest builds from this link:

https://flameshot.org/docs/installation/development-build/

**Closed** 2022-03-16 07:23 UTC
Labels: Bug, Duplicate
