### ISSUE TITLE
CLI option to capture the currently focused window

### ISSUE THREAD

**Issue by sean-abbott** [flameshot-org/flameshot#1228] opened 2021-01-08 17:05 UTC
So, I have dual screen 4ks, so I'm almost always wanting to just screen cap the window that I'm working on. I have two related requests. Prior to flameshot, I used <alt><prtscrn> to accomplish this. (I'm coming to flameshot 'cause pinta keeps crashing)

It would be very nice if 
- There was a flameshot cli for window capture. For instance `flameshot window` that would capture the window in current focus.
- An option to open an existing picture in the flameshot editor? honestly this is mostly 'cause I can'f find a simple picture editor other than pinta, which always starts crashing on me. I get you can open old screenshots? But I'd like to just be able to open flameshot as an editor. :-)

This is a great tool! thank you so much for it!

**Comment by Qwerty-Space** [comment] 2021-01-08 20:35
It would be nice to have this in the gui too.  By just clicking on a window to achieve it, like with `slop`

**Comment by vcalvert** [comment] 2021-01-21 19:33
For the capture bits, this duplicates #334; Qwerty-Space's request is #5.

Not sure about the open-for-edit part; that seems to be a request for a new feature?

**Comment by sean-abbott** [comment] 2021-01-21 22:05
I believe it is a request for a new feature. I apologize for the dupe on the window capture one.

**Comment by borgmanJeremy** [comment] 2021-02-04 02:42
The edit an existing file part is actually a duplicate of #240 

No worries on the duplicated issues, we have large backlog that can be hard for even me to search :) Most of these comments are in other issues but just to quickly put them here:

- Agree that capturing a window would be a good feature. Might be tricky to implement fully cross platform but Qt is supposed to have a cross platform window selection API.
- Opening an existing image is a bit more complicated that it might seem. Since flameshot is always fullscreen and the edits are overlayed on the entire screenshot, we need to figure out what to do with both screenshots smaller than the current screen resolution, and images larger than the current screen resolution.


Since both of these suggestions have duplicates, I'll close this and we can carry the discussion on the original issues.

**Closed by borgmanJeremy** 2021-02-04 02:42 UTC

**Comment by KES777** [comment] 2023-06-12 07:39
https://github.com/flameshot-org/flameshot/issues/273#issuecomment-1165360717
