### ISSUE TITLE
Alternate Hot Key Screen Capture needed for windows

### ISSUE THREAD

**Issue by kmeekva** [flameshot-org/flameshot#2167] opened 2021-12-17 16:37 UTC
### Feature Description

Windows ships with snip and sketch bound to the PrtScr key.   

Flameshot is programmed to bind to that key to launch graphical screen capture interface.

But this hotkey will not work if windows is already using it.

Therefore the only way  for me to take a screen shot is to click the icon in the windows tray to activate a screen grab.

While best solution would be to allow the user to 'customize' the hot key.  I'd propose just binding both PrtScr and Alt-PrtScr -- as the Alt-PrtScr  does not conflict with any default windows keybindings.

I will create a pull request to add this simple alternative which will make flameshot imensely easier to use for windows users.

**Comment by ngocphamm** [comment] 2022-06-16 19:56
I tried Flameshot and like it, but this is what keeping me from using it, due to my nature of using a remote Windows machine using RDP from my mac. My mac keyboard just doesn't have the Print Screen key...

**Comment by umernalla** [comment] 2023-01-30 15:29
+1 to this request. 
I really would prefer to be able to choose which key I use to capture the screen - similar to GreenShot.
I actually prefer the interface of FlameShot - i.e. in situ editing - which is so much better than having to use a separate editor.
Thanks.

**Comment by mmahmoudian** [comment] 2023-10-02 14:43
I believe this is duplicate of #1341, so I close this in favor of that. If you believe these two are different, please let me know and we will discuss

**Closed** 2024-06-19 08:20 UTC
Labels: Enhancement, Windows
