### ISSUE TITLE
Wayland Arch Linux

### ISSUE THREAD

**Issue by AnthonyMahe** [flameshot-org/flameshot#3315] opened 2023-08-23 06:24 UTC
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5

### Installation Type

User repository (AUR)

### Operating System type and version

linux: 6.1.45-273-tkg-linux-lts-tkg-cfs arch: unknown

### Description

Hello,
I have a double screen, when I launch flameshot it does not recognize what is on my main screen and only takes into account my secondary screen. So I have to change the application I want to screen on my second screen.

### Steps to reproduce

1. Launch Firefox
2. Launch Flameshot
3. Don't see firefox on space selector flameshot.

### System Information

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
linux: 6.1.45-273-tkg-linux-lts-tkg-cfs
arch: unknown

**Comment by mmahmoudian** [comment] 2023-08-23 18:30
What is your Desktop Environment?

**Comment by AnthonyMahe** [comment] 2023-08-24 14:35
ArchLinux

Le mercredi 23 août 2023, Mehrad Mahmoudian ***@***.***> a
écrit :
> What is your Desktop Environment?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/proxy/W6cvuwRMtx-dg3MpjixdDxgfCb5etxvvm1BhCcIV5JinsPALlykq9fpJHHujA6FnqlA4g5UgGZr1MkcZc_3XmKKxzoAzoFpMRhmqEmg-4qJ0SErD87kMP8dBzkGEAhuS7A25qqP99RfgP3Nhb5U2gkCmq03g-a_f1FYNyPnoO8VU0PFgMMmsC6Gxx7G9kC30EVGRUv9t08LIrKu02LhgvsvbC1kVUG0sO-bbNUkGWBqxYXklig=s0-d-e1-ft#https://github.com/notifications/beacon/AY4JZNXB3JN2G63O2FB3673XWZD5LA5CNFSM6AAAAAA326JMMWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTEYIMIS.gif>Message
ID: ***@***.***>

**Comment by mmahmoudian** [comment] 2023-08-24 14:49
This is duplicate of #2075 .

This issue was fixed up stream long time ago. Out of curiosity how often do you update your Arch Linux?

**Closed** 2023-08-24 14:49 UTC
Labels: Bug, Duplicate, Upstream
