### ISSUE TITLE
Wrong GUI when using multi-monitor

### ISSUE THREAD

**Issue by lyolve** [flameshot-org/flameshot#1386] opened 2021-02-23 12:13 UTC
English is not my native language, please forgive me if the description is wrong.

![_20210223200450](https://user-images.githubusercontent.com/43743367/108841377-9a96e000-7612-11eb-8c97-a330a644d1b8.jpg)
![_20210223200502](https://user-images.githubusercontent.com/43743367/108841414-ac788300-7612-11eb-8cbf-87dcb9f8fde2.jpg)
![_20210223200440](https://user-images.githubusercontent.com/43743367/108841313-87841000-7612-11eb-911e-a2e093109945.jpg)
![_20215823075851](https://user-images.githubusercontent.com/43743367/108841612-ffead100-7612-11eb-955d-de197df0f963.png)

**Comment by lyolve** [comment] 2021-02-23 12:21
screen shot if press <kbd>Enter</kbd> after <kbd>Prt Sc</kbd>
![image](https://user-images.githubusercontent.com/43743367/108842446-41c84700-7614-11eb-92dc-b8091ca29e0c.png)

**Comment by lyolve** [comment] 2021-02-23 14:35
> Please tell us the version of flameshot you installed. And how did you install it? Via github release installer?

- Flameshot v0. 8.4
- Compiled with Qt 5.15.1

Flameshot-0.8.4-win64.msi (via github release installer)

**Comment by ZetaoYang** [comment] 2021-02-23 14:38
Can you try the latest 0.9.0.rc2?
https://github.com/flameshot-org/flameshot/releases/tag/v0.9.0.rc2

**Comment by lyolve** [comment] 2021-02-23 14:45
Still have this problem

**Comment by ZetaoYang** [comment] 2021-02-23 14:57
In my case, I have a total of two screens, the laptop's built-in 2k screen, and an external 4k monitor, and the capture widget is displayed properly. This problem should only occur when the number of monitors exceeds two.

**Comment by ZetaoYang** [comment] 2021-02-23 15:01
Can you try to change the layout of the three monitors to three consecutive horizontal rows? See if the problem recurs? Just like this figure below,
![image](https://user-images.githubusercontent.com/10769951/108862151-ebb2ce00-762a-11eb-9e15-5e9dfc1888b2.png)

**Comment by ZetaoYang** [comment] 2021-02-23 15:04
I can confirm that the problem is caused by the layout of the monitors. Currently, only monitors are continuously arranged horizontally, not staggered, otherwise the above problem will occur.

**Comment by ZetaoYang** [comment] 2021-02-23 15:08
@borgmanJeremy @mmahmoudian I think flameshot should have to detect the monitor layout and then make adjustments to prevent this from happening.

**Comment by lyolve** [comment] 2021-02-23 15:17
> Can you try to change the layout of the three monitors to three consecutive horizontal rows? See if the problem recurs? Just like this figure below,
> ![image](https://user-images.githubusercontent.com/10769951/108862151-ebb2ce00-762a-11eb-9e15-5e9dfc1888b2.png)
I have changed to horizontal rows, still have some problems (notice the change of the desktop wallpapers )
![1](https://user-images.githubusercontent.com/43743367/108863845-9972ac80-762c-11eb-93e5-caa0c6281cf4.jpg)
![2](https://user-images.githubusercontent.com/43743367/108863851-9b3c7000-762c-11eb-98f9-cf81af86e20d.jpg)

**Comment by Qbsoon** [comment] 2021-02-24 09:55
I have similar issue:
Flameshot 0.9.0
Compiled with Qt 5.15.2

I have two monitors, set like this:
<img width="248" alt="2021-02-24_10-29" src="https://user-images.githubusercontent.com/29931713/108979738-3e23d700-768b-11eb-9c6e-23a3ac053aac.png">
When I use fullscreen option of screenshot, it screenshots both screens, but if I use the 2nd option, that where I can select area for screenshot, I cannot select anything from my main monitor, I can select only area from second monitor, but second monitor somehow shows on it's right side, left half of my first monitor, and on it's left side, black screen. So I can capture only black screen or something from left half of my main monitor.

**Comment by borgmanJeremy** [comment] 2021-02-24 13:47
Seems like this is not a new issue in 0.9. I think the fix will be something similar to what is currently in progress on #1070

**Comment by Qbsoon** [comment] 2021-02-24 15:36
> Seems like this is not a new issue in 0.9. I think the fix will be something similar to what is currently in progress on #1070

True, I updated today from 0.6, but the problem was also present on 0.6

**Comment by 33Fraise33** [comment] 2021-02-25 21:09
Please see my issue over at #1397. My setup looks like this:
![image](https://user-images.githubusercontent.com/6802744/109217471-2e54e180-77b6-11eb-8b00-45cf2c081d62.png)

**Comment by connorhodes** [comment] 2021-03-18 21:48
I also have this issue. I'm on Arch Linux running  I'm running version:
```
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

On Arch Linux with spectrwm. 

When I bring up the screenshot GUI, the content of the monitors is shifted so I cannot select the first half of the first monitor as with #1389.

![2021-03-18_16-40-32](https://user-images.githubusercontent.com/64938337/111701993-a046a680-8809-11eb-8fcd-c46a065f10dd.png)


Here is my monitor layout (shown in arandr.)
![image](https://user-images.githubusercontent.com/64938337/111701880-768d7f80-8809-11eb-9756-b38906e36cbc.png)

*Note that both of my monitors are the same size and are arranged continuously in a straight line. They aren't unevenly aligned as with the examples above.*

**Comment by TiagoPrata** [comment] 2021-03-21 14:24
Same issue here.

I'm using **v0.9.0** installed by **MSI**.

_System:_
Windows 10 Pro (10.0.19042 Build 19042)

_Monitors arragement:_
![image](https://user-images.githubusercontent.com/5435108/111908201-1845e400-8a37-11eb-9ae3-da391b94dff0.png)

Image | Note
---|-----
![image](https://user-images.githubusercontent.com/5435108/111908285-665ae780-8a37-11eb-960e-eb7b7492082a.png) | _**This is right!**_ All buttons show up normally
![image](https://user-images.githubusercontent.com/5435108/111908313-812d5c00-8a37-11eb-9035-130c53b8a863.png) | **This is wrong!** I can select the area but buttons never shows up.

_Note:_
This issue doesn't happen if I arrange the monitors side-by-side:
![image](https://user-images.githubusercontent.com/5435108/111908369-bf2a8000-8a37-11eb-8623-ae16fa91f7a7.png)

**Comment by ihipop** [comment] 2021-04-16 06:09
same issue on linux  when scale and dual monitor is enabled https://github.com/flameshot-org/flameshot/issues/668 
I‘m using X instead of wayland

**Comment by tyunkinilya** [comment] 2021-05-06 20:35
I've got the same issue even with two monitors side-by-side. The problem appears when I set the second monitor as main.
![image](https://user-images.githubusercontent.com/25621391/117362105-88afa400-aec3-11eb-9e70-72e3623256a4.png)
I am using windows 10 2004 (build 10.0.19041)

**Comment by fergalmoran** [comment] 2021-05-24 10:39
Same issue with arch & XFCE/XORG - nothing particularly funky going on here..

![image](https://user-images.githubusercontent.com/309139/119335688-9d8e8480-bc84-11eb-89af-bded0cd36890.png)

**Comment by Qbsoon** [comment] 2021-06-08 16:12
Today flameshot didn't turned on with autostart, didn't want to open at all. So I downloaded latest msi from github and after installing this issue no longer occurs.

**Comment by ihipop** [comment] 2021-08-07 07:34
> same issue on linux when scale and dual monitor is enabled #668
> I‘m using X instead of wayland

When I set scale via xrandr, I have to restart  flameshot to avoid the problem,I think that it's because flameshot didn't not detect display monitor information on every screen shot start,It use the cached display monitor information on  start up, which will obsoleted if I plug in or out or change the layout of screen or set a new xrandr scale.. etc..

I suggest to  detect display monitor information on every screen shot start @fergalmoran

**Comment by borgmanJeremy** [comment] 2021-08-07 14:49
That's likely an upstream QT bug. On every capture we use the native qt functions to get the screen size, dpi, and raw image.

**Comment by ihipop** [comment] 2021-08-09 06:04
> That's likely an upstream QT bug. On every capture we use the native qt functions to get the screen size, dpi, and raw image.

Sorry for my mistake,When I set scale via xrandr, I have to restart flameshot to avoid the problem,but not work with plug in or out monitor 
 I still have wrong preview GUI layout with dual monitor/4K screen/xrandr scale

`spectacle` https://apps.kde.org/spectacle/ made with QT by kde works well with multi monitor ，so it's not  an upstream QT bug.

could you reference to  the code of `spectacle` for any answer?

**Comment by ihipop** [comment] 2021-08-09 06:08
![微信图片_20210809140757](https://user-images.githubusercontent.com/423077/128665871-e09492d5-4a69-458b-bbc8-f8974a357342.png)

```
xrandr                 
Screen 0: minimum 8 x 8, current 6720 x 2160, maximum 32767 x 32767
eDP1 connected 2880x1620+3840+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1920x1080     60.01*+  59.93  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     60.00*+  30.00  
   2560x1440     59.95  
   1920x1080     60.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

**Comment by mmahmoudian** [comment] 2021-08-09 14:17
@ihipop I believe you only have this issue when your mouse is on your small right monitor, and you will not have this issue if you have your mouse and active window on your left monitor and then take the screenshot. Can you test my hypothesis and see if it holds. Also would be nice if you can also provide the output of:

```sh
inxi --system --graphics --width 80
```

**Comment by ihipop** [comment] 2021-08-10 02:12
@mmahmoudian

Nope, my mouse is on my big left monitor when I start flameshot gui, move my mouse to  my  small right monitor makes no deference

```
inxi --system --graphics --width 80

System:
  Host: ihipop-maj Kernel: 5.10.53-1-MANJARO x86_64 bits: 64 
  Desktop: KDE Plasma 5.22.4 Distro: Manjaro Linux 
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel 
  Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo 
  Display: x11 server: X.Org 1.20.11 driver: loaded: intel 
  unloaded: modesetting resolution: 1: 2880x1620~60Hz 2: 3840x2160~60Hz 
  OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 21.1.5 
```

**Comment by kerossin** [comment] 2021-08-17 10:48
I have the same problem on openSUSE Tumbleweed KDE and only on the Wayland session, X11 works perfectly.
Flameshot v0.10.1
Compiled with Qt 5.15.2

Laptop with a 1920x1080 screen on the left and a 2560x1440 monitor on the right. If I try to take a screenshot it always opens on the monitor but it has the view of what is on the laptop screen, it doesn't matter if I launch it from being on laptop screen or the monitor.

**Comment by mmahmoudian** [comment] 2021-08-18 09:56
@kerossin I believe your issue is not related to this thread. But to be sure, would you please provide some example of what Flameshot should capture and what it really captures. Also please include the command you use (e.g `flameshot gui` or `flameshot screen` or `flameshot full`).

**Comment by fergalmoran** [comment] 2021-11-10 21:41
> Same issue with arch & XFCE/XORG - nothing particularly funky going on here..
> 
> ![image](https://user-images.githubusercontent.com/309139/119335688-9d8e8480-bc84-11eb-89af-bded0cd36890.png)

Still happening... happy to share any info maintainers might feel is relevant?
[https://imgur.com/a/CuBVmqj](url)

**Comment by mmahmoudian** [comment] 2021-11-11 06:56
@fergalmoran would you please also confirm your Flameshot version and if you are using X11 or Wayland (I don't know if Xfce has implemented Wayland or not)

**Comment by gubareve** [comment] 2021-11-11 07:10
Interestingly enough, I just discovered that my issue also happens when using `ksnip`. This makes me think that this might not be a flameshot issue. @ihipop @fergalmoran could you grab ksnip from the community repositories and see if the bug also occurs there?

**Comment by fergalmoran** [comment] 2021-11-11 09:17
@mmahmoudian 
> @fergalmoran would you please also confirm your Flameshot version and if you are using X11 or Wayland (I don't know if Xfce has implemented Wayland or not)

Sure, I am using X11 (you are correct, XFCE does not have Wayland yet) and Flameshot v0.10.1 (installed from the AUR).

@gubareve 
> Interestingly enough, I just discovered that my issue also happens when using ksnip. This makes me think that this might not be a flameshot issue. @ihipop @fergalmoran could you grab ksnip from the community repositories and see if the bug also occurs there?

Tried that, and you are correct. The behaviour in ksnip is the same.

**Comment by ihipop** [comment] 2021-11-15 02:03
> @mmahmoudian
> 
> > @fergalmoran would you please also confirm your Flameshot version and if you are using X11 or Wayland (I don't know if Xfce has implemented Wayland or not)
> 
> Sure, I am using X11 (you are correct, XFCE does not have Wayland yet) and Flameshot v0.10.1 (installed from the AUR).
> 
> @gubareve
> 
> > Interestingly enough, I just discovered that my issue also happens when using ksnip. This makes me think that this might not be a flameshot issue. @ihipop @fergalmoran could you grab ksnip from the community repositories and see if the bug also occurs there?
> 
> Tried that, and you are correct. The behaviour in ksnip is the same.

The behavior in ksnip is the same, Maybe you use the same library to capture screen? but `spectacle` also use QT and it works well??

**Comment by MirtoBusico** [comment] 2021-11-25 18:41
I have the same problem with:

- Kubuntu 20.04.3
- flameshot 0.10.2 (qt 5.12.8) installed from the deb archive for Ubuntu 20.04 ( flameshot-0.10.2-1.ubuntu-20.04.amd64.deb )
- primary monitor 4K, secondary monitor Full HD

What I see when launching flameshot

![wrong-area](https://user-images.githubusercontent.com/11090934/143488756-f7a635e6-a2eb-46f7-abf5-0abc3d07f82c.png)

What Spectacle sees

![correct-area-spectacle](https://user-images.githubusercontent.com/11090934/143488785-9d2c5ce2-31d3-46bc-9311-b243f2cd0ad5.png)

Monitors layout

![monitor-layout](https://user-images.githubusercontent.com/11090934/143488910-7e9d9dec-4766-4128-826a-25b498a6e28a.png)

Any hint?

**Comment by MirtoBusico** [comment] 2021-11-30 11:14
@ihipop following the thread in issue  on ksnip #276  the solution is disable scaling. Setting global scale to 100% solves the problem

![scaling](https://user-images.githubusercontent.com/11090934/144037455-f3bcdba1-9172-4caf-963b-178e5a51bc6a.png)

**Comment by ihipop** [comment] 2021-11-30 14:16
@MirtoBusico  I'm using a 4K Monitor,Which make it necessary to have a sacled UI
If I use 100% scale On a 4K Monitor,why should I buy it?

**Comment by MirtoBusico** [comment] 2021-11-30 17:57
@ihipop 
Well, I also need to scale the UI; but, until the flameshot/ksnip bug is resolved, I'll use 16pt charachters everywere and use flameshot.
I'm writing manuals that need screenshots, so balancing a good UI with the possibility to use flameshot, I prefer the last

Obviously I'm  waiting for the bug correction

**Comment by gubareve** [comment] 2021-12-01 00:33
It seems that flameshot is using the _scaled_ resolution for creating the GUI. Would it be possible to add something to flameshot that allows you to hardcode your resolution? That seems like it would fix the problem.

**Comment by gubareve** [comment] 2021-12-01 00:34
And to further @ihipop's point, I have a 4k monitor meaning that I can't use 100% scale without a magnifying glass. So sadly, just changing the scale to 100% wont be a solution.

**Comment by borgmanJeremy** [comment] 2021-12-01 00:42
Until someone solves this (which I wrote to minimally produce the bug) , this will not be solved.  https://forum.qt.io/topic/121111/position-of-widget-with-fractional-scaling

This is a well known issue, I'm not holding out on some magic solution, I have no idea how to solve it.

Since we identified this is another bug with a root cause of fractional scaling I will close this one as duplicate.

**Closed** 2021-12-01 00:42 UTC
Labels: Bug

**Comment by borgmanJeremy** [comment] 2021-12-01 00:43
#564 is the original

**Comment by ihipop** [comment] 2021-12-01 01:36
>Until someone solves this (which I wrote to minimally produce the bug) , this will not be solved. https://forum.qt.io/topic/121111/position-of-widget-with-fractional-scaling




But I'm not using fractional scaling,I'm using 200% scale

**Comment by borgmanJeremy** [comment] 2021-12-01 02:33
Yeah the issue occurs whenever the scaling is not 100%

**Comment by adrianbuck** [comment] 2021-12-02 14:39
I am having the same problem as everyone else with three monitors, each at a resolution of 2560x1440 and fractional scaling set to 125% on Kubuntu 20.04.
Flameshot doesn't work correctly when using two or three monitors but Spectacle does when I only use 2 monitors. Because I need three monitors, I installed the latest KDE neon on a seperate partition for testing. Flameshot did not work properly, as excpected. But Spectacle (v21.08.3) did with two and three monitors at fractional scaling set to 125%. 
Back on Kubuntu 20.04, I installed the latest Spectacle version (21.08.03) and it behaved properly with two and three monitors, each at the aforementioned resolution and fractional scaling set to 125%.

I hope that this can be of help to developers and users as well.

**Comment by gubareve** [comment] 2021-12-05 20:22
@borgmanJeremy Would it be possible to implement something like [this](https://github.com/ksnip/ksnip/issues/276#issuecomment-986057884). This effectively solves the issue, no qt bugfix necessary.

**Comment by borgmanJeremy** [comment] 2021-12-05 22:45
Given that it's unlikely we find a true fix, yes I would accept this.

**Comment by ihipop** [comment] 2021-12-06 02:58
disable `QT_AUTO_SCREEN_SCALE_FACTOR` and `QT_SCREEN_SCALE_FACTORS` only for `flameshot` is the simplest workaround

see: https://github.com/ksnip/ksnip/issues/276#issuecomment-986390341

**Comment by MirtoBusico** [comment] 2021-12-06 08:33
@borgmanJeremy please can you give me the instructions on how to disable QT_AUTO_SCREEN_SCALE_FACTOR and QT_SCREEN_SCALE_FACTORS only for flameshot?

**Comment by ihipop** [comment] 2021-12-06 08:39
> @borgmanJeremy please can you give me the instructions on how to disable QT_AUTO_SCREEN_SCALE_FACTOR and QT_SCREEN_SCALE_FACTORS only for flameshot?

1. make sure you have closed all `flameshot` instance
if not,  try run `killall flameshot` if you're not using a Appimage

1. run `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="" flameshot`

1. if you got a very tiny UI, set a fixed font DPI which fit your scale level, if not , ignore this one

**Comment by MirtoBusico** [comment] 2021-12-06 10:39
With your command line flameshot works correctly
<img width="1913" alt="flameshot-works" src="https://user-images.githubusercontent.com/11090934/144831939-959f644e-2060-4e69-b680-1812efbfdc1f.png">

**Comment by mmahmoudian** [comment] 2021-12-11 10:25
@borgmanJeremy seems in ksnip they solved this situation: https://github.com/ksnip/ksnip/issues/276#issuecomment-989497064

Considering that both softwares are C++ QT and facing the same issue, the workaround should be similar enough I assume

**Comment by borgmanJeremy** [comment] 2021-12-11 13:38
No they just implemented a work around that lets users hardcode a Manual offset. On another thread i mentioned I'm good to add this workaround since we are not close at all to a true fix.

**Comment by mmahmoudian** [comment] 2021-12-11 13:54
@borgmanJeremy considering that the 4k monitors are getting more and more adopted, and more people will end up using fractional scaling, I think it worth the effort to implement a "calibration" mechanism. The following is my suggestion:

For example we display an overlay and ask the user to scroll mouse while hovering on different monitors to align certain calibration lines. For instance assume we use the same overlay as `flameshot gui` but instead of being able to select an area, it has some lines crossing each other at the center basically a combination of + and x (a star that the lines go to infinity).

This is practically the same as the workaround you mentioned but in a more user-friendly way. Typically users use the same monitor setup, so we can save the offsets (or perhaps coefficients) in the config file at a designated section.

**Comment by borgmanJeremy** [comment] 2021-12-11 14:19
I really like that idea. Can you open a new issue with that and we can track it that way?

**Comment by mfzha** [comment] 2022-02-04 11:45
@borgmanJeremy I'm looking at the commit which fixed this issue for KSnip, https://github.com/ksnip/ksnip/commit/33e80dff89a2233aa3d2ca0f8cb091cd37c05e77?diff=split, and I don't see the reference to letting users hardcode a manual offset. Am I just blind, or can you clarify what you meant?

Also, since `QT_SCREEN_SCALE_FACTORS="" flameshot gui` is the easiest workaround to these fractional scaling issues, would you accept that fix instead?

**Comment by dkasak** [comment] 2022-04-05 13:06
I have a similar issue, but just wanted to note that `QT_SCREEN_SCALE_FACTORS="" flameshot gui` doesn't do it for me, but `QT_AUTO_SCREEN_SCALE_FACTOR=0 flameshot` does. So if we're adding this, can we please add both env vars?

**Comment by LEONIDAS-0117** [comment] 2022-05-15 00:16
For those who have a KDE desktop environment, i have found a quick and easy fix until this is resolve.

First go to `Setting` > `Shortcuts` and remove any shortcuts that are assigned to either Spectacle or Flameshot for screen shooting, in my case `PrintScreen`.

Next you need to [add a custom keyboard shortcut](https://docs.kde.org/trunk5/en/khotkeys/kcontrol/khotkeys/manage.html#manage-add-shortcut), you can do this by going to:
`Custom Keyboard Shortcuts` > `Edit` > `New` >`Global Shortcut` > `Command/URL`
Give the new Shortcut the name Flameshot.

Now we need to edit the shortcut, you can leave the comment tab empty or add a description.

For the Trigger tab add the key combination that you want Flameshot to use, in my case `PrintScreen`.

Finally for the Action tab you need to enter:
`env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="" flameshot gui`
Hit apply to save the changes.

If someone fins a better way to execute the command please let me know.

NOTE: for the final step you don't need to use both `QT_AUTO_SCREEN_SCALE_FACTOR=0` and `QT_SCREEN_SCALE_FACTORS=""`, you can use one or both depending on what works for you.

**Comment by pourmand1376** [comment] 2022-08-30 08:17
For those using KDE, I have a simple fix to this solution. 

Just Go to `System Settings` > `Autostart` > Flameshot > Properties. 

![image](https://user-images.githubusercontent.com/32064808/187386283-7a67eab1-619c-45c8-b18e-a36a743d74ec.png)

Simply add 
```bash
env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS=""
```
to `command` and you're done.

**Comment by AysadKozanoglu** [comment] 2022-10-25 21:33
i installed  flameshot via apt package manager
```
sudo apt install flameshot -y

# flameshot -v
# Flameshot v11.0.0 (11.0.0-2 Debian)
# Compiled with Qt 5.15.2

```

i configured a global keyboard shortcut as shift+ctrl+S for following command with needed env  parameter:  
 ```env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="" flameshot gui ```

my system information
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
Desktop: Budgie
```

@pourmand1376  @LEONIDAS-0117 @ihipop thank you

**Comment by ppwwyyxx** [comment] 2022-11-14 10:04
Given that 4k monitors are more and more popular and this issue still exists, can maintainers consider enable the above workaround as a default option whenever users have scaling+multi-monitor?

Yes, it might cause weird font size to someone (although on my machine it looks fine). But without the workaround, flameshot is almost unusable.

**Comment by floatnz** [comment] 2023-03-01 05:37
Same issue here, non-linear 3 monitor layout.

Recent fresh install of Ubuntu 22.10 and it was working perfectly.

Then a few weeks later, this issue is happening.

```
$ flameshot --version
Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4
```

**Comment by MasterGroosha** [comment] 2023-04-23 17:24
@AysadKozanoglu Thank you SO MUCH! Your comment helped me to fix flameshot issue on Manjaro KDE

**Comment by Noir-Road** [comment] 2024-01-20 22:54
@LEONIDAS-0117 Thanks a lot.
