### ISSUE TITLE
"Save to Clipboard" doesn't work if "Close after capture" is enabled

### ISSUE THREAD

**Issue by darrSonik** [flameshot-org/flameshot#1140] opened 2020-11-05 05:37 UTC
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
If I enable _Close after capture_ in Flameshot configuration, _Save to clipboard_ feature in GUI mode doesn't work. _Save to disk_ works though.

**Expected behaviour**
If I enable _Close after capture_ in Flameshot configuration, _Save to clipboard_ feature in GUI mode should work.

**System Information**
OS: Arch Linux
Kernel: Linux 5.9.3
Display Server: X.org
DE: none
WM: bspwm

**Comment by SamantazFox** [comment] 2020-11-05 14:34
Looks like a duplicate of #1035

**Comment by darrSonik** [comment] 2020-11-05 14:40
@SamantazFox , Kind of, yes. But in #1035, the issue is present in Fedora 31, and it uses xwayland as its display server afaik. I'm using Xorg.
Wayland's underlying infrastructure is different from Xorg.

**Comment by SamantazFox** [comment] 2020-11-05 16:20
Yeah, It's flagged as "wayland" but some comments talk about X.org too.

**Comment by borgmanJeremy** [comment] 2020-11-05 23:37
I am going to close this as we are removing the close after capture feature. Its removed on master branch and will be backported to a 0.8.x release shortly.

**Closed by borgmanJeremy** 2020-11-05 23:37 UTC
