### ISSUE TITLE
Custom action button

### ISSUE THREAD

**Issue by ww7** [flameshot-org/flameshot#2555] opened 2022-04-21 17:12 UTC
### Feature Description

Unloading to Imgur not suitable for every case.
I'm request a button what can be assigned to any script/command, what allow making possible many usable things, as upload screenshot to any server/service or any other action what can be needed.

Currently, it can be implemented via CLI, but CLI not allow making Pins, just one screenshot.
Such buttons much more easy and straightforward.

**Comment by mmahmoudian** [comment] 2022-04-22 04:36
Duplicate of #2529

We are actively exploring and working on a plugin system. The detailed proposal and discussions can be found in the #2529

**Closed** 2022-04-22 04:37 UTC
Labels: Enhancement
