### ISSUE TITLE
[0.8 Beta] ALT+Tab can deactivate shortcuts

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#921] opened 2020-09-14 16:34 UTC
**Flameshot version**
0.8 Beta testing, compiled from source

**Describe the bug**
I don't know how realistic this bug is, but I noticed it during my tests. For it to work it is important that there is an open window on the screen (e.g. browser or terminal).

Click on the Flameshot tray icon to take a screenshot and then press ALT+Tab. Nothing happens visually Flameshot stays in the foreground and can still be used normally, but the shortcuts don't work anymore!
Editing the screenshot can't be stopped by pressing ESC and if the user has deactivated the Close button, he won't be able to get out of it and has to use a virtual console or in the worst case reset the system.

**System Information**
Arch Linux, Xfce, Xorg

**Comment by XMoon** [comment] 2020-09-15 13:18
after I write the bug report I found it already exist. so I paste here for not duplicate~ :joy: 

**Flameshot version**
Flameshot v0.8.0
r668.ab65c22-1

**Describe the bug**
when use `flameshot gui` (I set a shortcut for global system) to capture a screenshot, sometimes I can't use flameshot's hotkey, like ctrl + c to save the screenshot to clipboard or esc to escape from flameshot. And the keys I press passthrough to the program that running behind.

**To Reproduce**
start a flameshot capture and than press alt + tab. now you can't use the flameshot hotkey

**Expected behavior**
maybe disable alt+tab when active flameshot ?

**System Information**

Arch Linux @5.8.8-arch1-1 
GNOME Shell 3.36.6 on Wayland

**Comment by borgmanJeremy** [comment] 2020-09-21 15:08
duplicate of #133

**Closed by borgmanJeremy** 2020-09-21 15:08 UTC
Labels: Bug, Help Wanted, Needs Investigation
