### ISSUE TITLE
Use command without desktop entry to open a screenshot

### ISSUE THREAD

**Issue by LordMZTE** [flameshot-org/flameshot#3138] opened 2023-03-19 18:41 UTC
### Feature Description

Currently, the open dialog only shows desktop entries and does not allow entering arbitrary commands. I think it would be good if you could enter a command in the search bar (or somewhere else) and hit enter to have Flameshot run that without the need of a desktop entry.

**Comment by mmahmoudian** [comment] 2023-03-20 06:59
This sounds like a duplicate of #3137. So I'm going to close it

**Closed by mmahmoudian** 2023-03-20 06:59 UTC
Labels: Enhancement

**Comment by LordMZTE** [comment] 2023-03-20 08:46
I'm not sure it's necessarily a duplicate. #3137 suggests adding a default option for this, while this issue is about using programs without a desktop entry.

**Comment by mmahmoudian** [comment] 2023-03-20 16:31
By "desktop entry" do you mean by a `*.desktop` file?

**Comment by LordMZTE** [comment] 2023-03-20 16:36
Yes. Flameshot doesn't seem to allow opening with applications that don't have one.

**Comment by mmahmoudian** [comment] 2023-03-20 19:42
@LordMZTE that's the standard of freedesktop:

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

Every GUI application is expected to have a .desktop file. If something does not have .desktop file it means there is no specification on how to pass data to it. I am strongly against showing everything in $PATH to user due to this reason. I don't know any other GUI tool that is accepting things that does not have .desktop file. I believe this needs way more convincing argument as it has clear flaws.

I will keep this closed until we have a clear definitions. But for the sake of the argument, I'm going to tag few of the devs here to hear their opinions on this matter:

@ZetaoYang @veracioux @hosiet

**Comment by danielkrajnik** [comment] 2023-06-16 20:40
[sxiv](https://github.com/xyb3rt/sxiv) is a `suckless` image viewer without a .deskop entry by default. Is it possible to confiigure flameshot to use it?

**Comment by veracioux** [comment] 2023-09-14 15:51
@danielkrajnik Requiring a desktop file is according to my understanding pretty standard behavior for use cases like this. And I agree with @mmahmoudian that not all commands should be exposed in "Open with".

**Comment by mmahmoudian** [comment] 2023-09-17 04:43
@danielkrajnik 
> sxiv is a suckless image viewer without a .deskop entry by default. Is it possible to configure flameshot to use it?

Well, if you are a suckless user you should be very comfortable with patching, so it is not hard to patch the makefile and create a .desktop file before `make && make install`. These said, sxiv is dead. Last released version (v26) was released 3.7 years ago, and the [main git repo](https://github.com/xyb3rt/sxiv) was archived 9 months ago. As [suggested by suckless people](https://suckless.org/rocks/), try using things like `imv` (or `pqiv`).

> It sucks having to write something like this below just because flameshot is being special 

Well, suckless tool also suck, but "less". So it seems everything sucks! Also, following a standard *might* suck, but at least it is up to a standard. I suggest reading [my previous comment] (https://github.com/flameshot-org/flameshot/issues/3138#issuecomment-1476832205) again.
