### ISSUE TITLE
Flameshot isn't copying to clipboard

### ISSUE THREAD

**Issue by metruzanca** [flameshot-org/flameshot#1840] opened 2021-08-23 23:49 UTC
**Flameshot version**
0.10.1

**Describe the bug**
After selecting an area, ctrl+c or clicking the copy icon. Flameshot is telling me that something is being copied to clipboard but running `xclip -sel clip -o -t image/png` shows that nothinb was added to the clipboard.

EDIT: seems like disabling `useJpgForClipboard` fixes the issue, which is quite strange. Is that option bugged?

**Expected behavior**
Should copy to clipboard.

**System Information**
Arch w/ kernel 5.13.12-arch1-1 
Running KDE

**Comment by veracioux** [comment] 2021-08-24 00:08
@metruzanca Perhaps the issue was that you were using `-t image/png` while the output was in jpg format?

**Comment by metruzanca** [comment] 2021-08-24 04:48
@veracioux Ah, yeah thats a dumb missight on my part.

Also the actual reason I made this issue (*which probably should have been mentioned, sorry*) was that for some reason screenshots copied to clipboard with `useJpgForClipboard` weren't pastable in other apps e.g. signal-desktop or discord for some reason. This isn't an issue with those apps as if I copy [this jpeg](https://onlinejpgtools.com/images/examples-onlinejpgtools/random-grid.jpg) from my browser it pastes just fine.

I don't know enough about jpegs to even guess why this might be the case. For me `useJpgForClipboard`doesn't seem to work as expected.

**Comment by mmahmoudian** [comment] 2021-08-24 05:23
Either a duplicate of #1738 or very much related to it (similar issue with pasting in Discord). The difference I see is that in this thread because of xclip the user have Xorg but in the other one they have Wayland.

**Comment by mmahmoudian** [comment] 2021-08-24 05:36
@metruzanca considering you [other comment](https://github.com/flameshot-org/flameshot/issues/1121#issuecomment-904203971), would you please check if you are on Xorg or Wayland? If you don't know how, please visit [here](https://flameshot.org/guide/issue-reporting/)

**Comment by metruzanca** [comment] 2021-08-24 07:32
@mmahmoudian I'm using X version 1.20.13 & plasmashell version 5.22.4

**Comment by metruzanca** [comment] 2021-08-24 07:34
To clarify, my response from earlier `-t image/jpeg` does indeed show that content was added to che clipboard, but other apps don't seem to recognize it as valid for pasting images.

**Comment by Horuyuki** [comment] 2021-08-28 00:31
> Either a duplicate of #1738 or very much related to it (similar issue with pasting in Discord). The difference I see is that in this thread because of xclip the user have Xorg but in the other one they have Wayland.

So to this problem.

I actually posted system information with screen shot showing it is X11

I don't know why it is labeled as wayland but whatever.

Like OP said, turning formats to PNG made it work again. (when pasting into apps like discord)

**Comment by sitepodmatt** [comment] 2021-08-28 09:32
I had to turn it JPG then restart it and then back to PNG, it was originally on PNG and was broke at that point. perhaps some setting writer has changed?

**Comment by mmahmoudian** [comment] 2021-08-28 10:42
I think this is highly related to #1738 as @Horuyuki pointed out as well

**Comment by veracioux** [comment] 2021-08-28 16:18
Disclaimer: the following applies to my system, YMMV.

I have done a fair bit of testing and looked at other issues and I have concluded that there is no reason to believe there is a clipboard bug in flameshot. When "Use JPG format for clipboard" is disabled, the clipboard works in basically every app I tested. This is because in that case the image is copied in a bunch of formats. If the option is enabled, the output is in `image/jpeg` and it pastes just fine in GIMP. The problem is that other applications do not accept that format.

On my system it is something akin to https://github.com/flameshot-org/flameshot/issues/1738#issuecomment-884778610, although not completely identical. This is probably because we don't have the same MIME formats installed.

@metruzanca
> This isn't an issue with those apps as if I copy [this jpeg](https://onlinejpgtools.com/images/examples-onlinejpgtools/random-grid.jpg) from my browser it pastes just fine.

The fact that the format of the image is jpeg does not mean that your browser copies it to the clipboard in that format. For example on my machine using firefox, it copies it in a bunch of formats. Run `xclip -sel clip -o -t TARGETS` to check.

**My system:**
Arch Linux w/ kernel 5.13.12-arch1-1
i3wm (X11)

> It's doesn't work for me too. In particular, in google chrome, Examples pasteboard.co doesn't detect images from the clipboard. vk.com detect like text

Is that with `useJpgForClipboard` enabled or disabled?

**Comment by metruzanca** [comment] 2021-08-28 21:48
@veracioux 
> The fact that the format of the image is jpeg does not mean that your browser copies it to the clipboard in that format. For example on my machine using firefox, it copies it in a bunch of formats. Run xclip -sel clip -o -t TARGETS to check.

I went ahead and tried this on my machine too and I can confirm this works for me as well.

Interesting, I was not aware that the clipboard worked like this. (*infact, now I'm pretty sure the clipboard works nothing like I expected*)

**Comment by Optimoos** [comment] 2021-08-29 05:26
The X11 clipboard can be a peculiar beast. Flameshot has been working fine for me for some time, but I'd struggled to make it function initially and suddenly those issues re-appeared this week. When I found this thread I thought it was describing exactly what I was experiencing, but unfortunately I didn't have Use JPG enabled and enabling it and disabling it didn't change anything. However, the xclip command @veracioux provided above along with the link to #1738 provided some insight - I was not seeing any image data in the clipboard at all after a clip.

At this point I glanced over at copyq and saw the test images I'd been gathering had clearly been making it to the clipboard, and then I found the culprit - there was a text entry in the clipboard which refused to leave - ironically, the command from the page linked above to confirm whether you're using X11 or Wayland. I thought I had nailed it, as the text was still selected on the webpage and because of how the X11 clipboard works I figured that was the cause, but after clearing that selection the behavior didn't improve. So I started closing windows until copyq could successfully move an image to the clipboard, and it wasn't until I'd closed all my terminals that things started working.

Unfortunately, having pinned down the issue in this case, I've not been able to reproduce the issue. Grabbing that same text and pasting it into a terminal again does not get stuck as it did the last time around. Hopefully this is helpful to others trying to pin down this issue.

Arch Linux with kernel 5.13.13-arch1-1
AwesomeWM on X11
CopyQ 4.1.0
Flameshot 0.10.1
Firefox 91.0.2
Terminology 1.9.0

**Comment by mmahmoudian** [comment] 2021-08-29 09:16
@Optimoos would you please also specify how you have installed Flameshot and also right-click on the tray icon of Flameshot, click on About and then the copy button and the bottom of the window and paste the content here (I'm interested in the git hash that is in the version number as in rolling release distros v0.10.1 can mean anything from any commit after that tag in git).

Also thank you for investigating this throughly and writing the process here. Highly appreciated 👍🏼

**Comment by Optimoos** [comment] 2021-08-29 09:48
Using the package in the community repository - https://archlinux.org/packages/?name=flameshot

Currently have 0.10.1-1 installed.

There doesn't appear to be a git hash on the about screen: 
![image](https://user-images.githubusercontent.com/1445030/131246163-d01967c0-04c7-433b-b68b-2ea9af54a020.png)

**Comment by mmahmoudian** [comment] 2021-08-29 09:50
@Optimoos cool, because if you installed through AUR it would have the git hash in the parentheses instead of `(-)`.

**Comment by gaduaxe** [comment] 2021-09-04 09:23
I got same issue (Windows 10, latest flameshot...)

**Comment by alexfornuto** [comment] 2021-09-09 20:53
This issue started recently on my system as well:

```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
```

I was using the latest deb package, 0.3.x, which did not have the option to choose format. I upgraded to the 0.10 flatpak (which causes other problems not finding `flameshot` in the CLI), and switched the format back and forth between jpg and png, with no resolution.

**Comment by mmahmoudian** [comment] 2021-09-09 21:01
I believe this is related to #1864

**Comment by alexfornuto** [comment] 2021-09-09 21:05
I just tested, and yes it works in FF. I'll follow that thread for resolution, thanks.

**Comment by mattbdc** [comment] 2021-09-10 09:36
Can confirm at the times when broke it does continue to work in Firefox. Random guess, chrome has become more picky about clipboard contents.

**Comment by mattbdc** [comment] 2021-09-10 09:38
https://bugs.chromium.org/p/chromium/issues/detail?id=1247919&q=clipboard&can=2

**Comment by mattbdc** [comment] 2021-09-10 09:42
It's hard to say if this is indeed a shortterm reliable workaround but as the developers are talking about Ozone here, I ensured screenshots into Chrome from flameshot were broke, opened chrome://flags search ozone, disabled ozone, fully closed and restart chrome (careful if you have chrome to run in background - default setting iirc) and now flameshot is working fine (no restart of flameshot). ymmv

**Comment by mmahmoudian** [comment] 2021-09-10 09:45
@mattbdc interesting. Thanks for digging into this. This an alarming change in Chrome imho!

**Comment by borgmanJeremy** [comment] 2021-09-14 01:55
So if I am following all this, its an upstream chromium issue?

**Comment by mattbdc** [comment] 2021-09-14 07:16
I think it's best to wait until others confirm that disabling ozone works

**Comment by alexfornuto** [comment] 2021-09-14 14:58
Disabling Ozone fixed the issue for me on Pop_OS and Google Chrome 93.0.4577.63.
![image](https://user-images.githubusercontent.com/2349184/133281744-dac287c7-a880-4164-b6af-c2710437cce6.png)

**Comment by Kamillaova** [comment] 2021-09-24 16:03
> It's hard to say if this is indeed a shortterm reliable workaround but as the developers are talking about Ozone here, I ensured screenshots into Chrome from flameshot were broke, opened chrome://flags search ozone, disabled ozone, fully closed and restart chrome (careful if you have chrome to run in background - default setting iirc) and now flameshot is working fine (no restart of flameshot). ymmv

Hmm, but since 95 version ozone cannot be disabled, any ideas?

**Comment by Kamillaova** [comment] 2021-09-24 16:30
> > It's hard to say if this is indeed a shortterm reliable workaround but as the developers are talking about Ozone here, I ensured screenshots into Chrome from flameshot were broke, opened chrome://flags search ozone, disabled ozone, fully closed and restart chrome (careful if you have chrome to run in background - default setting iirc) and now flameshot is working fine (no restart of flameshot). ymmv
> 
> Hmm, but since 95 version ozone cannot be disabled, any ideas?

quick fix (i3wm): 
bindsym Print exec --no-startup-id flameshot gui -r | xclip -selection clipboard -t image/png

**Comment by Tealk** [comment] 2021-11-01 21:56
I have the same problem, I can't paste the images anywhere when I switch to jpg, but when I try `xclip -sel clip -o -t image/jpeg` then I get an output.

**Comment by mmahmoudian** [comment] 2021-11-02 05:48
@Tealk would you please specify the "anywhere". Have you only tried Chrome or you have also tried Firefox or Inkscape or Gimp? Also please provide your system info (operating system, Flameshot version, ...)

**Comment by Tealk** [comment] 2021-11-02 07:57
@mmahmoudian I tested Firefox, various chat programs(Threema, Signal, Guilded) and the [Gnome clipboard](https://extensions.gnome.org/extension/779/clipboard-indicator/).

**Comment by mmahmoudian** [comment] 2021-11-02 14:04
@Tealk and how about your Flameshot and operating system?

**Comment by Tealk** [comment] 2021-11-02 16:03
Kernel: 5.13.19-2-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: GNOME 40.5 tk: GTK 3.24.30

**Comment by mmahmoudian** [comment] 2021-11-02 16:15
@Tealk and Flameshot version please (right-click on the icon > About > copy)

**Comment by luisalvarado** [comment] 2022-01-14 00:10
If this helps, the moment I unchecked the JPG option it worked. The following image is from flameshot by pasting on Google Chrome directly after copying it

![image](https://user-images.githubusercontent.com/29236/149428669-d1b74e06-b970-4121-b926-550f7e5c0d09.png)

**Comment by jerry1970** [comment] 2022-01-25 12:30
Using Xubuntu 20, Flameshot v11.0.0 () compiled with Qt 5.15.3. Nothing is copied to the clipboard. Using default PNG or JPG makes no difference: trying to paste into Gimp gives nothing (Gimp says no image is on the clipboard).
I am using the Snappy edition of Flameshot, if that makes any difference.
Any solution would be greatly appreciated!

**Comment by borgmanJeremy** [comment] 2022-01-25 14:34
@jerry1970 I justed tested in a clean VM with the snap and it works fine.
![xubuntu](https://user-images.githubusercontent.com/46930769/150996619-2d346ca5-97da-4b3d-b8f7-9914f884cb1d.gif)

**Comment by borgmanJeremy** [comment] 2022-01-25 16:12
You might be able to run it from the CLI and see if there are any warnings. But if that doesn't show anything you will either need to find a step by step procedure to trigger the bug that I can replicate or work with your distro maintainers.

**Comment by jerry1970** [comment] 2022-01-25 16:19
Thanks for the feedback. I hope this will help then:

> $ flameshot full --clipboard
> 
> Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.345\" (uid=1000 pid=97743 comm=\"/snap/flameshot/180/usr/local/bin/flameshot full -\" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=7377 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.345\" (uid=1000 pid=97743 comm=\"/snap/flameshot/180/usr/local/bin/flameshot full -\" label=\"snap.flameshot.flameshot (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=7377 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"

**Comment by borgmanJeremy** [comment] 2022-01-25 16:26
Im looking into what causes that error, but it is not the cause of the clipboard issue. I see these errors as well.

**Comment by loxK** [comment] 2022-02-13 03:52
My experience, for what is worth.

I tried Wayland on Nvidia. So I added `GRUB_CMDLINE_LINUX="nvidia-drm.modeset=1"` to grub. Flameshot was so messy on Wayland (as reported by somebody else here: #2418) that I went back to X11. After then, copying screenshots to clipboard wasn't working anymore. I removed `nvidia-drm.modeset=1` from grub, updated grub and rebooted, and it is now working again.

Ubuntu 21.10
Flameshot v11.0.0 (from Snap)
Nvidia proprietary drivers (v510)

**Comment by adam-op** [comment] 2022-07-28 11:33
Hi @loxK,

would you be so kind to explain for me and future readers how to remove nvidia-drm.modeset=1 from grub and update grub?
I know how to reboot :) 

thank you

ps i am on Ubuntu 22.04 and i came across the disable Wayland already in another thread. just to give my 10 cents:
how to disable Wayland?

    Disbled Wayland by uncommenting WaylandEnable=false in the /etc/gdm3/custom.conf
    Add QT_QPA_PLATFORM=xcb in /etc/environment
    Check whether you are on Wayland or Xorg using:    echo $XDG_SESSION_TYPE

**Comment by UltiRequiem** [comment] 2023-01-18 22:11
Could we close this issue?

**Comment by mmahmoudian** [comment] 2023-01-19 15:01
Considering the half a year inactivity and lack of reproducibility in a clean VM, I will close this. Please comment if this is not related to nvidia thing that is mentioned three comments before.

**Closed by mmahmoudian** 2023-01-19 15:01 UTC
Labels: Unconfirmed Bug

**Comment by Ariandr** [comment] 2024-09-15 10:43
> @veracioux Ah, yeah thats a dumb missight on my part.
> 
> Also the actual reason I made this issue (_which probably should have been mentioned, sorry_) was that for some reason screenshots copied to clipboard with `useJpgForClipboard` weren't pastable in other apps e.g. signal-desktop or discord for some reason. This isn't an issue with those apps as if I copy [this jpeg](https://onlinejpgtools.com/images/examples-onlinejpgtools/random-grid.jpg) from my browser it pastes just fine.
> 
> I don't know enough about jpegs to even guess why this might be the case. For me `useJpgForClipboard`doesn't seem to work as expected.

I have the same issue on Mac still
