### ISSUE TITLE
After high resolution zoom 200%, the screenshot will show an error

### ISSUE THREAD

**Issue by skiychan** [flameshot-org/flameshot#1149] opened 2020-11-10 08:13 UTC
**Flameshot version**
> Flameshot v0.8.5
> Compiled with Qt 5.15.1

**Describe the bug**
> 200% scale
![2020-11-10 16-04-47 的屏幕截图](https://user-images.githubusercontent.com/24283064/98646562-8209ff00-236e-11eb-9e1d-a90326503ccb.png)
> 100% scale
![2020-11-10 16-05-53 的屏幕截图](https://user-images.githubusercontent.com/24283064/98646662-a2d25480-236e-11eb-9dbc-e7ba826b0c79.png)
> Disable Setting
![image](https://user-images.githubusercontent.com/24283064/98646765-cf866c00-236e-11eb-8773-1d41766a6555.png)

**To Reproduce**
Set mode to 2560 x 1600, scale 200%.
Run ```flameshot gui``` at terminal.

**Expected behavior**
The screenshot range is the entire screen.

**System Information**
Fedora release 33

**Comment by borgmanJeremy** [comment] 2020-11-12 13:50
This is a duplicate of the fractional scaling bug so I will close it. #748 #564

Thanks for reporting, this is proving to be a tricky issue that is taking some time to solve.

**Closed by borgmanJeremy** 2020-11-12 13:50 UTC
