### ISSUE TITLE
Tray Icon is invisible in PopOS

### ISSUE THREAD

**Issue by bautrey37** [flameshot-org/flameshot#1554] opened 2021-04-12 22:12 UTC
**Flameshot version**
v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
![flameshot-bug-tray-icon](https://user-images.githubusercontent.com/3743560/114469332-98560880-9bf5-11eb-9394-a88f8b7b6ef1.png)
The tray icon does not appear at the top. The setting is enabled and just a blank space appears where the icon should be. 

**To Reproduce**
Install Flameshot on PopOS

**Expected behavior**
the flameshot tray icon should appear

**System Information**
System:
  Host: pop-os Kernel: 5.11.0-7612-generic x86_64 bits: 64 
  Desktop: Gnome 3.36.7 Distro: Pop!_OS 20.04 LTS 
Graphics:
  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
  Device-2: NVIDIA TU106M [GeForce RTX 2070 Mobile] driver: nvidia v: 460.67 
  Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
  unloaded: fbdev,nouveau,vesa resolution: 3440x1440~60Hz, 1920x1080~144Hz 
  OpenGL: renderer: GeForce RTX 2070 with Max-Q Design/PCIe/SSE2 
  v: 4.6.0 NVIDIA 460.67

loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value

x11

**Comment by borgmanJeremy** [comment] 2021-04-13 01:26
You may need to tweak your icon settings. It seems like the system theme did not bundle a flameshot icon.

You installed via .deb?

**Comment by mmahmoudian** [comment] 2021-04-13 06:20
This can easily be duplicate of https://github.com/flameshot-org/flameshot/issues/1514#issuecomment-815466593

**Comment by rsaleri** [comment] 2021-04-13 08:27
@borgmanJeremy the icon is there, but it has the same color as the bar, that's why is "invisible"

**Comment by borgmanJeremy** [comment] 2021-04-13 13:16
Yes, but our project does not create any icon other than the colorful one. The issue is the icon pack you are using is the same color as the theme you are using. You need to either change your theme or icon pack, or submit a bug with the icon pack creator.

**Comment by bautrey37** [comment] 2021-04-14 10:19
Ah yes, #1514  seems to be same issue. I looked very closely and the icon is there but its practically the same color. I installed via flatpak, not deb. It seems that the issue would go here then? https://github.com/pop-os/icon-theme

**Comment by bautrey37** [comment] 2021-04-14 10:24
https://github.com/flameshot-org/flameshot/issues/1514#issuecomment-817092292

This happens to me too. Why does the icon change color and then back to the original icon theme?

**Comment by borgmanJeremy** [comment] 2021-04-18 01:58
I'm not sure, but its an issue with your DE or theme. We only package the standard colored icon.

**Closed by borgmanJeremy** 2021-04-18 01:58 UTC

**Comment by bautrey37** [comment] 2021-05-01 14:44
Not sure why, but the correct icon is being shown. Maybe PopOS updated and fixed it.
