### ISSUE TITLE
"Tool Settings" button become inaccessible

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#919] opened 2020-09-14 13:47 UTC
**Flameshot version**
Flameshot 0.8 Beta - AppImage

**Describe the bug**
When clicking on the button, the sidebar that contains tool settings opens and it covers the button.

**To Reproduce**
open the `flameshot gui` -> click on "Tool Settings"

**Expected behavior**
To my logic, I expected to be able to close the sidebar by clicking on the same button, or worst case pressing Esc or a close button on the sidebar.

Ideally, the sidebar should be able to push the button to the right. Alternatively, we can have a close button on the top-right corner of the sidebar.

**System Information**
- AppImage
- Ubuntu 18.04
- DE: Budgie

**Comment by borgmanJeremy** [comment] 2020-09-14 14:47
I am going to change this to an enhancement from a bug. It is working as intended since there is already a close button at the button of the tool setting screen. 

I agree now that we have the sidebar button it would be better if it acted as a Toggle.

**Comment by mmahmoudian** [comment] 2020-09-14 14:52
@borgmanJeremy what close button?! I don't see any close button anywhere:

![image](https://user-images.githubusercontent.com/390889/93101519-0a438f00-f6b3-11ea-9dc9-eabf1dca8843.png)

**Comment by borgmanJeremy** [comment] 2020-09-14 15:32
Do you have this close button? I am also running the appimage uploaded to the 0.8.rc1 release. 

![image](https://user-images.githubusercontent.com/46930769/93106186-9931b680-f675-11ea-9094-6f805fbe3a52.png)

**Comment by mmahmoudian** [comment] 2020-09-14 15:37
No, but I think I have a hypothesis that might explain why and if it's true it is a definite bug: My monitors are stacked on top of each other and not side-by-side. Does Flameshot calculate the height of the sidebar based on total height that it can operate on? In other words, is the height of the sidebar equal to the purple overlay?

**Comment by AlexP11223** [comment] 2020-09-14 15:40
@mmahmoudian  oh, that's strange, the panel is cropped.

Should be like on the screenshot above.

Is the Tool Settings button also below the center for you?

I managed to reproduce it in VMWare after resizing the guest several times. Restarting flameshot fixes it. Maybe the screen size is cached somewhere.

**Comment by mmahmoudian** [comment] 2020-09-14 15:42
yes the purple button is correctly located at the 9 o'clock of the primary monitor.

**Comment by borgmanJeremy** [comment] 2020-09-14 20:00
@AlexP11223 Can you help resolve this by our release on Sept-20?

**Comment by AlexP11223** [comment] 2020-09-14 20:18
>  This means that you are getting the dimensions of the primary monitor correctly for positioning the button but when defining the height of the sidebar, you use the another dimension.

Maybe it's just not shifted enough to be noticeable, when everything is correct and the panel fits it looks like this

![](https://i.imgur.com/7Ic2gHB.png)

They both use `QGuiApplication::primaryScreen()->geometry();` https://github.com/flameshot-org/flameshot/blob/master/src/widgets/capture/capturewidget.cpp#L610

**Comment by mmahmoudian** [comment] 2020-09-15 08:43
The good thing about AppImage is that it is agnostic to software setup (other than monitor positioning ;)

So I conducted the following tests:
1. unplugged the HDMI from the laptop to make sure it uses only one monitor  -> the "close" button was shown
2. Mirrored display  ->  the "close" button was shown
3. set the monitor as "extension" and put them side-by-side (HDMI on the right)  -> the "close" button was shown
4. set the monitor as "extension" and put them side-by-side (HDMI on the left)  -> the "close" button was shown
5. set the monitor as "extension" and put them on top of each other  -> No "close" button !

Both monitors ave the same exact resolution and same aspect ratio (1920x1080(16:9)).

This is clearly a bug and it is related to the way we are determining the height of the sidebar. My suggestions to debug
1. if you have two monitors, try setting your monitors as stacked on top of each other
2. display the dimension of the sidebar in the middle of the window, build an AppImage and I'll test it and report back

-------

@borgmanJeremy in the meanwhile, I'll change the label to a bug.

**Comment by borgmanJeremy** [comment] 2020-09-15 14:06
@mmahmoudian Does the top of the menu always work properly? We could move close button to the top as a quick fix for the 0.8 release.

**Comment by mmahmoudian** [comment] 2020-09-15 14:17
@borgmanJeremy the top is always there. I also suggest that Esc close the sidebar if it is open (and then the nex Esc can close the Flameshot)

**Comment by AlexP11223** [comment] 2020-09-15 14:21
> I also suggest that Esc close the sidebar if it is open (and then the nex Esc can close the Flameshot)

You can just press Space now if you have access to keyboard.

**Comment by borgmanJeremy** [comment] 2020-09-16 00:44
@mmahmoudian can you test the app image on PR #925 ? If it works ill get it merged.

**Comment by mmahmoudian** [comment] 2020-09-16 07:56
@borgmanJeremy & @AlexP11223  it works beautifully 👍🏼  Thank you both.

**Closed** 2020-09-16 11:38 UTC
Labels: Bug
