### ISSUE TITLE
Cannot get flameshot gui to run on Hyprland (wlroots) and Arch

### ISSUE THREAD

**Issue by ad-on-is** [flameshot-org/flameshot#2979] opened 2022-11-12 16:29 UTC
I'm trying to get flameshot working on Hyprland, but it does not work. Also, I tried on sway, and the results are the same

```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```

terminal 1: `flameshot` -> no output but flameshot is in the systemtray

terminal 2: `flameshot gui` -> nothing happens (no errors or whatsoever) just hangs there

terminal 3: `flameshot screen` -> `segmentation fault (core dumped)  flameshot screen`

EDIT:
I figured I had `xdg-desktop-portal-gnome` installed, which caused the issue. On sway it works fine, however in Hyprland there are glitches.

<details>
<summary>Stack trace</summary>

```
systemd-coredump[1226429]: [🡕] Process 1226422 (flameshot) of user 1000 dumped core.

Stack trace of thread 1226422:
#0  0x00007f7f2e5632e4 _ZNK7QScreen8geometryEv (libQt5Gui.so.5 + 0x1632e4)
#1  0x0000557e14bc1016 n/a (flameshot + 0x90016)
#2  0x0000557e14bb35ef n/a (flameshot + 0x825ef)
#3  0x0000557e14bb5444 n/a (flameshot + 0x84444)
#4  0x00007f7f2e0b0be0 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2b0be0)
#5  0x00007f7f2ed78b1c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x178b1c)
#6  0x00007f7f2e08cf98 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x28cf98)
#7  0x00007f7f2e08daa3 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x28daa3)
#8  0x00007f7f2e0d3e68 n/a (libQt5Core.so.5 + 0x2d3e68)
#9  0x00007f7f2c91687b g_main_context_dispatch (libglib-2.0.so.0 + 0x5587b)
#10 0x00007f7f2c96d279 n/a (libglib-2.0.so.0 + 0xac279)
#11 0x00007f7f2c915132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
#12 0x00007f7f2e0d7c4c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2d7c4c)
#13 0x00007f7f2e08573c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x28573c)
#14 0x00007f7f2e090269 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x290269)
#15 0x0000557e14b7ed59 n/a (flameshot + 0x4dd59)
#16 0x00007f7f2d83c290 n/a (libc.so.6 + 0x23290)
#17 0x00007f7f2d83c34a __libc_start_main (libc.so.6 + 0x2334a)
#18 0x0000557e14b87cd5 n/a (flameshot + 0x56cd5)

Stack trace of thread 1226425:
#0  0x00007f7f2d9140bf __poll (libc.so.6 + 0xfb0bf)
#1  0x00007f7f2d73bc7d n/a (libQt5WaylandClient.so.5 + 0x72c7d)
#2  0x00007f7f2dee42ea n/a (libQt5Core.so.5 + 0xe42ea)
#3  0x00007f7f2d89f8fd n/a (libc.so.6 + 0x868fd)
#4  0x00007f7f2d921a60 n/a (libc.so.6 + 0x108a60)

Stack trace of thread 1226424:
#0  0x00007f7f2d9140bf __poll (libc.so.6 + 0xfb0bf)
#1  0x00007f7f2c96d1df n/a (libglib-2.0.so.0 + 0xac1df)
#2  0x00007f7f2c915132 g_main_context_iteration (libglib-2.0.so.0 + 0x54132)
#3  0x00007f7f2e0d7c4c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2d7c4c)
#4  0x00007f7f2e08573c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x28573c)
#5  0x00007f7f2dee721f _ZN7QThread4execEv (libQt5Core.so.5 + 0xe721f)
#6  0x00007f7f2f460cba n/a (libQt5DBus.so.5 + 0x23cba)
#7  0x00007f7f2dee42ea n/a (libQt5Core.so.5 + 0xe42ea)
#8  0x00007f7f2d89f8fd n/a (libc.so.6 + 0x868fd)
#9  0x00007f7f2d921a60 n/a (libc.so.6 + 0x108a60)

Stack trace of thread 1226426:
#0  0x00007f7f2d9140bf __poll (libc.so.6 + 0xfb0bf)
#1  0x00007f7f2d73bc7d n/a (libQt5WaylandClient.so.5 + 0x72c7d)
#2  0x00007f7f2dee42ea n/a (libQt5Core.so.5 + 0xe42ea)
#3  0x00007f7f2d89f8fd n/a (libc.so.6 + 0x868fd)
#4  0x00007f7f2d921a60 n/a (libc.so.6 + 0x108a60)
ELF object binary architecture: AMD x86-64

```
</details>

Am I missing something?

**Comment by jacksgt** [comment] 2022-11-16 08:57
Probably the same issue as described in https://github.com/flameshot-org/flameshot/issues/2959

**Comment by Narice** [comment] 2022-12-08 17:32
Could be a duplicate of #2978.
If it is then consider closing this one and joining the fun there :yum:

**Closed** 2022-12-08 19:50 UTC
