### ISSUE TITLE
Not able to map a shortcut if it is already mapped to another tool

### ISSUE THREAD

**Issue by kaldown** [flameshot-org/flameshot#1575] opened 2021-04-22 12:03 UTC
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
Can not set Return using `flameshot config` GUI option. It just don't change key. But actually removed prev. one from `flameshot.ini`
More info: https://github.com/flameshot-org/flameshot/issues/480#issuecomment-824752037

**To Reproduce**
Arch linux: yay -S flameshot
`flameshot config`
go to shortcuts
find Save option
wait for an modal window to ask for input
hit Return (Enter)
Looks like it's being saved, But it's not

**Expected behavior**
Return to be put as a shortcut

**System Information**
Linux kaldown 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64 GNU/Linux

**Comment by Nohus** [comment] 2021-07-30 13:23
I have the same issue, so I can confirm it's still present on the latest version (Flameshot v0.10.1). I could set the shortcut in `flameshot.ini`, but as above, impossible with the GUI. Works fine for other keys.

**Comment by mmahmoudian** [comment] 2021-08-03 07:43
@Nohus Would you please provide your system information (Operating system, DE, WM)

**Comment by Nohus** [comment] 2021-08-03 09:25
Kubuntu 20.10
KDE Plasma 5.19.5
Kwin 5.19.5

**Comment by borgmanJeremy** [comment] 2021-08-04 02:04
Confirmed this on Arch + KDE

**Comment by borgmanJeremy** [comment] 2021-08-04 02:07
Actually I found the root cause. You may set Return as a hotkey, but only if it is not assigned to anything else. This is not specific to just Return, you can test it with any other hotkey.

We should fix this by showing a dialog box asking if we should unmap the current tool.

**Comment by mmahmoudian** [comment] 2021-08-04 07:18
Then this is duplicate of  #1574

**Comment by Nohus** [comment] 2021-08-04 14:22
@borgmanJeremy @mmahmoudian 
Uhh, sorry but this is not true. The issue you found with not being able to map and already mapped shortcut also exists, yes, but that would be a separate issue. I have tested this and I cannot assign Return even when it's not assigned anywhere else.

**Comment by mmahmoudian** [comment] 2021-08-04 14:28
@Nohus please post your config here. just as a QoL (Quality of life), the following copies your config file to clipboard:

```sh
xclip -selection clipboard ~/.config/flameshot/flameshot.ini
```

**Comment by Nohus** [comment] 2021-08-04 14:36
Aha! Looking through the config file I can see Return is assigned there to something else:
```
TYPE_IMAGEUPLOADER=Return
```
However that entry does not show up in the GUI:
![image](https://user-images.githubusercontent.com/11064768/128199722-f3185a28-0d6f-46d6-a5b6-ba7f50b378cf.png)

So this is a combination of not being able to assign an already assigned shortcut, and the `TYPE_IMAGEUPLOADER` shortcut not showing up in the GUI. Without being in the GUI, and no error message, a user cannot see it's already assigned somewhere else, and cannot unassign it either.

**Comment by borgmanJeremy** [comment] 2021-08-04 16:08
We just merged a fix to the main branch that shows all hotkeys even if the tool is disabled.

So I think this is a duplicate since it was a stack of 2 bugs:
1.) It didnt show hotkeys when the tool was disabled (fixed on main branch)
2.) Doesn't allow users to remap an assigned hotkey (duplicate and work in progress to fix)

**Comment by mmahmoudian** [comment] 2021-08-05 05:29
@Nohus So let's close this, but re-open if the issue is observed also in the new version.

**Closed** 2021-08-05 05:29 UTC
Labels: Enhancement, Good first issue
