### ISSUE TITLE
[feature request] text recognition from clipping

### ISSUE THREAD

**Issue by hnariman** [flameshot-org/flameshot#2814] opened 2022-07-21 13:08 UTC
### Feature Description

It will be great to have text recognition (OCR) in tools of Flameshot.

Say I'm taking a screenshot of image and can extract text from it (very much like Samsung Galaxy S-Pen does).
I think this might be very usefull feature, because not all the time we can select and copy paste text.
And having this feature in Flameshot will increase it's potential of the main content extraction tool.

Useage scenario-1:
- colleague have sent me screenshot of some console error
- I would like to run Flameshot, crop just what is important and extract text to the clipboard, so I can google and help my colleague to find the solution 

Useage scenario-2:
- found an image with nice poetry online
- I would like to run Flameshot crop just the text -> clipboard and send it to my friend as text

I was thinking of few libraries which already have this functionality and if we can just get the image in clipboard and send it into library method, we potentially can make this happen.

Lib suggestions:
- APOSE (not sure if they are propretiary) [APOSE](https://blog.aspose.com/2020/06/23/convert-image-to-text-using-cpp-ocr-library/ )
- Motorollas Tesseract - whcih I belive is best due to license and overall reputation of the lib (stability as well) [Tess](https://github.com/tesseract-ocr/tesseract)

Also code exmaples could be found here: 
[https://tesseract-ocr.github.io/tessdoc/Examples_C++.html](https://tesseract-ocr.github.io/tessdoc/Examples_C++.html)

**Comment by mmahmoudian** [comment] 2022-07-21 15:19
Duplicate of #702 

Please search before posting new issues. Thanks.
https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+OCR

**Closed by mmahmoudian** 2022-07-21 15:19 UTC
Labels: Enhancement
