### ISSUE TITLE
Linux Mint Zooming doesn't work reliably when screen zoom is 125%-175%

### ISSUE THREAD

**Issue by DeflateAwning** [flameshot-org/flameshot#3353] opened 2023-09-26 17:58 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 6.1.0-1022-oem
linuxmint: 21.2

Installed using Ubuntu 22 package from GitHub release

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint 21.2, Cinamon desktop manager

### Description

Sometimes the screen capture is only left top-left corner of the screen. Sometimes, the screen flashes and the zoom changes randomly. 

### Steps to reproduce

1. Set laptop screen zoom to 125%.
2. Try to take a screenshot, and observe the issues in the description.
3. Try plugging in an external monitor and unplugging it. See that the issues are often worse.

### System Information

Linux Mint 21.2. Cinamon.

**Comment by dmitry-j-mikhin** [comment] 2023-09-27 15:05
Have the same behavior on Gnome 45 in Fedora 39 when Display is configured with scale factor lager than 100%:
![image](https://github.com/flameshot-org/flameshot/assets/41896087/dff08f24-4a0b-4dd4-961f-7c926d7f33b8)

**Comment by mmahmoudian** [comment] 2023-09-27 20:29
This is duplicate of #564 and we have a workaround for it in our documentation:

https://flameshot.org/docs/guide/wayland-help/#4k-displayed-and-fractional-scaling

**Closed by mmahmoudian** 2023-09-27 20:29 UTC
Labels: Unconfirmed Bug
