### ISSUE TITLE
How to set custom Image Uploader?

### ISSUE THREAD

**Issue by jbugel-lol** [flameshot-org/flameshot#3467] opened 2024-01-09 12:57 UTC
I was following [this](https://github.com/diced/zipline#flameshot-linuxxorgwayland-and-macos) guide and I couldnt find a way to use this script, can someone tell me how I can use it?

Device: MacBook Pro
MacOS: Sonoma 14.0
brew: 4.2.3
Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 23.0.0

**Comment by mmahmoudian** [comment] 2024-01-09 16:37
You can't this is duplicate of so many other issues. Would save your time to search among open and closed issues before opening a new one. For instance just search "upload".

**Closed** 2024-01-09 16:37 UTC
