### ISSUE TITLE
Flameshot not launching when using Wayland

### ISSUE THREAD

**Issue by BlueskyFR** [flameshot-org/flameshot#675] opened 2019-12-16 20:25 UTC
**Flameshot version**
0.6.0-9(Debian)

**Describe the bug**
The commands `flameshot gui` or `flameshot config` doesn't do anything.

**To Reproduce**
I am using the sway (swaywm) window manager on Wayland.

**Expected behavior**
It should open properly.

**System Information**
Ubuntu 19.04

**Comment by vvrein** [comment] 2019-12-23 12:58
Try run flameshot as `QT_QPA_PLATFORM=wayland-egl flameshot`
Also, try to install waybar, which support (partially) tray, so you can see wether flameshot is running

**Comment by vvrein** [comment] 2019-12-23 13:06
Also, related to wayland based WM https://github.com/lupoDharkael/flameshot/issues/619
Currently, seems that flameshot does not support capturing screen under wayland.
So, even if you can run it, you can't do anything
```
15:00:41 vrein@tokk:~| QT_QPA_PLATFORM=wayland-egl flameshot
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
15:00:46 vrein@tokk:~| flameshot -v
Flameshot v0.6.0
Compiled with Qt 5.12.1
.....
Updated flameshot behind the scene
.....
15:00:56 vrein@tokk:~| QT_QPA_PLATFORM=wayland-egl flameshot
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
15:02:57 vrein@tokk:~| flameshot -v
Flameshot v0.6.0-70-g91ba28c
Compiled with Qt 5.13.2
```

**Comment by ZetaoYang** [comment] 2019-12-25 09:37
You can make all your QT apps use XWayland:
`export QT_QPA_PLATFORM=xcb`
Add this to `/etc/profile` file, then restart.

**Comment by bwoodruff** [comment] 2020-03-09 01:23
Doesn't work on Fedora 31 (GNOME) for me:

```
$ export QT_QPA_PLATFORM=              
$ flameshot 
QSocketNotifier: Can only be used with threads started with QThread
```

**Comment by Tids** [comment] 2020-03-22 09:32
Whats the point in starting flameshot in xwayland? You then can only screen up xorg apps, not pure wayland stuff.

**Comment by BlueskyFR** [comment] 2020-03-24 21:16
@Tids we should be able to.

**Comment by joaoeudes7** [comment] 2020-09-01 12:32
```sh
export QT_QPA_PLATFORM=xcb flameshot
```
This works, but this isn't possible set in installation?

**Comment by mmahmoudian** [comment] 2020-09-06 16:08
@ZetaoYang is this still a valid issue considering the recent changes?

**Comment by joaoeudes7** [comment] 2020-09-06 20:58
Yeah, I use ArchLinux, I believe it is with the latest versions and it is not working yet

**Comment by mmahmoudian** [comment] 2020-09-06 21:21
@joaoeudes7 I just realized the issue: Sway WM. Actually it is not sway's fault but I probably know what is happening. the same thing happens with the current `flameshot-git` AUR. When you run `flameshot gui` or any other argument of flameshot, the main application does not get launched. To bypass this while we are investigating this follow:

https://github.com/flameshot-org/flameshot/issues/790#issuecomment-687416350

**Comment by pengux** [comment] 2020-09-07 06:47
@mmahmoudian So I tried `( flameshot & ) && flameshot gui` and it launched flameshot, but it just show the notification `Unable to capture screen` whenever I try to take a screenshot. I'm using Sway and Arch Linux

**Comment by mmahmoudian** [comment] 2020-09-07 06:50
@pengux I'm so confused, it opened but throw an error? can you post a screenshot (or take a photo with your phone)?

**Comment by pengux** [comment] 2020-09-07 07:01
Yes, here's a screenshot. Is there a debug flag to get debug logs when launching flameshot?

![image](https://user-images.githubusercontent.com/2286687/92357720-9ae50280-f0e8-11ea-8675-bbc9b985091b.png)

**Comment by vvrein** [comment] 2020-09-07 08:38
@mmahmoudian here some logs for @pengux screenshot:
```
| QT_QPA_PLATFORM=wayland flameshot
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
1) I started flameshot from cli on sway
2) Flameshot icon appeared in the tray
3) On click on flameshot tray icon - I got same notifications as above 
(actually I clicked 3 times, so there is 3 messages in terminal)

WM: sway
OS: Arch Linux
| flameshot -v
Flameshot v0.8.0
Compiled with Qt 5.15.0

**Comment by ZetaoYang** [comment] 2020-09-07 08:41
@mmahmoudian I confirm this is a bug, when I used flameshot on Fedora 32 Gnome with Wayland, this issue appears.But on Fedora 31 with Wayland, it can start normally .

**Comment by borgmanJeremy** [comment] 2020-09-08 13:14
I can confirm this with sway on arch. Thanks for clarifying, It seems to work okay with KDE on Wayland.

**Comment by joaoeudes7** [comment] 2020-09-08 13:26
Using package flameshort-git works, but flameshort not.
https://www.archlinux.org/packages/community/x86_64/flameshot/

Thank you for your attention and commitment to the project

**Comment by vvrein** [comment] 2020-09-08 16:05
@joaoeudes7 what is your DE?
I'm still can not capture screenshot on sway (latest commit build a892766)

**Comment by joaoeudes7** [comment] 2020-09-08 16:33
> @joaoeudes7 what is your DE?
> I'm still can not capture screenshot on sway (latest commit build [a892766](https://github.com/flameshot-org/flameshot/commit/a892766359f67339d432607561254d19c0300329))

Operating System: Arch Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.7-arch1-1
OS Type: 64-bit

**Comment by DjinNO** [comment] 2020-09-14 13:56
![image](https://user-images.githubusercontent.com/15555838/93095022-45da5b00-f6ab-11ea-9ba9-6979c02a2f3c.png)

**Comment by mmahmoudian** [comment] 2020-09-14 14:05
@DjinNO Please report the Flameshot version (or the commit you built if from) and format (in case you use AppImage or Flatpak)

**Comment by DjinNO** [comment] 2020-09-14 14:07
@mmahmoudian Now i'm using v0.8.0 from AUR

**Comment by pavel-the-best** [comment] 2020-10-02 18:40
The bug is still present on master

**Comment by pavel-the-best** [comment] 2020-10-02 18:41
Maybe we should add it to milestones?

**Comment by mystiquewolf** [comment] 2020-10-10 18:38
Ubuntu 20.04 - GNOME 3.36.4 - Wayland - Flameshot 0.8.1
It was working before with the old 0.6.0 repo version from Ubuntu

![image](https://user-images.githubusercontent.com/16529989/95662564-827d6300-0b40-11eb-9781-9fb9b0970bc3.png)

**Comment by mystiquewolf** [comment] 2020-10-10 18:56
Excuse me, the version in Ubuntu Software is listed as 0.8.3, but in "About" it is said to be 0.8.1.

**Comment by borgmanJeremy** [comment] 2020-10-10 19:10
@mystiquewolf can you open a seperate issue for the version number mismatch so I don't clutter this one with questions?

**Comment by mng-25** [comment] 2020-10-16 12:36
Flameshot 0.8.5, compiled with Qt 5.15.1, from AUR flameshot-git with `debug` and `!strip` options on the following system:

Operating System: Arch Linux
KDE Plasma Version: 5.20.0
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.14-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

on Wayland, i can get the config and about pages, as well as the launcher, but I cannot use the overlay (`$ flameshot gui` ) nor can I use the launcher. gdb states the following when I attempt to take a full screenshot from the launcher (region causes the window to flicker and I hover over the screenshot button for a few seconds):

$ gdb -ex=r /usr/bin/flameshot
Reading symbols from /usr/bin/flameshot...
Starting program: /usr/bin/flameshot 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff147b640 (LWP 15761)]
[Detaching after fork from child process 15762]
[New Thread 0x7fffe2488640 (LWP 15799)]
[New Thread 0x7fffe1c87640 (LWP 15800)]
[New Thread 0x7fffe1486640 (LWP 15801)]
[New Thread 0x7fffe0c85640 (LWP 15802)]
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
[Detaching after fork from child process 16104]
kf.kio.core: We got some errors while running testparm "Weak crypto is allowed"
[Detaching after fork from child process 16105]

Annoyingly, I use screenshots infrequently enough that I can't be certain when this last worked.

**Comment by Kodehawa** [comment] 2020-12-24 22:48
This is still an issue for me on KDE Wayland. Any news? I haven't heard of this bug for a while but I definitely don't seem to be able to use it :(

**Comment by borgmanJeremy** [comment] 2021-02-03 01:24
Sway support was just added with this PR:  #1272

**Comment by AkechiShiro** [comment] 2021-02-05 19:57
@borgmanJeremy I just build flameshot from the AUR on Archlinux and I'm still facing the same bug as before on Sway, I also saw someone saying that installing xdg-desktop-portal would solve the issue but currently the issue still happens.

**Comment by pavel-the-best** [comment] 2021-02-05 21:28
@AkechiShiro 
AUR package is flagged out of date.
Please try building from source.

**Comment by vvrein** [comment] 2021-02-06 12:43
For @AkechiShiro, and maybe for others:
To properly start `flameshot` under sway you need a couple of things:
- install `xdg-desktop-portal` and `xdg-desktop-portal-wlr`
Those are systemd user services (e.g. `systemctl --user status xdg-desktop-portal`) and they don't run in system scope.

- put in yours `~/.pam_environment` (create if not exists):
`XDG_CURRENT_DESKTOP             DEFAULT=sway`

- put in yours `~/.config/environment.d/envvars.conf` (create if not exists):
`XDG_CURRENT_DESKTOP=sway`
`XDG_RUNTIME_DIR=/run/user/$YOUR_USER_ID`
`WAYLAND_DISPLAY=wayland-1`

- then, ideally, reboot, and check whether  xdg-desktop-portal and xdg-desktop-portal-wlr are started properly
- then start flameshot and try to capture the screen
- currently, you can make only one screenshot after flameshot start, to take anothor - restart flameshot

**Comment by svelle** [comment] 2021-02-17 14:55
Getting this with Fedora 33 on latest master when running `flameshot gui` for example.

**Comment by arran-nz** [comment] 2021-03-15 09:48
> For @AkechiShiro, and maybe for others:
> To properly start `flameshot` under sway you need a couple of things:
> 
>     * install `xdg-desktop-portal` and `xdg-desktop-portal-wlr`
>       Those are systemd user services (e.g. `systemctl --user status xdg-desktop-portal`) and they don't run in system scope.
> 
>     * put in yours `~/.pam_environment` (create if not exists):
>       `XDG_CURRENT_DESKTOP             DEFAULT=sway`
> 
>     * put in yours `~/.config/environment.d/envvars.conf` (create if not exists):
>       `XDG_CURRENT_DESKTOP=sway`
>       `XDG_RUNTIME_DIR=/run/user/$YOUR_USER_ID`
>       `WAYLAND_DISPLAY=wayland-1`
> 
>     * then, ideally, reboot, and check whether  xdg-desktop-portal and xdg-desktop-portal-wlr are started properly
> 
>     * then start flameshot and try to capture the screen
> 
>     * currently, you can make only one screenshot after flameshot start (due to [emersion/xdg-desktop-portal-wlr#82](https://github.com/emersion/xdg-desktop-portal-wlr/pull/82)), to take anothor - restart flameshot
> 
> 
> The main idea is you need correctly configure xdg-desktop-portal-wlr environment, so it could hook up to sway.
> Without XDG_CURRENT_DESKTOP and WAYLAND_DISPLAY in my case it was silently failing to start.
> And since your session env vars have nothing common with systemd's env vars - you need to set those in `~/.config/environment.d/`

To confirm - This worked for me, thank you for sharing.

**Comment by schmitzkr** [comment] 2021-04-30 15:39
Since upgrading Ubuntu to 21.04 hirsute (default wayland) I am getting this with the snap version 0.9

**Comment by All3xJ** [comment] 2021-05-22 09:58
flameshot-git version works. repo version doesn't.

**Comment by mmahmoudian** [comment] 2021-05-23 07:28
@All3xJ As far as I know and as far as it make sense logically, Flameshot doesn't use Spectacle simply because it is cross-platform and Spectacle is KDE-specific. That is that.

About the difference between `pacman -S flameshot` and `yay -S flameshot-git`, the flameshot-git points at the HEAD of the master branch of git. So it should be considered as "nightly build". Also because of this reason, the version number can be different from when you install it from official repo of your linux. Therefore, every time you are reporting something about the flameshot-git, please make sure to mention which build version you are using. I don't know about `yay`, but in `pamac` you can do `pamac search flameshot-git` and copy the exact version here.

**Comment by All3xJ** [comment] 2021-05-23 09:04
@mmahmoudian 
```
$ flameshot --version
Flameshot v0.10.0
Compiled with Qt 5.15.2
```

**Comment by mmahmoudian** [comment] 2021-05-23 09:24
@All3xJ 
Regarding your issue with Spectacle, the only reason I can think of is that you have a conflict in your keybinding. One easy way to test it is:
1. Kill spectacle and flameshot
2. Run Flameshot with command line (e.g `flameshot gui`)
3. Check if spectacle is running (for example with `pgrep`)

4. Repeat step 1
5. Run Flameshot with keyboard shortcut
6. Repeat step 3

The difference between steps 3 and 6 should confirm my hypothesis.

Regarding your version 0.10.0 install, I suggest create a new issue and also possibly link to this thread) as:
1. It is "beta" version
2. It is hot topic as we are planning to release it soon and performance issue needs attention


Last but not least, thank you for spending time and putting effort into reporting bugs and issues.

**Comment by apaes** [comment] 2021-06-07 11:43
> For @AkechiShiro, and maybe for others:
> To properly start `flameshot` under sway you need a couple of things:
> 
> * install `xdg-desktop-portal` and `xdg-desktop-portal-wlr`
>   Those are systemd user services (e.g. `systemctl --user status xdg-desktop-portal`) and they don't run in system scope.
> * put in yours `~/.pam_environment` (create if not exists):
>   `XDG_CURRENT_DESKTOP             DEFAULT=sway`
> * put in yours `~/.config/environment.d/envvars.conf` (create if not exists):
>   `XDG_CURRENT_DESKTOP=sway`
>   `XDG_RUNTIME_DIR=/run/user/$YOUR_USER_ID`
>   `WAYLAND_DISPLAY=wayland-1`
> * then, ideally, reboot, and check whether  xdg-desktop-portal and xdg-desktop-portal-wlr are started properly
> * then start flameshot and try to capture the screen
> * currently, you can make only one screenshot after flameshot start (due to [emersion/xdg-desktop-portal-wlr#82](https://github.com/emersion/xdg-desktop-portal-wlr/pull/82)), to take anothor - restart flameshot
> 
> The main idea is you need correctly configure xdg-desktop-portal-wlr environment, so it could hook up to sway.
> Without XDG_CURRENT_DESKTOP and WAYLAND_DISPLAY in my case it was silently failing to start.
> And since your session env vars have nothing common with systemd's env vars - you need to set those in `~/.config/environment.d/`

I'm running on Arch and have installed all git versions of all the packages from AUR (`wlroots-git`, `sway-git`, `xdg-desktop-portal-git`, `xdg-desktop-portal-wlr-git`, `flameshot-git`), I've followed all the above settings with `~/.pam_environment` and `~/.config/environment.d/envvars.conf`. Upon booting I can see all services running (pipewire, pipewire.socket, xdg-desktop-portal and xdg-desktop-portal-wlr), they seem to be running OK from boot. The only weird thing I'm getting is the following message when checking status of xdg-desktop-portal-wlr using systemctl:

`xdg-desktop-portal-wlr[2480]: 2021/06/07 12:29:37 [ERROR] - config: no config file found`

Still, whenever I launch flameshot I still get that nasty "Unable to capture screen" notification. Would anyone have any idea of what to test additionally or how to debug the whole thing? I rely heavily on flameshot on a daily basis and would hate to have to go back to X.org and i3wm just because of this...

**Comment by kachapman** [comment] 2021-09-14 20:55
I get this issue on Pop!OS 21.04 in wayland. Is there a work around yet for debian/ubuntu distros?

**Comment by borgmanJeremy** [comment] 2021-11-18 13:58
Closing this since the issue has kind of wandered all over the place and i know for certain it is working on Fedora35 and Arch Gnome41.

**Closed by borgmanJeremy** 2021-11-18 13:58 UTC
Labels: Bug, Linux, Wayland

**Comment by logrusorgru** [comment] 2021-11-18 18:22
It works on Arch KDE Plasma too (at this time).

**Comment by ovk** [comment] 2021-11-18 19:03
Doesn't work on Sway though.

**Comment by mmahmoudian** [comment] 2021-11-19 07:42
@ovk have you read this:

https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

**Comment by ovk** [comment] 2021-11-21 01:02
I didn't, thank you for the info. Although, I find the requirement to have xdg-desktop-portal a bit strange. Is this a temporary or a permanent solution?

**Comment by borgmanJeremy** [comment] 2021-11-21 01:08
Permanent

**Comment by egisz** [comment] 2022-01-14 07:24
I had same problem with Ubuntu impish 21.10 when installed flameshot using snap (via Ubuntu Software app)
I followed proposed [route](https://github.com/flameshot-org/flameshot/issues/675#issuecomment-774472057), but I hate make making modifications on system I don't understand, so I removed snap version it and installed using 
```apt install flameshot```
 and voilia - it works fine now :)
