### ISSUE TITLE
I can't upload a picture to imgur on wayland

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1667] opened 2021-06-14 13:30 UTC
**Flameshot version**

Latest git version
**Describe the bug**

When I try to upload a picture to imgur,then there is an infinite loading screen.
**To Reproduce**

take screenshot and try to upload it
**Expected behavior**

That I can upload it.
**System Information**

Arch.

**Comment by strakhov** [comment] 2021-06-16 11:16
I too
![image](https://user-images.githubusercontent.com/856821/122209645-69863800-cead-11eb-90e4-6d2382d8c0c9.png)

**Comment by linwaytin** [comment] 2021-06-16 12:33
I got the same error on X11.

**Comment by rizaardiyanto** [comment] 2021-07-13 09:20
Same for me as well on max os
![2021-07-13_16-20](https://user-images.githubusercontent.com/26299312/125426673-0acba796-a842-4227-8313-7b169e1b0063.png)

**Comment by mmahmoudian** [comment] 2021-07-14 08:51
@rizaardiyanto @strakhov What you see is the error that Imgur returns and has nothing to do with Flameshot. When you use Flameshot, practically you are using Flameshot's Imgur account to upload your photos (your issue is duplicate of #1542). As the users of Flameshot increases, there is higher chance that we run out of quota for our account. That is the reason you "sometimes" get that error. We are working on releasing a feature in which users can use their own account's API key.

**Closed** 2021-07-19 19:05 UTC
Labels: Bug, High Priority
