### ISSUE TITLE
Flameshot crashes when using 'copy to clipboard' on Manjaro

### ISSUE THREAD

**Issue by MariusCC** [flameshot-org/flameshot#1171] opened 2020-11-28 09:27 UTC
**Flameshot version**
flameshot -v
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
Flameshot crashes when using 'copy to clipboard'.
Error:
> \# flameshot
> QPainter::begin: Paint device returned engine == 0, type: 2
> QPainter::setRenderHint: Painter must be active to set rendering hints
> QPainter::setCompositionMode: Painter not active
> QPainter::translate: Painter not active
> QPainter::setPen: Painter not active
> QPainter::setBrush: Painter not active
> QPainter::setBrush: Painter not active
> WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
> WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
> WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
> YOUR CODE IS RELYING ON DEPRECATED FUNCTIONALTIY IN THE JASPER LIBRARY.
> THIS FUNCTIONALITY WILL BE REMOVED IN THE NEAR FUTURE.
> PLEASE FIX THIS PROBLEM BEFORE YOUR CODE STOPS WORKING!
> The specific problem is as follows:
> negative buffer size for jas_stream_memopen
> QXcbClipboard: Unable to receive an event from the clipboard manager in a reasonable time

**To Reproduce**
Launch flameshot
Select something on the screen
Click 'copy the selection into the clipoard'

**Expected behavior**
Don't crash.

**System Information**
5.9.11-2-MANJARO

**Comment by grigoriy-a** [comment] 2020-11-28 22:42
Hi guys!
I too have this problem.
Manjaro latest, KDE latest, Flameshot latest from official repo.

**Comment by borgmanJeremy** [comment] 2020-11-28 22:50
Can you post your config file?

**Comment by grigoriy-a** [comment] 2020-11-29 09:37
@borgmanJeremy 
`[General]
closeAfterScreenshot=true
contrastUiColor=#7b7b7b
copyAndCloseAfterUpload=true
disabledTrayIcon=true
drawColor=#ff0000
drawThickness=0
saveAfterCopyPath=/home/gri/Pictures
savePath=Pictures/Screenshots
showDesktopNotification=false
showHelp=false
showSidePanelButton=false
startupLaunch=false
uiColor=#3d3d3d
`

**Comment by grigoriy-a** [comment] 2020-11-29 09:44
In my case it is `closeAfterScreenshot=true` which is preventing from taking screenshots. If I disable this option, everything works fine.

**Comment by MariusCC** [comment] 2020-11-29 10:52
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\r\0\0\0\0\0\0\0\x6\0\0\0\x12\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\f\0\0\0\r\0\0\0\xe)
closeAfterScreenshot=true
copyAndCloseAfterUpload=true
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
saveAfterCopy=true
saveAfterCopyPath=/home/marius/Pictures/screenshots
savePath=/home/marius/Pictures/screenshots
startupLaunch=true

**Comment by MariusCC** [comment] 2020-11-29 10:53
> Can you post your config file?

It worked fine with the same config file until a week or tow ago.

**Comment by borgmanJeremy** [comment] 2020-11-30 16:28
Ahh okay, please disable "close after capture" This feature is being removed due to the number of bugs it adds.

Closing as duplicate of #1140

**Closed** 2020-11-30 16:33 UTC
Labels: Bug
