### ISSUE TITLE
Freezed system while making screenshot

### ISSUE THREAD

**Issue by lovermann** [flameshot-org/flameshot#713] opened 2020-04-05 22:38 UTC
**Flameshot version**

**Describe the bug**
I was making screenshot of LibrOffice Calc and wrote explaining text on screenshot in Flameshot. While writing text, I clicked Right Mouse Button to change the color of the text, then my system freezed and I was forced to restart my laptop.

**To Reproduce**
I tried it one more time, but I didn't meet a problem. Unfortunately, I cannot reproduce the bug.

**Expected behavior**

**System Information**
Flameshot v0.6.0
Compiled with Qt 5.9.7

openSUSE Leap 15.1, XFCE

[screenshot](http://www.edustorage.net/thumbs/1000x1000r/flameshot/flameshot_bug_freezed.jpg)

**Comment by borgmanJeremy** [comment] 2020-09-28 00:19
Since this bug is not reproducible and we have squashed many bugs in the 0.8 release I will close this issue.

**Closed by borgmanJeremy** 2020-09-28 00:19 UTC
