### ISSUE TITLE
CLI options do not work on Windows

### ISSUE THREAD

**Issue by thx1200** [flameshot-org/flameshot#1561] opened 2021-04-16 23:06 UTC
**Flameshot version**
0.9.0 x64

**Describe the bug**
Launching Flameshot with any command line option on the Windows build causes Flameshot to launch then exit without doing anything.  Launched with no command line arguments, the interactive tray tool appears.

**To Reproduce**
"C:\Program Files\Flameshot\bin\flameshot.exe" gui
"C:\Program Files\Flameshot\bin\flameshot.exe" config
etc...

**Expected behavior**
Flameshot open and perform the command requested, such as doing a GUI screenshot or showing the config screen.

**System Information**
Windows 10, 1909

**Comment by ZetaoYang** [comment] 2021-04-17 07:57
@mmahmoudian This's not a bug, just haven't been accomplished for WIndows platform.

**Comment by mmahmoudian** [comment] 2021-04-17 07:59
@ZetaoYang so can you or @thx1200 create a Feature Request m, or should we just relabel this as a feature request?

**Comment by ZetaoYang** [comment] 2021-04-17 08:04
> 
> 
> @ZetaoYang so can you or @thx1200 create a Feature Request m, or should we just relabel this as a feature request?

https://github.com/flameshot-org/flameshot/issues/945

**Comment by mmahmoudian** [comment] 2021-04-17 08:45
Then I suggest closing this issue as the other two are in progress.

**Closed by mmahmoudian** 2021-04-17 08:45 UTC
Labels: Unconfirmed Bug, Windows
