### ISSUE TITLE
Stich Multiple Images & Scrolling 

### ISSUE THREAD

**Issue by thorrrr** [flameshot-org/flameshot#2763] opened 2022-07-05 11:07 UTC
### Feature Description

HI

1. Would love the facilty to stich multiple screen shots together after capture.
2. Also a rolling screenshot would be great like a awebpage scroll capture.

I have moved from WIndows and used Fasstone Caputure and Xshare but had this faclity and it is very useful

**Comment by mmahmoudian** [comment] 2022-07-05 19:26
Duplicate of #1130

**Closed** 2022-07-05 19:26 UTC
Labels: Duplicate, Enhancement
