### ISSUE TITLE
CLI arguments doesn't work in Mac OS

### ISSUE THREAD

**Issue by Midren** [flameshot-org/flameshot#1579] opened 2021-04-24 10:19 UTC
**Flameshot version**
v.0.9.0

**Describe the bug**
CLI argument doesn't work in the mac os, as in Linux. So I cannot bind the shortcut to make screenshots. Also, as you cannot launch config from CLI, if you disabled the tray icon in the bar, you are actually trapped and need to find the config file to make flameshot usable again.

**To Reproduce**
1. `cd /Applications/flameshot.app/Contents/MacOS/`
2. `./flameshot config` or `./flameshot gui`

**Expected behavior**
Have the same behavior as in Linux

**System Information**
MacOS Big Sur Version 11.2.3

**Comment by koaie** [comment] 2021-04-25 17:45
can confirm, on big sur with apple silicon.

**Comment by borgmanJeremy** [comment] 2021-04-25 18:50
Duplicate of #1291 work is in progress

**Comment by Midren** [comment] 2021-04-25 19:10
@borgmanJeremy Sorry, but I don't see, how it the duplicate. Moreover, that issue is closed, so I don't know, how I can track progress on the issue.

**Comment by borgmanJeremy** [comment] 2021-04-25 20:01
Oh oops I linked to the wrong issue since I'm on mobile.I'll reopen this until I find the right link.

Right now cli parsing only works on Linux but I'm working on a  refactor to address this.

**Comment by Hanlen** [comment] 2021-05-24 01:53
> Oh oops I linked to the wrong issue since I'm on mobile.I'll reopen this until I find the right link.
> 
> Right now cli parsing only works on Linux but I'm working on a refactor to address this.

The CLI feature is disabled on Windows and MacOS. I can build a package to enable it, but you have to install dbus first by running the command `brew install dbus && brew services start dbus`

**Comment by ianwijma** [comment] 2021-06-06 23:13
I've the same issue on Intel, installed using brew.
version: 0.9.0

**Comment by borgmanJeremy** [comment] 2021-06-06 23:14
It's not a bug it's simply not implemented for anything except Linux.

**Comment by TH-C013** [comment] 2021-07-19 02:28
> > Oh oops I linked to the wrong issue since I'm on mobile.I'll reopen this until I find the right link.
> > Right now cli parsing only works on Linux but I'm working on a refactor to address this.
> 
> The CLI feature is disabled on Windows and MacOS. I built a package to enable it, but you have to install dbus first by running the command `brew install dbus && brew services start dbus`
> The package link I built https://github.com/kingods/flameshot/releases/tag/0.10.0-pci


I've installed dbus but now  I'm not sure how to proceed with the install of the package provided. (https://github.com/kingods/flameshot/releases/tag/0.10.0-pci)
Do you just drop the files in the package on the in the /Applications or need to drop them in a specific location ?

![image](https://user-images.githubusercontent.com/71526018/126093461-070c34d8-12f6-432b-9b8c-a3a78fa21d7b.png)

**Comment by mmahmoudian** [comment] 2021-07-19 05:49
@TH-C013 download the dmg file from the [release section] from the "assets" section of the version you want. Then double-click the dmg file and drag-and-drop the `flameshot.app` in the `/Application` folder (similar to any other app you install from dmg). Then as explained [here](https://flameshot.org/guide/faq/#on-macos-flameshot-only-captures-a-blank-desktop) go to Settings of your Mac, from Security and Privacy give Flameshot screen recording permission.

**Comment by Hanlen** [comment] 2021-07-19 06:23
> > > Oh oops I linked to the wrong issue since I'm on mobile.I'll reopen this until I find the right link.
> > > Right now cli parsing only works on Linux but I'm working on a refactor to address this.
> > 
> > 
> > The CLI feature is disabled on Windows and MacOS. I built a package to enable it, but you have to install dbus first by running the command `brew install dbus && brew services start dbus`
> > The package link I built https://github.com/kingods/flameshot/releases/tag/0.10.0-pci
> 
> I've installed dbus but now I'm not sure how to proceed with the install of the package provided. (https://github.com/kingods/flameshot/releases/tag/0.10.0-pci)
> Do you just drop the files in the package on the in the /Applications or need to drop them in a specific location ?
> 
> ![image](https://user-images.githubusercontent.com/71526018/126093461-070c34d8-12f6-432b-9b8c-a3a78fa21d7b.png)

you can enter the bin Dir, then simply drag the `flameshot` file to the Applications dir.
![flameshot-install](https://user-images.githubusercontent.com/7788177/126112310-92c53269-181a-4df8-b1bf-f2df8b1ec39c.gif)
(url)

**Comment by TH-C013** [comment] 2021-07-19 15:42
> @TH-C013 download the dmg file from the [release section] from the "assets" section of the version you want. Then double-click the dmg file and drag-and-drop the `flameshot.app` in the `/Application` folder (similar to any other app you install from dmg). Then as explained [here](https://flameshot.org/guide/faq/#on-macos-flameshot-only-captures-a-blank-desktop) go to Settings of your Mac, from Security and Privacy give Flameshot screen recording permission.

@mmahmoudian  Thanks got it up and running 👍🏾

**Comment by TH-C013** [comment] 2021-07-19 15:45
> > > > Oh oops I linked to the wrong issue since I'm on mobile.I'll reopen this until I find the right link.
> > > > Right now cli parsing only works on Linux but I'm working on a refactor to address this.
> > > 
> > > 
> > > The CLI feature is disabled on Windows and MacOS. I built a package to enable it, but you have to install dbus first by running the command `brew install dbus && brew services start dbus`
> > > The package link I built https://github.com/kingods/flameshot/releases/tag/0.10.0-pci
> > 
> > 
> > I've installed dbus but now I'm not sure how to proceed with the install of the package provided. (https://github.com/kingods/flameshot/releases/tag/0.10.0-pci)
> > Do you just drop the files in the package on the in the /Applications or need to drop them in a specific location ?
> > ![image](https://user-images.githubusercontent.com/71526018/126093461-070c34d8-12f6-432b-9b8c-a3a78fa21d7b.png)
> 
> you can open the bin Dir, then simply drag the `flameshot` file to the Applications dir.
> ![flameshot-install](https://user-images.githubusercontent.com/7788177/126112310-92c53269-181a-4df8-b1bf-f2df8b1ec39c.gif)
> (url)

@Hanlen Thanks got it up and running 👍🏾

**Closed** 2021-12-08 21:18 UTC
Labels: MacOS

**Comment by rjhilgefort** [comment] 2022-03-25 15:57
@Hanlen  Tried out your fork and seeing this issue when trying to run on the cli.
<img width="729" alt="image" src="https://user-images.githubusercontent.com/2034823/160156475-82265ad3-ea1e-40d6-980e-30c852d0c224.png">

**Comment by rjhilgefort** [comment] 2022-03-25 21:06
@borgmanJeremy Oh great! I couldn't find how to do it and found my way to this issue because the CLI wasn't working. Can you point me and future googlers to docs on how to use Flameshot from the CLI?

**Comment by borgmanJeremy** [comment] 2022-03-25 21:13
@rjhilgefort sure!

It depends a bit on how you installed the program but basically you just need to make sure the binary is in your path, or call it from the fully qualified path:
```
~
❯ /Applications/flameshot.app/Contents/MacOS/flameshot --version
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
```

**Comment by mmahmoudian** [comment] 2022-03-25 21:17
@rjhilgefort 

For installation on macOS read this link:

https://flameshot.org/docs/installation/installation-osx/

and for how to work with CLI take a look at:

https://flameshot.org/docs/advanced/commandline-options/
