### ISSUE TITLE
cli argument to to take a shot of active window

### ISSUE THREAD

**Issue by yt59** [flameshot-org/flameshot#1540] opened 2021-04-07 20:14 UTC
Something like:
```
xfce4-screenshooter -wd 1
```

**Comment by borgmanJeremy** [comment] 2021-04-07 21:14
If you are typing in a terminal isn't the active window the terminal?

**Comment by mmahmoudian** [comment] 2021-04-08 15:17
Can this be duplicate of  #334 ?

**Comment by borgmanJeremy** [comment] 2021-04-08 15:19
Yes

**Closed by borgmanJeremy** 2021-04-08 15:19 UTC
Labels: Waiting For Info
