### ISSUE TITLE
Allow using environment variables in the flameshot.ini file

### ISSUE THREAD

**Issue by strboul** [flameshot-org/flameshot#2486] opened 2022-03-14 08:20 UTC
### Feature Description

It would be useful to allow tilde expansion or environment variables in the `flameshot.ini` config file.

I have dotfiles I use between different user-profiles and I need a dynamic path for the `savePath` key.

```ini
savePath=/home/user/Pictures
# ...
savePath=~/Pictures  # <-- error
# ...
savePath=$HOME/Pictures  # <-- error
```

Version:

```sh
flameshot --version
# Flameshot v11.0.0 (-)
# Compiled with Qt 5.15.2
```

**Comment by mmahmoudian** [comment] 2022-03-14 09:00
Duplicate of #208

**Closed by mmahmoudian** 2022-03-14 09:00 UTC
Labels: Enhancement
