### ISSUE TITLE
A screenshot containing the menu of some application

### ISSUE THREAD

**Issue by xaozai** [flameshot-org/flameshot#2889] opened 2022-08-26 12:35 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.11.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linuxmint 20.3 una, x86_64 Linux 5.4.0-125-generic, xfce4-session 4.16.0

### Description

It is not possible to create a screenshot containing the menu of some application.

### Steps to reproduce

1. Launch some application (for example, Thunderbird)
2. In the running application, open the main menu (for example, click the "Message" item in the Thunderbird main menu).
3. Press the hotkey to take a screenshot (PrtSc).
At this stage, we see that the previously opened application (Thunderbird) menu item has disappeared and it will not be possible to take a screenshot of it.
The same thing happens with any other application, for example with the Firefox browser.

### Screenshots or screen recordings

![Peek 2022-08-26 15-31](https://user-images.githubusercontent.com/8542452/186903997-e1f3d5aa-8e04-44cd-be8a-fcd9b5326057.gif)

### System Information

Linuxmint 20.3 una
x86_64 Linux 5.4.0-125-generic
xfce4-session 4.16.0
x11

**Comment by mmahmoudian** [comment] 2022-08-26 18:33
This is how window managers typically work. If you want to take a photo from such menu, you can either use Launcher or alternatively from CLI use the `--delay`.

I have to close this because this is not a bug, but let me know if you need more help or guidance to get it working

**Closed** 2022-08-26 18:33 UTC
Labels: question

**Comment by xaozai** [comment] 2022-08-29 14:27
> 

To be honest, I didn't understand which launcher I should use to take a screenshot of the app with the menu expanded... :(

**Comment by mmahmoudian** [comment] 2022-08-29 16:12
> which launcher I should use

- Approach 1:
Right click on the tray icon, select Launcher

- Approach 2: run this in terminal to open the launcher:

```sh
flameshot launcher
```

- Approach 3: run this to have a delayed screenshot right from your terminal:

```sh
flameshot gui --delay 2000
```

More information about the CommandLine Interface can be found here:

https://flameshot.org/docs/advanced/commandline-options/

**Comment by xaozai** [comment] 2022-08-30 13:10
OK, thanks!
