### ISSUE TITLE
Flameshot freezes, when I`m coping image to clipboard

### ISSUE THREAD

**Issue by aweone** [flameshot-org/flameshot#1179] opened 2020-12-03 12:06 UTC
Flameshot v0.8.5
Compiled with Qt 5.15.1

I make screenshot with flameshot, and when I press "copy to clipboard" flameshot stoping for 10-15 secs. I cant use my PC, only mouse cursor work. Logs from console:
`QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
`

Running flameshot, making screenshot, pressing "copy to clipboard"

Flameshot freezing for 10-15 secs

Arch Linux, lxde + i3/openbox

**Comment by jeromecst** [comment] 2020-12-05 18:48
Same problem here, using dwm

Flameshot v0.8.5
Compiled with Qt 5.15.1

And same output from console.

**Comment by Feresey** [comment] 2020-12-06 08:50
do you have a notification manager?
before, if notifications were turned on in flmeshot, then it behaved exactly like this

**Comment by pav311** [comment] 2020-12-06 09:03
> do you have a notification manager?
no
> before, if notifications were turned on in flmeshot, then it behaved exactly like this
I disabled notification message from flameshot in his settings, but nothing changed

**Comment by jeromecst** [comment] 2020-12-06 16:19
Update : I think dunst caused the problem.

I uninstalled dunst and now it works as expected.

**Comment by mmahmoudian** [comment] 2020-12-08 11:36
I have dunst version 1.5.0 and it works nicely with Flameshot. I wonder what the issue can be. The part that @Feresey pointed out is true, that Flameshot expects a notification manager.

**Comment by willysr** [comment] 2020-12-09 18:09
I had the same issue on Slackware-Current with Qt 5.15.2 on both Plasma 5 and MATE desktop

**Comment by mmahmoudian** [comment] 2020-12-09 18:42
@willysr considering that they (KDE Plasma and MATE) both have their own notification backend, I highly doubt that your issue is related to this issue. To confirm, would you please provide the following information:
1. your Flameshot version
2. your method of installation of Flameshot
3. try running `notify-send "test"` in terminal and confirm if you see the notification

**Comment by willysr** [comment] 2020-12-10 00:24
@mmahmoudian 
1. 0.8.5
2. via SlackBuilds (https://slackbuilds.org/repository/14.2/graphics/flameshot/ but adjusted to version 0.8.5)
3. no notification here (tested on mate with mate-notification-daemon)

**Comment by mmahmoudian** [comment] 2020-12-10 06:32
@borgmanJeremy  are we really that dependent on notification? Considering that notification is just a quality-of-life feature and is not part of the main functionality of the software, would it be possible to use a try-catch for notification and prevent Flameshot from crashing when notification daemon/service is not available?

**Comment by Arkl1te** [comment] 2020-12-11 18:39
This is happening to me as well. Installed Flameshot via apt command.

```
$ flameshot -v
Flameshot 0.6.0-11(Debian)
Compiled with Qt 5.11.3

$ uname -srvmo
Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```
Using **Debian 10.7** with i3wm 4.16.1 (i3 window manager). 
No desktop environment chosen from OS installation.

**Comment by mmahmoudian** [comment] 2020-12-11 21:43
@Arkl1te Your Flameshot is from Aug 17, 2018. The newest version is 0.8.5 which is released in Oct 15, 2020 . Please update your Flameshot.

In case your Ubuntu repository does not have the recent versions, you can uninstall it from apt and install it via snap or flatpak. You can also download the .deb file from [the release page](https://github.com/flameshot-org/flameshot/releases/latest) and install it via the following command (get the Ubuntu version that corresponds to your Debian):

```sh
sudo dpkg -i flameshot-0.8.5-1.ubuntu-20.04.amd64.deb
```

-------

Now, back to your point, you most probably are lacking a notification daemon. Try installing for example the one I use is  "[dunst](https://dunst-project.org/screenshots/)" which is a "customizable and lightweight notification-daemon".

**Comment by borgmanJeremy** [comment] 2020-12-12 01:42
It may be possible to refactor the code to work without a notification manager but it's not high on my priority list. 

Primarily because ever larger feature flag doubles the amount of testing I need to do each release and we already are understaffed to add features / close bugs. Additionally this strikes me as something that is useful to 1% of our user base, so I don't want to take on a large amount of work for a small payoff.

**Comment by Arkl1te** [comment] 2020-12-12 03:05
> @Arkl1te You can also download the .deb file from [the release page](https://github.com/flameshot-org/flameshot/releases/latest) and install it via the following command (get the Ubuntu version that corresponds to your Debian):
> 
> ```shell
> sudo dpkg -i flameshot-0.8.5-1.ubuntu-20.04.amd64.deb
> ```

@mmahmoudian I appreciate the info. I tried first as you suggested, the `flameshot-0.8.5-1.debian-10.amd64.deb`:
```bash
$ flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.11.3
```
Then the `buster-backports` release. Despite the version, the same freeze keeps happening.

```bash
$ flameshot --version
Flameshot v0.8.5-1_bpo10+1(Debian)
Compiled with Qt 5.11.3
```

Console log is the same for
* `v0.8.5`, and
* `v0.8.5-1_bpo10+1(Debian)`

as follows:
```
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

**Comment by mmahmoudian** [comment] 2020-12-12 12:10
@Arkl1te please install a notification daemon as I suggested in my previous comment.

**Comment by willysr** [comment] 2020-12-12 12:31
This is not flameshot's fault, but it roots from single dbus name for all of them and there's a race situation about who gets the name. If the winner doesn't get activated in your DE, then flameshot will not be able to use it.

i solved my issue by making changes in mate-notification-daemon so that it became the primary notification daemon instead of being taken by other notification daemon.

**Comment by pavel-the-best** [comment] 2020-12-16 07:37
seems related:
https://github.com/flameshot-org/flameshot/blob/master/src/utils/screenshotsaver.cpp#L30
```// TODO: If data is saved to the clipboard before the notification is sent via
// dbus, the application freezes.```

**Comment by mmahmoudian** [comment] 2020-12-27 09:18
@sffred can you confirm that you have notification manager/daemon?

Example test:
```sh
notify-send "test"

```

**Comment by sffred** [comment] 2021-01-03 01:51
@mmahmoudian You are right. I haven't installed a notification server. After I installed notification-daemon and start it, the issue was solved.

**Comment by khalil2535** [comment] 2021-01-10 21:08
It worked after installing `dunst`.

**Comment by bloodnighttw** [comment] 2021-01-30 09:05
I got the same problem on i3wm (arch linux).
And I Install dunset,run it.
The problem is solved.

And pls consider add this solution for those who don't have notification-daemon in README.md.
(Sorry for my bad english)

**Comment by Chaeold** [comment] 2021-04-11 07:55
> I went to add the option to disable notifications and saw it was already in the code base. Can someone try the following:
> 
>     1. Remove dunst
> 
>     2. In the flameshot config file add: showDesktopNotification=false
> 
>     3. Run flameshot and hit the copy button

work for me, best solution

**Comment by borgmanJeremy** [comment] 2021-04-13 00:17
Great, thanks for reporting back.

**Closed by borgmanJeremy** 2021-04-13 00:17 UTC

**Comment by althedoc** [comment] 2021-05-24 16:33
I had the same problem on Fedora KDE, Flameshot 0.9.0

`sudo dnf install dunst`

Solved the problem :)
