### ISSUE TITLE
Macbook Pro 14" & 16" 2021 - screenshot crop bottom of screen

### ISSUE THREAD

**Issue by sbissonnette** [flameshot-org/flameshot#2636] opened 2022-05-31 21:06 UTC
### Flameshot Version

11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

MacOS 12.4

### Description

If using a Macbooks Pro 14" or 16" (those with Notch), taking a screenshot crop the bottom of the screen. This isnt an issue on a separate monitor, only the screen of the laptops.

### Steps to reproduce

1. Run flameshot
2. Notice the bottom part of the screen being crop on latest Macbook Pro 14" & 16" (2021 model)

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/45381174/171282935-4306040b-89ca-4c8a-be51-73dc07706552.png)

### System Information

Macbook Pro 14" (2021)
MacOS Monterey 12.4 
![image](https://user-images.githubusercontent.com/45381174/171284267-360597a4-746a-4a1e-affc-3127d5e6a39c.png)
![image](https://user-images.githubusercontent.com/45381174/171284302-fe8d6271-9874-4f53-bc05-6232c56fe260.png)

**Comment by mmahmoudian** [comment] 2022-06-01 05:17
Duplicate of #2612

**Closed** 2022-06-01 05:17 UTC
Labels: Duplicate, Unconfirmed Bug
