### ISSUE TITLE
Add the function of rotating screenshots after screenshots

### ISSUE THREAD

**Issue by liuqi0202** [flameshot-org/flameshot#2644] opened 2022-06-03 01:32 UTC
### Feature Description

Add the function of rotating screenshots after screenshots
能否增加截图固定于屏幕后，旋转该截图的功能。谢谢！

**Comment by mmahmoudian** [comment] 2022-06-03 08:09
Duplicate of ##2214

**Closed by mmahmoudian** 2022-06-03 08:09 UTC
Labels: Enhancement
