### ISSUE TITLE
Windows- change global keybind from prtscn to ctrl+shift+s

### ISSUE THREAD

**Issue by barelyadev** [flameshot-org/flameshot#3133] opened 2023-03-17 14:42 UTC
### Feature Description

Before lightshot i've been using lightshot and sharex- both of them allowed to set custom keybind to start the tool.

Flameshot is superior to both in terms of functionality, speed and ease of use but old habits die hard, and i can't get my head around to pressing the prtscn to start the flameshot.

In flameshot the menu is grayed out- i was hoping to set this in \flameshot\flameshot.ini but docs say nothing about it for windows. Did i miss something, or is it an actual feature that has to be requested (if so, consider this a request, please:) ).

**Comment by mmahmoudian** [comment] 2023-03-18 06:55
Currently this has not been implemented for Windows. As a feature request it is duplicate of:

- #2167
- #1341

**Closed** 2023-03-18 06:55 UTC
Labels: Duplicate, Enhancement
