### ISSUE TITLE
Timestamp feature

### ISSUE THREAD

**Issue by dienavarrete** [flameshot-org/flameshot#3217] opened 2023-06-05 18:46 UTC
### Feature Description

I would like to have an option to add timestamp directly burn in the image

**Comment by jroeber** [comment] 2024-02-21 23:49
This would be very nice to have. If I take screen captures of webpages that might change over time, I want to easily put a date/time mark in the image so I can remember when I took the screenshot. I know Flameshot automatically includes the date/time in the filename, but filenames can be changed easily. I'd like to instead imprint that info into the image itself.

I know there is the option to use an external program (https://github.com/flameshot-org/flameshot/issues/158), but that is a hassle. Just a button in Flameshot that lets me place a timestamp somewhere would be great, maybe with some program setting to give it a format according to the Linux `date` command.

**Comment by dienavarrete** [comment] 2024-04-09 23:54
> Do you mean as a watermark?

Yes!

**Comment by mmahmoudian** [comment] 2024-04-11 12:16
@dienavarrete As @jroeber kindy mentioned, this issue is duplicate of #158 in which I provided a way to do it for now in Linux, but this feature request is still open in #158 .



@jroeber 
> I know Flameshot automatically includes the date/time in the filename, but filenames can be changed easily. I'd like to instead imprint that info into the image itself.

Regardless of this watermark feature, I would like to suggest you a good way to store date information into the screenshot:

```sh
# to write the Date/Time Original
exiftool -DateTimeOriginal="2024-04-11 15:11" my-beautiful-screenshot.png

# to read the Date/Time Original
exiftool -DateTimeOriginal my-beautiful-screenshot.png

# to read all metadata of the picture
exiftool my-beautiful-screenshot.png
```

This way if your file name is changed, you still have the metadata. Also unlike the watermark that cannot be read as a text, the metadata can be read as text and is handy for writing scripts.

More information and useful links:
- https://exiftool.org
- https://linuxconfig.org/how-to-get-and-change-image-metadata-in-linux

**Closed by mmahmoudian** 2024-04-11 12:16 UTC
Labels: Enhancement

**Comment by unnohwn** [comment] 2024-12-18 08:54
Also missing watermark with time and date! A must for my area of ​​use.
