### ISSUE TITLE
Failure to paste from clipboard

### ISSUE THREAD

**Issue by bec2** [flameshot-org/flameshot#1035] opened 2020-10-08 12:21 UTC
**Flameshot version**
0.8.3
Installed from flameshot-0.8.3-1.fc31.x86_64.rpm 
From the releases page of this repo

**Describe the bug**
First of all, thank you so much for all your hard work maintaining this app :) 
Both this and the previous version of Flameshot I had installed (0.6 series) have had the same error in which the image captured fails to paste from the clipboard.

**To Reproduce**
I select an area and press the copy to clipboard button, following which I got a notification of success. However, when it came to pasting into any of my apps (I have tried LibreOffice, Google Docs, and Discord) the clipboard appears empty. I do not use any special clipboard managers which may cause conflicts. Also, I have searched online for similar issues in forums etc. and it does not seem to return anything.

**Expected behavior**
I would like to copy/paste from the clipboard; it should be noted that my clipboard works as expected for any other purposes.

**System Information**
Fedora 31 WE

Again, thank you so much for your time. Apologies if I filled some of this out incorrectly - it's my first time filling out a bug report.

**Comment by borgmanJeremy** [comment] 2020-10-08 13:24
Thanks for all the details. A couple questions:

Do you see the flameshot tray icon before and after hitting copy? Or are you launching flameshot in such a way that it closes after copy?

**Comment by bec2** [comment] 2020-10-08 15:24
I'm running it as follows; I haven't changed any settings or anything (close after capture has not been checked):
- Right clicking on the program icon and doing 'Take Screenshot'
- Taking my screenshot and adding it to the clipboard by pressing the two squares
- The program closes itself
- Getting the tray notification with the flameshot icon saying that the copy to clipboard was successful

**Comment by ZetaoYang** [comment] 2020-10-08 15:56
I confirmed this bug appears on wayland envrionment, tested on Fedora 32 Gnome Wayland.

**Comment by AndydeCleyre** [comment] 2020-10-17 20:21
I'm using X, on Arch Linux, and Plasma Desktop (with klipper). I am unable to paste the images, though ~they are~ **something is** in the clipboard, since the upgrade from `0.6.0` to `0.8.0`. It's as if the ~type of~ clipboard content isn't set.

I do have set:

```ini
closeAfterScreenshot=true
```

So I compared the output of `xclip -sel clip -o -t TARGETS` between the versions, after saving a screenshot to clipboard with each. They're *nearly* identical, include many image formats, and start with `application/x-qt-image`; but:

- `0.8.0`: `application/x-kde-onlyReplaceEmpty` is the second target, just before `image/png`
- `0.6.0`: flameshot stays open after copying to clipboard
- `0.6.0`: killing flameshot, then pasting, still pastes properly
- `0.6.0`: killing flameshot adds that `application/x-kde-onlyReplaceEmpty`

So that extra target isn't the problem, it's just a result of using klipper's prevent-empty-clipboard feature and killing flameshot.

Ah, but:

- `0.8.5`: setting `closeAfterScreenshot=false` pastes properly, even after manually killing flameshot
- `0.8.5`: with `closeAfterScreenshot=true`, `xclip -sel clip -o -t image/png` produces nothing

So it seems to be related to the *way it sets the clipboard when auto-close is enabled.* It looks like it's empty data. klipper displays it as `0x0 0bpp`.

But given that this is only when auto-close is enabled, is this a totally different issue from OP's?

```ini
[General]
closeAfterScreenshot=true
copyAndCloseAfterUpload=true
disabledTrayIcon=true
drawColor=#00ff00
drawThickness=28
saveAfterCopy=true
saveAfterCopyPath=/home/andy/Images
savePath=/home/andy/Images
```

**Comment by hparlak** [comment] 2020-11-23 12:55
I have the same problem ( #635 ) , which @mmahmoudian just mentioned, and it is not only when auto-close is enabled.
Flameshot v0.8.5
Compiled with Qt 5.15.1
--
wayland /gnome 3.38.1 / Fedora 33
--
Linux appc 5.9.8-200.fc33.x86_64 #1 SMP Tue Nov 10 21:58:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
--
  *-display                 
       description: VGA compatible controller
       product: HD Graphics 5500
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:43 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:3000(size=64) memory:c0000-dffff
--
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x14\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\f\0\0\0\r\0\0\0\xe\0\0\0\x11)
closeAfterScreenshot=false
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
saveAfterCopy=false
saveAfterCopyPath=/home/.../Pictures
savePath=/home/.../Pictures
showDesktopNotification=true
showHelp=true
showSidePanelButton=true
startupLaunch=true

**Comment by jlogar** [comment] 2020-11-25 08:26
I can confirm this on F33, Wayland, flameshot 0.8.5.

**Comment by leadenhead** [comment] 2021-01-13 22:07
**The same issue.**
_command to take screeshot_: `flameshot gui`, then press `ctrl+c` or click `copy to clipboard` icon.
Then `ctrl + v` and nothing happens...

ArchLinux / spectrwm / xorg
Flameshot v0.8.5, Compiled with Qt 5.15.1
`closeAfterScreenshot=true`

**Comment by borgmanJeremy** [comment] 2021-02-06 01:28
The original bug in this issue was related to wayland. This is fixed with #1282 .

The other issue with closeAfterCapture has already been resolved on master branch (by removing close after capture feature).

**Closed by borgmanJeremy** 2021-02-06 01:28 UTC
Labels: Bug, Linux, Wayland

**Comment by leandrocastro** [comment] 2021-12-07 21:05
This same problem continues for me.
Version 0.10.2
Ubuntu 20.04

**Comment by tonio-m** [comment] 2022-04-14 20:27
hi, Im having the same issue on Arch linux. with  xorg-server 21.1.3-6

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
