### ISSUE TITLE
Gnome 42, AppIndicator stretched

### ISSUE THREAD

**Issue by techyporcupine** [flameshot-org/flameshot#2541] opened 2022-04-09 23:50 UTC
### Flameshot Version

Flameshot v11.0.0 (-)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 36, Gnome 42

### Description

When looking at the flameshot icon in the status bar, it is akwardly stretched. I can give any more info if required.

### Steps to reproduce

1. Start flameshot so the icon appears in top bar
2. Look at the icon
3. Notice it is stretched

### Screenshots or screen recordings

Attached here is an image of my top bar.
![ZAG8TKZSQCZmm7WswCr](https://user-images.githubusercontent.com/70345789/162736486-fe71514c-a9bc-4289-bf50-6475b15250de.png)

### System Information

Fedora 36
Gnome 42
2x Dell P2210 60hz monitors running in landscape side by side. 
Xorg

**Comment by mmahmoudian** [comment] 2022-04-10 19:30
Please always upload the images to Github itself. It is a matter of privacy and security. I have removed the potentially malicious URL. Edit your post and upload to GitHub.

**Comment by techyporcupine** [comment] 2022-04-11 12:10
Done.

**Comment by techyporcupine** [comment] 2022-04-12 10:33
Seems to have been fixed/fixed itself.
![image](https://user-images.githubusercontent.com/70345789/162941562-e8edd270-6d34-4ab5-986a-7fc7bffc1845.png)

**Comment by mmahmoudian** [comment] 2022-04-12 10:57
@techyporcupine what changed? dod you update anything or rebooted?

**Comment by techyporcupine** [comment] 2022-04-12 11:02
I may have ran `sudo dnf update` but I don't think it did anything with flameshot. I did reboot once.

**Comment by mmahmoudian** [comment] 2022-04-13 14:06
I cannot reproduce this in a clean VM of Fedora 36 and Gnome 42.

![2022-04-13_17-03](https://user-images.githubusercontent.com/390889/163198350-ad1daa40-9455-4d8a-9257-11034ea78467.png)

I will close this as:
1. Fedora36 is not a stable release and you are even warned about it during installation
2. this is not reproducible
3. since Gnome does not have systray capability and you have to side-load a shell extension, this issue can well be for that shell extension or your installation method, or Gnome, or Fedora, or ...

**Closed by mmahmoudian** 2022-04-13 14:06 UTC
Labels: Unconfirmed Bug
