### ISSUE TITLE
CLI usage doesn't work in Flatpak edition

### ISSUE THREAD

**Issue by Victor239** [flameshot-org/flameshot#1177] opened 2020-12-01 14:22 UTC
**Flameshot version**
v.0.8.5

**Describe the bug**
When trying to use Flameshot via command line it shows the error message `bash: /usr/bin/flameshot: No such file or directory` and doesn't work. 

**To Reproduce**
Use the command `flameshot gui` for example. 

**Expected behavior**
Should work, but it doesn't.

**System Information**
Kubuntu 20.04

**Comment by cerulis64** [comment] 2020-12-14 23:31
This is because Flatpak applications do not place binaries in `/bin` (similar to Docker).
`/usr/bin/flameshot` not existing is *expected behaviour* due to Flatpak applications being run in containers.

To run `flameshot gui`, just run `flatpak run org.flameshot.Flameshot gui`

**Comment by mmahmoudian** [comment] 2020-12-23 11:59
@Victor239 the answer @cerulis64 gave is correct. Flatpak by design is not behaving like a normal binary. Try what @cerulis64 said and please report back if it works or not, so that we can either close this issue or investigate this.

**Comment by Victor239** [comment] 2020-12-23 14:19
Yup that Flatpak command works fine, thanks for the help.

**Closed** 2020-12-23 19:06 UTC

**Comment by andrew-attard** [comment] 2024-06-14 10:12
> This is because Flatpak applications do not place binaries in `/bin` (similar to Docker). `/usr/bin/flameshot` not existing is _expected behaviour_ due to Flatpak applications being run in containers.
> 
> To run `flameshot gui`, use `flatpak run org.flameshot.Flameshot gui` instead

This did the trick for me in 2024 :)
