### ISSUE TITLE
flameshot gives error when trying to upload to imgur

### ISSUE THREAD

**Issue by kaiakrystal** [flameshot-org/flameshot#3244] opened 2023-06-27 15:22 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

PoPOS 22.04

### Description

When choosing the upload selection on flameshot, I get an error message.
" Error transferring https://api.imgur.com/3/image?title-&description-2023-06-274_09-10 - server replied: Unknown Error "

### Steps to reproduce

1. use key command to run flameshot gui
2. select region to clip
3. choose upload option
4. get error message stated above

### System Information

System:
Linux pop-os 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux

Monitors: 2
 0: +*HDMI-0 1920/700x1080/390+1920+0  HDMI-0
 1: +DP-5 1920/477x1080/268+0+0  DP-5
![system monitor](https://github.com/flameshot-org/flameshot/assets/65958725/b972cb89-402b-4649-9798-2d4992c946d4)

**Comment by mmahmoudian** [comment] 2023-06-27 18:29
Thanks for filing this issue, but few points:
1. Please always search among open *and* closed issues. This can help you find the answer faster and also avoid creating duplicate issue
2. We are at version 12.1.0 and you are using v11.0.0 . During this time lots of bug have been fixed
3. We do not manage Imgur. Flameshot just facilitates the upload process for you. Any error returned by Imgur is not something we can change. Please read the issue below for a remedy:

This issue is duplicate of #3080

**Closed by mmahmoudian** 2023-06-27 18:29 UTC
Labels: Unconfirmed Bug
