### ISSUE TITLE
2 important things

### ISSUE THREAD

**Issue by LEV7n** [flameshot-org/flameshot#1112] opened 2020-10-28 11:48 UTC
Hi, it possible to do 2 these features?

1. ![image](https://user-images.githubusercontent.com/3475776/97431870-e1aee600-193c-11eb-9b60-ef9cc512f927.png)
![image](https://user-images.githubusercontent.com/3475776/97431907-f3908900-193c-11eb-83cc-6f695b956861.png)
to use these patterns ![image](https://user-images.githubusercontent.com/3475776/97431959-07d48600-193d-11eb-89f3-e409c97ec7fb.png) not only for filename but for folder too, if folder {%Y-%m} doesn't exists in /Screenshots then create it, else store file in folder.

2. Capture active window
it will helpful when need to capture active window, not want waste time to draw square and then capture it.

Thanks

**Comment by mmahmoudian** [comment] 2020-10-29 09:03
@LEV7n We encourage people to post one "feature request"/"bug report" per issue for the reason that it would be possible to discuss them independently and also they typically have separate development process which can potentially be assigned to two different developers.

Considering that your second feature request is duplicate of #334 and #395, you can change the title of this issue to reflect your first feature request.

**Comment by borgmanJeremy** [comment] 2020-10-29 17:41
I believe the first request is also a duplicate of #510. I have no issues supporting this, let me mark #510 as a good first issue. 

I will also close this out since they are both duplicates.

**Closed by borgmanJeremy** 2020-10-29 17:41 UTC
Labels: Enhancement
