### ISSUE TITLE
Tools appear way on the left, not attatched to the frame.

### ISSUE THREAD

**Issue by alexandrerufato** [flameshot-org/flameshot#1584] opened 2021-04-26 21:56 UTC
Flameshot version: v0.9.0

**Describe the bug**
Whenever I try capturing something on the screen, occasionally the tools for marking something up on the selected image go all the way up left on my left monitor. The screen on the right is the default one inside the windows options.
![Error](https://user-images.githubusercontent.com/37677664/116138428-2d9fd500-a6ab-11eb-9b97-fa3b8cd37ecd.png)

**To Reproduce**
Unclear how it starts, I use the tool frequently during the day and one time it works as expected and the other it does not. But, when it happens, if you try to capture something on the left monitor, the issue can go away for the next time it's used but not always.

https://user-images.githubusercontent.com/37677664/116155755-eae8f780-a6c0-11eb-978e-21ec05a8aa1c.mp4

**Expected behavior**
The tools should always appear along the marked section.

**System Information**
platform: Windows 10 pro 64-bit
dual screen: 1x 1920x1080 (left) + 1x 2560x1080 (right)

Thanks in advance!

**Comment by mmahmoudian** [comment] 2021-04-27 06:19
Duplicate of #1440

**Closed** 2021-04-27 06:19 UTC
Labels: Duplicate
