### ISSUE TITLE
Flameshot not working on Plasma Wayland

### ISSUE THREAD

**Issue by DemonicSavage** [flameshot-org/flameshot#2660] opened 2022-06-12 14:46 UTC
### Flameshot Version

```
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3
```

### Installation Type

Flatpak from Flathub

### Operating System type and version

Arch Linux

### Description

When I open Flameshot and click on "Take Screenshot" in the system tray icon, nothing happens.
"Open Launcher" opens the launcher, but "Take new screenshot" does nothing.

### Steps to reproduce

1. Run Flameshot
2. Click on "Take Screenshot" on system tray icon

### System Information

```
System:
  Host: Belphegor Kernel: 5.18.3-zen1-1-zen arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Device-2: Generalplus GENERAL WEBCAM type: USB
    driver: snd-usb-audio,uvcvideo
  Display: wayland server: X.org v: 1.21.1.3 with: Xwayland v: 22.1.2
    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
    gpu: amdgpu resolution: 1: 1920x1080 2: 1920x1080
  OpenGL: renderer: AMD Radeon RX 6600 XT (dimgrey_cavefish LLVM 13.0.1 DRM
    3.46 5.18.3-zen1-1-zen)
    v: 4.6 Mesa 22.1.1
```

Both `xdg-desktop-portal` and `xdg-desktop-portal-kde` are installed.

**Comment by LennyPenny** [comment] 2022-06-12 19:48
I can confirm the same problem on the fedora 36 KDE spin. 

```
~ 7.5s ❱ flameshot --version
Flameshot v11.0.0 (-)
Compiled with Qt **5.15.2**
```

```
OS: Fedora release 36 (Thirty Six) x86_64
Kernel: 5.17.13-300.fc36.x86_64
DE: Plasma 5.24.5
```

**Comment by cprpolo** [comment] 2022-06-14 09:44
Same thing happening in Manjaro Wayland:

`flameshot -v                                                                                                                                                                                                        
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3  `


` OS: Manjaro Linux x86_64
Kernel: 5.17.14-1-MANJARO
DE: Plasma 5.24.5`

**Comment by mmahmoudian** [comment] 2022-06-14 10:06
I can confirm this issue in a clean install Fedora 36 Wayland KDE in VM and installed Flameshot v11.0.0 using `sudo dnf install flameshot`.

As explained, when left-clicking on Flameshot tray icon "nothing happens" (i.e no error or notification). The same with when I right-click on the tray icon and click Take Screenshot".

When I kill Flameshot and run `flameshot gui`, I get the following:

![image](https://user-images.githubusercontent.com/390889/173551594-3e0cf49e-3a68-46c1-b140-ce18db646eb1.png)

**Comment by borgmanJeremy** [comment] 2022-06-14 13:44
@mmahmoudian If i build from source this is not an issue so I suspect we have already resolved this. Please follow the steps below. It's a little strange on KDE wayland because of the way the security works (you need to copy the binary to match the path in the .desktop file)
```
dnf install flameshot # Hack to install runtime files
dnf install kf5-kguiaddons-devel # Required for wayland clipboard on KDE


git clone https://github.com/flameshot-org/flameshot
cd flameshot
mkdir build
cd build
cmake -GNinja -DUSE_WAYLAND_CLIPBOARD=True ../
ninja
sudo cp ./src/flameshot /usr/bin/flameshot
```

**Comment by mmahmoudian** [comment] 2022-06-14 14:38
@borgmanJeremy 
if `kf5-kguiaddons-devel` (in Arch `kguiaddons`) is always required in wayland, should we add it as dependency?

> If i build from source this is not an issue

I can confirm that, although I had to install `qt5-qtsvg-devel` as a dependency for compiling as well.

btw, while testing it, I realized that one of out SVGs are not rendered properly:

![image](https://user-images.githubusercontent.com/390889/173604468-22e19f3d-754b-4411-8bcc-349e28353ec6.png)

**Comment by mmahmoudian** [comment] 2022-06-14 14:57
@borgmanJeremy Done: #2667

**Comment by lenny-optiopay** [comment] 2022-06-15 13:48
@borgmanJeremy this issue is not related to the SVG thing, please reopen

**Comment by LennyPenny** [comment] 2022-06-15 13:49
@borgmanJeremy this issue is not related to the SVG thing, please reopen

**Comment by borgmanJeremy** [comment] 2022-06-15 13:50
This is resolved on the master branch. I tested on fedora 36

**Comment by LennyPenny** [comment] 2022-06-15 13:51
What about this optional dependency that is required for plasma? If its not included then its not really
 resolved I guess

**Comment by borgmanJeremy** [comment] 2022-06-15 13:52
That's not a flameshot issue, that's something that needs to be resolved with your distribution

**Comment by Victor239** [comment] 2022-06-15 15:27
@borgmanJeremy this issue is regarding the Flatpak. There should be no additional distro-specific packages that need to be installed, otherwise what's the point of Flatpak?

**Comment by borgmanJeremy** [comment] 2022-06-15 15:28
Ah I was testing the RPM. Let me see if the latest flatpak works.

**Comment by borgmanJeremy** [comment] 2022-06-15 17:04
I tested the latest flatpak from our CI and it is working on Fedora 36 KDE. I'll have the version 12 beta out today or tomorrow so if you want to wait to test that I would appreciate it.

**Comment by DemonicSavage** [comment] 2022-06-15 17:30
Is the issue where it only works on one screen already known, or should I file another bug report?

**Comment by Victor239** [comment] 2022-06-16 14:34
@borgmanJeremy thanks, will that be on Flathub Beta channel or the normal Flathub? Also could you reopen this issue?

@DemonicSavage #2364

**Comment by mmahmoudian** [comment] 2022-06-17 08:23
@Victor239 
> Also could you reopen this issue?

Sure, but considering the sheer volume of issues we should keep track of, please remind me to close this issue when/if it was resolved.

**Closed** 2022-06-17 14:16 UTC
Labels: Bug, Wayland

**Comment by SpidFightFR** [comment] 2022-06-25 15:55
i installed the [flameshot-git](https://aur.archlinux.org/packages/flameshot-git) package from the AUR, it doesn't seem to work.
The other version of the package, [flameshot](https://archlinux.org/packages/community/x86_64/flameshot/) does work but the app works weirdly: it "casts" my main screen on the second screen and i have to capture my main screen on the second one.

It's weird.
