### ISSUE TITLE
Dual Monitors at different heights cause incorrect positioning of tool buttons

### ISSUE THREAD

**Issue by yamanq** [flameshot-org/flameshot#1346] opened 2021-02-18 03:31 UTC
**Flameshot version**

Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**

In a dual monitor setup where one monitor is at a different height than the other, tools will arrange themselves on the horizontal level of the other monitor. This [comment](https://github.com/flameshot-org/flameshot/issues/564#issuecomment-644154420) has the same issue, but I do not use any scaling.

Some screenshots:
![2021-02-17_22-19](https://user-images.githubusercontent.com/8166212/108300788-f96ddc80-716e-11eb-9cea-4739d1bf2c34.png)
![2021-02-17_22-24](https://user-images.githubusercontent.com/8166212/108300791-fd016380-716e-11eb-90b1-a6cb1ee86ebd.png)

**To Reproduce**

1. Set two monitors at different heights
![image](https://user-images.githubusercontent.com/8166212/108301203-81ec7d00-716f-11eb-8792-30278ffb2eba.png)
2. Start flameshot gui
3. Create a selection that overlaps with the top or bottom of the other screen.
4. There is a line of tools that aligns with the top or bottom of the other screen, but is inside the selection box.

**Expected behavior**

Tool buttons should be arranged around the outside of the selection box.

**System Information**

Arch Linux with KDE Plasma

**Comment by thepurple** [comment] 2021-02-18 07:11
I can confirm that. I fixed the same issue for MacOS, but the fix doesn't work for Linux and possibly Windows.

**Comment by borgmanJeremy** [comment] 2021-02-18 14:50
Believe this is a duplicate of #1070

**Closed by borgmanJeremy** 2021-02-18 14:50 UTC
