### ISSUE TITLE
Sometimes the "numeration" feature skips some numbers

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#1213] opened 2021-01-03 02:47 UTC
**Flameshot version**
Flameshot v0.8.5-1(Debian)
Compiled with Qt 5.14.2

loginctl show-session $(loginctl show-user $(whoami) -p Display --value) -p Type --value
x11

**Describe the bug**
Sometimes the "numeration" feature skips some numbers

**To Reproduce**
Not consistent

**Expected behavior**
Show numbers sequentially

**System Information**
5.7.17-1rodete4-amd64 #1 SMP Debian 5.7.17-1rodete4 (2020-10-01) x86_64 GNU/Linux

**Comment by mmahmoudian** [comment] 2021-01-03 10:01
I have experienced this. It is not deterministic and therefore I also about provide steps to reproduce.

**Comment by elad2109** [comment] 2021-01-03 12:03
"I also about provide steps to reproduce" ?

**Comment by mmahmoudian** [comment] 2021-01-03 12:07
@elad2109 srry, bad autocorrect. I just modified my comment

**Comment by borgmanJeremy** [comment] 2021-01-04 19:09
@mmahmoudian You have experienced this too?

**Comment by mmahmoudian** [comment] 2021-01-04 20:53
@borgmanJeremy yes, few times already.

**Comment by kpcee** [comment] 2021-01-11 21:48
I don't know if the bug I found is related to the one described here, but I found a way to mess up the numeration (version 0.8.5).

* Select the tool and place some numbers
* Open "Tool Settings" on the left and click through the list "Circle Counter"
* Then place more counters, they contain unreadable text afterwards, but after a few clicks it works again. See screenshot. 
![2021-01-11_22-39](https://user-images.githubusercontent.com/39984895/104241937-ad889300-545e-11eb-9fb3-297f284cd8e7.png)

**Comment by borgmanJeremy** [comment] 2021-01-11 21:50
Perfect, this is a great lead I'll start looking at.

**Comment by elad2109** [comment] 2021-01-14 00:55
> I don't know if the bug I found is related to the one described here, but I found a way to mess up the numeration (version 0.8.5).


1) How did you put a "zero" or any other text?
2) How were you able to double "1"?

**Comment by kpcee** [comment] 2021-01-17 12:14
You can mess up the counter by using the Tool Settings. I guess the internal counter is subtracted and doesn't reset properly when you click back and forth in the list, which is why it can take on negative values.

**Comment by elad2109** [comment] 2021-01-17 13:33
> You can mess up the counter by using the Tool Settings.

How do you use the "tool settings" while in a capture mode after you added a few counters? with a backspace?

**Comment by mmahmoudian** [comment] 2021-01-17 13:46
@borgmanJeremy I tried to test the hypothesis @kpcee mentioned and I got super interesting bug:

![Peek 2021-01-17 15-41](https://user-images.githubusercontent.com/390889/104844771-bf44bd00-58da-11eb-9a1a-fd2549d11b85.gif)


Basically this is how it goes:
1. start the Flameshot
2. select the "auto incrementing counting bubble" tool
3. add some numbers to kinda fill the history of actions
4. open the "Tool Settings" and shuffle through the history
5. place one more bubble
6. if you didn't see the error, go to step 4


Flameshot version 0.8.5

**Comment by mmahmoudian** [comment] 2021-01-17 13:51
> > You can mess up the counter by using the Tool Settings.
> 
> How do you use the "tool settings" while in a capture mode after you added a few counters? with a backspace?
either press <kbd>SPACE BAR</kbd> or click on the button on the far left of the screen.

**Comment by kpcee** [comment] 2021-01-17 15:11
> P.s: I never could generate negative numbers though.

Yes, negative numbers are not possible. I didn't look into the source but the counter must use unsigned int, so negative values are not possible (value range 0 - 4.294.967.295) which exactly matches the displayed number in the screenshot and why the counter starts again at 0. The problem is probably that the counter is not reset correctly when you go back to the front in the history.

**Comment by borgmanJeremy** [comment] 2021-01-20 01:15
Ok thanks, I found the root cause. When you click "back" through the tool history, there is a call to the decrement function for each item in the list. So if you click back 4 in the stack, it will decrement 4 times as it should. However if you click forward in the list 4, it only calls to increment once. This allows you to get negative numbers. The proper solution is to make sure we call increment the proper number of times.

**Comment by borgmanJeremy** [comment] 2021-01-22 01:24
This should be fixed with PR #1251 @mmahmoudian if you want to test the app image it should be in the CI, otherwise I'll merge it to main tomorrow.

**Comment by mmahmoudian** [comment] 2021-01-22 09:18
@borgmanJeremy I got some error. I got the link from [appimage action](https://github.com/flameshot-org/flameshot/pull/1251/checks?check_run_id=1745961429) and:

```sh
wget "https://github.com/flameshot-org/flameshot/suites/1876911134/artifacts/36609068"
unzip -d "Linux-distribution-artifact" "Linux-distribution-artifact.zip"
chmod +x "Linux-distribution-artifact/Flameshot-0.8.5.x86_64.AppImage"
./Linux-distribution-artifact/Flameshot-0.8.5.x86_64.AppImage
```

> ```
> Run experimental self-contained bundle
> /tmp/.mount_FlamesxSRJ59/AppRun: line 84: /tmp/.mount_FlamesxSRJ59/usr/lib64/ld-linux-x86-64.so.2: Permission denied
> /tmp/.mount_FlamesxSRJ59/AppRun: line 84: /tmp/.mount_FlamesxSRJ59/usr/lib64/ld-linux-x86-64.so.2: Success
> ```

**Comment by kpcee** [comment] 2021-01-22 10:29
Looks very good, I can no longer reproduce the bug. :+1:

By the way, I have a guess how it can happen that numbers are omitted. This can easily happen by unintentional double clicks. This can be prevented either by setting a time limit until the next item can be set or by preventing the coordinates of the previous and the new item from being identical.
![Beispiel](https://user-images.githubusercontent.com/39984895/105479244-87f05a80-5ca4-11eb-9ff0-8254de3c9fba.png)

**Comment by elad2109** [comment] 2021-01-22 13:13
Thanks guys, it could actually be a feature to be able to start a new enumeration in the same screenshot.

BTW, can you please point to the code that fixes this bug?

**Comment by mmahmoudian** [comment] 2021-01-22 13:16
@elad2109 The code change can be seen in this Pull Request: #1251

**Comment by borgmanJeremy** [comment] 2021-01-23 01:12
@kpcee Thanks for confirming, I think you are probably right about double clicking. I think another solution will be to allow users to adjust the current number value, then even if you double click you can either adjust the value or undo it.

**Closed by borgmanJeremy** 2021-01-23 01:12 UTC
Labels: Bug

**Comment by marcelarie** [comment] 2022-02-07 11:05
I can make a separated issue but how can I make the bubble counter start with 0 ?

**Comment by mmahmoudian** [comment] 2022-02-07 12:53
@marcelarie I'm afraid you cannot. Typically in real life counting does not start from zero  😉  but you are welcome to open an issue and suggest it and see how the community feels about this.

**Comment by marcelarie** [comment] 2022-02-07 12:57
> @marcelarie I'm afraid you cannot. Typically in real life counting does not start from zero wink but you are welcome to open an issue and suggest it and see how the community feels about this.

Yes I know it's a pretty niche request. At my work I use flameshot to describe different levels of a data tree, and the numeration of the levels that we use starts at `0` in the code. So that will be a cool feature maybe just for me.
maybe I open a Issue. Thanks @mmahmoudian !!
