### ISSUE TITLE
Crash on special behavior (see Video)

### ISSUE THREAD

**Issue by xstable** [flameshot-org/flameshot#2663] opened 2022-06-13 07:32 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3
linux: 5.15.41-1-MANJARO
manjaro: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Manjaro (latest)

### Description

This issue is a hidden one, that lead to "abort Screenshot", but I found a way to reproduce it 💪🏼 

NOTE: 
It appears if you do exactly the steps, which are shown in "Steps to reproduce" below.

### Steps to reproduce

1. run flameshot
2. start screenshot
3. choose T icon to enter Text
4. enter Text (optinaly click with mouse outside of the text-frame to unfocus, or stay focused in it... )
5. Click on the "arrow" icon
6. The Application close without screenshot. A message appears: Screenshot aborted (no error-msg at the cli if that happend.

BUT, 
if you are at Topic 4 above, AND resize the font by moving the mouse-wheel, this error doesn't appear !!!! 
It seems only appearing, if you choose text, enter one or more Text-boxes where you don't change the font-size, and click at the arrow icon right after that.

### Screenshots or screen recordings

![flameshot-bug](https://user-images.githubusercontent.com/1778068/173302001-57ea8edc-6116-4fa9-bcb5-f069ba321ec9.gif)

### System Information

- Manjaro Linux (latest)
- Monitors: 2
    0: +*VGA1 1920/530x1080/300+0+0  VGA1
    1: +LVDS1 1920/380x1080/210+1920+0  LVDS1
- Xorg

Inixi output: 

> System:
>   Host: secondone Kernel: 5.15.41-1-MANJARO arch: x86_64 bits: 64
>     Desktop: KDE Plasma v: 5.24.5 Distro: Manjaro Linux
> Graphics:
>   Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel
>   Device-2: NVIDIA GK107M [GeForce GT 650M] driver: N/A
>   Device-3: Sunplus Innovation Asus Webcam type: USB driver: uvcvideo
>   Device-4: Logitech BRIO Ultra HD Webcam type: USB
>     driver: hid-generic,snd-usb-audio,usbhid,uvcvideo
>   Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.2 driver: X:
>     loaded: intel gpu: i915 resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
>   OpenGL: renderer: Mesa Intel HD Graphics 4000 (IVB GT2) v: 4.2 Mesa 22.1.1

**Comment by borgmanJeremy** [comment] 2022-06-13 14:13
Can you try with flameshot-git? I merged a patch a few days ago that should fix this #2645

**Comment by mmahmoudian** [comment] 2022-06-13 18:02
It seems that it is duplicate of #2641 I close this issue. If it was not resolved, please reopen it

**Closed** 2022-06-13 18:02 UTC
Labels: Unconfirmed Bug

**Comment by xstable** [comment] 2022-06-14 07:00
> Can you try with flameshot-git? I merged a patch a few days ago that should fix this #2645

Yep, work like a charm. Thanks a lot!
