### ISSUE TITLE
Icon positions

### ISSUE THREAD

**Issue by robinheidrich** [flameshot-org/flameshot#3648] opened 2024-06-22 15:14 UTC
### Feature Description

It's quite annoying that the position of the icons is always different and you always have to search for them. Instead, I would like the icons to always stay in the same place, similar to Lightshot. Maybe as an optional setting.

Also, I would like the size of the selection area to be displayed not in an icon, but as text either above or within it.

**Comment by mmahmoudian** [comment] 2024-06-23 17:18
> It's quite annoying that the position of the icons is always different and you always have to search for them. Instead, I would like the icons to always stay in the same place, similar to Lightshot. Maybe as an optional setting.

Duplicate of #573 and #2245 

>  I would like the size of the selection area to be displayed not in an icon, but as text either above or within it.

Already implemented in #2766

**Closed** 2024-06-23 17:18 UTC
Labels: Duplicate, Enhancement
