### ISSUE TITLE
Completely broken feature "Take Screenshot" for multiple monitors with different resolution

### ISSUE THREAD

**Issue by thepurple** [flameshot-org/flameshot#1883] opened 2021-09-11 10:22 UTC
**Flameshot version**
Flameshot v0.10.1 (04793d7)
Compiled with Qt 5.12.8
linux: 5.11.0-34-generic
ubuntu: 20.04

**Describe the bug**
"Take Screenshot" captures wrong area for multiple displays. 
In general it is completely broken by the commit: 
908d9187162f75f7f380af4fee6e151504ec2b61 Refactor code related to CaptureWidget (#1801)

Please rollback this update. We cannot rollback this commit because it also contains code refactoring and further commits with this refactoring.

**To Reproduce**
Just try to capture with multiple screens with different resolutions (with or without scaling).

**Expected behavior**
FullHD + 4k
Expected:
![Screenshot-4k-expected](https://user-images.githubusercontent.com/15923484/132944454-020c7dbd-15f7-4720-9367-c9c0178b0061.png)

Actual:
![Screenshot-4k-actual](https://user-images.githubusercontent.com/15923484/132944523-ea12e405-1eaf-4eed-8a78-d1837e57a6d1.png)

FullHD + 4k (scaled to FullHD)
Expected:
![Screenshot-expected-4k-scaled](https://user-images.githubusercontent.com/15923484/132944498-f7c6dc95-bc39-4066-b6a2-31a6900d9570.png)

Actual:
![Screenshot-expected-4k-actual](https://user-images.githubusercontent.com/15923484/132944481-3005f06e-0bcc-47e0-aff5-1fec19d2c6c0.png)

**System Information**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by veracioux** [comment] 2021-09-11 12:13
I think I have identified a small chunk of code that causes your issue:

https://github.com/flameshot-org/flameshot/blob/908d9187162f75f7f380af4fee6e151504ec2b61/src/widgets/capture/capturewidget.cpp#L134-L138

In the refactor commit I added the preprocessor directives to prevent flameshot from overriding the WM to make debugging easier (on linux). I assume that you compiled flameshot in a debug configuration?

Please compile [this branch](https://github.com/veracioux/flameshot/tree/capturewidget_fix) and tell me if the issue is fixed. The branch is committed on top of the commit that causes the issue.

Now, I can remove the preprocessor flags and leave it to the developers to comment out the code for debugging purposes when needed, but that would be very annoying. On the other hand if we leave the preprocessor flags, I don't know how we would let the developers know to watch out for this.

@borgmanJeremy thoughts?

**Comment by thepurple** [comment] 2021-09-11 13:27
@veracioux this fix returns the previous behavior, great, thx.
Everything fine with FullHD+4k scaled to FullHD

And the issue with not similar displays resolution or if they are not in a line (as we had before):
![fullhd+4k](https://user-images.githubusercontent.com/15923484/132948930-c6f3b420-981f-4a71-b3ab-34b36f84a687.png)

@veracioux thanks for really fast reaction and I feel myself as a fool, I really didn't check it in Release mode. I was so surprised with such "Capturing", that I forgot about anything else. The issue is in the Debug mode only and not so critical at last.

PS: As for me, the only way to fix it is to go MacOS way (capture current screen only) or forget about inline editor. But the last one is the Flameshot's killer feature.

**Comment by thepurple** [comment] 2021-09-11 13:31
@veracioux thanks and sorry for such reaction from my side. It was a hard day. 
And send please a PR with this fix for Debug mode anyway.

**Comment by veracioux** [comment] 2021-09-11 17:11
@thepurple It's fine, we all make mistakes. I changed it so that you have to explicitly pass a `-DFLAMESHOT_DEBUG_CAPTURE` option to `cmake` to enable the debugging tweak. Is that ok?

**Comment by thepurple** [comment] 2021-09-11 17:19
It looks great, thx.

**Closed** 2021-09-11 17:54 UTC
Labels: Bug, High Priority

**Comment by smt923** [comment] 2022-01-19 21:49
I'm getting basically this exact thing both on master and the v11 release, is this a known and fixed issue? I have a 1680x1050 secondary monitor to my left and a 1920x1080 as my primary, when I trigger flameshot gui (regardless of display I'm focused on) it will open a croppsed view of my left monitor on my primary monitor as well as a tiny bit of my primary monitor, it's also pretty slow to start up now since I tried it on wayland, if I turn my secondary monitor off and leave my 1920x1080 primary monitor as my only monitor it works as expected

```
Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.1-237-tkg-pds (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 570 Series
```

**Comment by borgmanJeremy** [comment] 2022-01-19 21:51
Did it work with an old version? Do you have fractional scaling?

**Comment by smt923** [comment] 2022-01-19 22:05
no fractional scaling, with the v10.2 currently in arch repos it works but I believe the plasma/wayland support is a bit less stable and it doesn't let me fully copy the screenshot to clipboard unless I click the button manually, but the monitor thing doesn't happen with that at least, no

some logs from v11 when I try to screenshot:

```
Jan 19 21:59:48 arch kstart5[19425]: Omitting both --window and --windowclass arguments is not recommended
Jan 19 21:59:48 arch systemd[841]: Started flameshot.
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration: Adding output:
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration:     manufacturer:  "Samsung Electric Company"
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration:     model:  "SyncMaster/808464435"
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration:     resolution:  QSize(1920, 1080)
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration: Adding output:
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration:     manufacturer:  "Samsung Electric Company"
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration:     model:  "SyncMaster/H9XQB61038"
Jan 19 21:59:48 arch xdg-desktop-portal-kde[1473]: xdp-kde-wayland-integration:     resolution:  QSize(1680, 1050)
Jan 19 21:59:50 arch flameshot[19427]: Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Jan 19 21:59:50 arch flameshot[19427]: Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Jan 19 21:59:50 arch flameshot[19427]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Jan 19 21:59:50 arch flameshot[19427]: Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Jan 19 21:59:52 arch flameshot[19427]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
I only just switched to wayland so I don't know if I'm just missing some package or if this should be it's own issue or something - switching back to X11 just to test flameshot v11 and it works fine there, grabs the right monitor, is pretty fast, ctrl-c puts it in my clipboard like normal
