### ISSUE TITLE
Create Directory in Save-Path if not exist

### ISSUE THREAD

**Issue by xstable** [flameshot-org/flameshot#2674] opened 2022-06-16 09:15 UTC
### Feature Description

In Linux you can save stuff to /tmp, and generally this directory will be cleared on next reboot.

To get an better overview of your screenshots (and found them faster) I've created a little script of my own, which allow me to save the image, that flameshot put into the clipboard to `/tmp/+++Screenshots`.
If this directory not exist, my script will create it.

BTW: `+++Screenshots` is choosed to place this directory at the very top in the directory-listing.
This way it's a breath to go to /tmp and found the screenshots of flameshot in a nice named folder ... all together.

# FEATURE-WISH:
I wish, that I can skip my self-made script, and handling image-saving via clipboard.
To archive that, you should make users able to declare a "wished directory-name" additional to the path they can choose: 
If this directory not exist, my script will create it.
![image](https://user-images.githubusercontent.com/1778068/174036799-fa2245d2-a4c1-466d-8296-b2634010e154.png)

And if flameshot save an image, it should be checked, if this "wished directory-name" exist... if not it should be created... and the images should be put inside.

**Comment by mmahmoudian** [comment] 2022-06-16 10:33
duplicate of #2613.

For detailed response, read the thread in  #2613, but to save your time, the short answer is: "folder creation should be delegated to the shell not Flameshot"

**Closed by mmahmoudian** 2022-06-16 10:33 UTC
Labels: Enhancement
