### ISSUE TITLE
No support for screen recording

### ISSUE THREAD

**Issue by godalming123** [flameshot-org/flameshot#2201] opened 2021-12-29 08:57 UTC
### Feature Description

I think it would be nice if flameshot could take small screen recordings nothing fancy just say a 60 second capture that can be shown in you tray or a permenant capture that can also be shown and paused or saved from your tray.

**Comment by mmahmoudian** [comment] 2021-12-29 10:46
I think that is out of the scope of Flameshot. There are already very good software (e.g peek) that you can use. Perhaps reinventing the wheel is not good at this point.

I'll keep this open and tag the following devs to know their opinion and then we can close it if everyone share the same opinion with me.

@borgmanJeremy @veracioux @ZetaoYang @hoiset @thepurple @Martin-Eckleben

**Comment by mmahmoudian** [comment] 2021-12-29 10:48
@ho

**Comment by thepurple** [comment] 2021-12-29 11:20
I think that it's out of scope now. I had such requests too, but current concept is far from video recording.
I think that the only possible option is to integrate some 3rd-party screen recording tool and to call it transparently from the Flameshot. But it will be a challenge to find and support a good cross-platform tool with ability to integrate it.

**Comment by ZetaoYang** [comment] 2021-12-29 11:30
Maybe it can be achieved in flameshot plugins.

**Comment by mmahmoudian** [comment] 2021-12-29 12:53
I agree with both points so far. Flameshot can get feature rich through plugins and the core can be/should get more stable and light weight. There is a narrow but perhaps a fine line that should be drawn and defined by devs. I personally am not a C++ developer and therefore I'll try to minimise my influence/voice in this context as more knowledgeable fellows are onboard 🤓

**Comment by godalming123** [comment] 2021-12-29 18:57
I would agree I just didn't realise that there was simple alternatives to get the job done and flameshot defenately needs some more important features such as being able to copy the selected color as seen in flameshot 11

**Comment by veracioux** [comment] 2021-12-29 19:25
@mmahmoudian

> I think that is out of the scope of Flameshot. There are already very good software (e.g peek) that you can use. Perhaps reinventing the wheel is not good at this point.

Absolutely agree. Flameshot should not be a screen recorder. Except in plugins, where all cards are on the table.

**Comment by borgmanJeremy** [comment] 2021-12-29 20:42
This is also a duplicate of #172

**Closed by borgmanJeremy** 2021-12-29 20:42 UTC
Labels: Enhancement
