### ISSUE TITLE
flameshot not working on HiDPI with Scale

### ISSUE THREAD

**Issue by jdkcn** [flameshot-org/flameshot#2955] opened 2022-10-20 13:04 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.19.16-76051916-generic
pop: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Pop!_OS 22.04

### Description

Not working with scale except with 200% scale, 125%, 150%, 175%, 225%, 250%, 275% not working.

### Steps to reproduce

1. change the display scale to 125%
2. run flameshot
3. do Take Screenshot

### Screenshots or screen recordings

[125% not working video](https://homolo-public.oss-cn-shanghai.aliyuncs.com/temp/125-not-working.mp4)

[200% working](https://homolo-public.oss-cn-shanghai.aliyuncs.com/temp/200-working.mp4)

[125% working with gnome screenshot](https://homolo-public.oss-cn-shanghai.aliyuncs.com/temp/125-not-working.mp4)

### System Information

![image](https://user-images.githubusercontent.com/3855/196953292-f2a473a3-882e-4c0d-a7cc-433cd7bce7f4.png)

**Comment by mmahmoudian** [comment] 2022-10-21 11:44
Please search before posting a new issue. This is duplicate of #564

**Closed by mmahmoudian** 2022-10-21 11:44 UTC
Labels: Unconfirmed Bug
