### ISSUE TITLE
macOS customize shortcut grayed out

### ISSUE THREAD

**Issue by nippyin** [flameshot-org/flameshot#1711] opened 2021-07-16 02:55 UTC
**Flameshot version**
V0.9.0

**Describe the bug**
Unable to setup custom shortcut key to capture screen shot as its grayed out.
![image](https://user-images.githubusercontent.com/41337248/125884418-f8f99098-39a2-4106-a732-9e1860cdf220.png)

**To Reproduce**
Click on the Configuration -> Shortcuts -> Screen capture

**Expected behavior**

When click on configuration -> Shortcuts -> Screen Capture, should be able to choose any shortcut key from keyboard. like other options does allow.

**System Information**
macOS 11.4 BigSur

**Comment by mmahmoudian** [comment] 2021-07-16 05:59
For the time being this is not possible for non-linux operating systems. But there are ways to solve this. For example for MacOS you can read this thread which has some very good and quick solutions: #1593

I close this issue as this is not a bug and is duplicate of #1593

**Closed** 2021-07-16 06:00 UTC
Labels: Duplicate, OSX

**Comment by nippyin** [comment] 2021-07-27 17:14
> For the time being this is not possible for non-linux operating systems. But there are ways to solve this. For example for MacOS you can read this thread which has some very good and quick solutions: #1593
> 
> I close this issue as this is not a bug and is duplicate of #1593 in terms of the issue it tries to solve.

Is this in priority list anyway? because otherwise it will be unnecessary complicated and tough way to capture a screen shot. you know what I mean.

**Comment by mmahmoudian** [comment] 2021-07-27 22:12
I don't think 21 lines of code is a big deal if it should be done once. 

Regarding you comment on the other thread, most probably your issue is with trying to use backtick (```). Try using another key.


About whether this is priority, I'm not sure, but I doubt it as it already has a workaround solution, where as there are some bugs that need more immediate attention. Nevertheless, if you feel like solving this and creating a Pull Request, we would highly appreciate it.
