### ISSUE TITLE
history and delete funtion for uploads to imgur

### ISSUE THREAD

**Issue by AWHubGit** [flameshot-org/flameshot#1028] opened 2020-10-04 08:09 UTC
I use flameshot 0.8.3-1install from Arch repo.

I already uploaded some screenshots to imgur in the past.
[https://i.imgur.com/HtUdX24.png](url)

I would like to have a history of my uploads to imgur and a delete function to be able to delete specific uploads.

**Comment by mmahmoudian** [comment] 2020-10-05 06:26
Duplicate of #777

**Closed** 2020-10-06 01:13 UTC
Labels: Duplicate, Enhancement
