### ISSUE TITLE
Changing key "print screen" for win 10

### ISSUE THREAD

**Issue by konoval-a** [flameshot-org/flameshot#2887] opened 2022-08-26 08:25 UTC
### Feature Description

Can you add option to change default key to take screenshot on windows?

**Comment by mmahmoudian** [comment] 2022-09-02 08:26
Please search in the issues before creating a new one.

Duplicate of  #1341

Read this for a workaround:

https://github.com/flameshot-org/flameshot/issues/1861#issuecomment-910552032

**Closed by mmahmoudian** 2022-09-02 08:26 UTC
Labels: Enhancement
