### ISSUE TITLE
printscr doesnt open flameshot

### ISSUE THREAD

**Issue by QuantaNeon** [flameshot-org/flameshot#3147] opened 2023-04-05 08:08 UTC
### Flameshot Version

12.1.0 latest

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

windows 11

### Description

i just installed flameshot, i had the printsc key to open up windows snipping tool i disabled that and when i press printsc now, flameshor doesnt open
i tried enabling use printsc to open snipping tool in settings and again pressed printsc, the snipping tool opened but flameshot doesnt
i have flameshot running in the system tray

### System Information

windows 11
no tweaks to monitor just a vanilla hp laptop monitor

**Comment by mmahmoudian** [comment] 2023-04-05 08:22
Please search among open and closed issues before opening a new issue. This is potential duplicate of #2261

Try rebooting after disabling the snipping tool. Almost every time we got such issue reported, they came back few days after and said that it automatically got fixed. I think the issue is that Windows tries to be "smart" and the reboot is not actually a reboot, but it instead it is more of a hibernation and reboot.

I will close this, but please consider commenting on the #2261 if you either found the root cause or if you still needed help.

Thanks.

**Closed by mmahmoudian** 2023-04-05 08:22 UTC
Labels: Unconfirmed Bug
