### ISSUE TITLE
Error transferring https://api.imgur.com/3/image?title=&description=2024-03-14_18-50 - server replied: Too Many Requests

### ISSUE THREAD

**Issue by jam-2000** [flameshot-org/flameshot#3535] opened 2024-03-14 17:12 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.12.8
linux: 5.15.0-100-generic
linuxmint: 21.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linux mint 21.3

### Description

Error transferring https://api.imgur.com/3/image?title=&description=2024-03-14_18-50 - server replied: Too Many Requests

the error occurs on different platforms (windows, macos, linux)
30+ users in the office
most users use their own imgur ClienIDs
some users use the default ClientID from flameshot

all users encounter this error from time to time 

### Steps to reproduce

the error occurs on different platforms (windows, macos, linux) time to time

### Screenshots or screen recordings

![Screenshot from 2024-03-14 19-02-31](https://github.com/flameshot-org/flameshot/assets/43862171/e61e5ed6-808a-49d6-aede-11834a687f5a)

### System Information

System:
  Kernel: 5.15.0-100-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
CPU:
  Intel Core i5-6400
Graphics:
  Device-1: AMD Tonga PRO [Radeon R9 285/380]
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 2560x1440 s-dpi: 96 s-size: 677x381mm (26.7x15.0") s-diag: 777mm (30.6")
  Monitor-1: HDMI-A-0 mapped: HDMI-A-1 model: Dell S2722QC serial: <filter> res: 2560x1440
    hz: 60 dpi: 109 size: 597x336mm (23.5x13.2") diag: 685mm (27") modes: max: 3840x2160
    min: 720x400
  OpenGL: renderer: AMD Radeon R9 380 Series (tonga LLVM 15.0.7 DRM 3.42 5.15.0-100-generic)
    v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2 direct render: Yes

![image](https://github.com/flameshot-org/flameshot/assets/43862171/3cb33471-a0c4-49d5-8bbb-ef147694ce33)

**Comment by mmahmoudian** [comment] 2024-03-14 18:49
Literally the issue before this one was about this. Trust me, searching among open **and** close issues can first and foremost save your own time. I'm thankful that you invested time in filling this bug report, but please consider searching first next time.

Duplicate of so many including #3534

Please read the answer I provided there.

**Closed by mmahmoudian** 2024-03-14 18:50 UTC
Labels: Unconfirmed Bug

**Comment by jam-2000** [comment] 2024-03-18 15:41
"Too many requests" ...
... from ip address OR from ClientID???

Literally the issue before this one was NOT about this ...
My report is not similar to [#3534](https://github.com/flameshot-org/flameshot/issues/3534) because as I wrote:
"most users use their own imgur ClienIDs"
"most users" it is 99% in this exact case.


1. Perhaps I need to configure Flameshot to use other image storage services.
2. Perhaps I need to use a premium Imgur account.
3. Alternatively, if Flameshot cannot provide seamless integration with the Imgur service, then I should simply use another screenshot tool. Could you please recommend a good alternative?

Thank you for your assistance, and have a great day!

**Comment by mmahmoudian** [comment] 2024-03-18 16:44
> My report is not similar to #3534 because as I wrote:
> "most users use their own imgur ClienIDs"
> "most users" it is 99% in this exact case

It is for one simple reason:
Flameshot just sends a query to imgur. The returned error has NOTHING to do with Flameshot.

> 30+ users in the office

Since you are using Flameshot in your business setup to boost your staff productivity, perhaps it is just fair to also invest in the tools you are freely and liberally using?

> Could you please recommend a good alternative?

No, sorry, I don't know any other Free and Libre OpenSource Software that can resolve internal error from imgur.

> have a great day!

You too, and may your business prosper.
