### ISSUE TITLE
Gnome Wayland: Save screenshot portal doesn't offer filename to save

### ISSUE THREAD

**Issue by darkblaze69** [flameshot-org/flameshot#2703] opened 2022-06-22 20:22 UTC
### Flameshot Version

Flameshot 11, 12

### Installation Type

Linux pacman, User repository (AUR)

### Operating System type and version

Manjaro Linux

### Description

"Save screenshot" portal doesn't offer filename to save. You must put the filename manually every time.

Tried official manjaro's package 11.0
and AUR's fresh 12.0 build b4737f8a

### Steps to reproduce

run 'flameshot gui'
select area, save to file

### Screenshots or screen recordings

![ok1](https://user-images.githubusercontent.com/6976920/175128316-4b7a4bb6-0029-46f8-adcb-bdb65c509c00.png).

### System Information

Gnome 42.2

**Comment by mmahmoudian** [comment] 2022-06-23 06:20
Please provide your config file (`~/.config/flameshot/flameshot.ini`)

**Comment by darkblaze69** [comment] 2022-06-23 06:31
```
[General]
checkForUpdates=false
contrastOpacity=188
drawColor=#ff0000
drawThickness=2
saveAfterCopy=true
savePath=/home/user/Pictures/domain-trust
showDesktopNotification=false
```

**Comment by mmahmoudian** [comment] 2022-06-23 06:39
As you can see there is no file pattern configured. Please right-click on the tray icon, open Configurations, and in File Name tab select a file pattern.

**Comment by darkblaze69** [comment] 2022-06-23 06:47
Well. Removed old config, applied pattern, but the same behavior.

```
[General]
contrastOpacity=188
filenamePattern=%F-%T
saveAsFileExtension=png
showStartupLaunchMessage=false
```

**Comment by mmahmoudian** [comment] 2022-06-23 18:04
Seems this is duplicate of #1563. I'm not 100% sure though. This need to be checked again

**Comment by allen-munsch** [comment] 2022-06-23 20:44
Also see: https://github.com/flameshot-org/flameshot/issues/2455#issuecomment-1117401037

**Comment by borgmanJeremy** [comment] 2022-06-28 13:21
Yeah this is a duplicate of #2455. This is a bug withing the Qt GTK layer.

**Closed by borgmanJeremy** 2022-06-28 13:21 UTC
Labels: Needs Investigation, Unconfirmed Bug
