### ISSUE TITLE
Text Outline

### ISSUE THREAD

**Issue by JosukeHigashkata** [flameshot-org/flameshot#3150] opened 2023-04-08 09:13 UTC
### Feature Description

I think it would be great if it has adding outline(stroke) for texts

**Comment by mmahmoudian** [comment] 2023-04-19 10:43
Isn't this duplicate of #1249  and to some extent #313 ?

**Comment by JosukeHigashkata** [comment] 2023-05-20 03:07
YES but with adjustable border strength and custamizable colors

**Comment by mmahmoudian** [comment] 2023-05-20 11:58
I suggest you mention your suggestions on those threads because when a developer starts implementing, they will not sieve through all the issues in the repo. It is good to have everything in one place.

I will close this issue.

**Closed by mmahmoudian** 2023-05-20 11:58 UTC
Labels: Enhancement, Waiting For Info
