### ISSUE TITLE
[Feature request] Need to store size for every tool separately.

### ISSUE THREAD

**Issue by aplab** [flameshot-org/flameshot#1142] opened 2020-11-05 08:53 UTC
For example, i use small tiny arrows but big font size, or middle-sized smoothing at the same time.

**Comment by borgmanJeremy** [comment] 2020-11-05 23:38
Hello,

Good suggestion! However it is a duplicate of #782  so I will close this one. Thanks

**Closed by borgmanJeremy** 2020-11-05 23:38 UTC
