### ISSUE TITLE
flameshot not working when Monitor scale is larger than 100%

### ISSUE THREAD

**Issue by karolskolasinski** [flameshot-org/flameshot#3250] opened 2023-06-30 09:22 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-76-generic
linuxmint: 21.1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linuxmint: 21.1

### Description

To reproduce change Monitor scale form example to 150%. Then whole screen start blinking and you cannot use Flameshot.

monitor Dell 
resolution 3840x2160
refresh rate: 60.00 Hz
Monitor scale 150%

### Steps to reproduce

To reproduce change Monitor scale form example to 150% and try to capture screenshot with Flameshot.

### System Information

linuxmint: 21.1

monitor Dell 
resolution 3840x2160
refresh rate: 60.00 Hz
Monitor scale 150%

**Comment by mmahmoudian** [comment] 2023-07-02 10:49
Thanks, but two points:
1. please consider searching among open and closed issues before creating a new one
2. latest Flameshot version is 12.1.0 . It would be pointless to accept bug reports for very old versions because many of them have been fixed in newer versions

Duplicate of #564

**Closed by mmahmoudian** 2023-07-02 10:49 UTC
Labels: Unconfirmed Bug
