### ISSUE TITLE
Updates and forks?

### ISSUE THREAD

**Issue by Saibamen** [flameshot-org/flameshot#3569] opened 2024-04-16 10:55 UTC
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10

### Description

Hey there,

Just wondering if Flameshot is still being updated? Also, any active forks?

Latest release is very old, and I still have critical bug - need to exit Flameshot after switching monitors from work/home setup, because Flameshot cannot detect new monitor.

I know that current master branch is actively developed in 

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/905878/d5a72a5a-4abf-4b23-9289-ddb727236a1e)

![image](https://github.com/flameshot-org/flameshot/assets/905878/c44fced7-6700-46ae-8ec5-0dd3429ebd85)

### System Information

Windows 10.0.19045.4291

**Comment by mmahmoudian** [comment] 2024-04-16 12:06
@Saibamen
> Just wondering if Flameshot is still being updated?

Yes this project is active. You can check the commits instead of the latest release. If you want the nightly builds, you can easily get them from https://flameshot.org/docs/installation/development-build/

> Latest release is very old, and I still have critical bug

About why there have not been a new version: This project is maintained by volunteers (including myself) that are not getting paid a single cent for their time. Last year one of our main devs left the project due to personal reasons and also burn out. So we now have one less volunteer than before. Therefore, the next version will happen when it happen, and in the meantime users can use the beta nightly releases if they want the latest features and bug fixes.

You can see all the changes lined up for the next version here:
https://github.com/flameshot-org/flameshot/issues?q=milestone%3Av13+

> I still have critical bug - need to exit Flameshot after switching monitors from work/home setup, because Flameshot cannot detect new monitor.

Well, sorry to hear that you are experiencing a bug, but as I explained before, we are all volunteer. If you are willing to give us a hand and help us in any way, that is highly appreciated (code, documentation, translation, ...).

If you want to help this project progress, you can financially help but putting bounty on issues that you think should be fixed with higher priority. This way your money directly translates to the improvement you are wishing for. More information here:

https://flameshot.org/donate/

Just to clarify, we don't accept donation and we don't get paid for what we do, but there are many programmers that might be willing to fix a bug or add a feature if there is enough money on that issue. So by putting some money (e.g $5) you can make the issue at hand more attractive for other programmers.

Lastly, the bug you are reporting is already mentioned before and this issue is duplicate, so I'm going to close this one in favor or the other one.

**Closed by mmahmoudian** 2024-04-16 12:06 UTC
Labels: Unconfirmed Bug

**Comment by Saibamen** [comment] 2024-04-16 12:38
Duplicated of https://github.com/flameshot-org/flameshot/issues/3505

**Comment by mmahmoudian** [comment] 2024-04-17 18:09
Also a duplicate of #3459

**Comment by Saibamen** [comment] 2024-04-28 07:24
Cannot download nightly builds
![image](https://github.com/flameshot-org/flameshot/assets/905878/55d823d7-b8be-4b38-a1c1-603b4bfa9e8a)

**Comment by mmahmoudian** [comment] 2024-04-28 08:29
@Saibamen sorry, it seems our Windows build system has faced an issue. I'll try to fix it if I can, otherwise we should wait for someone who know the Windows CI better.

**Comment by mmahmoudian** [comment] 2024-04-28 12:23
@Saibamen I manage to fix the issue in #3585 . In few minutes all pipeline runs will be finished and things should get back to normal. Please try downloading the file again for instance at 2024-04-28 15:22 Polish time. Enjoy the software.

**Comment by AyoungDukie** [comment] 2024-09-13 16:50
Just an FYI, it does seem to be held up again; looks like it is trying to find a different name for the file ("Windows-Artifact" vs the 4 different Installer/Protable x86/x64 artifacts). Downloading from Github directly seems to work though!

![image](https://github.com/user-attachments/assets/e71a4432-c76b-41c2-ae66-f02aacd5887a)

**Comment by mmahmoudian** [comment] 2024-09-13 16:52
@AyoungDukie thanks, I'll look into it

**Comment by AyoungDukie** [comment] 2024-09-13 17:18
Made an issue on the website's repo for easier reference. Thank you!

https://github.com/flameshot-org/flameshot-org.github.io/issues/160
