### ISSUE TITLE
Gui closes after Text editing

### ISSUE THREAD

**Issue by DarkTrick** [flameshot-org/flameshot#2825] opened 2022-07-24 01:23 UTC
### Flameshot Version

This is a copy of the bug on launchpad:
https://bugs.launchpad.net/ubuntu/+source/flameshot/+bug/1982674

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu

### Description

Summary:
After using the text tool: if you click any other tool, the editing mode will end.

Reproducibility: 100%

### Steps to reproduce

- Call flameshot with `flameshot gui`.
- Define the area to be screenshotted.
- Select the text tool.
- Click somewhere and write anything.
- Click somewhere else on the canvas to finish editing with the text tool.
- Click the pen tool.
- EXPECTED: you can use the pen tool now.
- ACTUAL: editing ends.

### System Information

DistroRelease: Ubuntu 22.04
Package: flameshot 11.0.0-2
ProcVersionSignature: Ubuntu 5.15.0-41.44-generic 5.15.39
Uname: Linux 5.15.0-41-generic x86_64
ApportVersion: 2.20.11-0ubuntu82.1
Architecture: amd64
CasperMD5CheckResult: pass
CurrentDesktop: XFCE
Date: Sat Jul 23 16:00:49 2022
InstallationDate: Installed on 2022-02-14 (158 days ago)
InstallationMedia: Xubuntu 21.10 "Impish Indri" - Release amd64 (20211012)
SourcePackage: flameshot
UpgradeStatus: Upgraded to jammy on 2022-07-18 (5 days ago)

**Comment by mmahmoudian** [comment] 2022-07-24 07:56
Duplicate of #2528 which was fixed in #2369

**Closed** 2022-07-24 07:58 UTC
Labels: Bug, Duplicate

**Comment by mmahmoudian** [comment] 2022-07-28 14:00
> Unfortunately Ubuntu users have to wait until the end of October until the new version gets released :/

You can use Flatpak, Snap, or AppImage, or even you can get the deb file and install it yourself. More information here:
https://flameshot.org/docs/installation/installation-linux/#distro-agnostic
