### ISSUE TITLE
Flameshot doesn't work properly with fractional scaling

### ISSUE THREAD

**Issue by YaMoef** [flameshot-org/flameshot#3474] opened 2024-01-15 19:14 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04 

### Description

When using Flameshot with fractional scaling set to 200% it will only take the upper left 1/4 of the screen to crop. When setting the scaling to 100% it works as it should.

### Steps to reproduce

1) Use Ubuntu 22.04 with Wayland
2) Turn on fractional scaling to 200%

### System Information

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 6.5.0-14-generic
ubuntu: 22.04
4K display set to 200% fractional scaling

**Comment by mmahmoudian** [comment] 2024-01-16 12:03
Duplicate of #564

Also your flameshot version is few years old. Please try using the latest version.

**Closed as completed** 2024-01-16 12:03 UTC
Labels: Bug, Duplicate

**Comment by leoelrojo** [comment] 2024-02-14 10:23
Hey there,
I'm running into the exact same issue on Ubuntu 22.04 Wayland with fractional scaling (any percentage out of 100%) on the latest version (v12.1.0).
Please note that that latest version available on apt is the initially mentioned version (v11) and that the snap can't be installed because of [missing dependencies](https://github.com/flameshot-org/flameshot/issues/3471). I'm using the AppImage.

**Comment by YaMoef** [comment] 2024-02-14 10:35
> Hey there, I'm running into the exact same issue on Ubuntu 22.04 Wayland with fractional scaling (any percentage out of 100%) on the latest version (v12.1.0). Please note that that latest version available on apt is the initially mentioned version (v11) and that the snap can't be installed because of [missing dependencies](https://github.com/flameshot-org/flameshot/issues/3471). I'm using the AppImage.

Hi I use the AppImage now as well. In the end I decided to stop using fractional scaling by lowering the resolution on one of my screens since that was what made me use fractional scaling. When doing this workaround Flameshot works as I expect.

**Comment by mmahmoudian** [comment] 2024-02-15 09:54
@leoelrojo @YaMoef we have a part in our documentation that you might find useful:

https://flameshot.org/docs/guide/wayland-help/#4k-displayed-and-fractional-scaling

**Comment by YaMoef** [comment] 2024-02-15 11:14
> @leoelrojo @YaMoef we have a part in our documentation that you might find useful:
> 
> https://flameshot.org/docs/guide/wayland-help/#4k-displayed-and-fractional-scaling

I've seen this documentation and tried it out, but I couldn't get it working. How do I calculate the scaling? In my case I'm using a 4K display set to 200% with fractional scaling and a 1080p monitor

**Comment by mmahmoudian** [comment] 2024-02-15 11:59
> How do I calculate the scaling?

tbh I have no idea how the underlying mechanism works. People have suggested multiple numbers but the majority have settled with `1:1` as far as I've seen. Perhaps you can try some of the logics people have proposed in #564

I'm sorry you are experiencing this issue, but the best approach we have had so far is this; and for how this issue is progressed, you can follow #564

**Comment by YaMoef** [comment] 2024-02-15 12:07
> > How do I calculate the scaling?
> 
> tbh I have no idea how the underlying mechanism works. People have suggested multiple numbers but the majority have settled with `1:1` as far as I've seen. Perhaps you can try some of the logics people have proposed in #564
> 
> I'm sorry you are experiencing this issue, but the best approach we have had so far is this; and for how this issue is progressed, you can follow #564

I've gone to this issue a few weeks back and tried all the solutions, but none of them solved my problem. But it doesn't really matter now, when I work on multiple displays I set my 4K screen to 1080p and that workaround is good for me :). Thanks for following up!

**Comment by SFBB** [comment] 2024-11-10 16:40
I have found the reason for this problem.
In `ScreenGrabber::freeDesktopPortal`, scale the PixMap res to match the device pixel ratio. However, the `qApp->devicePixelRatio` only returns an integer which is not exact at all for fractional scaling.
Anyway, we only expect the screenshot result to match with out monitor/screen size. So we can directly get the screen geometry and calculate the fractional scaling of our DE by ourself.
```C++
QScreen* screen = QGuiAppCurrentScreen().currentScreen();
if (screen)
{
const auto screenRect = screen->geometry();
res.setDevicePixelRatio(res.height() * 1.0f / screenRect.height());
}
else
{   
res.setDevicePixelRatio(qApp->devicePixelRatio());
}
```
For sure, if there is a more proper API for it, it is better.
