### ISSUE TITLE
Display issue for General Config entries

### ISSUE THREAD

**Issue by zensubz** [flameshot-org/flameshot#1697] opened 2021-07-06 10:43 UTC
Hi,
I use git commit 6a54285. Would it be possible to adjust the window contents (checkbox entries) with a scroll-bar in the General Config dialog? I use a GNU/Linux variant which uses Qt 5.9.7, and the contents do not fit well (or display well) in the dialog window. I have attached a screenshot to highlight this issue. Please provide a fix, if possible. Thanks.

![general_config](https://user-images.githubusercontent.com/5127872/124586840-93ab9400-de74-11eb-8caa-7ae3b60b56fa.jpg)

**Comment by borgmanJeremy** [comment] 2021-07-19 18:48
I don't think this is a core flameshot issue. Ubuntu 18.04 is a support platform and uses the same Qt Version. 

I think its more likely there is a theming or Qt issue on your distro? Without the ability to reproduce this issue I cant provide any additional help.

**Comment by zensubz** [comment] 2021-07-22 15:27
I also use a Ubuntu 18.04 variant, and checked this issue with the latest release (v0.10.0) available. The UI problem seem to persist. I use qt5ct to control the look-n-feel of Qt5 apps, and checked with two theme variants, i.e., Fusion and Gtk2. The screenshots are attached here, just in case. Thanks.

![flameshot_ubuntu1804_fusion](https://user-images.githubusercontent.com/5127872/126665260-8fb18d73-4949-48c5-9047-a3f498608528.jpg)

![flameshot_ubuntu1804_gtk2](https://user-images.githubusercontent.com/5127872/126665306-0792fbce-7109-4a79-92d9-cf109052d3c1.jpg)

**Comment by HarisGusic** [comment] 2021-07-29 02:44
I submitted a [pull request](https://github.com/flameshot-org/flameshot/pull/1782) that is supposed to fix the issue.

I found that this bug gets triggered when the user resizes the window. Because
there was a call setMinimumSize, it couldn't be resized below a certain point. I
suspect that due to different themes and sizes on different systems, this
minimum size was enough for the bug rarely to show.

This seems to be caused by a bug with QTabWidget (see the image attached in this [bug report](https://bugreports.qt.io/browse/QTBUG-7792?jql=status%20%3D%20Open%20AND%20text%20~%20%22qtabwidget%22)).
When QTabWidget is the top-level widget (the window), it doesn't size properly. It
doesn't even respect the minimum sizes of its children. So I set ConfigWindow's
base class to QWidget, and added a QTabWidget attribute inside it. I removed the
minimum size constraint as it is no longer necessary.

I have tried this on my Arch Linux machine and in an Ubuntu 20.04 VM.
As far as I can see,  this and #1726 are the same issue.

Btw this is my first issue ever :)

**Comment by borgmanJeremy** [comment] 2021-07-29 13:45
Thanks for the contribution!! I'll get it tested and merged.

**Comment by zensubz** [comment] 2021-07-29 15:38
@HarisGusic, thanks for the work. I have checked if that would solve my issue, and well, it is in a way, but a portion of the Config UI is sort of hidden behind the bottom panel, and I am unable to resize it. Have attached the screenshot here:

![flameshot-ui-config](https://user-images.githubusercontent.com/5127872/127521287-090240f4-938b-4d8b-8dcd-95163cb34a49.jpg)

If you could introduce a scroll-bar for the check-box entries and fix the UI window size as well, it would be great.

**Comment by HarisGusic** [comment] 2021-07-29 16:03
@zensubz I think I can do that. @borgmanJeremy did suggest a scroll bar in #1726 but I thought it wasn't necessary so I didn't include it. I can introduce a scroll bar as in your screenshot that will be present only if it is necessary for the window to fit the screen.

@borgmanJeremy  Do I have the green light to do this?

**Comment by borgmanJeremy** [comment] 2021-07-29 20:00
Yes please do

**Comment by HarisGusic** [comment] 2021-07-30 23:07
@zensubz I have implemented the changes in the latest commit of this pull request: https://github.com/flameshot-org/flameshot/pull/1782

**Closed** 2021-07-31 01:56 UTC
Labels: Bug, Visuals
