### ISSUE TITLE
Copy icon missing in 11.0.rc1-1, Ubuntu 21.10

### ISSUE THREAD

**Issue by heynnema** [flameshot-org/flameshot#2603] opened 2022-05-13 13:17 UTC
### Flameshot Version

11.0.rc1-1

### Installation Type

apt or Ubuntu Software

### Operating System type and version

Ubuntu 21.10

### Description

Although selected in the configuration, the COPY icon is missing. Control-C does work.

### System Information

Ubuntu 21.10
X11/Xorg

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
linux: 5.13.0-41-generic
ubuntu: 21.10

**Comment by mmahmoudian** [comment] 2022-05-13 17:28
@heynnema 

This is not a bug, it is briefly explained in [the release notes](https://github.com/flameshot-org/flameshot/releases/tag/v11.0.0):

> The CLI now supports pinning (`--pin`), uploading (`--upload`), and copying to clipboard (`--clipboard`).
Note that in case one of these options (or `--path`, `--raw` also) is used, an Accept button is shown and the Save, Copy, Upload, Pin, Open With buttons are hidden.

and it has been in detailed explained on our website:

https://flameshot.org/docs/advanced/commandline-options/#final-actions

I encourage you to to have a quick look at the link above to be able to use Flameshot efficiently and enjoy it :)

You can set the path in your config. There is no need to set it in the command itself every time.

-------

Additionally, this issue is duplicate of:

- #2275
- #2362
- #2365
- #2431
- #2399
- #2391
- #2370
- #2477
- #2526
- #2597
- and potentially many more that I don't have time to search for

So I will close this issue.

**Closed** 2022-05-13 17:28 UTC
Labels: Duplicate, question
