### ISSUE TITLE
Weird behavior on Wayland with KDE

### ISSUE THREAD

**Issue by Gigas002** [flameshot-org/flameshot#3204] opened 2023-05-19 17:48 UTC
### Flameshot Version

Flameshot v12.1.0 (3ededae5)

### Installation Type

User repository (AUR)

### Operating System type and version

Manjaro Linux

### Description

Flameshot's being very slow with screenshoting process and cropping screen to 1:4 of it's original size

### Screenshots or screen recordings

https://github.com/flameshot-org/flameshot/assets/24297712/6b9f5948-85b6-4e9e-adf6-4b81b9766c05

### System Information

```
System:
  Host: gigas-acer Kernel: 6.3.3-x64v3-xanmod1 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.5 Distro: Manjaro Linux
Graphics:
  Device-1: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 530.41.03
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: Quanta HD User Facing driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.1.1
    compositor: kwin_wayland driver: X: loaded: amdgpu,nvidia
    unloaded: modesetting,nouveau dri: radeonsi gpu: nvidia,amdgpu
    resolution: 1536x864
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon Graphics (renoir LLVM
    15.0.7 DRM 3.52 6.3.3-x64v3-xanmod1)
 ```

**Comment by mmahmoudian** [comment] 2023-05-20 12:48
Thanks for reporting this. You are basically describing two issue here:
1. being slow in selecting the region which is duplicate of few issues and is fixed in #3059
2. the smaller picture which is mostly due to you having fractional scaling (which is also duplicate of multiple issues)

Please consider searching among the open and closed issues before opening a new issue as it would save your time and get you to the answer and work-arounds faster.

**Closed by mmahmoudian** 2023-05-20 12:48 UTC
Labels: Unconfirmed Bug

**Comment by mmahmoudian** [comment] 2023-05-20 12:50
I forgot to point you to the direction of workaround. Please read this:

https://github.com/flameshot-org/flameshot/issues/2978#issuecomment-1520466349

**Comment by Gigas002** [comment] 2023-05-20 12:54
Thank you for pointing on a PR above, I haven't seen it.
I've seen workaround, that uses `QT_SCREEN_SCALE_FACTORS`, but these didn't help me

**Comment by mmahmoudian** [comment] 2023-05-20 18:07
> I've seen workaround, that uses `QT_SCREEN_SCALE_FACTORS`, but these didn't help me

Which value have you tried? Have you tried `export QT_SCREEN_SCALE_FACTORS="1;1"` ?

**Comment by Gigas002** [comment] 2023-05-21 03:16
My scaling is set to `125%` in setteings, I tried these values:

```sh
QT_SCREEN_SCALE_FACTORS="1;1" flameshot gui
QT_SCREEN_SCALE_FACTORS="0.10" flameshot gui
QT_SCREEN_SCALE_FACTORS="0.25" flameshot gui
QT_SCREEN_SCALE_FACTORS="0.5" flameshot gui
QT_SCREEN_SCALE_FACTORS="0.75" flameshot gui
QT_SCREEN_SCALE_FACTORS="1" flameshot gui
QT_SCREEN_SCALE_FACTORS="1.25" flameshot gui
QT_SCREEN_SCALE_FACTORS="1.5" flameshot gui
QT_SCREEN_SCALE_FACTORS="1.75" flameshot gui
QT_SCREEN_SCALE_FACTORS="2" flameshot gui
```

**Comment by Gigas002** [comment] 2023-05-28 12:46
Just to make sure I've built the abandoned [qt6 branch](https://github.com/flameshot-org/flameshot/tree/qt6) (_cause I heard qt6 supports fractional scaling on wayland way better_) but the problem still persists in it
