### ISSUE TITLE
Command line options don't work on windows

### ISSUE THREAD

**Issue by jrozner** [flameshot-org/flameshot#2554] opened 2022-04-21 16:02 UTC
### Flameshot Version

11.0.0 and master

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11

### Description

Application starts and exits with no error message and doesn't take a screenshot.

### Steps to reproduce

1. run `flameshot gui`

### System Information

windows 11
2 displays

**Comment by veracioux** [comment] 2022-04-24 12:40
This is a duplicate of #2118.

**Closed by veracioux** 2022-04-24 12:40 UTC
Labels: Unconfirmed Bug, Windows
