### ISSUE TITLE
Take screenshot of the active(focused) window

### ISSUE THREAD

**Issue by zim0369** [flameshot-org/flameshot#2662] opened 2022-06-12 16:26 UTC
### Feature Description

There seems no way to take a screenshot of only the currently active window with flameshot.

Feature request to be able to take a screenshot of only the window that is focused or active.

**Comment by mmahmoudian** [comment] 2022-06-12 17:22
Duplicate of #334

Please consider searching through the existing issues before creating a new one. It would save everyone's time. Thanks.

**Closed by mmahmoudian** 2022-06-12 17:22 UTC
Labels: Enhancement

**Comment by dxcvvxd** [comment] 2023-03-14 18:58
why is everyone saying "duplicate of n" but the issue is still unresolved, and since everyone is mentioning it, why not just implement it already?

**Comment by mmahmoudian** [comment] 2023-03-15 06:30
@dxcvvxd 

> why is everyone saying "duplicate of n" but the issue is still unresolved, and since everyone is mentioning it, why not just implement it already?

This is an opensource project anyone in the world with some minimal internet can contribute to this project. Also any positive contribution is as always very welcome. Have you contributed yet? If not, here are some links that can guide you how to contribute:

https://github.com/flameshot-org/flameshot/blob/master/docs/CONTRIBUTING.md

If you don't have technical skills, you can always contribute in other ways:

https://flameshot.org/donate/
