### ISSUE TITLE
Flameshot gui is not working with a shortcut

### ISSUE THREAD

**Issue by olikiverjesus** [flameshot-org/flameshot#3401] opened 2023-11-04 16:19 UTC
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Unbuntu 23.10

### Description

I run flameshot and flameshot gui into terminal and just flameshot works and I can't take screenshots with the shortcut

He's the log:

olikiver@olikiver-Vostro-3500:~$ dbus-monitor --session sender=org.flameshot.Flameshot
signal time=1699113953.140365 sender=org.freedesktop.DBus -> destination=:1.132 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.132"
signal time=1699113953.140513 sender=org.freedesktop.DBus -> destination=:1.132 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.132"
method call time=1699113969.837606 sender=:1.133 -> destination=org.freedesktop.DBus serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1699113969.837668 sender=:1.133 -> destination=org.freedesktop.DBus serial=13 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameHasOwner
   string "org.a11y.Bus"
method call time=1699113969.837895 sender=:1.133 -> destination=org.freedesktop.DBus serial=14 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
method call time=1699113969.837961 sender=:1.133 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method call time=1699113969.838151 sender=:1.133 -> destination=org.a11y.Bus serial=16 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "ScreenReaderEnabled"
method call time=1699113969.838910 sender=:1.133 -> destination=org.a11y.Bus serial=17 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "IsEnabled"
method call time=1699113986.437269 sender=:1.133 -> destination=org.freedesktop.Notifications serial=18 path=/org/freedesktop/Notifications; interface=org.freedesktop.DBus.Introspectable; member=Introspect
method call time=1699113986.438361 sender=:1.133 -> destination=org.freedesktop.DBus serial=19 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method call time=1699113986.438466 sender=:1.133 -> destination=org.freedesktop.DBus serial=20 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.Notifications"
method call time=1699113986.438940 sender=:1.133 -> destination=org.freedesktop.Notifications serial=21 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "flameshot"
   uint32 0
   string "flameshot"
   string "Flameshot Info"
   string "Captura salva na área de transferência."
   array [
   ]
   array [
   ]
   int32 5000
method call time=1699113986.451455 sender=:1.133 -> destination=org.freedesktop.DBus serial=22 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.Notifications'"
method return time=1699113986.458374 sender=:1.133 -> destination=:1.135 serial=23 reply_serial=21
method call time=1699113988.365877 sender=:1.133 -> destination=org.freedesktop.portal.Desktop serial=24 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.DBus.Introspectable; member=Introspect
method call time=1699113988.371057 sender=:1.133 -> destination=org.freedesktop.DBus serial=25 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699113988.371347 sender=:1.133 -> destination=org.freedesktop.DBus serial=26 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Desktop"
method call time=1699113988.372208 sender=:1.133 -> destination=org.freedesktop.DBus serial=27 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Desktop"
method call time=1699113988.372804 sender=:1.133 -> destination=org.freedesktop.DBus serial=28 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.portal.Desktop',path='/org/freedesktop/portal/desktop/request/1_133/8319b1ecf5e545c4b0e16e7629ca0084',interface='org.freedesktop.portal.Request',member='Response'"
method call time=1699113988.372835 sender=:1.133 -> destination=org.freedesktop.DBus serial=29 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699113988.372850 sender=:1.133 -> destination=org.freedesktop.DBus serial=30 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Desktop"
method call time=1699113988.373207 sender=:1.133 -> destination=org.freedesktop.portal.Desktop serial=31 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.Screenshot; member=Screenshot
   string ""
   array [
      dict entry(
         string "handle_token"
         variant             string "8319b1ecf5e545c4b0e16e7629ca0084"
      )
      dict entry(
         string "interactive"
         variant             boolean false
      )
   ]
method call time=1699113988.947758 sender=:1.133 -> destination=org.freedesktop.portal.Desktop serial=32 path=/org/freedesktop/portal/desktop/request/1_133/8319b1ecf5e545c4b0e16e7629ca0084; interface=org.freedesktop.portal.Request; member=Close
method call time=1699113988.949660 sender=:1.133 -> destination=org.freedesktop.DBus serial=33 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.portal.Desktop',path='/org/freedesktop/portal/desktop/request/1_133/8319b1ecf5e545c4b0e16e7629ca0084',interface='org.freedesktop.portal.Request',member='Response'"
method call time=1699113988.949692 sender=:1.133 -> destination=org.freedesktop.DBus serial=34 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699113988.949728 sender=:1.133 -> destination=org.freedesktop.DBus serial=35 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699114161.191172 sender=:1.133 -> destination=org.freedesktop.DBus serial=36 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699114161.191208 sender=:1.133 -> destination=org.freedesktop.DBus serial=37 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Desktop"
method call time=1699114161.191372 sender=:1.133 -> destination=org.freedesktop.DBus serial=38 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Desktop"
method call time=1699114161.191529 sender=:1.133 -> destination=org.freedesktop.DBus serial=39 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.portal.Desktop',path='/org/freedesktop/portal/desktop/request/1_133/eccbe35cca124e82a2c46ecf88f97d2b',interface='org.freedesktop.portal.Request',member='Response'"
method call time=1699114161.191538 sender=:1.133 -> destination=org.freedesktop.DBus serial=40 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699114161.191572 sender=:1.133 -> destination=org.freedesktop.DBus serial=41 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.freedesktop.portal.Desktop"
method call time=1699114161.191755 sender=:1.133 -> destination=org.freedesktop.portal.Desktop serial=42 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.Screenshot; member=Screenshot
   string ""
   array [
      dict entry(
         string "handle_token"
         variant             string "eccbe35cca124e82a2c46ecf88f97d2b"
      )
      dict entry(
         string "interactive"
         variant             boolean false
      )
   ]
method call time=1699114161.759118 sender=:1.133 -> destination=org.freedesktop.portal.Desktop serial=43 path=/org/freedesktop/portal/desktop/request/1_133/eccbe35cca124e82a2c46ecf88f97d2b; interface=org.freedesktop.portal.Request; member=Close
method call time=1699114161.759840 sender=:1.133 -> destination=org.freedesktop.DBus serial=44 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.portal.Desktop',path='/org/freedesktop/portal/desktop/request/1_133/eccbe35cca124e82a2c46ecf88f97d2b',interface='org.freedesktop.portal.Request',member='Response'"
method call time=1699114161.759873 sender=:1.133 -> destination=org.freedesktop.DBus serial=45 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"
method call time=1699114161.759888 sender=:1.133 -> destination=org.freedesktop.DBus serial=46 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.freedesktop.portal.Desktop'"

### Steps to reproduce

Try to define a shortcut and print the screen 

Try to run flameshot gui into terminal of linux

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/149892232/4b0a6efe-c27e-47d1-8db2-d6db8e0f61e9)

![image](https://github.com/flameshot-org/flameshot/assets/149892232/f8f4b9be-b043-44f5-b29d-ca48cccbc548)

### System Information

![image](https://github.com/flameshot-org/flameshot/assets/149892232/75f440e7-be37-46aa-92ad-10870275e92c)

**Comment by Dazix** [comment] 2023-11-06 10:13
Same for me, after update Ubuntu from 23.04 to 23.10. 

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8

Works from cli but not through shortcut.

**Comment by neo-turak** [comment] 2023-11-07 02:39
same here, Ubuntu 23.10 Gnome Wayland, not working witch shortcut.

**Comment by mmahmoudian** [comment] 2023-11-08 06:06
This seems to be duplicate of #3383 and the solution to this round of Gnome's behavior is here:

https://github.com/flameshot-org/flameshot/issues/3383#issuecomment-1789630803

**Closed** 2023-11-08 06:06 UTC
Labels: Duplicate, Unconfirmed Bug

**Comment by neo-turak** [comment] 2023-11-10 02:34
just set the shortcut value to ``/bin/sh -c '/usr/bin/flameshot gui'`` then it works.

**Comment by superuser-miguel** [comment] 2024-05-29 02:34
@neo-turak Does not work for me. . .
