### ISSUE TITLE
Captures 'old' area when 'Allow applications to block compositing' is disabled on KDE Plasma.

### ISSUE THREAD

**Issue by nerve-sys** [flameshot-org/flameshot#2464] opened 2022-03-02 00:16 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.11-arch1-1
arch: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux version 5.16.11-arch1-1 (linux@archlinux) [from `cat /proc/version`]

### Description

Sometimes, when invoking flameshot through `flameshot gui`, 'Allow applications to block compositing' disabled, flameshot will capture an 'old' version of the screen (eg. a file explorer that was open 5 minutes ago, but has been closed since.) I was able to fix this by going into System Settings > Compositor > 'Allow applications to block compositing' and checking the box/enabling it. After pressing 'Apply', flameshot worked as normal once again. After disabling once again, flameshot still worked normally, so I'm not entirely sure what the cause of this problem is.

Notes:
This persisted across reinstalls, I first reinstalled flameshot from  the `community` repo, and it persisted. I reinstalled using `flameshot-git` from the AUR, and it still persisted. (The version I am using at the time of this post is what I posted in Flameshot Version, from the `community` repo.)

This issue was not always present on my system. I had the option disabled in KDE compositor settings when I installed flameshot for the first time, and it worked normally for a while.

### Steps to reproduce

1. Ensure 'Allow applications to block compositing' is disabled in System Settings > Compositor 
2. Invoke flameshot through `flameshot gui`
3. Observe the 'flameshot screen' being different than the 'real screen'

### Screenshots or screen recordings

I am no longer able to replicate this issue, however if I can, I will provide a screen recording.

### System Information

Arch Linux version 5.16.11-arch1-1 (linux@archlinux) [from `cat /proc/version`]

![image](https://user-images.githubusercontent.com/75956940/156270552-82538f55-ff4a-4b70-b190-9c63aa27a80b.png)

KDE Plasma, KWin
Xorg

**Comment by hidden-r4d** [comment] 2022-03-02 22:49
Sorry, I wasn't able to find the issue by searching so I made this one. As for graphics card and driver, I'm using a laptop with integrated graphics. I'm not sure how I would get information for these, but if you know a command I'll be happy to show the output.

**Comment by mmahmoudian** [comment] 2022-03-03 07:28
The issue is not invalid, the problem is we don't know how to make it happen on our computers so that we can investigate it. Yesterday I turned off the compositor settings on my Manjaro KDE and so far it hasn't happened. I'll keep it for few more days just in case. On that computer my graphics card is also Intel

**Comment by hidden-r4d** [comment] 2022-03-03 19:09
I was able to reproduce it a few more times (forgot to record, sorry) and the setting was enabled, so that alone isn't the deciding factor. However, toggling the setting a couple times fixed it again, so that's interesting.

**Comment by mmahmoudian** [comment] 2022-03-03 21:33
I have toggled that compositor setting and still haven't been able to reproduce it. I'll keep it some more days with the hope of getting the bug...

**Comment by borgmanJeremy** [comment] 2022-04-05 15:47
I'll close this in favor of the duplicate.

**Closed by borgmanJeremy** 2022-04-05 15:47 UTC
Labels: Bug, Waiting For Info
