### ISSUE TITLE
Ability to bind the "select area to grab" capture method to the "print screen" button in the General Configuration.

### ISSUE THREAD

**Issue by Dereavy** [flameshot-org/flameshot#3060] opened 2023-01-18 08:53 UTC
## The Feature:
A General configuration setting to bind preferred capture method options to the print screen button for ease of use.

**The process that lead to me wanting this feature:**
When I press the print screen button I get a full screen screen shot with the buttons "cancel", "options" and "share".
When I got to the "options" I have a few options:
- Grab the whole screen
- Grab the current window
- Select area to grab
- Grab after a delay of [n] seconds

I select "select area to grab".
After selecting this option I have to click the "take screenshot" button to take a second screenshot, the one that I need.

**How this improves ease of use**
 1. Being able to use the preferred capture method on print screen button press would greatly improve the user experience.
 2. The above process to get a screenshot of a portion of a screen currently doesn't allow me to get certain screenshots, **without this feature it is near impossible to capture specific events** (ex a specific part of a video presentation) as the video or moving elements continue to move in the background while I try to select the "Select area to grab" option.
Meanwhile pressing "print screen" and having the screen freeze and taking the time to select the needed part straight away is a major improvement rendered possible by setting some default configuration settings beforehand.

## Notes :
After updating to the new version of Ubuntu, I had to change my print screen button to work with Flameshot since it was overwritten by the default screenshot program, I did so following the guide ["How to assign PrtScr(Print Screen) key to Flameshot screenshot tool in Gnome 3"](https://gist.github.com/linuxkathirvel/5e8bb416f487b4b47a97daa42288502f) on Github .
I did not find any way to bind flameshot to the print screen button from the flameshot gui. 
**Specifications**
Operating system: Ubuntu 22.04
Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-57-generic
ubuntu-core: 20

**Comment by mmahmoudian** [comment] 2023-01-21 12:12
Thank you for filing this issue, but this has two folds:
1. you are using Gnome and that window with cancel and share button are Gnome thing which is very well explained in the following link. It has nothing to do with Flameshot and **any other screenshot too will have the same behavior** due to the way Gnome is treating other developers. Your solution is to se better desktop environments like KDE, Xfce, LxQt, Budgie, ... :
https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time
2. key binding in Linux distros should be done via your Window Manager or Desktop Environment. You have to bind the keybinding you want to a particular command or application yourself (it is very easy even in Gnome). Usually people bind it to this command: `flameshot gui`, but you can see the following link on how to use the flameshot via commandline and what are your options and how you can improve your workflow:
https://flameshot.org/docs/advanced/commandline-options/ 

I will close this issue as it is duplicate of many other similar issues, and because both points you raised are things that are not under our control. You can of course comment here if you need help and I will try to help you setup your computer to use Flameshot better and easier (even in Gnome).

**Closed by mmahmoudian** 2023-01-21 12:12 UTC
Labels: Enhancement

**Comment by thenishantsoni78** [comment] 2023-07-03 05:42
Uncomment the line in gdm configuration.
sudoedit /etc/gdm3/custom.conf

`#WaylandEnable=false`

After that, reboot your system or run below command
`sudo systemctl restart gdm3`


It will fix all issues. No more issues related to selection type or share and edit.
