### ISSUE TITLE
Difficulty assigning capture shortcut on Windows 10

### ISSUE THREAD

**Issue by Dont-ask-for-it** [flameshot-org/flameshot#2925] opened 2022-09-28 15:31 UTC
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

Shortcut option is greyed out to PrtSC and does not work. Windows capture tool is opened instead. 

### System Information

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

**Comment by mmahmoudian** [comment] 2022-09-28 18:37
Duplicate of #1341

About Windows Snipping Tool, follow these instructions:

https://github.com/flameshot-org/flameshot/issues/1551#issuecomment-1232164940


Please search before creating a new issue.

**Closed** 2022-09-28 18:37 UTC
Labels: Duplicate, question, Windows
