### ISSUE TITLE
MacOS White Trayicon

### ISSUE THREAD

**Issue by kholisrag** [flameshot-org/flameshot#2017] opened 2021-10-28 05:32 UTC
**Is your feature request related to a problem?**

Can we have MacOS White Tray Icon?

![Screenshot_2021-10-28_12-31](https://user-images.githubusercontent.com/4683704/139192911-0fe8077e-721f-4c22-b01f-da604f3406af.png)

its not good enough for my eye 😄 

any simple way to make this possible?

**Comment by borgmanJeremy** [comment] 2021-10-30 20:09
@mmahmoudian we actually dont directly have a monochrome icon. Other people have themed the icon [here for example](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/f8bc341fe1412c6c11bf97695564185f545ecd9f). Then on linux Qt picks up that themed icon first. 

On Mac the icon is actually compiled into the binary we would need to copy the svg from that git repo into our source tree and build the Mac version against it. 

If we do that we need to modify the svg to include its license (GPLv3) and point back to the original author.

**Comment by mmahmoudian** [comment] 2021-10-30 21:06
@borgmanJeremy interesting! I didn't know this. But about adding the SVG, we have the actual Flameshot icon. I think we can put together a monochrome stroke only version. This way it would be our own svg and we can license it to our project's preference.

**Comment by borgmanJeremy** [comment] 2021-10-30 21:19
Yeah I'm not worried about the licensing, just want to make sure we credit properly. But yeah by all means if someone wants to make a new one that's fine with me.

**Comment by Faetu** [comment] 2021-11-01 08:33
Hi mmahmoudian

What ending has a monochrome icon?
And what is the size?

best regards

**Comment by mmahmoudian** [comment] 2021-11-01 08:58
@Faetu If by ending you mean file extension or file format, would be nice to have SVG file. You can use the content of the following folder:
https://github.com/flameshot-org/flameshot/tree/master/data/img/app

**Comment by Faetu** [comment] 2021-11-01 16:19
Hi @mmahmoudian 

Its done!
![image](https://user-images.githubusercontent.com/55803495/139704665-5e247ff1-cff7-4c09-8112-dc875d6f0209.png)
I made three types. One normal, without gaps between the flames.
A second with small gaps and a third with lager gaps between the flames.
All three in .png and .svg format.
[flameshot.tray.zip](https://github.com/flameshot-org/flameshot/files/7454638/flameshot.tray.zip)

Now, how to continue to make this public and downloadable for everyone?
Do we need to make a pull-request?

best regards

**Comment by mmahmoudian** [comment] 2021-11-01 19:08
@borgmanJeremy @veracioux what do you think is the best approach? Would it be good if @Faetu create a PR with these new icons in the same folder as the other icons:

https://github.com/flameshot-org/flameshot/tree/master/data/img/app

**Comment by veracioux** [comment] 2021-11-02 08:15
I think it's better that one of the developers creates the PR, because the code needs to be changed as well. Of course ensuring proper credit to @Faetu. I could do it, but I don't have a Mac VM set up (yet), so I think it's better that someone else do it.

**Comment by borgmanJeremy** [comment] 2021-11-02 12:11
Ok cool I'll do it.

**Comment by borgmanJeremy** [comment] 2021-11-02 19:33
I think maybe we should take this opportunity to add a config option to switch between color and monochrome icons? Im certain someone on windows will ask for the same thing.

The alternative to is to simply package the monochrome icon on Mac when we build the .dmg.

**Comment by veracioux** [comment] 2021-11-02 20:16
@borgmanJeremy We are adding too many config options :smile:.

**Comment by borgmanJeremy** [comment] 2021-11-02 20:17
I think the issue isn't the number of options, but how they are organized in the config screen.

**Comment by mmahmoudian** [comment] 2021-11-02 20:40
As long as customisability doesn't affect the performance I personally don't see any issues in that. In contrary I think it would make it much easier for people to adopt it to their workflow.

**Comment by borgmanJeremy** [comment] 2021-11-16 21:28
Okay so adding this as a run time configuration turned out to be pretty complicated to support across all the different DE's and operating systems. Not impossible, but as a first step I made it a build time option.

Feel free to test in on #2071 but it seems to work for me

![image](https://user-images.githubusercontent.com/46930769/142068519-faae9360-7e07-4ccd-b5ba-6c1066a21828.png)

**Comment by makeworld-the-better-one** [comment] 2021-11-17 01:01
How can I use the white tray icon on Linux XFCE? Right now it is the black version which is near impossible to see.

![image](https://user-images.githubusercontent.com/25111343/142090265-07695075-6627-438f-a875-3e149ab51bdc.png)

**Comment by borgmanJeremy** [comment] 2021-11-17 01:11
Can you please open a separate issue for that? Icons in Linux are managed totally different and I don't want to clog this issue with that discussion. As a quick answer if you google XFCE change icon theme you will find it. But feel free to open something on the GitHub discussions if you need help.

**Comment by makeworld-the-better-one** [comment] 2021-11-17 01:18
My bad. I've created issue #2083.

**Comment by borgmanJeremy** [comment] 2021-11-18 03:25
Merged new icon on Macos

**Closed by borgmanJeremy** 2021-11-18 03:25 UTC
Labels: Enhancement, Visuals, MacOS

**Comment by ww7** [comment] 2021-12-20 16:13
Bug with multiple monitors setup, icon flattened on non active screen
https://github.com/flameshot-org/flameshot/pull/2071#issuecomment-998003292
