### ISSUE TITLE
v11 breaks copying screenshot to clipboard in kde wayland

### ISSUE THREAD

**Issue by pizzadude** [flameshot-org/flameshot#2276] opened 2022-01-17 20:38 UTC
### Flameshot Version

v11

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Fedora 35 KDE

### Description

After latest update to Flameshot v11, when I try to copy a screenshot to clipboard either by using the button or keybind, the screenshot is not copied to the clipboard at all. I use Fedora 35 KDE Wayland. Downgrading to version 0.10.2 solves the issue. Flameshot is installed from rpm.

### Steps to reproduce

1. be on flameshot v11
2. be on kde 5.23.x wayland
3. take a screenshot and use the copy to clipboard function
4. notice the screenshot is not copied

### System Information

Operating System: Fedora Linux 35
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.15.14-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by borgmanJeremy** [comment] 2022-01-17 21:09
version 10.2 ran on XCB, but users reported this caused hotkeys to break: https://github.com/flameshot-org/flameshot/pull/2131

So we reverted it to run on actual wayland. KDE Wayland isn't as stable as gnome yet and tends to have more issues with flameshot. It's really hard at this time to understand if its a flameshot, plasma wayland, or Qt issue

**Comment by borgmanJeremy** [comment] 2022-01-17 21:10
Hopefully it is resolved with QT6 https://github.com/flameshot-org/flameshot/issues/2099, my focus will be on Qt6 before triaging this issue.

**Comment by xvitaly** [comment] 2022-01-18 08:22
> version 10.2 ran on XCB, but users reported this caused hotkeys to break: #2131

Fedora's 0.10.2 had backported patch from this commit. If he said that everything worked fine, then the problem is something else.

**Comment by pizzadude** [comment] 2022-01-18 08:39
> version 10.2 ran on XCB, but users reported this caused hotkeys to break: #2131
I'm the one who reported that issue, and I used Fedora's package with that commit backported, and it worked right. So I agree with xvitaly, it has to be something else.

**Comment by borgmanJeremy** [comment] 2022-01-18 15:11
I tested this on a hacked flameshot built against Qt 6.2.2 and the issue is still present. I might be hitting a dead end with this, any ideas on how to troubleshoot the clipboard?

**Comment by pizzadude** [comment] 2022-01-18 15:21
I'm not a dev but something tells me it might be related to getting rid of d-bus support?

**Comment by borgmanJeremy** [comment] 2022-01-18 15:22
I updated my comment with steps to make it work and fail

**Comment by pizzadude** [comment] 2022-01-18 15:32
I can't try those steps because wl-paste -l hangs when I copy from flameshot and I tried the workaround without using wl-clipboard and it didn't cause it to work correctly.

**Comment by h0nus** [comment] 2022-01-18 16:32
Having same issue on Fedora 35 updated.

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

OS: Fedora Linux 35 (Workstation Edition) x86_64
Kernel: 5.15.14-200.fc35.x86_64
DE: GNOME 41.3

Flameshot seems to be broken

if i start normally with `flameshot` no data nor output is given

with `flameshot gui` the GUI opens, but when i save it to clipboard nothing is saved,
same goes with `full -c` and `screen -c` commands.

**Comment by h0nus** [comment] 2022-01-18 16:45
Yep
```
Last metadata expiration check: 3:02:36 ago on Tue 18 Jan 2022 02:42:23 PM CET.
Package xdg-desktop-portal-gnome-41.1-1.fc35.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
 ```

**Comment by borgmanJeremy** [comment] 2022-01-18 16:58
Iets move the gnome discussion to its own issue. I'm going to moderate this thread to only focus on KDE.

**Comment by borgmanJeremy** [comment] 2022-01-18 16:59
I dont think there is one yet

**Comment by borgmanJeremy** [comment] 2022-01-19 20:00
#2284  Should fix this. I tested it on arch built from source. I still need to do testing on the flatpak and snap before merging. 

Please read the comment on that PR. I only implemented this in flatpak and snap because i didnt want to deal with backporting the dependency on other platforms. I'm open to a PR to add it to the .debs and .rpms.

**Comment by xvitaly** [comment] 2022-01-19 20:07
> I'm open to a PR to add it to the .debs and .rpms.

Fedora has kf5-kguiaddons packaged. I can try building with it.

**Comment by borgmanJeremy** [comment] 2022-01-19 20:10
I think you will need 5.89.0 or later. I only tested 5.90, and 5.88 and earlier did not contain the clipboard code. 

I didn't try on fedora but the issue on debian and ubuntu was the versions of kf5-kguidaddons they  package were too old. I tried to embed the source, but it isnt really feasible because of the transient dependencies.

**Comment by xvitaly** [comment] 2022-01-19 20:24
> I think you will need 5.89.0 or later. I only tested 5.90, and 5.88 and earlier did not contain the clipboard code.

kf5-kguiaddons-5.89.0-1.fc35.x86_64

**Comment by borgmanJeremy** [comment] 2022-01-21 21:58
Okay #2284  is merged so I will close this issue. It will be present for the next snap / flatpak release. Distributions can optionally enable the fix if the required dependencies are present.

@mmahmoudian can you update the AUR to enable this flag and add the dependency?

**Closed by borgmanJeremy** 2022-01-21 21:58 UTC
Labels: Unconfirmed Bug, Wayland

**Comment by mmahmoudian** [comment] 2022-01-22 08:08
@borgmanJeremy is only for Wayland and it will hurt xorg users or it can work for both? I'm asking this because you added a flag to make it configurable and I wonder if it is because of Ubuntu and other distros, as you explained in your PR message, or because of xorg.

If it doesn't hurt the xorg users I think it should be added as a normal dependency, otherwise it should become an optional dependency.

**Comment by xvitaly** [comment] 2022-01-22 10:19
[Backported](https://src.fedoraproject.org/rpms/flameshot/c/226b41efa77e74907f3a2c58f2f9a2e8b04794f2?branch=rawhide) upstream fix Fedora.

@h0nus Can you try [this build](https://bodhi.fedoraproject.org/updates/FEDORA-2022-c2a1f83868)?

**Comment by pizzadude** [comment] 2022-01-22 10:48
@xvitaly I can confirm the bug is fixed with that build. :D

**Comment by borgmanJeremy** [comment] 2022-01-22 15:44
@mmahmoudian it should only affect wayland users. The reason its behind a flag is most distro's do not have a new enough version of KF5GuiAddons so compilation will fail. Fedora and Arch have new enough versions.

**Comment by mmahmoudian** [comment] 2022-01-30 15:14
AUR was modified accordingly:
https://aur.archlinux.org/cgit/aur.git/commit/?h=flameshot-git&id=d84205033b1f27c112a0b9cbc952a2c70234b300

**Comment by AshleySchaeffer** [comment] 2023-04-18 08:04
> I tested this on a hacked flameshot built against Qt 6.2.2 and the issue is still present. ~I might be hitting a dead end with this, any ideas on how to troubleshoot the clipboard?~
> 
> Okay this is almost certainly a mime issue. Steps to figure this out:
> 
>     * Install wl-clipboard
> 
> 
> ## Make it Fail
> 
>     * wl-copy -c #Clear clipboard
> 
>     * Use flameshot to take picture and copy to clipboard
> 
>     * wl-paste -l
>       
>       * Notice that the mime type is not set
>       * try to paste into pinta and it fails
> 
> 
> ## Make it work
> 
>     * wl-copy -c # clear clipboard
> 
>     * use spectacle to take screen shot and copy to clipboard
> 
>     * wl-paste -l
>       
>       * See that mime types are correct
>       * Able to paste into pinta
> 
>     * take a new screenshot with flameshot and copy to clipboard
> 
>     * wl-paste -l
>       
>       * See that the MIME type from spectacle is still there
>       * try to paste into pinta and the flameshot image properly pastes in

FYI this fixed the issue for me on:

Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
linux: 6.2.10-200.fc37.x86_64
org.kde.Platform: 5.15-21.08

Installed via flatpak flathub
