### ISSUE TITLE
have a Confirmation option to confirm abort

### ISSUE THREAD

**Issue by paulpreibisch** [flameshot-org/flameshot#3102] opened 2023-02-16 18:02 UTC
### Feature Description

Often times I click the arrow button a second time, and my flameshot is aborted! Please add an option that confirms abort

Here are the steps to reproduce:

    start a screenshot
    click text icon,
    click the screenshot somewhere, and then type text, or don't type text, either one is ok
    click arrow icon

Result: screenshot is aborted as soon as I click the arrow icon
### Feature Request: 
If flameShot wants to abort the screenshot, a confirmation message should read: "Do you want to abort this screenshot? Ok? Cancel

Workaround: User must first click the text icon again, to deselect the text tool, THEN click arrow tool

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 6.2.6-76060206-generic
pop: 22.04

**Comment by mmahmoudian** [comment] 2023-02-19 10:54
Are you implying that double click on arrow button aborts the whole screenshot?! This is so confusing for me. Can you elaborate more.

**Comment by paulpreibisch** [comment] 2023-07-10 15:07
Hi mmahmoudian, sorry for the confusion, here are the steps to reproduce:
1) start a screenshot
2) click text icon,
3) click the screenshot somewhere, and then type text, or don't type text, either one is ok
4) click arrow icon

Result: screenshot is aborted as soon as I click the arrow icon
Expected:  after clicking the arrow icon, the arrow tool should be selected so I can start drawing arrows
Expectation 2:  If flameshot wants to abort the screenshot, a confirmation message should read: "Do you want to abort this screenshot? Ok? Cancel

Workaround:  User must first click the text icon again, to deselect the text tool, THEN click arrow tool

**Comment by mmahmoudian** [comment] 2023-07-12 13:58
This is duplicate of #2238 (and 9 other duplicates) which have been already resolved by #2369 on 2022-02-05.

Please consider updating to the latest version.

**Closed by mmahmoudian** 2023-07-12 13:58 UTC
Labels: Enhancement, Waiting For Info
