### ISSUE TITLE
Keyboard does not have 'prtscr'

### ISSUE THREAD

**Issue by youmoxiaozi** [flameshot-org/flameshot#2493] opened 2022-03-19 02:54 UTC
### Flameshot Version

 v11

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

win10

### Description

Shortcut keys cannot be changed

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/26620499/159104023-31928945-ef9f-49b9-9210-4d181ce26f72.png)

### System Information

win10

**Comment by mmahmoudian** [comment] 2022-03-19 07:42
Duplicate of #1341

Read this for a workaround:

https://github.com/flameshot-org/flameshot/issues/1861#issuecomment-910552032

**Closed** 2022-03-19 07:43 UTC
Labels: Duplicate, Enhancement, Windows
