### ISSUE TITLE
Does not work correctly flameshot

### ISSUE THREAD

**Issue by babaSveta** [flameshot-org/flameshot#2905] opened 2022-09-11 08:33 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-47-generic
ubuntu: 22.04

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 22.04

### Description

Hello. Switched from ubuntu version 20.04 to 22.04, changing the computer. I have 2 problem, most likely they are related to the fact that the resolution of my new laptop 3456x2160. I tried to change all proprietary drivers, it didn't help. Now I have a "Megapackage of Nginx drivers from nvidia-driver-470"

Problems:
1. When I run the "flameshot gui" command from terminal, the following happens. 
https://youtu.be/RRkDAXyrCKs?t=40

2. When I run the "flameshot" from interface, the following happens. the selection area can only be made to a limited area of the monitor. Changing the resolution in the Ubuntu settings does not help, I lowered it to 2k.
https://youtu.be/andwhPboz34

### System Information

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 5.15.0-47-generic
ubuntu: 22.04

![image](https://user-images.githubusercontent.com/26580395/189512757-18dfa917-1f34-442c-8da6-c822f22add7c.png)

**Comment by mmahmoudian** [comment] 2022-09-11 16:35
Thank you for the bug report, please do the following:

- change the title to an English title
- add if you are using Wayland or X11 (if do you don't know how, read this: https://flameshot.org/docs/guide/issue-reporting/ )

Please try these:

- change your display scaling to 100% and see if it still flickers
- reboot and see if it flickers

**Comment by babaSveta** [comment] 2022-09-11 17:08
@mmahmoudian Yes, thank you, changing the scale to multiples of 100 helped, i.e. 100%, 200%, 300% works well and solves the 2 problems described above. Tell me, when will there be approximately 150%, 175% scale support?

**Comment by mmahmoudian** [comment] 2022-09-11 17:13
Duplicate of #564. Please follow the progress in that issue. I'll closing this issue.

**Closed** 2022-09-11 17:13 UTC
Labels: Waiting For Info, Unconfirmed Bug
