### ISSUE TITLE
independent thickness for each tool

### ISSUE THREAD

**Issue by yderi** [flameshot-org/flameshot#1662] opened 2021-06-09 15:29 UTC
Hi

It would be great to have an independent thickness for each tool.

So, when I set active thickness for the "Text" tool to be 30 units, at the same time, the "Line" tool with 30 units makes an inappropriate look, the same for other tools. 

An independent thickness for each tool will solve the problem of the constant setting of thickness after changing the tool. 

OS: Ubuntu 20.04.2 LTS
Flameshot: 0.9.0

Regards,
Flameshot user

**Comment by mmahmoudian** [comment] 2021-06-09 16:22
This is duplicate of #782. Please read [this comment](https://github.com/flameshot-org/flameshot/issues/782#issuecomment-841414610)

**Closed** 2021-06-09 16:22 UTC
Labels: Duplicate, Enhancement
