### ISSUE TITLE
copy image function problem

### ISSUE THREAD

**Issue by MrAnon-dev** [flameshot-org/flameshot#935] opened 2020-09-18 11:54 UTC
**Flameshot version**
0.8.0

**Describe the bug**
With option "Close after capture" enabled, when take a screenshot and copy it, it doesn't stay on the clipboard.

**To Reproduce**
Open the application with the option "Close after capture" enabled, select a portion of the image and click on the copy button, then try to paste the image for example in gimp. With "Close after capture" disabled, it works fine, launcher shows again and image stays in clipboard.

**Expected behavior**
make the image available on the clipboard before closing the application

**System Information**
Ubuntu 20.04 64bit with flameshot_ubuntu_0.8.0-1_amd64.deb package

thanks so much!

**Comment by mmahmoudian** [comment] 2020-09-18 12:32
In the AppImage on Ubuntu 18.04 I don't see this issue.

@MrAnon-dev do you have a special clipboard manager? (e.g CopyQ)

**Comment by MrAnon-dev** [comment] 2020-09-18 14:14
@mmahmoudian no, I don´t, default ubuntu clipboard.

maybe can be related with this? https://bugs.launchpad.net/ubuntu/+bug/11334

**Comment by borgmanJeremy** [comment] 2020-09-18 15:05
I believe this is a duplicate of #896 . We are going too look at integrating flameshot with xclip to fix this issue.

**Closed** 2020-09-24 16:11 UTC
Labels: Duplicate, Linux
