### ISSUE TITLE
Auto-select windows on hover

### ISSUE THREAD

**Issue by eugenesvk** [flameshot-org/flameshot#1904] opened 2021-09-17 08:55 UTC
Currently, if I wanted to select a **window** of some app **precisely,** I have to manually move&adjust the selection window to match the app's window, which is not easy to do perfectly
It would be great if flameshot could **auto-identify** and auto-select the window **on hover**

Below is an example screenshot of another screenshotting app's process that does exactly this: note the orange dashed rectangle around the **Security & Privacy** window that is automatically identified&suggested by the app once I hover the crosshair tool over a window (I can then click to select it and do any additional adjustments if needed)

![Snagit_Autoselect](https://user-images.githubusercontent.com/12956286/133754040-488c40e5-50f8-43ba-b38d-3f1086a8728e.png)

**Comment by mmahmoudian** [comment] 2021-09-17 11:08
Isn't this a duplicate of #1814 ?

**Comment by eugenesvk** [comment] 2021-09-17 11:28
> Isn't this a duplicate of #1814 ?

It's close to how ZetaoYang understood it https://github.com/flameshot-org/flameshot/issues/1814#issuecomment-895660648, though I believe that the hover method proposed here vs a shortcut mentioned in the issue you linked is more convenient

Though now I've just found another feature request that is like mine with the mouse hover (https://github.com/flameshot-org/flameshot/issues/1816, apologies for overlooking it initially), which was closed in favor of https://github.com/flameshot-org/flameshot/issues/334, though that one also doesn't have a `hover` method proposed, but rather a focused window only, so none of the currently opened issues seem to exactly match this

**Comment by borgmanJeremy** [comment] 2022-07-07 00:54
Given that there is no clear strategy to implement #334, and that is a building block for this I am going to close this until we have some strategy for capturing a window. Feel free to comment on that issue that a hover capture would be nice.

**Closed by borgmanJeremy** 2022-07-07 00:54 UTC
Labels: Enhancement
