### ISSUE TITLE
Larger UI font size

### ISSUE THREAD

**Issue by dgmulf** [flameshot-org/flameshot#645] opened 2019-11-01 23:02 UTC
On my HiDPI monitor, the text in the Flameshot UI is uncomfortably small.

**Comment by Mart-Bogdan** [comment] 2020-01-03 22:16
What OS, is this Windows?

**Comment by dgmulf** [comment] 2020-01-06 03:50
Arch Linux.

**Comment by Mart-Bogdan** [comment] 2020-01-08 12:48
Strange, I thought on Linux HiDPI scaling was messed up, so everything got double scale.

Are you using UI scaling? so UI elements of regular apps are larger? Only flameshot not scaling?

**Comment by dgmulf** [comment] 2020-01-08 16:41
I've got a high DPI specified in my Xorg config, but I don't have any
specific configuration for GTK/QT scaling, if that even exists.

**Comment by Mart-Bogdan** [comment] 2020-01-09 00:29
I have't tryed any xorg configurations. Actually my xorg info says i have 96x96 ppi.
But i tested kde scaling and corsponding gnome settings.

Lightshot was completely messed up with scaling settings.

But after my fix (not merged) it works. Qnd I can record that flameshot text and buttons are scaled up in such case.

But I can notice that on Windows OS flameshots text and buttons are small disregarding DPI settings, both on old version and with my patch.

Perhaps you could share some screenshots took by other program or photos?

Actually i was able to take screenshots of flameshot with Spectacle, lol.

But I'm not sure I'll be able to reproduce x.org settings, as I'm unfamiliar with this. Ubuntu user :)

**Comment by rodmax** [comment] 2020-05-10 10:31
Hi there. bellow i show my example of text over screenshot, 

personally i ll be happy, if this font size will be at least the same as cropped message text size on screenshot


![image](https://user-images.githubusercontent.com/6079597/81496648-b7e80100-92c1-11ea-83a9-b85dc54a5a79.png)

env: Ubuntu 20.04, flameshot version

![image](https://user-images.githubusercontent.com/6079597/81496714-4fe5ea80-92c2-11ea-9354-e90e98cb7dde.png)

![image](https://user-images.githubusercontent.com/6079597/81496736-786de480-92c2-11ea-8bc4-6305538b4e50.png)

**Comment by borgmanJeremy** [comment] 2020-09-20 17:27
Can you see if this is still an issue in 0.8? I do not have a hidpi screen to test on 😁

**Comment by mlubimow** [comment] 2020-10-09 08:19
@dgmulf Its enough to run flame shot with QT_SCALE_FACTOR=2 to solve this issue

**Comment by dgmulf** [comment] 2020-10-11 00:13
I'm on Manjaro GNOME instead of the Arch + dwm setup I was using when I opened the issue, but I can happily say that the teeny text issue is gone now!

**Comment by damufo** [comment] 2020-12-21 15:26
Same issue in Xubuntu 20.04 XFCE desktop.
![2020-12-21_16-25](https://user-images.githubusercontent.com/4057369/102792768-3bfe7d00-43a9-11eb-9455-065effe39c4d.png)

**Comment by sw-yx** [comment] 2021-02-13 02:57
same here on mac mini, external 24' monitor (nothing crazy in terms of monitor size or resolution)

![image](https://user-images.githubusercontent.com/6764957/107839971-21b1b000-6dea-11eb-90e4-34ff044d5b66.png)


this is unfortunately a dealbreaker, even adding the ability to manually override the text size would be nice

**Comment by borgmanJeremy** [comment] 2021-02-13 03:13
The text size uses the global size which you may increase by scrolling up.

**Comment by sw-yx** [comment] 2021-02-22 21:03
@borgmanJeremy ah! that was not evident. thank you! but still not able to move the text after placing it right?

**Comment by borgmanJeremy** [comment] 2021-03-04 01:47
@sw-yx Correct, This is a highly requested feature though and I think a developer will be starting to add it soon. I will close this since the font size issue was resolved.

**Closed by borgmanJeremy** 2021-03-04 01:47 UTC
