### ISSUE TITLE
flameshot does not work in sway and fedora 38 on intel gpu

### ISSUE THREAD

**Issue by hholst80** [flameshot-org/flameshot#3205] opened 2023-05-20 08:47 UTC
### Flameshot Version

```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.8
```

```
sway version 1.8.1
```

```
NAME="Fedora Linux"
VERSION="38 (Thirty Eight)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
```

```
00:02.0 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 38 x86_64

### Description

flameshot gui does not do shit.

### Steps to reproduce

1. run `flameshot gui`
2. nothing.

### Screenshots or screen recordings

Are you trying to be smart? I can't take screenshots, thats the whole problem.

### System Information

Provided.

**Comment by mmahmoudian** [comment] 2023-05-20 12:40
> flameshot gui does not do shit.

Well, thanks for your kind words. Flameshot in fact was not designed to "do shit". You can perhaps open a feature request.

> Are you trying to be smart? I can't take screenshots, thats the whole problem.

Do you know how we have pictures of the first invented camera in the world? We used another camera! Here is a good article going deep into the history: https://www.nfi.edu/when-was-the-camera-invented

Also a constructive criticism: I know English in not your mother-tongue, but you missed adding the apostrophe. It is not "thats" but rather "that's". Generally attention to details is essential for working with data (not that I'm better than you).

-------

Now, about this issue, I will close this because:
1. you failed to respect the bug report form
2. you did not provide information to reproduce the issue (did you run `flameshot gui`? or did you click on the tray icon?, or used a custom script?, was the daemon running when you tried to capture the screen?, ...)
3. this is most probably a duplicate and didn't even read [our documentation](https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md) nor searched the [open and closed issues](https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+sway)
4. you did not provide the information we asked for in the correct field (e.g Desktop Environment and Display Server) and no, adding it in the title is not appropriate
5. zero tolerance policy for rudeness 

Perhaps next time we can contain our frustration, [as you are an expert in](https://github.com/morecontainers), and be more calm and polite while asking for help about a free software that we have not contributed a single bit to it.

**Closed by mmahmoudian** 2023-05-20 12:40 UTC
Labels: Unconfirmed Bug
