### ISSUE TITLE
Flameshot capture image in multiple screen

### ISSUE THREAD

**Issue by nedoshi** [flameshot-org/flameshot#2834] opened 2022-07-26 17:50 UTC
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.5
darwin: 21.5.0
osx: 12.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

mac M1 machine mac OS Monterey 12.4

### Description

I am trying to take screenshot on main screen but it goes to my desktop without applications

### Steps to reproduce

1. run flameshot gui
2. Select region on main mainscreen

### Screenshots or screen recordings

https://user-images.githubusercontent.com/103272684/181075943-429f7e74-b5a7-4015-b3de-2de973ac3655.mp4

### System Information

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
mac OS Monterey 12.4

**Comment by mmahmoudian** [comment] 2022-07-26 19:49
Have you read and followed instructions in these places:

https://flameshot.org/docs/installation/installation-osx/
https://flameshot.org/docs/guide/troubleshooting/#macos


Please search in issues **before** making a new bug report. Thank you.

Duplicate of #2292 and many many others.

**Closed by mmahmoudian** 2022-07-26 19:49 UTC
Labels: Unconfirmed Bug
