### ISSUE TITLE
Crashing when atempting to upload to imgur when copy URL after upload is enabled

### ISSUE THREAD

**Issue by FunWithUrban** [flameshot-org/flameshot#1423] opened 2021-03-04 00:18 UTC
**Flameshot version**
v0.9.0

**System Information**
Kubuntu 20.10

**Describe the bug**
Flameshot crashes when trying to upload to imgur if I enable "copy URL after upload" in the settings. If I disable that setting then the upload succeeds and I am able to copy the the URL from the GUI like normal. I will also add that I'm not using any keyboard shortcuts when this crash happens.

**Comment by borgmanJeremy** [comment] 2021-03-04 01:30
Thanks, the "easy" fix will be merged shortly. This issue keeps popping up and we don't understand the root cause. Anywhere in the codebase where a clipboard action occurs ahead of a DBUS notification a freeze occurs. I'd like to ultimately understand **why** this happens, but we can mask the issue by changing the order of function calls. 

For more details on the analysis see #896

**Closed** 2021-03-04 01:53 UTC
