### ISSUE TITLE
Flameshot is not working on Ubuntu 22.10 Wayland

### ISSUE THREAD

**Issue by fulljackz** [flameshot-org/flameshot#2929] opened 2022-09-30 07:29 UTC
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.10 / Gnome 43 / Wayland

### Description

Using Wayland on Ubuntu 22.10, flameshot writes a Warning and error in `/var/log/syslog` :

```
Sep 30 09:23:25 LIN-ELN flameshot[8408]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Sep 30 09:23:25 LIN-ELN flameshot[8408]: flameshot: error: Unable to capture screen
Sep 30 09:23:25 LIN-ELN flameshot[8408]: flameshot: error: Unable to capture screen
Sep 30 09:23:25 LIN-ELN flameshot[8408]: flameshot: info: Screenshot aborted
```

Here are the xdg packages installed : 
```
ii  xdg-desktop-portal         1.15.0-1ubuntu1  amd64        desktop integration portal for Flatpak and Snap
un  xdg-desktop-portal-backend <none>           <none>       (no description available)
ii  xdg-desktop-portal-gnome   43.0-1           amd64        GNOME portal backend for xdg-desktop-portal
ii  xdg-desktop-portal-gtk     1.14.0-1build1   amd64        GTK+/GNOME portal backend for xdg-desktop-portal
```

### Steps to reproduce

1. run `flameshot gui`

### System Information

Ubuntu 22.10 
Gnome 43
Wayland

**Comment by WebsiteDeveloper** [comment] 2022-10-03 01:59
Can confirm a similar error with the flatpak version:![grafik](https://user-images.githubusercontent.com/2150814/193488735-5e16c1dd-202f-4490-b2fd-cd11cd3265c6.png)

**Comment by mmahmoudian** [comment] 2022-10-03 18:14
Duplicate of #2880

Please search among existing issues before creating a new one.

**Closed** 2022-10-03 18:14 UTC
Labels: Duplicate, Unconfirmed Bug
