### ISSUE TITLE
Flameshot can't create Screenshot on Ubuntu 23.10

### ISSUE THREAD

**Issue by ajung2** [flameshot-org/flameshot#3396] opened 2023-10-30 09:30 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.3
linux: 6.5.0-10-generic
ubuntu-core: 20

### Installation Type

Snap from

### Operating System type and version

Ubuntu 23.10

### Description

I can't take a screenshot by pressing Flamshot > Take a screenshot it show an error message by the notification.

![grafik](https://github.com/flameshot-org/flameshot/assets/100683969/8599c41b-be7e-4175-ba1c-aa365675f5a1)

Systemlog:

> dbus-daemon[7516]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/gnome/Mutter/IdleMonitor/Core" interface="org.gnome.Mutter.IdleMonitor" member="GetIdletime" mask="send" name=":1.43" pid=22866 label="snap.firefox.firefox" peer_pid=7812 peer_label="unconfined"
2023-10-30T10:13:32.675366+01:00 HP-ProBook-Alex dbus-daemon[7516]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/gnome/Mutter/IdleMonitor/Core" interface="org.gnome.Mutter.IdleMonitor" member="GetIdletime" mask="send" name=":1.43" pid=22866 label="snap.firefox.firefox" peer_pid=7812 peer_label="unconfined"
2023-10-30T10:13:33.380926+01:00 HP-ProBook-Alex dbus-daemon[7516]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/MenuBar" interface="com.canonical.dbusmenu" member="Event" name=":1.43" mask="receive" pid=15371 label="snap.flameshot.flameshot" peer_pid=7812 peer_label="unconfined"
2023-10-30T10:13:33.385793+01:00 HP-ProBook-Alex dbus-daemon[7516]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/MenuBar" interface="com.canonical.dbusmenu" member="Event" name=":1.43" mask="receive" pid=15371 label="snap.flameshot.flameshot" peer_pid=7812 peer_label="unconfined"
2023-10-30T10:13:33.389440+01:00 HP-ProBook-Alex gnome-shell[7812]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.43" (uid=1000 pid=7812 comm="/usr/bin/gnome-shell" label="unconfined") interface="com.canonical.dbusmenu" member="Event" error name="(unset)" requested_reply="0" destination=":1.138" (uid=1000 pid=15371 comm="/snap/flameshot/183/usr/local/bin/flameshot" label="snap.flameshot.flameshot (enforce)")#012asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23#012@resource:///org/gnome/shell/ui/init.js:21:20
2023-10-30T10:13:33.389597+01:00 HP-ProBook-Alex gnome-shell[7812]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.43" (uid=1000 pid=7812 comm="/usr/bin/gnome-shell" label="unconfined") interface="com.canonical.dbusmenu" member="Event" error name="(unset)" requested_reply="0" destination=":1.138" (uid=1000 pid=15371 comm="/snap/flameshot/183/usr/local/bin/flameshot" label="snap.flameshot.flameshot (enforce)")#012asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:114:23#012@resource:///org/gnome/shell/ui/init.js:21:20

### Steps to reproduce

1. upgrade from ubuntu 23.04 to 23.10
2. install flameshot from ubuntu snap store
3. run flameshot
4. click on menu > Take screen shot
5. error pops up

### Screenshots or screen recordings

![grafik](https://github.com/flameshot-org/flameshot/assets/100683969/8599c41b-be7e-4175-ba1c-aa365675f5a1)

### System Information

Ubuntu 23.10
Desktop Env: ubuntu:GNOME

**Comment by mmahmoudian** [comment] 2023-10-30 20:47
duplicate of #3383

**Closed by mmahmoudian** 2023-10-30 20:47 UTC
Labels: Unconfirmed Bug

**Comment by ajung2** [comment] 2023-10-31 07:18
Why you mix apples with pears you reference Arch linux i have ubuntu 22.10 and Gnome no wayland?

**Comment by mmahmoudian** [comment] 2023-10-31 07:28
Thank you for your feedback.

Here are few points to clarify my logic:
1. You said Ubuntu 23.10 in your main post and now you stated 22.10. my bet is it is 23.10
2. Gnome is gnome, if it is the latest gnome, it doesn't matter which distro you are on
3. Wayland is a protocol and not a desktop environment. Gnome has both X11 and Wayland.
4. I've been maintaining Flameshot for over 3 years now, and based my experience with users and bug reports, and based on what I see in this issue, you are 99% on 23.10 with Gnome Wayland.

Now, if you want to test, here is a very quick way of testing it:

https://flameshot.org/docs/guide/issue-reporting/#display-server-protocol

Please let me know if I'm wrong and I will correct all the labels and reopen this issue if you are on X11

**Comment by ajung2** [comment] 2023-10-31 08:32
Thank you for your feedback.

My mistake i mean 23.10 and yes you are right, it is the same like the other post.
