### ISSUE TITLE
Only one keybinding should be valid

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#1574] opened 2021-04-22 10:53 UTC
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
The Flameshot should only accept a keybinding if it is not already bound to anything else. Best behavior would be to ask user if they want to remove the previous assignment and assign the key to the new function.

At the moment I managed to assign `Return` to two functions without facing any message or error:

![image](https://user-images.githubusercontent.com/390889/115702277-666d4080-a371-11eb-99e8-9cecc2c305ec.png)

**To Reproduce**
1. Right-click on tray icon
2. click on "configuration" 
3. go to "shortcuts" tab
4. click on an item and press enter
5. repeat step 4 for another item

**Expected behavior**
Should ask user if they want to remove the previous assignment and assign the key to the new function.

**System Information**
> ```
> System:
>   Host: precisiontower Kernel: 5.9.16-1-MANJARO x86_64 bits: 64
>   Desktop: KDE Plasma 5.21.4 Distro: Manjaro Linux
> ```

**Comment by hadis-git** [comment] 2021-04-22 13:33
I can't reproduce this behavior on my Linux machine.
When I try to assign the same shortcut to more than one function it gets caught [here](https://github.com/flameshot-org/flameshot/blob/cfd47cef3e70f406a7e46b8bcb1d1e6e621b0b0b/src/utils/confighandler.cpp#L682) and does not get saved.

**Comment by mmahmoudian** [comment] 2021-04-22 14:18
I'm positive that I'm on 0.9.0.
Did you build it yourself or installed it from a repo?

**Comment by hadis1000** [comment] 2021-04-22 15:02
Both. I compiled the current version and tried flameshot 0.9.0 from the arch repo.

Can you run a debugger and see why `ConfigHandler::setShortcut` fails to catch your duplicate assignment?

**Comment by borgmanJeremy** [comment] 2021-04-27 18:32
That function is only called if the hotkeys are set via the gui. If you manually edit the ini file we do not check for duplicates. This is reasonable behavior for now because we have no great way to handle / indicate the error.

I suppose we could check if the ini file has unique hotkeys and if not remove all duplicates from the ini directly.

**Comment by mmahmoudian** [comment] 2021-04-27 18:42
@borgmanJeremy I used the GUI config windows and got those duplicates.

**Comment by borgmanJeremy** [comment] 2021-12-10 02:54
@mmahmoudian I believe this is fixed now with the work @veracioux  (at least I cant replicate it on mastert)

**Closed by borgmanJeremy** 2021-12-10 02:54 UTC
Labels: Bug
