### ISSUE TITLE
Flameshot snap saves screenshots to /run/usr/1000/xxxx

### ISSUE THREAD

**Issue by cerobotics** [flameshot-org/flameshot#1144] opened 2020-11-07 10:34 UTC
**Flameshot version**
v0.8.5+git10.376a6f2

**Describe the bug**
If clicking on save image inside the snap installed via Ubuntu Snap Store always saves the screenshot to "/run/user/1000/XXXX". It doesn't matter if you change the location to save to in configuration or start from command line with -p <path> option. Same behavior. The dialog to choose a save path instead shows a "open" button. The permission option in snap store is set to "Access to home folder - ON".

!! Everything works quite fine with installing flameshot via "apt install flameshot".""

**To Reproduce**
Install Flameshot snap via Ubuntu snap store.

**Expected behavior**
Save to home folder or custom path.

**System Information**
Linux 5.4.0-52-generic #57~18.04.1-Ubuntu

**Comment by borgmanJeremy** [comment] 2020-11-07 16:47
Not able to replicate this on Kubuntu 20.04, I'll try in a gnome VM and report back.

**Comment by borgmanJeremy** [comment] 2020-11-08 01:36
@cerobotics Can you post the contents of your flameshot config? It's located at ~/.config/flameshot

If you see the /run/user/<> in that file delete it and try again.

**Comment by cerobotics** [comment] 2020-11-08 12:40
Hey, there is no config inside ~/.config/flameshot.
There is a config file under: ~/snap/flameshot/6/.config/flamshot/flameshot.ini with the following content:

[General]
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
saveAfterCopyPath=/home/<USER>/Pictures
savePath=/run/user/1000/doc/1760920b

When I delete the savePath param and restart it gets rebuild automatically (with different run id).

**Comment by skorasaurus** [comment] 2020-11-13 02:29
I am also experiencing the same issue; reproducible as @cerobotics described. 
I'm using ubuntu 20.04, gnome; X11, Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Likewise, there is no directory at ~/.config/flameshot; only at ~/snap/flameshot/6/.config/flamshot/flameshot.ini 

I've tried to export my configuration through flameshot's gui but receive the message 'unable to save file' in my home directory even though I did verify that through the 'software install' and snap that the access to home folder is on. 

my infi file:
[General]
disabledTrayIcon=false
drawColor=#800000
drawThickness=0
savePath=/run/user/1000/doc/4ce1be

**Comment by borgmanJeremy** [comment] 2020-11-24 19:12
When you get the save dialog, can you try adding .png to the file name? That seems to fix it for me, still going to find the root cause and patch it, but that might be a good first step.

**Comment by skorasaurus** [comment] 2020-11-24 19:33
@borgmanJeremy Thanks for your effort; I was able to save the screenshot in my home directory.

**Comment by borgmanJeremy** [comment] 2020-11-24 19:34
Thanks for confirming! That means I am on the right track here. I will leave this issue open until we fix the root cause.

**Comment by borgmanJeremy** [comment] 2020-11-25 17:58
Okay the root cause is the interaction between gnome file manager and Qt's QFileDialog. If I used a Qt file prompt instead of the native dialog box, this issue (and other issues) go away. Here is a similar issue from another project: https://github.com/OPM/ResInsight/issues/6345

Unfortunately this means I need to disable the native dialogs for file saving which makes the theme ugly.

**Comment by andrew-ma** [comment] 2020-11-28 20:40
I have this issue as well

**Comment by gjcooper** [comment] 2020-12-01 01:17
I am also experiencing this same issue with some slight differences:

**Flameshot version**
v0.8.5+git10.376a6f2

**System Information**
Kernel: 4.15.0-112-generic
OS: Ubuntu 18.04.5 LTS

**Details**
Similar to above, choose to save the screenshot in a specific folder, give the file a name. However a message is displayed (via dunst) that the file was actually saved to `/run/user/1000/XXXX` where XXXX is a unique string per save.

The differences to the above though are that:
* The file is not saved there, it is actually saved in the location: `/run/user/1000/doc/by-app/snap.flameshot/XXXX/`
* The file is always saved there, even if I add the .png to the end of the filename.

**Other info**

Noticed that your site on [Snapcraft.io](https://snapcraft.io/flameshot) links to a non-existing page -> https://flameshot.js.org/

Thanks for an awesome tool.

**Comment by borgmanJeremy** [comment] 2020-12-01 01:22
@gjcooper Are you using gnome?

Also thanks for pointing out the link issue, I'll fix that tonight. I'm working the the permanant fix for the path, but taking extra time to refactor this portion of the code and write some tests.

**Comment by gjcooper** [comment] 2020-12-01 12:40
> @gjcooper Are you using gnome?

Kind of, my system was based on standard 18.04 Ubuntu (ie Gnome) - however day to day I generally run with the i3 window manager.

**Comment by matrixes** [comment] 2020-12-03 07:05
At the point of this writing, if I install and use the Ubuntu 18.04 snap package, this exact thing happens. It doesn't save in the folder I specify but in /run/user/1000......
If I use the Aptitude package manager provided version "Flameshot 0.5.1-1(Debian)" of flameshot, everything works as expected.

**Comment by MXTcomunica** [comment] 2021-02-02 07:55
Same issue here on:
Ubuntu 20.04.1 LTS
64-bit
GNOME 3.36.8

**Comment by hlascelles** [comment] 2021-02-15 09:28
Same issue, Mint Linux 20, using snap.

To expand on this point: "The dialog to choose a save path instead shows a "open" button" - it means (for me) that the chooser dialog for save location won't let you select a folder, but insists on file, which of course won't work.

**Comment by mrkeuz** [comment] 2021-02-15 13:58
@borgmanJeremy, have same issue.  

Ready to test this case on edge release in snap for give feedback for you. Just add some notice here.

Ubuntu 20.04.2 + Gnome 3

Thanks for great tool!

**Comment by borgmanJeremy** [comment] 2021-02-15 14:04
Sorry for the delay, Ive tracked to root cause of this problem down but dont have a good fix yet. Earlier I posted:

>Okay the root cause is the interaction between gnome file manager and Qt's QFileDialog. If I used a Qt file prompt instead of the native dialog box, this issue (and other issues) go away. Here is a similar issue from another project: OPM/ResInsight#6345

After further thought I don't really want everyone to get an ugly dialog box. I might need to submit this upstream to GTK or Gnome.

**Comment by mrkeuz** [comment] 2021-02-15 14:20
@borgmanJeremy, agree with you, non-native dialogs look ugly in most cases. I.e. I always use left panel shortcuts for folders that shared between dialogs and file-manager. Think you're in right way. If for someone it's critical they can just downgrade to previous version. `0.6.0+git20191001-2(Debian)` works just fine for me. In my opinion.

**Comment by borgmanJeremy** [comment] 2021-02-16 02:26
This is relevant: https://forum.snapcraft.io/t/qt-file-dialog-open-folder-and-kde-neon-extension/20876/4

**Comment by j4r3kb** [comment] 2021-02-25 14:25
Flameshot version: 0.8.5
Compiled with Qt 5.12.3
Ubuntu 18.04 LTS
installed via apt

same issue, saving to /run/user/1001/doc/xxx/{my_file.png}

**Comment by borgmanJeremy** [comment] 2021-02-25 14:28
Yeah this issue is on hold until the upstream QT and KDE neon snap plugins are updated to core20.

**Comment by skorasaurus** [comment] 2021-02-26 15:55
> Yeah this issue is on hold until the upstream QT and KDE neon snap plugins are updated to core20.

No worries, thanks for the update :)

**Comment by vijay-prema** [comment] 2021-03-10 18:31
I have this same issue (but works if i add .png as suggested), and also noticed that if I try to change the savepath via gui, the folder selection dialog does not let me open the ~/Pictures folder, it only lets me select another file or folder under the ~/Pictures folder if you know what I mean. Basically its impossible for me to choose a folder unless it is empty, otherwise it selects a file or folder within the folder if it has stuff in it.

**Comment by LZHD** [comment] 2021-03-24 15:55
Flameshot v0.9.0
Compiled with Qt 5.12.3
OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.15.0-139-generic
installed via snap

same issue, saving to /run/user/1000/doc/by-app/snap.flameshot/xxx

**Comment by rjaus** [comment] 2021-06-27 04:13
I found these settings work, as a temporary work around.

`~/snap/flameshot/6/.config/flamshot/flameshot.ini` (the your number will be different)

```
savePath=/home/rj/Pictures
savePathFixed=true
```

Saves fine, in the specified directory.  Only limitation is you can't choose your filename (tho you can use the config to determine how that file name is generated)/.

**Comment by AShuba** [comment] 2021-08-20 14:54
Flameshot v.0.10.1
Compiled with Qt 5.12.3
Ubuntu 20.04

Same issue. 

$cat ./135/.config/flameshot/flameshot.ini
[General]
contrastOpacity=188
copyPathAfterSave=true
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=2
saveAfterCopyPath=/home/shuba/Pictures
savePath=/run/user/1000/doc/af195290

**Comment by seahindeniz** [comment] 2021-09-08 11:28
`savePath=~/Pictures` also does the job

**Comment by Abdur-rahmaanJ** [comment] 2021-09-29 06:12
Same issue with Linux Mint 20.2

**Comment by DrWhiteApes** [comment] 2021-10-19 09:54
I have the same issue, Ubuntu 20.04. Resetting the settings seems to work when the file path changes.

**Comment by Abdur-rahmaanJ** [comment] 2021-10-19 13:02
A useful info: when installing without snap store all ok.

**Comment by vijay-prema** [comment] 2021-10-19 20:10
> A useful info: when installing without snap store all ok.

yeah.. everything works perfectly simply by installing the deb in Ubuntu instead of snap.  Also, I went as far as uninstalling all of my snap packages for other software and replaced with debs, or failing that, flatpaks.

**Comment by borgmanJeremy** [comment] 2022-01-14 23:19
Good news, this is fixed now and will make it to stable in a day or so. This dragged on because the snapcraft build service did not let me append CLI arguments. I learned I can manually upload a .snap to the store.

**Closed by borgmanJeremy** 2022-01-14 23:19 UTC
Labels: Bug, High Priority, Linux, Upstream

**Comment by mishafeingold** [comment] 2022-06-16 02:33
Removing the snap version and installing with apt get worked for me. Ubuntu 20.04.4 LTS

**Comment by phuocntsts** [comment] 2022-12-20 07:26
For temporary situations, you can use "fixed the path for screenshots to save". it will work but you can't choose another folder to save
`Configuration > General > check the box "fixed the path for screenshots to save" > enjoy`
