### ISSUE TITLE
It would be nice to have a CLI option to capture the last captured region

### ISSUE THREAD

**Issue by henriqueccapozzi** [flameshot-org/flameshot#1678] opened 2021-06-22 02:24 UTC
**Is your feature request related to a problem?**
No

I would like to be able to have a CLI option to capture the last region I selected, and in case there isn't any
fallback to full screen

The idea is to make it easy to capture several pages or parts of a document that are 'always' at the same position relative to the 
screen

[Greenshot](https://github.com/greenshot/greenshot) tool has this feature for windows.

**Comment by mmahmoudian** [comment] 2021-06-22 10:19
@henriqueccapozzi isn't this duplicate of #479? If it is, please close this issue and also in addition to #479, please checkout #417

**Comment by henriqueccapozzi** [comment] 2021-06-22 12:31
@mmahmoudian is exactly what I wanted
thanks

**Closed** 2021-06-22 12:31 UTC
Labels: Waiting For Info
