### ISSUE TITLE
The pin button disappeared

### ISSUE THREAD

**Issue by JinNiuMengMeng** [flameshot-org/flameshot#2477] opened 2022-03-09 05:41 UTC
### Feature Description

➜  ~ flameshot -v
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.9.5

![L](https://images.gitee.com/uploads/images/2022/0309/120148_1e2e1005_2227396.jpeg)

I've selected pin, but I didn't have it in the screenshot

**Comment by mmahmoudian** [comment] 2022-03-09 06:13
How have you ran Flameshot?

Btw, please next time fill the correct form and provide all the requested information.

**Comment by nag5000** [comment] 2022-03-09 08:23
I am having the same issue after upgrading to v11, and also Copy and Save buttons disappeared too.

**Comment by mmahmoudian** [comment] 2022-03-09 21:34
@nag5000 i would ask you the same exact question that I asked in my previous comment: "How have you ran Flameshot?"

My hypothesis for all four of you ( @JinNiuMengMeng, @nag5000, @Grivel-l, and @pellizzetti ) is that you are running `fameshot gui --path /some/path/`. Is my hypothesis correct?

**Comment by nag5000** [comment] 2022-03-10 00:34
@mmahmoudian It seems to be just `flameshot`.
![image](https://user-images.githubusercontent.com/4932134/157563285-22eecf55-85a7-4b57-993e-f44fe62c1415.png)

**Comment by mmahmoudian** [comment] 2022-03-10 06:43
@nag5000 but that is "startup applications". Please run `flameshot gui` in terminal and see if those buttons are still missing.

If they were missing. I need these information:
1. The exact Flameshot version 
2. The correct installation method
3. The complete system information (output of `inxi --width 80 --system --graphics`)

**Comment by Grivel-l** [comment] 2022-03-10 10:37
Thanks @mmahmoudian , your hypothesis was correct for me. Running `flameshot gui` gave the expected result

**Comment by nag5000** [comment] 2022-03-10 10:53
Hmm, yes, if I run `flameshot` with the `gui` argument, everything is fine.

Interestingly, in v10, the buttons were not missing even if you run the command without the `gui` argument.

**Comment by nag5000** [comment] 2022-03-10 11:16
But it's a bit confusing to me what is happening to the buttons if I run the command with the `--path' argument.

**Comment by mmahmoudian** [comment] 2022-03-10 11:43
@nag5000 

> Removing the path argument fixes the problem.
> But it's a bit confusing to me what is happening to the buttons if I run the command with the `--path` argument.

This is not a problem, it is intended behavior which was briefly explained in the [release notes](https://github.com/flameshot-org/flameshot/releases/tag/v11.0.0) and extensively explained [on our website](https://flameshot.org/docs/advanced/commandline-options/#final-actions).

The OP (@JinNiuMengMeng ) has intentionally disabled the Accept button in their config and that is causing the confusion I guess. That setting is enabled by default.

**Comment by JinNiuMengMeng** [comment] 2022-03-14 05:50
> How have you ran Flameshot? And how have you installed it?
> 
> Btw, please next time fill the correct form and provide all the requested information.

I use dpkg to install 
```bash
sudo dpkg -i flameshot-11.0.0-1.ubuntu-18.04.amd64.deb
```
Use F1 as the shortcut key

![shortcut key](https://images.gitee.com/uploads/images/2022/0314/134725_6d85a04d_2227396.png)

**Comment by mmahmoudian** [comment] 2022-03-15 12:23
@JinNiuMengMeng So [my hypothesis](https://github.com/flameshot-org/flameshot/issues/2477#issuecomment-1063394046) is correct. You intentionally have disabled the Accept button (it is visible in your first screenshot) and you are using the `--path` argument.

This is intended behavior and Make sure you read this: 
https://flameshot.org/docs/advanced/commandline-options/#final-actions

This is issue is duplicate of:

- #2365
- #2431
- #2399
- #2391
- #2370
- and potentially many more that I don't have time to search for

**Closed by mmahmoudian** 2022-03-15 12:23 UTC
Labels: Waiting For Info, Unconfirmed Bug
