### ISSUE TITLE
Flameshot v11.0.0 from dnf is weird

### ISSUE THREAD

**Issue by mkikets99** [flameshot-org/flameshot#2539] opened 2022-04-09 17:30 UTC
### Flameshot Version

Flameshot v11.0.0 (-)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

linux: 5.16.18-200.fc35.x86_64 fedora: 35

### Description

Using Cinnamon UI on Fedora and turns out that `Infomation block` that appears before selecting area is with wrong width, while snap and flatpack works good.

### Steps to reproduce

Before steps, make sure you have:  

- Cinnamon 5.2.7
- Fedora 35

Steps: 

1. Start Flameshot from menu
2. Click on icon in tray
Or...
1. Run `flameshot gui

### Screenshots or screen recordings

https://user-images.githubusercontent.com/22869811/162584933-c018e7b0-a5ce-4d58-8b57-a1f850de8eeb.mp4

### System Information

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
System:
  Host: MiWiFi-R3-srv Kernel: 5.16.18-200.fc35.x86_64 x86_64 bits: 64
    Desktop: Cinnamon 5.2.7 Distro: Fedora release 35 (Thirty Five)
Graphics:
  Device-1: Intel CometLake-H GT2 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA TU106M [GeForce RTX 2070 Mobile / Max-Q Refresh]
    driver: nvidia v: 510.60.02
  Display: x11 server: X.Org v: 1.20.14 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,vesa gpu: i915
    resolution: 1920x1080~144Hz
  OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 21.3.8

**Comment by msr8** [comment] 2022-04-09 19:52
Came here to submit an issue for the same bug. Heres the bug in action:
![image](https://user-images.githubusercontent.com/79649185/162589556-a5278813-79d1-467b-b6b8-9cc7eabc0b83.png)
Here are my specs:
![image](https://user-images.githubusercontent.com/79649185/162589582-a49b5dcd-1a24-42a7-a2f6-5ac028eb8b06.png)

**Comment by mmahmoudian** [comment] 2022-04-15 14:55
I could reproduce this in a clean VM:


![image](https://user-images.githubusercontent.com/390889/163585954-c9349cbc-7c1d-4fec-ae97-a705099a7974.png)

**Comment by borgmanJeremy** [comment] 2022-05-05 01:51
The bug is here: https://github.com/flameshot-org/flameshot/blob/0870eca81f61f233e3c96b2d7f9a7f2b9ad7a145/src/widgets/capture/overlaymessage.cpp#L116

The sizeHint() is returning the improper size. I dont have any root cause yet but this is 100% the offending line.

**Comment by borgmanJeremy** [comment] 2022-05-06 20:50
Small update. This is an issue with the version of Qt in Fedora. Not sure yet wether its an actual bug or just undocumented behavior change:

I carved out this portion of code to make a very small minimal testing ground. 

![image](https://user-images.githubusercontent.com/46930769/167214607-952bf8b5-f486-41d7-b114-57916b125013.png)

**Comment by borgmanJeremy** [comment] 2022-05-06 21:08
Once I realized it was likely a Qt bug I tested in Fedora36 beta and it is resolved.

@mmahmoudian I propose closing this as won't fix. There is not an easy workaround I could identify and it is already resolved in the next Fedora release.

**Closed** 2022-05-07 06:40 UTC
Labels: Bug, Won't Fix, Upstream
