### ISSUE TITLE
flameshot does not work on macOS

### ISSUE THREAD

**Issue by nippyin** [flameshot-org/flameshot#1691] opened 2021-07-03 13:25 UTC
**Flameshot version**
NA

**Describe the bug**
after running following command, I expected the flameshot would run, however I don't see anything.

```sh
brew install --cask flameshot
```

When I check process I do see its running.

> ```
> macUser           4288   0.0  0.0  4268448    724 s001  R+    9:22am   0:00.00 egrep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox flame
> macUser           3843   0.0  0.2  5005184  35044   ??  S     9:09am   0:01.13 /Applications/flameshot.app/Contents/MacOS/flameshot
> ```

Also allowed this app to be installed and run from system preferences. Finally allowed screen recording for this app too.

**To Reproduce**
Under Application I do see flameshot.app

**Expected behavior**

Does not start

**System Information**
    System Software Overview:

      System Version: macOS 11.4 (20F71)
      Kernel Version: Darwin 20.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: mac-computer
      User Name: my Name (myuser)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 38 minutes

**Comment by nippyin** [comment] 2021-07-13 14:30
Thanks for responding however application does not work either ways. I also tried to install manually from dmg file and putting it in application folder. Allowed from security to allow this app to run as its not from verified source.

Are you able to make it work on any macOS

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmahmoudian** [comment] 2021-07-14 06:59
In my previous comment I asked for the output of those commands in two separate terminal so that I be able to help you to track down the issue. Without those outputs I'll be blind to the issue and I'm afraid I cannot help you.

P.s: remember to also give Flameshot the "screen recording" access from: Settings > Security and Privacy > Privacy

**Comment by nippyin** [comment] 2021-07-14 17:44
![image](https://user-images.githubusercontent.com/41337248/125667989-b25b5ac7-f0b6-4e86-bea1-8851e0e1a20b.jpeg)


As asked here is the screen shot from two terminals.
Note: Already allowed flameshot.app to run anyways as app is not verified & Screen recording is allowed for this App.

**Comment by mmahmoudian** [comment] 2021-07-15 06:03
Ok, so it seems brew has correctly put `flameshot.app/` in the `Applications/`. And considering the fact that you have given the permissions, it means that your OS has recognised Flameshot. Now, the next step to debug this is to see why when you type `flameshot` your shell cannot find it. Please provide the output of the following commands:

```sh
# command 1
echo $PATH
```

```sh
# command 2
find /Applications/flameshot.app/ -iname "flameshot" 
```

**Comment by nippyin** [comment] 2021-07-15 11:53
![image](https://user-images.githubusercontent.com/41337248/125783716-bedcddc3-e6c3-487c-8cbb-e1ed20d57349.jpeg)


I manually exported the environment variable in my .zshrc too. still does not work.

**Comment by mmahmoudian** [comment] 2021-07-15 13:02
Nice job for using `tr` to format the `$PATH `. I am used to reading it as is, but now I can see some if the benefits.

Some general tips about your `$PATH`:
1. You don't need to add the Flameshot binary to the path, the path to the top level folder would be suffice as far as I know
2. Having the `/Applications/` (line 6) would make any lines beginning with `/Applications/` redundant (lines 2, 4, 16, 20, 21)

Now the next order of business would be to
1. Check if the flameshot is executable
2. Check if it runs if we trigger it manually

please provide the output of the following:

```sh
# Command 1
ls -al $(find /Applications/flameshot.app -iname "flameshot")
# or
ls -al /Applications/flameshot.app/Contents/MacOS/flameshot

# The reason for the latter is that I don't know how MacOS handles `//` as it
# was in the output in your last screenshot when we used `find`.
```


```sh
# Command 2
command /Applications/flameshot.app/Contents/MacOS/flameshot gui
# or
exec /Applications/flameshot.app/Contents/MacOS/flameshot gui

# The reason I have two alternative commands here is because I'm not sure which
# one might fail in MacOS.
```

**Comment by borgmanJeremy** [comment] 2021-07-15 13:51
I'll chime in here just to say I use homebrew on my mac to install flameshot without issue. @mmahmoudian if you want me to post anything particularly related to my setup let me know.

**Comment by nippyin** [comment] 2021-07-15 14:23
That will be great help. Also share the versions of OS.

-S

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nippyin** [comment] 2021-07-15 14:27
This screen shot has most of the info.
![image](https://user-images.githubusercontent.com/41337248/125804883-aa594662-8122-4860-a8e3-f9c9683684f6.jpeg)

**Comment by mmahmoudian** [comment] 2021-07-15 16:47
@nippyin any luck in running the Command2 of my previous comment?

**Comment by nippyin** [comment] 2021-07-15 18:31
No it didn’t ran.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mmahmoudian** [comment] 2021-07-15 19:17
@nippyin As we cannot reproduce the issue, I need to know the error or the output and try my beat to make some sense out of it.

**Comment by nippyin** [comment] 2021-07-16 01:08
![image](https://user-images.githubusercontent.com/41337248/125876543-68da986f-47fd-4a53-aa84-3ea825327e7c.jpeg)

when I run exec /Applications/flameshot.app/Contents/MacOS/flameshot             
the terminal exists. Is there a way we can check logs?

**Comment by nippyin** [comment] 2021-07-16 01:55
Finally it worked. Somehow ~/.config/flameshot/flameshot.ini had an entry of disable tray icon= true which didn't let it appear in tray and I was not trying to use shortcuts to try and capture screen shot.

**Comment by mmahmoudian** [comment] 2021-07-16 05:29
> when I run exec /Applications/flameshot.app/Contents/MacOS/flameshot
the terminal exists. Is there a way we can check logs?

This is expected. If the command `flameshot` runs without any error and either finishes running or goes into background, `exec` exists and with it will exit terminal as well.

**Comment by mmahmoudian** [comment] 2021-07-16 05:32
> Finally it worked. Somehow ~/.config/flameshot/flameshot.ini had an entry of disable tray icon= true which didn't let it appear in tray and I was not trying to use shortcuts to try and capture screen shot.

That was something I didn't think about as I thought you have installed it for the first time. Anyways, I'm glad that it works now.

Shall we close this issue?

**Closed** 2021-07-19 16:36 UTC
Labels: OSX, Unconfirmed Bug, Waiting For Info
