### ISSUE TITLE
Flameshot Crashing After Typing Caption then Selecting Rectangle Box

### ISSUE THREAD

**Issue by jpierce-coder** [flameshot-org/flameshot#3120] opened 2023-03-06 12:56 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 6.1.11-76060111-generic
pop: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Pop!_OS 22.04 LTS

### Description

After taking a screenshot with `flameshot-gui`, after typing text onto the screenshot, the next tool I use (have tested with non-filled box, blur/pixelate, and filled box) will for some reason abort the screenshot when I'm just trying to select the next tool.

### Steps to reproduce

1. run `flameshot gui` (whether by keyboard shortcut or not. My shortcut is set to Meta + Shift + S)
2. Take selection
3. Click the Text tool, and type whatever out
4. Click any other tool (NOT cancel though), and the screenshot will "abort".

### Screenshots or screen recordings

[flameshot-gui_issue.zip](https://github.com/flameshot-org/flameshot/files/10898336/flameshot-gui_issue.zip)

### System Information

1. Pop!_OS 22.04 LTS
2. 
![image](https://user-images.githubusercontent.com/70922864/223116300-3f2780ca-870d-4c99-af1a-bf3673c33e0d.png)

3. 
![image](https://user-images.githubusercontent.com/70922864/223116418-bdcb8cdc-8f13-4381-8747-dec86e49d60b.png)
Gnome, Mutter, and X11

**Comment by mmahmoudian** [comment] 2023-03-06 16:31
Thanks for the bug report, but please search before creating a new issue. This is duplicate of #2454 and it is already fixed. Try updating your Flameshot version (e.g install from Flatpak or use AppImage). More information about what and how to install can be found here:

https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

**Closed by mmahmoudian** 2023-03-06 16:31 UTC
Labels: Unconfirmed Bug

**Comment by jpierce-coder** [comment] 2023-03-13 15:45
@mmahmoudian 
https://github.com/flameshot-org/flameshot/issues/2283 mentions that the bug is resolved as of last year, so why is this still happening? Do I need to update to the latest or install the `git` version?

**Comment by mmahmoudian** [comment] 2023-03-14 07:52
Because you are using a very old version. We are now at version 12.1.0 since July 2022! So you should update the software to get the bug fixes and new features. If uour distro does not provide the latest version, then you have the option to install Flameshot via Flatpak, Snap, or AppImage. On how to install on linux, please refer to this page:

https://flameshot.org/docs/installation/installation-linux/

**Comment by jpierce-coder** [comment] 2023-03-29 17:13
Ahh that would make sense. I'll update from that. Thank you!
