### ISSUE TITLE
Can't paste into non-Qt apps on Sway

### ISSUE THREAD

**Issue by alecmev** [flameshot-org/flameshot#1568] opened 2021-04-20 12:29 UTC
**Flameshot version**

55e61b8

**Describe the bug**

100% the same bug as #1035, but the fix - [`QT_QPA_PLATFORM=xcb`](https://github.com/flameshot-org/flameshot/pull/1282/files#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2R63) - isn't enabled for Sway. The pasting works when I run `QT_QPA_PLATFORM=xcb flameshot`, but then I'm unable to select a region outside of the status bar (Waybar in my case).

[This is supposed to be fixed in Qt 5.15.2](https://bugreports.qt.io/browse/QTBUG-88293), which I have, but it doesn't appear to be so. I have [the exact same problem](https://github.com/telegramdesktop/tdesktop/issues/9836) with Telegram Desktop, which is also Qt-based, but unlike Flameshot I'm able to run it in XWayland without side effects.

~~Enabling "Use JPG format for clipboard" doesn't help either, so this isn't just a matter of getting rid of `application/x-qt-image` ([which is absent in the "JPEG mode"](https://github.com/flameshot-org/flameshot/blob/55e61b874320c864c3abbd47c61d33babfc5fe3d/src/utils/screenshotsaver.cpp#L59-L60)).~~ ["Use JPG format for clipboard" helps, but not with browsers.](https://github.com/flameshot-org/flameshot/issues/1568#issuecomment-830627639)

This sounds like a Qt bug, but reporting here for visibility, and to also figure out if there's something that can be done until it's fixed, e.g. utilize `wl-copy` instead of `QClipboard` when running on Sway.

**System Information**

Up-to-date Arch as of writing this, Sway 1.6, Qt 5.15.2.

**Comment by borgmanJeremy** [comment] 2021-04-26 18:26
Does anything here help? https://github.com/flameshot-org/flameshot/pull/1272

**Comment by alecmev** [comment] 2021-04-26 18:43
It doesn't, since I don't have any issues with capture. Are you unable to reproduce this?

**Comment by nullobsi** [comment] 2021-04-30 00:22
i can confirm this issue, as it's been annoying me a lot. if i copy into other applications, it appears to have the image/png mimetype, but is actually in BMP format. i feel like this would have to be a Qt issue, since I don't think there's an easy way to fix it from flameshot... unless I'm mistaken

**Comment by mmahmoudian** [comment] 2021-04-30 08:51
@borgmanJeremy @nullobsi  should this be marked as "Upstream" bug?

**Comment by nullobsi** [comment] 2021-04-30 21:42
Okay, I just made a test branch... and it seems setting the clipboard explicitly to image/png with a QImageWriter like is done with JPEG fixes it on wayland, although it feels really hacky...

https://github.com/nullobsi/flameshot/tree/wayland-screenshot-png

If it's needed, I can clean it up and make a PR, while we wait for Qt to fix it

**Comment by alecmev** [comment] 2021-04-30 22:23
Does this actually fix the pasting for you? As mentioned in the OP, the JPEG mode has the right MIME, but still doesn't work.

**Comment by borgmanJeremy** [comment] 2021-04-30 22:33
If it fixes the issue I'm okay merging a hack. We had to do it for JPEG anyway. Just make sure it's wrapped in functions.

**Comment by nullobsi** [comment] 2021-05-01 02:23
> Does this actually fix the pasting for you? As mentioned in the OP, the JPEG mode has the right MIME, but still doesn't work.

the issue is that some applications do not accept a jpeg as a format, and thus do not accept the paste. I made a branch that uses the same method to force only image/png type, and it is accept in Firefox properly

> If it fixes the issue I'm okay merging a hack. We had to do it for JPEG anyway. Just make sure it's wrapped in functions.

yup, I'll just make sure I do a clang-tidy and I'll make a PR in a bit

**Comment by alecmev** [comment] 2021-05-01 12:50
You're right! I was testing with Firefox and Chromium, and neither of them accept `image/jpeg`, checked [here](http://madebyevan.com/clipboard-test/). GIMP accepts it just fine though. Then, indeed, the PNG "hack" should help, thanks for putting it together!

**Closed** 2021-05-02 17:49 UTC
Labels: Wayland

**Comment by alecmev** [comment] 2021-05-03 14:55
[Reported in Qt](https://bugreports.qt.io/browse/QTBUG-93411).
