### ISSUE TITLE
Adding shadow to the image

### ISSUE THREAD

**Issue by huyndnse63331** [flameshot-org/flameshot#958] opened 2020-09-22 12:50 UTC
Hi, is there any option allowing user to add shadow to the captured image? Like this one below, this is a plugin that Shutter supported.
![image](https://user-images.githubusercontent.com/25204246/93884281-e7e1ef00-fd0c-11ea-912e-eb081504875d.png)
![image](https://user-images.githubusercontent.com/25204246/93884292-eb757600-fd0c-11ea-8af9-5c4304fe8802.png)

**Comment by borgmanJeremy** [comment] 2020-09-22 12:52
Not at this time. You can use "Open with External App" to add a shadow in a different program.

**Comment by borgmanJeremy** [comment] 2020-09-22 13:17
Duplicate of #344

**Closed by borgmanJeremy** 2020-09-22 13:17 UTC
