### ISSUE TITLE
Improvement - Stable size

### ISSUE THREAD

**Issue by BiLachner** [flameshot-org/flameshot#1913] opened 2021-09-20 09:49 UTC
Hi,
ich often make Screenshots that need to have the same size, e.g. pictures for quizzes.

I prepare the pictures in a wordprocessor in a table, every cell the same size.

It would be much faster, if I do not need to choose the area of the screenshot every time.
The workflow should be like that.

1. First picture: choose the size.
2. Start next picture ...
3. move the screenshot-selection area ...
4. take next picture.
5. Go to (2.)

Thanks, Birgit

**Comment by mmahmoudian** [comment] 2021-09-20 10:19
I believe this is duplicate of #1509 and partly #479 and #417

**Comment by BiLachner** [comment] 2021-10-06 06:23
Yes, my idea is like  #1509

**Closed** 2021-10-06 07:11 UTC
Labels: Duplicate, Enhancement
