### ISSUE TITLE
Request : Area selection for marker/highlight tool

### ISSUE THREAD

**Issue by nav33nb** [flameshot-org/flameshot#2917] opened 2022-09-23 08:14 UTC
### Feature Description

Currently if I select marker/highlight tool, I can drag and draw a line with scroll wheel to set some thickness of that line

I think it would be great if it was also area based just like pixelate tool

**Comment by mmahmoudian** [comment] 2022-09-24 19:14
duplicate of  #1498

**Closed by mmahmoudian** 2022-09-24 19:14 UTC
Labels: Enhancement
