### ISSUE TITLE
flameshot-0.8.3 — TLS initialization failed

### ISSUE THREAD

**Issue by govegasbudapest** [flameshot-org/flameshot#1031] opened 2020-10-04 17:27 UTC
**Flameshot version**
v0.8.3

**Describe the bug**
Error after clicking upload image to imgur cloud.

**To Reproduce**
1. Download, install or run any of the suggested options for windows:

https://github.com/flameshot-org/flameshot/releases/download/v0.8.3/flameshot-0.8.3-win32.zip
https://github.com/flameshot-org/flameshot/releases/download/v0.8.3/flameshot-0.8.3-win64.zip
https://github.com/flameshot-org/flameshot/releases/download/v0.8.3/Flameshot-0.8.3-win32.msi
https://github.com/flameshot-org/flameshot/releases/download/v0.8.3/Flameshot-0.8.3-win64.msi

2. Select an area to create a snapshot and take it.
3. Click on the image upload logo on imgur.

Act: https://imgur.com/RNhtcEI

**Expected behavior**
I expect that the upload to the cloud service will start.

**System Information**
Windows 10 - 2004, 19041.508

**Comment by ZetaoYang** [comment] 2020-10-05 03:57
@govegasbudapest Now the temporary solution is to download the openssl binary file manually. You can download `openssl-1.1.0h` zip from https://indy.fulgan.com/SSL/Archive/Experimental/ according to your system, unzip and copy `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` to flameshot `bin` folder. Then flameshot will work when you using imgur uploader tool. 

We'll fix the problem soon.

---
- https://wiki.openssl.org/index.php/Binaries

**Comment by govegasbudapest** [comment] 2020-10-05 08:04
> @govegasbudapest Now the temporary solution is to download the openssl binary file manually. You can download `openssl-1.1.0h` zip from https://indy.fulgan.com/SSL/Archive/Experimental/ according to your system, unzip and copy `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` to flameshot `bin` folder. Then flameshot will work when you using imgur uploader tool.
> 
> We'll fix this problem soon.
> 
> * https://wiki.openssl.org/index.php/Binaries

@ZetaoYang Hello, I tried to do this, but the error is still relevant.
I used file https://indy.fulgan.com/SSL/Archive/Experimental/openssl-1.1.0h-x64-VC2017.zip

**Comment by ZetaoYang** [comment] 2020-10-05 08:49
> > @govegasbudapest Now the temporary solution is to download the openssl binary file manually. You can download `openssl-1.1.0h` zip from https://indy.fulgan.com/SSL/Archive/Experimental/ according to your system, unzip and copy `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` to flameshot `bin` folder. Then flameshot will work when you using imgur uploader tool.
> > We'll fix this problem soon.
> > 
> > * https://wiki.openssl.org/index.php/Binaries
> 
> @ZetaoYang Hello, I tried to do this, but the error is still relevant.
> I used file https://indy.fulgan.com/SSL/Archive/Experimental/openssl-1.1.0h-x64-VC2017.zip

The latest code doesn't seem to be working properly. After manually copying the openssl two libraries dlls, I ran into this problem `TLS initialization failed` as well.

**Comment by borgmanJeremy** [comment] 2020-10-07 00:47
Per this thread its apparently critical that the version of the dll matches the version of OpenSSL used to build Qt:

https://forum.qt.io/topic/95700/qsslsocket-tls-initialization-failed/27

**Comment by mmahmoudian** [comment] 2021-07-07 22:22
I believe the #1187 is a duplicate of this issue and it also has some good discussions in it.

**Closed** 2022-02-17 03:25 UTC
Labels: High Priority, Windows
