### ISSUE TITLE
Flameshot does not accept capture

### ISSUE THREAD

**Issue by christianm666** [flameshot-org/flameshot#3230] opened 2023-06-12 09:06 UTC
### Flameshot Version

12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

6.4.0-1-MANJARO (64-bit)

### Description

Accepting the capture does not work, i.e. pressing enter does nothing.

### Steps to reproduce

1. open flameshot
2. select area
3. press enter
4. nothing happens

### System Information

Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.4.0-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 4800H with Radeon Graphics
Memory: 15,0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: HUAWEI
Product Name: KLVL-WXX9
System Version: M1010

![image](https://github.com/flameshot-org/flameshot/assets/62308177/763f3ec0-5347-444b-8110-0bd63ec5c602)

**Comment by mmahmoudian** [comment] 2023-06-12 14:41
> Accepting the capture does not work, i.e. pressing enter does nothing.

1. Have you defined Enter to do anything? What is your config?
2. have you read this: https://flameshot.org/docs/guide/key-bindings/

> ## Steps to reproduce
> 
> 1. open flameshot

There are many ways to "open" Flameshot. Which one did you use??

**Comment by christianm666** [comment] 2023-06-12 15:39
1. I did not change the configuration. In the config file the shortcut seems to be assigned properly: TYPE_ACCEPT=Return
2. I have read this and I don't think the issue comes from anything related to shortcuts as I also do not see a "Accept" button, albeit being activated in the settings.

- **flameshot** and **flameshot gui** show exactly this behaviour after clicking on the tray icon. And again: there is still no accept-button.

- **flameshot gui --clipboard** does work and the button shows.
- **flameshot screen** also does work.

**Comment by mmahmoudian** [comment] 2023-06-13 05:45
> 1. I did not change the configuration. In the config file the shortcut seems to be assigned properly: TYPE_ACCEPT=Return

This is not a bug. Lets think about it this way: when you run `flameshot gui`, what are you "accepting"? There is nothing to accept. You have not told Flameshot which action you want. Copy is Ctrl+c, save is Ctrl+s, cancel is Esc, upload and pin also have their shorcuts. So what are you accepting? But when you run `flameshot gui --clipboard`, the final action is defined and Flameshot knows what are you accepting.

Read here for more CLI information:

https://flameshot.org/docs/advanced/commandline-options/

> *flameshot* and *flameshot gui* show exactly this behaviour after clicking on the tray icon. 

The `flameshot` start the flameshot daemon in the background. For user, it means faster trigger for taking screenshot and tray icon. It does *not* take screenshot. The `flameshot gui` checks first if daemon is running, if it is, it tells daemon to start the `gui` mode, if not, it will start a one-off `gui` mode which will be killed after the screenshot process is complete. So they don't do the same thing and they are for different purposes.


> When using flameshot screen the resulting screenshot is cut to a 16:9 aspect ratio, even though the primary monitor is 3:2

That is because you have fractional scaling enabled on your monitor settings (visible in the screenshot of your monitor arrangements. Turn it to 100% or 200% and it will work correctly. This is a bug and if you are interested, read #564.

I'll close this issue as this is not a bug and just your misunderstanding on the terminology. I hope my comments have cleared up the situation for you.

**Closed** 2023-06-13 05:46 UTC
Labels: question
