### ISSUE TITLE
Configurable shortcuts?

### ISSUE THREAD

**Issue by zohozer** [flameshot-org/flameshot#1541] opened 2021-04-08 09:45 UTC
I would like to use Flameshot but unfortunately I don't have a "PrintScreen" button on my keyboard.

It is possible to change the default keyboard shortcuts of this app?

**Comment by mmahmoudian** [comment] 2021-04-08 10:39
You can change the keybindings of functions inside Flameshot, but mapping any keybinding to run Flameshot is something that your window manager (e.g KDE, Gnome, MATE, Xfce, bspwm, ...) should do.

Although it would be off-topic, if you mention what is your operating system (Windows, OSX, Linux, BSD, ...) and what is your Desktop Environment or Window Manager, I might be able to guide you to the correct direction.

**Comment by zohozer** [comment] 2021-04-08 10:43
I forgot to mention that I'm using Windows10 and the shortcuts from "Quit Capture" and below can't be changed.
![flameshot_nJ4xyskuyb](https://user-images.githubusercontent.com/5983791/114013539-90960d00-985f-11eb-90ef-9b91b75c7659.png)

**Comment by mmahmoudian** [comment] 2021-04-08 11:00
Based on your penguin Avatar I thought you are Linux user. Since you are on Windows, then yours is a duplicate of #1341. I suggest closing this issue and adding a comment in #1341 to reflect that you also have this issue.

**Comment by zohozer** [comment] 2021-04-08 11:19
> Based on your penguin Avatar I thought you are Linux user. Since you are on Windows, then yours is a duplicate of #1341. I suggest closing this issue and adding a comment in #1341 to reflect that you also have this issue.

I do am a Linux and MacOS user but this is for a Windows10 machine!

**Comment by mmahmoudian** [comment] 2021-04-08 11:39
@zohozer The #1341 is about Windows. Considering that such feature is not implemented yet, please close this issue and post a comment on #1341 . Thanks

**Closed** 2021-04-08 15:09 UTC
Labels: question
