### ISSUE TITLE
macOS: copy not working when using `flameshot gui`

### ISSUE THREAD

**Issue by dzg** [flameshot-org/flameshot#2567] opened 2022-04-27 16:22 UTC
### Flameshot Version

11.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macos 10.15.7

### Description

Copy to clipboard works when running flameshot.app via GUI (from menubar or shift-cmd-x) but NOT when initiated from CLI with `flameshot gui`

### Steps to reproduce

1. Open Terminal
2. Run `/Applications/flameshot.app/Contents/MacOS/flameshot gui`
3. Select a region
4. Press cmd-C or click Copy button
5. Nothing new in clipboard

### System Information

macos 10.15.7

**Comment by mmahmoudian** [comment] 2022-04-27 22:51
Duplicate of
- #2508
- #2496

**Closed** 2022-05-01 14:18 UTC
Labels: Bug, Duplicate

**Comment by Ariandr** [comment] 2022-07-12 11:15
Hi @mmahmoudian 
I don't think this issue needs to be closed. Behavior is inconsistent and it's definitely a bug.

I read the issues you attached, they don't explain much and the workaround is unclear.

I have this issue too, I'm on 12.1.0 and MacOS 12.4.

I just launch the screenshot capture with the hotkey combination.
When I'm done and want to copy to the clipboard, `CMD+C` sometimes works, sometimes doesn't.

But when I click 'Copy selection to clipboard' button, it always works.

**Comment by mmahmoudian** [comment] 2022-07-12 11:22
@Ariandr it seems your issue is different. In this thread there is no mention of inconsistency. What you are reporting is in exact contradiction to the OP:

> 4. Press cmd-C or click Copy button
> 5. Nothing new in clipboard

I suggest you open a new issue dedicated to this issue you have

**Comment by Ariandr** [comment] 2022-07-12 11:46
@mmahmoudian 
Okay, thanks.
I'll create a new issue.

**Comment by Ariandr** [comment] 2022-07-12 11:58
@mmahmoudian 
Created https://github.com/flameshot-org/flameshot/issues/2786
