### ISSUE TITLE
Change the dimensions of placed objects after placing them

### ISSUE THREAD

**Issue by aha999** [flameshot-org/flameshot#1852] opened 2021-08-29 17:00 UTC
**Is your feature request related to a problem?**

Currently we can't change the placement/size/dimensions of placed objects, like square, arrow, circle etc. and it's annoying because you have to place it perfectly the first time from all sides, or undo and try again. 

### Solution
After placing whichever item, show resize icons in each edge that can be moved, so we can move each side of the object precisely. Look into other software like ShareX how they accomplish this.

**Comment by majkinetor** [comment] 2021-08-29 18:58
You can change placement and color of objects by selecting  the object in the sidebar. While it is open you can click on the object in the picture and move around, change color etc.  Resizing doesn't seem to be possible.

**Comment by aha999** [comment] 2021-08-30 08:03
yes, the directional resizing (if that's what is called) should imo show little circles to resize the item on each side, after placing an item/shape.

**Comment by majkinetor** [comment] 2021-08-30 08:06
Not only directional resizing but also rotating.

**Comment by mmahmoudian** [comment] 2021-08-31 05:10
Thanks to @majkinetor this issue got a good direction and shape. Considering the last comments what you are asking for are:
1. Displaying resizing handles (those small points at the corners and middle of the edges)
2. The ability to rotate the object (possibly by some sort of clicking on the corner handles)

If my above understanding is correct, then I believe this is duplicate of #1712

@aha999 and @majkinetor would you please check if this is duplicate or not?

**Comment by majkinetor** [comment] 2021-08-31 05:15
@mmahmoudian its duplicate regarding point 1, not regarding point 2.

**Comment by mmahmoudian** [comment] 2021-08-31 05:30
Yeap, you are right, rotation was not mentioned in that thread. I propose closing this issue and create a new one in which we extend the #1712 about rotation

**Comment by aha999** [comment] 2021-08-31 10:26
I believe it is a duplicate, yes.

**Closed** 2021-08-31 10:26 UTC
Labels: Enhancement, Waiting For Info
