### ISSUE TITLE
App works only through command line

### ISSUE THREAD

**Issue by vladpoly90** [flameshot-org/flameshot#289] opened 2018-07-28 15:31 UTC
When starting flameshot, nothing appears, no error either.
When starting through console, nothing appears, but I do receive the message "qt5ct: using qt5ct plugin", no error.
When using flameshot -gui, it works fine, but still no tray icon.

I would like to return the icon in tray with all the functionality of flameshot.

Linux atmosphere 4.17.9-1-MANJARO #1 SMP PREEMPT Sun Jul 22 20:01:56 UTC 2018 x86_64 GNU/Linux
xfdesktop 4.12.4 
GTK+ 2.24.32

**Comment by hosiet** [comment] 2018-07-28 15:33
How did you install flameshot? Which version of flameshot are you running?

**Comment by Tuplad** [comment] 2018-07-28 15:44
Oh yes:
flameshot 0.5.1-5 from the Manjaro repo, not the AUR GIT version, installed through pacman.

**Comment by farseerfc** [comment] 2018-07-28 15:44
Adding to @hosiet 's question, which systray provider/ icon panel are you using? I see xfdesktop version in your report, may I assume that you are using xfce4-panel?

**Comment by Tuplad** [comment] 2018-07-28 15:56
@farseerfc exactly! it does work from time to time, but I'm not sure what the variable is for this.

**Comment by farseerfc** [comment] 2018-07-28 15:59
@Tuplad do you have any `libappindicator-*` package installed? do you have other panel on your desktop besides xfce4-panel? if there is, what is the panel/dock/trayer's name?

**Comment by farseerfc** [comment] 2018-07-28 16:50
Just tried a fresh install of manjaro xfce, and flameshot worked flawlessly there, with or without `libappindicator-gtk{2,3}`.
![manjaro-flameshot](https://user-images.githubusercontent.com/861563/43358740-5b91d940-92d1-11e8-87ed-c2ab143fc4db.png)

**Comment by Tuplad** [comment] 2018-07-28 21:40
@farseerfc installed libappindicator3, still no effect.

flameshot gui trough shell > OK
flameshot through shell > not OK, just this "qt5ct: using qt5ct plugin"

**Comment by Tuplad** [comment] 2018-07-28 21:41
Did pkill flameshot and started flameshot again, works fine:
[vlad@atmosphere bot]$ flameshot
qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
qt5ct: custom style sheet is disabled


weird...

**Comment by farseerfc** [comment] 2018-07-29 14:51
@Tuplad I think when flameshot is running in the background (with a systray icon showing), running `flameshot` command in a shell should do nothing, and this is its intended behavior. When flameshot is running, using `flameshot gui` or clicking on the systray icon will communicate the background process to get a screenshot.
If the systray icon is nowhere to find, that is a issue though. 
About the icon in "start menu", you can right click it and choose "Take screenshot" action to call `flameshot gui`.

**Comment by borgmanJeremy** [comment] 2021-03-04 02:06
Closing this since its a very old version of flameshot and latest testing works fine as long as you have the right gnome extensions.

**Closed by borgmanJeremy** 2021-03-04 02:06 UTC
