### ISSUE TITLE
Not working on external display after sleep (macos)

### ISSUE THREAD

**Issue by bilak** [flameshot-org/flameshot#2945] opened 2022-10-14 09:16 UTC
### Flameshot Version

Flameshot 12.1.0 (installed via brew)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macos 12.6

### Description

I'm using external monitor attached via usb-c. When I put computer to sleep and wake it up, then when I want to create a screenshot Flameshot only recognises macos display (internal). I need to always restart Flameshot to be able create screenshots on external monitor. I'm not 100% sure that this is related to sleep functionality but I often see that Flameshot is not working after sleep.

If there is some way how can I help with some debug option, please let me know.

### System Information

1. macos 12.6
2. ![image](https://user-images.githubusercontent.com/5826062/195809756-9234a020-adab-4505-886b-5ee0d8cfefa2.png)

**Comment by farisjarrah** [comment] 2022-10-14 19:19
I can recreate this issue as well. My monitor is a Samsung LS27A800UNNXZA 27" 4k 60hz monitor. Screen seems to blank out on the newest version of flameshot on the external monitor over USB-C. This monitor is also handling usb-pd at the same time as data delivery as well. 

Happy to help provide additional information if necessary.

![image](https://user-images.githubusercontent.com/24551292/195924525-884a120c-5614-4003-815e-65cd7e39e707.png)
![image](https://user-images.githubusercontent.com/24551292/195924968-129f176a-4524-4376-a919-f7e0e2a2a1df.png)

**Comment by borgmanJeremy** [comment] 2022-10-14 20:38
This is a duplicate of #2610

**Closed by borgmanJeremy** 2022-10-14 20:38 UTC
Labels: Unconfirmed Bug

**Comment by borgmanJeremy** [comment] 2022-10-14 21:31
@bilak  I am going to track progress on that other issue, but since you are monitoring this can you please provide the exact steps? I have had this issue on my Mac but now I cant replicate it. What im looking for is something like:

1. Open flameshot on the laptop with no monitor
2. Put PC to sleep
3. Connect to dock
4. Open lid
5. Flameshot only works on internal display

I tried a few different combinations but I can't replicate it. Testing on an M1 air with Montery 12.6
