### ISSUE TITLE
Printer Button Request

### ISSUE THREAD

**Issue by joshuaekingsbury** [flameshot-org/flameshot#953] opened 2020-09-21 18:30 UTC
Request ability to print from flameshot.

For university coursework and day to day I frequently print out screenshots.

Instead of selecting screenshot, opening app launcher, opening app, and printing, then closing the app,

I'd like to open the print dialog from the flameshot screen selection.

**Comment by mmahmoudian** [comment] 2020-09-21 18:33
Duplicate of #768

**Closed** 2020-09-21 18:33 UTC
Labels: Duplicate, Enhancement
