### ISSUE TITLE
Webp Lossless

### ISSUE THREAD

**Issue by DylanMcBean** [flameshot-org/flameshot#2743] opened 2022-06-30 20:15 UTC
### Feature Description

I think it would be really good if when selecting image formats with multiple save patterns that you could select what type to use, so for WebP that would be like lossless or lossy, just now when selecting webP it appears to use lossy, i would prefer lossless for these so it would not effect the image details. i could use png yes; but webp saves files alot smaller than png so it's better.

**Comment by borgmanJeremy** [comment] 2022-07-07 00:45
I think this is a duplicate of #506  since both are asking for the ability to customize the compression ratio.  I am not against the idea, just need someone to sit down and do the work in a way that integrations nicely with the program

**Closed by borgmanJeremy** 2022-07-07 00:45 UTC
Labels: Enhancement
