### ISSUE TITLE
Running `flameshot gui` without running `flameshot` does not pass environment variables

### ISSUE THREAD

**Issue by UmarJ** [flameshot-org/flameshot#2097] opened 2021-11-20 09:11 UTC
### Flameshot Version

Flameshot v0.10.1 (53cc11ac)
Compiled with Qt 5.15.2

### Installation Type

Compiled from source

### Operating System type and version

Arch Linux x86_64 5.15.2-arch1-1

### Description

If you run `flameshot gui` with no instances of flameshot open, environment variables are not passed to flameshot. I set the theme using `QT_QPA_PLATFORMTHEME="qt5ct"`, but I still get the default theme. Running `flameshot`, however, passes the environment variables correctly.

The same behaviour is observed when running `flameshot screen`, `flameshot full`, `flameshot config` and `flameshot launcher`.

### Steps to reproduce

1. Use an environment variable to set the Qt theme
2. Close the running instance of flameshot
3. Run `flameshot gui`

#### Running `flameshot gui`
![2021-11-20_14-08](https://user-images.githubusercontent.com/34779641/142720896-e6c8ba3b-6041-4d34-8ecb-d9f57e2e3b5d.png)

#### Running `flameshot`
![2021-11-20_14-07](https://user-images.githubusercontent.com/34779641/142720894-a2b07efb-19df-4780-a5b4-cc0a163d290f.png)

### System Information

Arch Linux x86_64 5.15.2-arch1-1
Xorg

**Comment by mmahmoudian** [comment] 2021-11-20 20:13
This is an interesting finding 🤔 if this is true, this might also explain some of the issues Sway users have.

**Comment by veracioux** [comment] 2021-11-20 20:40
This behavior should be expected. The `flameshot gui` and other subcommands only signal to the daemon (that was started as `flameshot`) what it has to do via D-Bus, without sending any env vars around. In any case, when #2003 is merged there will be no need to run the daemon, except in some specific circumstances. In the future, the daemon may be completely optional.

**Comment by mmahmoudian** [comment] 2021-11-21 08:15
@veracioux I thought that the `flameshot gui` will start the daemon if it is not running and then it will pass the `gui` dbus call to the newly launched daemon. If this understanding is correct (which according to your comment it is not), then I expected the daemon to also get the env variables.

Anyways, if this is expected, then it is not a bug, so what the label of this issue should be? And also should we close it?

**Comment by veracioux** [comment] 2021-11-21 09:01
@mmahmoudian My knowledge is limited, but I believe the daemon is auto-started via DBus, which in turn starts  a service that launches the daemon. I dont see how envvars could be passed around with this mechanism alone, unless we implement that ourselves.

I think it should be labeled as Needs investigation, because I believe it should be fixed by #2003 but I'm not able to test it currently.

**Comment by UmarJ** [comment] 2021-11-21 09:56
Tried out #2003 and `QT_QPA_PLATFORMTHEME` is passed to flameshot when running `flameshot gui`.

Flameshot v0.10.1 (e7b090f)
Compiled with Qt 5.15.2

**Comment by mmahmoudian** [comment] 2021-11-21 11:43
nice, then we close this until there is a severe need for implementing the env vars loading.

**Closed by mmahmoudian** 2021-11-21 11:43 UTC
Labels: Bug
