### ISSUE TITLE
GUI mode displays wrong contents with multiple screens

### ISSUE THREAD

**Issue by M1cha** [flameshot-org/flameshot#1162] opened 2020-11-21 15:37 UTC
**Flameshot version**
0.8.5-1

**Describe the bug**
I have two screens. A big one on the left and a smaller one on the right.
When I want to do a screenshot in gui mode the content of the left screen vanishes, and the content of the right screen is being displayed in the upper left corner of the left screen.
normal usage:
![2020-11-21_16-21](https://user-images.githubusercontent.com/878458/99880814-02a1e880-2c16-11eb-8c16-5dae9b44b350.png)
after starting selection mode:
![2020-11-21_16-21_1](https://user-images.githubusercontent.com/878458/99880819-09c8f680-2c16-11eb-84e1-30e326b9f450.png)

And it's not just a preview bug because screenshots actually contain what I had selected.
Full screenshots work just fine - the files I've uploaded where taken using flameshot.

**To Reproduce**
I guess duplicating my setup should let you have the same issue.

**Expected behavior**
I should be able to take a screenshot of the actual screen contents

**System Information**
- OS: Arch Linux
- desktop environment: plasma
- CPU: AMD Ryzen 7 4700U
- GPU: 4700's Renoir
- scaling: 200%
- screen layout: ![image](https://user-images.githubusercontent.com/878458/99880929-c622bc80-2c16-11eb-8f03-17c0e2e41a3b.png)

**Comment by JavierGonzalez** [comment] 2020-11-22 01:59
Me too. :(

**Comment by M1cha** [comment] 2020-11-22 09:09
This seems to be a scaling issue and I've fixed it in this PR: https://github.com/flameshot-org/flameshot/pull/1165

**Comment by borgmanJeremy** [comment] 2020-11-22 18:47
This is a duplicate of the fractional scaling bug I have been investigating. Please follow the progress on #564

**Closed by borgmanJeremy** 2020-11-22 18:47 UTC
Labels: Linux
