### ISSUE TITLE
Wayland does not support QWindow::requestActivate() on KDE Plasma

### ISSUE THREAD

**Issue by snyssen** [flameshot-org/flameshot#2436] opened 2022-02-17 11:11 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.8-200.fc35.x86_64
fedora: 35

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Flatpak from Flathub

### Operating System type and version

Fedora 35 with KDE Plasma 5.23.5 on Wayland

### Description

The application starts without an itch, but it fails to take any screenshot afterward. Problem is similar to issue #619, and as far as I can see was fixed under Sway, but is still encountered under KDE Plasma on Wayland.

### Steps to reproduce

1. Run `flameshot`
2. Click on the tray icon to take a screenshot
3. Visually nothing happens, but on the terminal you can see the following messages:
```
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

I also tried running `flameshot full`, it seems to take the screenshot but fails when saving the file with the following message:
```
kf.kio.widgets.kdirmodel: No node found for item that was just removed: QUrl("file:///home/snyssen/Pictures/28382-gunar-streu-midwinter-morning.jpg")
```
(the mentioned file is the first that appear inside the folder when ordered alphabetically, and it has nothing to do with the actual screenshot)
I doubt the bugs are correlated, but I wanted to include it in case it could be.

### System Information

Output from Neofetch:
-------------- 
OS: Fedora Linux 35 (KDE Plasma) x86_64 
Host: XPS 15 7590 
Kernel: 5.16.8-200.fc35.x86_64 
Uptime: 1 hour, 6 mins 
Packages: 2187 (rpm), 28 (flatpak) 
Shell: zsh 5.8.1 
Resolution: 3840x2160 
DE: Plasma 5.23.5 
WM: kwin 
Theme: Layan [Plasma], Adwaita [GTK2], Breeze [GTK3] 
Icons: [Plasma], Tela [GTK2/3] 
Terminal: konsole 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
Memory: 17899MiB / 31721MiB

**Comment by borgmanJeremy** [comment] 2022-02-18 23:59
How did you install Flameshot?

**Comment by mmahmoudian** [comment] 2022-02-19 07:52
Based on the answer to the form I believe both `dnf` and `flatpak` version? @snyssen please confirm/correct me.

**Comment by snyssen** [comment] 2022-02-19 08:55
Hi,
yes I tried them both and the result was the same. I used `sudo dnf install flameshot`and `flatpak install flathub org.flameshot.Flameshot` to install them.

**Comment by greenfoo** [comment] 2022-02-20 11:37
Regarding this piece of information contained in the original comment:
```
...as far as I can see was fixed under Sway, but is still encountered
under KDE Plasma on Wayland
```

...I can confirm that it was fixed on sway, **but the bug returned** (same error message you get in KDE: `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`) a few weeks (maybe ~1 month) ago.

This is what I'm using:
```
sway version 1.7
Flameshot v11.0.0 (compiled with Qt 5.15.2)
```

**Comment by fraschm1998** [comment] 2022-02-27 15:29
I have the same problem with DWL version 0.2.2 running flameshot 11

**Comment by Keksgesicht** [comment] 2022-02-27 20:03
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Graphics Platform: Wayland
```

pacman version:
```
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
```

flatpak version
```
Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
```

for me the problem only exists with the flatpak version.

**Comment by greenfoo** [comment] 2022-03-09 22:05
It looks like many other applications (OBS, LibreOffice, QtDockir, ...) are reporting a similar issue.

It also looks like Qt developers don't consider this to be a bug (see last paragraph of [this comment](https://forum.qt.io/topic/90639/comparing-qt-widgets-app-under-gnome-wayland-using-platform-wayland-egl-to-xcb/8)):
```
>> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

This means your window tried to grab focus in the compositor,
which is not allowed in wayland. Don't create a bug for it, there's
nothing we can do.
```

**Comment by snyssen** [comment] 2022-03-10 08:26
This is really annoying since because of this bug Flameshot is literally unusable at the moment on Plasma Wayland :( Of course I am not blaming anyone, but I hope a solution is possible, otherwise I will simply have to find an alternative to Flameshot (for the moment I am using Spectacle, but it is nowhere near Flameshot in term of ease of use and functionalities)

**Comment by borgmanJeremy** [comment] 2022-03-11 18:48
I don't use wayland on KDE so its support for it is way behind. Need some more dev's to commit to helping fix wayland specific bugs.

**Comment by greenfoo** [comment] 2022-03-18 23:33
Update from my side: turns out, in my case (using sway) the problem was that I was not setting `XDG_CURRENT_DESKTOP=sway` from gdm (I was setting it before... but something must have broken in a recent update).

Anyway... I figured out the specific problem by running flameshot under gdb, setting a breakpoint in `ScreenGrabber::grabEntireDesktop()` and continuing step by step from that point until the error message was triggered (which was a consecuence of `DesktopInfo::windowManager()` not being able to read `XDG_CURRENT_DESKTOP` as it was not set).

Maybe others with KDE (instead os sway) can try a similar approach to figure out where exactly the error is coming from.

**Comment by snyssen** [comment] 2022-03-19 17:14
I echoed `$XDG_CURRENT_DESKTOP` and it returned `KDE`, so I don't think it's problem for me. I could indeed try to debug the application myself, but since I have literally no experience in C++ I will have to learn its tools first... Will update if I ever get to it, but more realistically I will stick to the alternative for now.

**Comment by greenfoo** [comment] 2022-03-20 15:53
It's been raining all day here... so I decided to install KDE and try to debug this issue :)

The result is pull request #2495, which (at least in my computer) seems to fix the problem. It might break backwards compatibility... so let's discuss that on the PR thread.

In the meantime, @snyssen, can you please apply that patch + rebuild + confirm it works also for you? Thanks!

**Comment by snyssen** [comment] 2022-03-21 08:08
I built your commit locally and it worked flawlessly, thank you ! Now let's just hope your PR will be merged soon :)

**Comment by borgmanJeremy** [comment] 2022-03-21 12:45
I'll take a look at the pr this week. Thanks!

**Comment by m2jest1c** [comment] 2022-03-27 18:30
Interesting. I'm on Fedora 35 as well, with KDE Wayland. I compiled using with the fixes in that pull request and I've still got this issue.
`❱❱❱ flameshot gui 
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
[14:25:13] [cost 3.007s] flameshot gui                                                                                                                                                                            
`

No clue what it's talking about in terms of qt.svg. Flameshot works fine in Xorg though. 

- plasmashell 5.24.3
- 5.15.18-200.m2jest1c_acs.fc35.x86_64
- Fedora 35 
- Flameshot v11.0.0 (59a3943) Compiled with Qt 5.15.2

I've removed all other versions of Flameshot, and this version was installed using `make install`.

Glad to see I'm not alone though, and that there's attempts at fixing it that have worked for others. I can provide other logs if needed.

**Closed** 2022-04-05 00:34 UTC
Labels: Unconfirmed Bug

**Comment by snyssen** [comment] 2022-06-01 05:35
Hi,

Sorry to dig out this issue, but do we have an expected date for a new release? I am still unable to use Flameshot since this fix hasn't been deployed yet.

Have a nice day,
Simon Nyssen.

**Comment by snyssen** [comment] 2022-06-01 09:54
Thank you, I will take a look at this :smile:

**Comment by SohamG** [comment] 2022-07-31 20:56
Has this been solved? I still have this issue on KDE Wayland (NixOS, built from nixpkgs-unstable)

**Comment by mmahmoudian** [comment] 2022-08-01 05:32
@SohamG 

> Has this been solved?

Yes, via #2495

> I still have this issue on KDE Wayland

1. Make sure you have the latest version of flameshot
2. Have you read this: https://flameshot.org/docs/guide/wayland-help/#kde-wayland

**Comment by leiha** [comment] 2022-08-09 13:34
Maybe can help : with kde wayland 
i must install this dependencies for flameshot v12.1.0 worked. ( i am on arch but maybe it's the same in others linux )
- xdg-desktop-portal
- grim

**Comment by mmahmoudian** [comment] 2022-08-09 13:40
@leiha 
Thanks for the comment. We always try to keep the AUR updated and therefore the dependencies for Arch-based distros can be adopted from there. Check out the line 62-64:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=flameshot-git

**Comment by aarav2you** [comment] 2024-07-05 04:37
Still happening:
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10
6.9.7-arch1-1
Arch Linux with KDE Plasma 6 on Wayland

Does not save screenshot to clipboard on ctrl+c:
```shell
qt.qpa.wayland: Wayland does not support QWindow::requestActivate() # happens right after command
qt.qpa.wayland: Wayland does not support QWindow::requestActivate() # happens on Ctrl+c
```

**Comment by NebulaBC** [comment] 2025-02-22 04:36
I switched to wayland recently, and all was good. I updated my Arch system (running KDE) today, and Flameshot no longer works.

**Comment by evanlesmez** [comment] 2025-05-02 19:44
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()


I get this error when running `flameshot gui` after disabling my builtin display on sway.  
With my builtin enabled along with my other monitors, flameshot works  although did require some setup in the sway config.

**Comment by LeRatierBretonnien** [comment] 2025-05-26 12:45
Same issue here, KDE+Plasma+Wayland -> black screen for capture.

**Comment by mmahmoudian** [comment] 2025-05-26 22:11
@LeRatierBretonnien 
I have Plasma Wayland on Endeavour, Arch, and Manjaro on different machines and don't have this issue. What is your monitor configuration?

Also the "no signal" points to the direction of graphics card driver imho. Flameshot simply requests the screenshot from the OS and then displays it to user. Perhaps this is better to be discussed with OpenSuse folks?
