### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by TragicWarrior** [flameshot-org/flameshot#591] opened 2019-08-19 14:10 UTC
Any chance of a new release?  The current released is exactly a year old.

**Comment by orschiro** [comment] 2019-08-28 06:17
Wondering about the same. Thanks!

**Comment by Rmano** [comment] 2019-08-29 08:01
Duplicate of #463 ?

**Comment by borgmanJeremy** [comment] 2020-09-04 15:34
Closing as duplicate. Working on a new release.

**Closed by borgmanJeremy** 2020-09-04 15:34 UTC
