### ISSUE TITLE
Flameshot PIN feature doesn't work

### ISSUE THREAD

**Issue by Neykuratick** [flameshot-org/flameshot#2598] opened 2022-05-11 04:56 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3

### Installation Type

User repository (AUR)

### Operating System type and version

Arch with Qtile window manager

### Description

Pin feature just refuses to work. When i click on 'pin' the app just closes and that's all. I assume it has something to do with the window manager i'm using, but i didn't find any log files flameshot provides (if any), so i couldn't troubleshoot it neither

My window manager has no logs related to Flameshot

### Steps to reproduce

1. run ``` flameshot gui ```
2. select region
3. click on the pin icon

### Screenshots or screen recordings

https://user-images.githubusercontent.com/63598014/167771914-f381cb10-4ab9-4e05-95cb-5de51282f41e.mp4

### System Information

```
                   -`
                  .o+`
                 `ooo/
                `+oooo:                  roman@arch
               `+oooooo:                 ----------
               -+oooooo+:                OS: Arch Linux x86_64
             `/:-:++oooo+:               Host: MS-7996 1.0
            `/++++/+++++++:              Kernel: 5.17.5-zen1-1-zen
           `/++++++++++++++:             Uptime: 11 hours, 3 mins
          `/+++ooooooooooooo/`           Packages: 854 (pacman)
         ./ooosssso++osssssso+`          Shell: zsh 5.8.1
        .oossssso-````/ossssss+`         Resolution: 1920x1080, 1920x1080, 1920x1080
       -osssssso.      :ssssssso.        WM: LG3D
      :osssssss/        osssso+++.       Theme: Adwaita [GTK2/3]
     /ossssssss/        +ssssooo/-       Icons: Adwaita [GTK2/3]
   `/ossssso+/:-        -:/+osssso+-     Terminal: alacritty
  `+sso+:-`                 `.-/+oso:    CPU: Intel i5-6600 (4) @ 3.900GHz
 `++:.                           `-/+/   GPU: NVIDIA GeForce GTX 1060 6GB
 .`                                 `/   Memory: 4240MiB / 15963MiB
```

**Comment by gutyina70** [comment] 2022-05-16 13:39
how did you fix this? I have the same issue on dwm

**Comment by Neykuratick** [comment] 2022-05-16 16:21
I didn't. It just randomly starts and stops working
    On Monday, May 16, 2022, 04:39:24 PM GMT+3, Gutyina Gergő ***@***.***> wrote:  
 
 


how did you fix this? I have the same issue on dwm

**Comment by mmahmoudian** [comment] 2022-05-17 15:57
When we find a way to reproduce the problem, we can then try to investigate and potentially fix it. Therefore, if it is possible for you, try to replicate it in a clean VM and see if you managed to reproduce it. :+1:

**Comment by gutyina70** [comment] 2022-05-18 04:36
Now it's working for me too. Not sure what fixed it, but I was messing with dbus, put `flameshot &` in autostart then rebooted. Maybe a completely different change solved it. I'll try to reproduce the bug on a clean install in a few days.

**Comment by gutyina70** [comment] 2022-05-22 18:09
I tested flameshot in a vm using a clean install with minimum packages to run flameshot, and turns out the solution was running `flameshot &`. For anyone having this issue, check out the [arch wiki](https://wiki.archlinux.org/title/Flameshot#Troubleshooting).

When I first tried to fix this, I ran `flameshot &` but closed the terminal, because I didn't know closing kills all the background jobs.

**Comment by mmahmoudian** [comment] 2022-05-22 18:51
@gutyina70 the pinning should work regardless of you running the daemon or not. Flameshot should sustain the daemon if and when needed (i.e. keeping things in clipboard or pinning). Considering that you have managed to reproduce this in a clean VM, I'll re-open this issue but will keep it as "Unconfirmed bug" unless one of the devs can also reproduce it either on their system or a clean VM. Thanks for investigating this.

**Comment by gutyina70** [comment] 2022-05-22 19:53
> Flameshot should sustain the daemon if and when needed (i.e. keeping things in clipboard or pinning).
I think it's only the case when you have dbus running. Running either `dbus-launch` or flameshot in the background fixes this issue.

**Comment by mmahmoudian** [comment] 2022-05-22 20:19
You are right, dwm does not run any dbus system in the background. Perhaps flameshot can check if the the dbus is running and accessible and throw an error otherwise.

**Comment by borgmanJeremy** [comment] 2022-05-22 20:33
IMO users just need to read the docs and meet the minimum requirements on something like DWM. I feel we should not add complexity for 0.01% of users

**Comment by mmahmoudian** [comment] 2022-05-22 21:41
Then perhaps we should add something to our website and to the Arch Wiki. I'll handle those.

**Comment by mmahmoudian** [comment] 2022-05-29 10:31
This info is now available in Arch Wiki and out website

**Closed by mmahmoudian** 2022-05-29 10:31 UTC
Labels: Documentation
