### ISSUE TITLE
Eraser

### ISSUE THREAD

**Issue by geekthought** [flameshot-org/flameshot#926] opened 2020-09-16 07:33 UTC
Can we get an eraser please? Undo and redo just doesnt cut it. Thank you...

**Comment by borgmanJeremy** [comment] 2020-09-16 12:11
Thanks for the feedback. This is a duplicate of #202 so I will close it for now, but we are working are way through all the issues and will consider this.

**Closed by borgmanJeremy** 2020-09-16 12:11 UTC
Labels: Enhancement
