### ISSUE TITLE
“flameshot” cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by jain6196** [flameshot-org/flameshot#3572] opened 2024-04-17 05:10 UTC
### Flameshot Version

All

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Apple M3 Pro, macOS Sonoma Version 14.3

### Description

I am unable to install flameshot in mac as I am getting this issue as "macOS cannot verify that this app is free from malware"
Is there any way that I can do that.

<img width="269" alt="image" src="https://github.com/flameshot-org/flameshot/assets/32647371/888ef04c-b64b-43d4-88d4-b1afafde18e6">

### Steps to reproduce

Download flameshot.dmg and double click to install

### Screenshots or screen recordings

<img width="269" alt="image" src="https://github.com/flameshot-org/flameshot/assets/32647371/888ef04c-b64b-43d4-88d4-b1afafde18e6">

### System Information

Apple M3 Pro, macOS Sonoma Version 14.3

**Comment by HeinanCA** [comment] 2024-04-17 07:08
Occurs to me as well on M3 Pro, macOS Sonoma v14.4.1

**Comment by ObjectOrientedGuy** [comment] 2024-05-01 20:24
check this section in [README.md](https://github.com/flameshot-org/flameshot?tab=readme-ov-file#macos) file

**Note**  that because of macOS security features, you may not be able to open flameshot when installed using brew. If you see the message `“flameshot” cannot be opened because the developer cannot be verified`. you will need to follow the steps below:
1. Go to the Applications folder (Finder > Go > Applications, or Shift+Command+A)
2. Right-Click on "flameshot.app" and choose "Open" from the context menu
3. In the dialog click "Open"

After following all those steps above, `flameshot `will open without problems in your Mac.

**Comment by Karreg** [comment] 2024-05-30 08:43
I just came across the same issue. Thanks for the link.

It should definitely be written in the [MacOS install documentation](https://flameshot.org/docs/installation/installation-osx/) :)

**Comment by mmahmoudian** [comment] 2024-05-30 13:21
@jain6196 @HeinanCA 
Duplicate of #3533 and #3404 . We always encourage users to search among open and closed issues before creating a new one. This is primarily to save your own time.

@ObjectOrientedGuy Thanks for addressing this issue before we find a chance to do so.

Also @Karreg kindly provided [a PR on out website repo](https://github.com/flameshot-org/flameshot-org.github.io/pull/149) to have this information more spread across our documentations. Thank you @Karreg 

I wish you all enjoy Flameshot

**Closed** 2024-05-30 13:21 UTC
Labels: Duplicate, question, MacOS

**Comment by krema** [comment] 2024-06-14 10:12
> check this section in [README.md](https://github.com/flameshot-org/flameshot?tab=readme-ov-file#macos) file
> 
> **Note** that because of macOS security features, you may not be able to open flameshot when installed using brew. If you see the message `“flameshot” cannot be opened because the developer cannot be verified`. you will need to follow the steps below:
> 
> 1. Go to the Applications folder (Finder > Go > Applications, or Shift+Command+A)
> 2. Right-Click on "flameshot.app" and choose "Open" from the context menu
> 3. In the dialog click "Open"
> 
> After following all those steps above, `flameshot `will open without problems in your Mac.

This is not working for me. Other ideas?

**Comment by Grechanin** [comment] 2025-03-10 11:53
It is possible to bypass the error via the System Settings:

Open System Settings -> Privacy & Security
Scroll all the way to the bottom and click "Open anyway" below "flameshot.app was blocked from use because it is not from an identified developer".
Alternatively (or if the above approach didn't help), it is possible to allow Flameshot to launch via the following command:

`sudo xattr -rd com.apple.quarantine /Applications/flameshot.app`

check [this link](https://flameshot.org/docs/guide/troubleshooting/#:~:text=%F0%9F%94%97%20%E2%80%9Cflameshot%E2%80%9D%20app%20cannot%20be%20opened&text=Open%20System%20Settings%20%2D%3E%20Privacy%20%26,not%20from%20an%20identified%20developer%22.)

**Comment by amkronii** [comment] 2025-05-19 01:20
> It is possible to bypass the error via the System Settings:
> 
> Open System Settings -> Privacy & Security Scroll all the way to the bottom and click "Open anyway" below "flameshot.app was blocked from use because it is not from an identified developer". Alternatively (or if the above approach didn't help), it is possible to allow Flameshot to launch via the following command:
> 
> `sudo xattr -rd com.apple.quarantine /Applications/flameshot.app`
> 
> check [this link](https://flameshot.org/docs/guide/troubleshooting/#:~:text=%F0%9F%94%97%20%E2%80%9Cflameshot%E2%80%9D%20app%20cannot%20be%20opened&text=Open%20System%20Settings%20%2D%3E%20Privacy%20%26,not%20from%20an%20identified%20developer%22.)

This works perfectly to me, thanks mate
