### ISSUE TITLE
Easy OCR

### ISSUE THREAD

**Issue by leoneivaw** [flameshot-org/flameshot#1344] opened 2021-02-17 23:44 UTC
I would like to suggest OCR feature. 
It is very useful for a lot of people.
It demands no more than 8 lines code and one dependence.
I use Flameshot with OCR and is great. It as native feature is a lot better!

ocr.sh file

trap "rm ~/Imagens/ocr*" EXIT
flameshot gui -p ~/Imagens 
while [ ! -f ~/Imagens/ocr.png  ]; do sleep 1; done
tesseract -l por ~/Imagens/ocr.png ~/Imagens/ocr &> /dev/null 
while [ ! -f ~/Imagens/ocr.txt ]; do sleep 1; done
cat ~/Imagens/ocr.txt | xsel -bi
sleep 2
exit

**Comment by borgmanJeremy** [comment] 2021-02-18 01:48
Thanks for posting this, but it is a duplicate of #702 and we actually had someone submit a PR to add an OCR feature. It requires some clean up so it wont make it into 0.9 but its on the way.

**Closed** 2021-02-18 01:55 UTC

**Comment by mmahmoudian** [comment] 2021-07-02 14:13
@leoneivaw I just faced a PDF that needed OCR and reading your message got me to think if there is a better way (not to write to disk and read and while loop and etc., and I found it:

```sh
flameshot gui --raw | tesseract -l fin stdin stdout | xclip -selection clipboard
```

I have used the Finnish language here, but of course that should be changes according to your needs.

The following are the software versions I have:

> tesseract 4.1.1
> Flameshot v0.10.0
> xclip version 0.13

**Comment by leoneivaw** [comment] 2021-07-02 15:21
@mmahmoudian 

Works great!
Simple and fast.

Thanks

**Comment by stefanocudini** [comment] 2022-05-30 09:37
it would be very useful a button OCR which transforms the image in the selection into text.
That would be really cool

**Comment by mmahmoudian** [comment] 2022-05-30 20:11
@stefanocudini you should wait until the plugins are implemented. For the time being you can use the script I suggested above and bind it to a keybinding

**Comment by ashuvssut** [comment] 2022-08-01 12:37
@mmahmoudian  your command works fine for large enough texts
`flameshot gui --raw | tesseract -l fin stdin stdout | xclip -selection clipboard`

BUT, for small fonts, it doesnt work so well...

is there some way use imagemagick to magnify and then OCR it?
I tried something like the command below after reffering [this StackOverflow ANs](https://stackoverflow.com/a/4945131/12872199)
`flameshot gui --raw | convert -resize 400% stdin stdout | tesseract -l eng stdin stdout | xclip -selection clipboard`
(The command writted above is wrong)

can you please help me in this

**Comment by stefanocudini** [comment] 2022-08-01 12:58
if flameshot had a plugin system that allows you to enter custom commands(like the one above) this would make things very easy
and it would be a truly great tool!

**Comment by DO-Ui** [comment] 2023-04-11 23:09
> @mmahmoudian your command works fine for large enough texts `flameshot gui --raw | tesseract -l fin stdin stdout | xclip -selection clipboard`
> 
> BUT, for small fonts, it doesnt work so well...
> 
> is there some way use imagemagick to magnify and then OCR it? I tried something like the command below after reffering [this StackOverflow Answer](https://stackoverflow.com/a/4945131/12872199) `flameshot gui --raw | convert -resize 400% stdin stdout | tesseract -l eng stdin stdout | xclip -selection clipboard` (The command written above is wrong)
> 
> can you please help me in this

Somewhat a late reply but I was fiddling with imagemagick and got this to work

`flameshot gui --raw | convert -resize 400% png:- png:- | tesseract -l eng stdin stdout | xclip -selection clipboard`
