### ISSUE TITLE
Crashing when doing Text first then Arrow

### ISSUE THREAD

**Issue by makomoulage** [flameshot-org/flameshot#2860] opened 2022-08-05 22:20 UTC
### Flameshot Version

Flameshot v11.0.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

EndeavourOS   linux: 5.18.5-arch1-1  XFCE

### Description

Running "flameshot gui" mapped on  the printScreen key of my keyboard.
When typing some Text first then drawing an Arrow, it exits/crashes.
It works well when drawing the arrows first then typing some text.

### Steps to reproduce

1. run "flameshot gui"
2. click on the text icon
3. type some texts
4. click on the arrow icon
5. crash as soon as i start drawing the arrow

### Screenshots or screen recordings

![flameshot_crash](https://user-images.githubusercontent.com/35504636/183218701-3fad8aae-9c19-4cdc-90e9-05291f4bcfb5.gif)

### System Information

EndeavourOS
linux: 5.18.5-arch1-1
XFCE
xorg
nvidia

**Comment by borgmanJeremy** [comment] 2022-08-05 22:22
Update to the latest version (12.1) . It’s resolved there

**Comment by mmahmoudian** [comment] 2022-08-06 05:32
Duplicate of #2528 which was fixed in #2369.

**Closed** 2022-08-06 05:32 UTC
Labels: Bug, Duplicate

**Comment by makomoulage** [comment] 2022-11-24 21:02
[image: image.png]
This works for me with this version.
