### ISSUE TITLE
Ubuntu / Crashes when saving the screenshot

### ISSUE THREAD

**Issue by omersi** [flameshot-org/flameshot#1260] opened 2021-01-27 09:06 UTC
**Flameshot version**
0.8.5
**Describe the bug**
It crashes when I try to save the selected area.
I removed it and reinstalled it already.

**To Reproduce**
1. Select an area to capture
1. click on the `save` button.

**Expected behavior**
save the image.

**System Information**
Ubuntu 20.04.1 LTS

**Comment by mmahmoudian** [comment] 2021-01-28 07:03
@omersi Please provide the complete system information as requested in the issue template (i.e your desktop environment or window manager)

Also please specify how you have installed Falmeshot (e.g distro repository, snap, flatpak, compiling)

**Comment by omersi** [comment] 2021-01-28 22:37
Installed via snap

uname -a

```bash
Linux imubit-omer 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by borgmanJeremy** [comment] 2021-01-29 01:34
Can you post the contents of ~/.config/flameshot/flameshot.ini?

I am not able to replicated it in my Ubuntu VM. I'm installing updates now and will update this if that makes the problem occur.

**Comment by omersi** [comment] 2021-01-29 09:57
it's empty :/

```bash 
\cat ~/.config/flameshot/flameshot.ini 
cat: /home/omer/.config/flameshot/flameshot.ini: No such file or directory
```

**Comment by borgmanJeremy** [comment] 2021-02-05 23:33
I can't do anything to recreate this :/ 

If I had to guess its likely a common issues such as:

- Incorrectly configured locales (is your system in a different language)?
- Notification manager not working - unlikely given ubuntu

**Comment by ZurMaD** [comment] 2021-02-13 19:16
snap uses a different path for config but I don't know exactly where. Try to use
```
whereis flameshot # on terminal
```

**Comment by omersi** [comment] 2021-02-14 10:08
1. when installing `flameshot` from `apt` the version is`0.6.0` while from snap it's `0.8.5`
2. I completely removed `flameshot` from my laptop.
3. reinstalled v. 0.8.5 using snap.
```bash
flameshot                        v0.8.5+git10.376a6f2        6      latest/stable    borgman-jeremy   -
```

Notes:
1. still crashes when using `save` option
2. cat /home/omer/snap/flameshot/6/.config/flameshot/flameshot.ini  
```ini
[General]
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
```

also, trying to lunch `configuration` causing it to crash.

**Comment by mmahmoudian** [comment] 2021-02-14 14:40
It seems your config file does not have certain lines. Try to add them manually and see if the issue is fix. This is my config

```
[General]
closeAfterScreenshot=false
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=5
saveAfterCopy=false
saveAfterCopyPath=/home/mehrad/Pictures
savePath=/home/mehrad/Pictures
uiColor=#fa8c00
```

**Comment by hosiet** [comment] 2021-02-14 16:41
Manually adding the lines shall not be the real solution. The real problem is that why the snap build lacks the missing lines, and that why the missing lines led to the crash.

**Comment by mmahmoudian** [comment] 2021-02-14 17:40
@hosiet I agree that this is not a permanent solution. I just wanted to know if this is the thing that causes the issue. If you think/confirm this is the one, we can mark this as a bug (I should try it in a VM though)

**Comment by omersi** [comment] 2021-02-15 13:35
I tried adding these lines as suggested, but the crashing continue.

**Comment by borgmanJeremy** [comment] 2022-01-15 17:05
This should be fixed in the snap released yesterday. Can you try it?

**Closed** 2022-02-19 21:05 UTC
Labels: Bug, Waiting For Info, Linux

**Comment by MeKLiN2** [comment] 2022-03-27 02:07
NOT FIX YET... CRASHES IN LIVE MODE AND INSTALLED MODE. PERMISSIONS ERROR? i notice it save different folder for... home folder save, randomly, or saved to pictures folder. this works fine on my gigabyte hd3p i5-6600 rx560... crashing my 3600x ryzen asus b550m-a wifi rx570... bios problem?

**Comment by MeKLiN2** [comment] 2022-03-27 02:24
sudo apt install nautilus
sudo nautilus
right click the folder /home/ within your user name folder, which is within the root / folder called backslash, in there is home, you can right click that or if theres your user name folder maybe that one instead but i did the main /home/ folder on the root which is with all the other big folders, etc, or whatvever u guys are sudo gediting n stuff. then i click permissions within enclosed and set ALL THINGS TO READ AND DELETE ABLE.... then that was the 'sub'menu of permissions, make sure teh main menu says that too, and then , for whatever reason, when the prnt screen button wants to save to root /home instead of /home/pictures, it wont blue screen

**Comment by MeKLiN2** [comment] 2022-03-27 02:28
just a access denied when manually trying to save to etc so the error lies in the 'automatic' selection of folder, when it says either 'pictures' as an option and clicking save just goes and the place its going to is just shown.
