### ISSUE TITLE
Pin image can not penetrates the edge of the screen with Linux mint 20.2

### ISSUE THREAD

**Issue by wurenny** [flameshot-org/flameshot#2569] opened 2022-04-29 04:01 UTC
### Flameshot Version

``` shell
$ flameshot -v
Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Mint 20.2 with Cinnamon 5.0.7

### Description

Pin desktop image can not penetrates the edge of the screen
But if you hold the Alt key while moving the image, it's OK
I think it is more troublesome to hold the alt key, and it is not necessary

[](https://user-images.githubusercontent.com/6622574/165882896-1e503ea7-8650-406d-b1f0-3583c312d707.mp4)

### System Information

1. OS:Linux Mint 20.2 with Cinnamon 5.0.7
2. display configuration
![linux-display-info](https://user-images.githubusercontent.com/6622574/165882819-e2270bf9-599f-4464-9e2e-3a03fc6eb2a3.png)
4. Desktop Env:Cinnamon 5.0.7

**Comment by mmahmoudian** [comment] 2022-04-29 06:10
Please search the issues properly before creating a new issue.
Duplicate of #1786 solved by #2520

**Closed** 2022-04-29 06:10 UTC
Labels: Duplicate, Enhancement
