### ISSUE TITLE
Keyboard not caught properly in Wayland

### ISSUE THREAD

**Issue by s-iso** [flameshot-org/flameshot#2031] opened 2021-10-31 17:34 UTC
**Flameshot version**
```
Flameshot v0.10.1
Compiled with Qt 5.15.2
```

**Describe the bug**
Keyboard is not properly caught by Flameshot, meaning that shortcuts are not working at all. This is especially annoying with the "Esc to close" shortcut, and can force the user to have to hard reset their PC if the mousecursor is being forcefully caught in the process of creating a screenshot (for example by a game).

**To Reproduce**
Run Flameshot.

OS: Arch (every package up to date)
WM: sway (on Wayland)

Let me know if you can't reproduce with the already given information.

**Expected behavior**

Keyboard is being caught by Flameshot, Keybinds work properly.

**System Information**

already mentioned above, newest Arch on Wayland.

**Comment by r79** [comment] 2021-10-31 17:35
Small update: *some* of the keybinds seem to work when "flameshot config" is opened and selected as the active window.

**Comment by veracioux** [comment] 2021-10-31 17:45
It has been reported a bunch of times that keybindings don't work in flameshot, the cause being that some other window takes focus away from flameshot. A fix has been introduced in the newest versions (we are not sure if it works 100% of the time).

Can you try installing the newest development version of flameshot? 3 ways you can do that:
- compile directly from master branch
- install `flameshot-git` from the AUR
- download a package from [here](https://flameshot.org/nightly)

**Comment by mmahmoudian** [comment] 2021-11-02 14:38
I don't have any machines with a functional Wayland at the moment (blame the damn Nvidia card), but you don't need hard-reset, just go to tty and `pkill flameshot` or any process that you suspect that misbehaving.

I will try to install Sway on a computer and see if I can reproduce this.

**Comment by C0rn3j** [comment] 2021-12-03 10:23
@veracioux The current git version seems to fix the issue for me

**Comment by veracioux** [comment] 2021-12-03 10:38
@C0rn3j If it's not too bothersome, can you try compiling from #2003 and seeing if something changes for you? These things can be difficult to debug.

**Comment by C0rn3j** [comment] 2021-12-03 12:41
I am using `AUR/flameshot-git` and just swapped the source line for `source=("git+https://github.com/veracioux/flameshot.git#branch=die_dbus")`

Clipboard on XWayland seems still broken(wayland was broken before already).

If you need help setting up Wayland, I can try to help.

**Comment by veracioux** [comment] 2021-12-03 13:08
@C0rn3j It's more of a "finding the time to get around to it" type of problem, but thanks anyway 😄

**Comment by pinsard** [comment] 2022-01-14 15:05
Wait a minute. I think it is not exclusively related to Wayland as it also happens on my Pop!_OS install. As you can see from my inxi output, it is Xorg. I've tried installing 0.9, 0.10, even 0.11 which is currently in RC-1, all versions either Debian, Ubuntu debs, or AppImage, present the same behavior. 

```
System:    Kernel: 5.15.11-76051511-generic x86_64 bits: 64 Desktop: GNOME 40.5 Distro: Pop!_OS 21.10 
Machine:   Type: Laptop System: Dell product: Latitude 7480 v: N/A serial: <filter> 
           Mobo: Dell model: 083N35 v: A01 serial: <filter> UEFI: Dell v: 1.23.0 date: 10/07/2021 
Battery:   ID-1: BAT0 charge: 44.2 Wh (100.0%) condition: 44.2/60.0 Wh (73.7%) 
CPU:       Info: Dual Core model: Intel Core i5-7300U bits: 64 type: MT MCP cache: L2: 3 MiB 
           Speed: 1059 MHz min/max: 400/3500 MHz Core speeds (MHz): 1: 1059 2: 1026 3: 700 4: 700 
Graphics:  Device-1: Intel HD Graphics 620 driver: i915 v: kernel 
           Device-2: Realtek Integrated_Webcam_HD type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.13 driver: loaded: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.2.2 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio driver: snd_hda_intel 
           Sound Server-1: ALSA v: k5.15.11-76051511-generic running: yes 
           Sound Server-2: PulseAudio v: 15.0 running: yes 
           Sound Server-3: PipeWire v: 0.3.32 running: yes 
Network:   Device-1: Intel Ethernet I219-LM driver: e1000e 
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi 
           IF: wlp2s0 state: down mac: <filter> 
           IF-ID-1: wwan0 state: down mac: <filter> 
Bluetooth: Device-1: Intel Bluetooth wireless interface type: USB driver: btusb 
           Report: hciconfig ID: hci0 state: up address: <filter> bt-v: 2.1 
Drives:    Local Storage: total: 238.47 GiB used: 84.92 GiB (35.6%) 
           ID-1: /dev/sda vendor: LITE-ON model: CV8-8E256-11 SATA 256GB size: 238.47 GiB 
Partition: ID-1: / size: 48.97 GiB used: 12.53 GiB (25.6%) fs: ext4 dev: /dev/sda2 
           ID-2: /boot/efi size: 1022 MiB used: 180.1 MiB (17.6%) fs: vfat dev: /dev/sda1 
           ID-3: /home size: 167.19 GiB used: 72.21 GiB (43.2%) fs: ext4 dev: /dev/sda4 
Swap:      ID-1: swap-1 type: partition size: 16.6 GiB used: 0 KiB (0.0%) dev: /dev/dm-0 
Sensors:   System Temperatures: cpu: 40.0 C mobo: N/A 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 275 Uptime: 2d 13h 45m Memory: 15.51 GiB used: 4.91 GiB (31.7%) Shell: Zsh inxi: 3.3.06 
```

**Comment by pinsard** [comment] 2022-01-14 17:19
I found the problem with Pop!_OS: the tiling extension. When the tiling extension is active, Flameshot's tools shortcurs aren't captured. Damn... I switched to Pop exactly because their take on tiling was very good, but I depend on Flameshot a lot more, so I guess it's time to move to i3 or the likes.

**Comment by borgmanJeremy** [comment] 2022-01-14 17:22
If it's tiling there was a bug filed yesterday. It seems it's an upstream pop issue that's already been fixed. On mobile so I don't have the link but you can find it by searching our issues.

**Comment by pinsard** [comment] 2022-01-14 17:29
Borg, already helped a lot. Will look for the bug report and check with System76. 
However, what the OP claimed, that the problem is related with Wayland, could probably also be related with some other aspect of his system, just like mine was. In my case, it is obviously not caused by Flameshot, but by something in Gnome tiling extensions intercepting keys etc.

**Comment by C0rn3j** [comment] 2022-02-12 15:20
This does not seem to be an an issue anymore with flameshot 11.0.0.

![image](https://user-images.githubusercontent.com/1641362/153717140-160e1d70-ed99-4b5e-b50b-fe6b765acae9.png)

**Comment by borgmanJeremy** [comment] 2022-04-05 00:57
It seems like this has been resolved in other projects and was not a flameshot bug.

**Closed by borgmanJeremy** 2022-04-05 00:57 UTC
Labels: Bug, Waiting For Info
