### ISSUE TITLE
截图加水印？

### ISSUE THREAD

**Issue by omaidb** [flameshot-org/flameshot#577] opened 2019-07-08 02:38 UTC
能否添加一个功能，截图加水印……盗图现象严重

**Comment by hosiet** [comment] 2019-07-08 14:26
Hi @omaidb , please consider editing the issue and rewrite your question in English. Thanks!

**Comment by AkariMarisa** [comment] 2019-07-09 00:53
> 能否添加一个功能，截图加水印……盗图现象严重

Can we add a feature that we can add watermark on screenshot?

Actually I don't think this is necessary.

**Comment by borgmanJeremy** [comment] 2020-09-16 01:10
Thank you for the suggestion. This is a duplicate of #158 but it is something we will consider!

**Closed by borgmanJeremy** 2020-09-16 01:10 UTC
