### ISSUE TITLE
Screenshot tool selection buttons glitched on multi-monitor setup

### ISSUE THREAD

**Issue by PPhenolOxidase** [flameshot-org/flameshot#1645] opened 2021-05-28 05:00 UTC
Currently running v0.9.0 on Windows 10 update 2004
Downloaded `Flameshot-0.9.0-win64.msi`

My current monitor setup consists of 4 monitors in an "L" shape. When trying to take a screenshot, none of the tool selection buttons appear. However, the toggle-able side panel just barely appears on one of the monitors (the one that is below the top-left corner).

![Screenshot 1](https://user-images.githubusercontent.com/68681724/119930910-5fc48100-bf4e-11eb-82fb-11c8fcf45421.png)

To see if the icons and side panel were stuck in the top left, I rearranged the monitors in the display settings to a 2x2 square and took a screenshot in the top left monitor. Was met with buttons and side panel.

![Screenshot 2](https://user-images.githubusercontent.com/68681724/119930626-c7c69780-bf4d-11eb-8e32-48187f20e33b.png)

 However, screenshots on any other monitor resulted in the buttons being left in the top left monitor.

![Screenshot 3](https://user-images.githubusercontent.com/68681724/119930816-2ee44c00-bf4e-11eb-9a80-05ade3a8b992.png)

**Comment by mmahmoudian** [comment] 2021-05-28 06:10
Duplicate of #1440

**Closed** 2021-05-28 06:10 UTC
