### ISSUE TITLE
The shortcut to take a screenshot is broken on KDE

### ISSUE THREAD

**Issue by rapiz1** [flameshot-org/flameshot#1875] opened 2021-09-09 07:15 UTC
**Flameshot version**

 0.10.1-1

**Describe the bug**

Pressing the shortcut to take a screenshot doesn't work on KDE.
**To Reproduce**

1. Open KDE Settings / Shortcuts
2. Add Flameshot
3. Set "Take a screenshot" with key PrintScr
4. Press PrintScr. Nothing happens.

**Expected behavior**

A screenshot will be taken
**System Information**

Operating System: Arch Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.13-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-6600U CPU @ 2.60GHz
Memory: 19.4 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520

**Comment by mmahmoudian** [comment] 2021-09-09 07:51
Would you please post here a screenshot of the command tab of the shortcut you created?

**Comment by rapiz1** [comment] 2021-09-09 07:57
![Screenshot_20210909_155703](https://user-images.githubusercontent.com/20105061/132646423-7e0aa0d9-64c6-4ad2-9cf6-13469b7dc842.png)

**Comment by rapiz1** [comment] 2021-09-09 07:59
BTW, it was working until recently update, like 3 months? However, I'm not using Arch much during that time so I'm not sure which update broke this.

**Comment by mmahmoudian** [comment] 2021-09-09 10:43
Try this:
![image](https://user-images.githubusercontent.com/390889/132672031-dc720b56-008b-47dc-9d5b-42aaf8c1e063.png)

**Comment by rapiz1** [comment] 2021-09-10 05:04
Thanks. This works.
However, I think some users may still face the original issue.

**Comment by mmahmoudian** [comment] 2021-09-10 05:17
I don't know why that issue happened to you as we don't/can't create global shortcuts for the window managers (e.g KDE Plasma).

But since sunrise you had that, I don't see why it has stopped working as we haven't had any breaking changes in our CLI. If you open a terminal and run `flameshot gui` it should work and this form of command has existed perhaps since versions < 0.5.x

**Comment by mmahmoudian** [comment] 2021-09-10 05:21
Since this is the first time such thing is reported and as it is not clear hire such simple thing has gone wrong, I suggest closing this issue for now. If anyone faces the same issue, they can reopen this thread and add a bit more information so that we can track is down and fix it if it is Flameshot's issue.

**Comment by mindyourlifeguide** [comment] 2021-09-10 08:41
I also ran into a similar one. But I decided it myself using the solution described earlier.

**Comment by mmahmoudian** [comment] 2021-09-10 09:06
@mindyourlifeguide would you please explain your experience. Basically I want to know how was your system and when and how it got broken. Please also include your OS, Desktop Environment, Window Manager, Flameshot versions and etc.

**Comment by mindyourlifeguide** [comment] 2021-09-11 05:05
OS: Arch Linux x86_64 
Kernel: 5.14.2-arch1-2 
DE: Plasma 5.22.5
WM: KWin
Flameshot: 0.10.1-1

I reinstalled the system as I was changing the file system. After that I downloaded the list of hotkeys for KDE from github and imported it. And they did not work, although it worked with the last installation (about a year and a half ago)

**Comment by mmahmoudian** [comment] 2021-09-11 06:48
@mindyourlifeguide it should work. I'll look into it.

**Comment by rapiz1** [comment] 2021-09-12 07:52
After some digging, the shortcut comes from `/usr/share/applications/org.flameshot.Flameshot.desktop`
```
[Desktop Action Capture]
Name=Take screenshot
Name[zh_CN]=进行截图
Name[pl]=Zrzut ekranu
Name[fr]=Prendre une capture d'écran
Name[ja]=スクリーンショットを撮る
Name[ru]=Сделать скриншот
Name[sk]=Zachytiť obrazovku
Name[sr]=Сними екран
Name[uk]=Зробити знімок
Name[nl]=Schermfoto maken
Name[nl_NL]=Schermfoto maken
Name[es]=Tomar captura de pantalla
Name[de]=Bildschirmfoto aufnehmen
Name[pt_BR]=Capturar tela
Exec=flameshot gui --delay 500
```

I wonder why there's a delay here. After removing it, the shortcut works again.
BTW, run `flameshot gui --delay 500` from console always work.

@mmahmoudian Any changes about the delay parameters?

**Comment by rapiz1** [comment] 2021-09-12 09:45
@mindyourlifeguide Can you test the workaround I gave?

**Comment by mmahmoudian** [comment] 2021-09-12 11:01
@rapiz1 Interesting! Your comments made me to dive into the rabbit-hole of finding the source of the issue and finally managed to find why the KDE shortcuts does not work. I'm creating a PR for the fix and I will update this post.

**Comment by mmahmoudian** [comment] 2021-09-12 11:42
@rapiz1 I believe the delay in the line below is now unnecessary:

https://github.com/flameshot-org/flameshot/blob/c3dd1ce5e6b5919cfa2394b05788293ab3ea018b/data/desktopEntry/package/org.flameshot.Flameshot.desktop#L84

Based on [the definition of actions in the freedesktop.org](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions):

> An action represents an additional way to invoke the application. Application launchers should expose them to the user (for example, as a submenu) within the context of the application.

So basically as long as you are not using your launcher (e.g in the picture below is the [Plasma Kickoff](https://userbase.kde.org/Plasma/Kickoff)) to call the submenus, you will never run these codes. So basically it does not matter what is written in those actions of the .desktop file.

![image](https://user-images.githubusercontent.com/390889/132986003-0c6d9cdc-f050-4cbc-8dad-70f21092da81.png)

I believe the source of the issue was what I made the #1887 PR for and not the desktop file, in spite of agreeing with you that the delay is unnecessary and should be removed unless it is implemented there just to give the system enough time to close the right-click menu that I showed above.

@borgmanJeremy Do you think there is merit in having that delay anymore?

**Comment by mindyourlifeguide** [comment] 2021-09-12 20:17
@rapiz1 This did not fix the current issue

**Comment by maguilara** [comment] 2021-09-12 21:18
I'm facing the same issue myself, but I think mine was working until a few months ago (I just came back to my arch partition). I tested a new key combo, and then I reverted to the same key (PrntScr), and I think just then it started to fail. I use the KDE shortcut with the action `flameshot gui`

**Comment by mmahmoudian** [comment] 2021-09-13 09:29
@mindyourlifeguide would you please try importing [this file](https://github.com/flameshot-org/flameshot/blob/4405f9ae72c3b978b878e6244b18bbef036a0363/docs/shortcuts-config/flameshot-shortcuts-kde) into your KDE shortcuts and see if it has fixed it for you. The file is from https://github.com/flameshot-org/flameshot/pull/1887/files

**Comment by mindyourlifeguide** [comment] 2021-09-14 05:59
@mmahmoudian did not fix

**Comment by mmahmoudian** [comment] 2021-09-14 06:53
@mindyourlifeguide would you please send me some screenshots from your KDE Plasma shortcuts for Flameshot. Also please Export them and give me a link to download it.

**Comment by mindyourlifeguide** [comment] 2021-09-14 07:12
![image](https://user-images.githubusercontent.com/35348648/133211674-5156c046-0061-4ff3-93c7-fa8708cd1354.png)
![image](https://user-images.githubusercontent.com/35348648/133211706-fafb7f8f-fe20-4e03-b845-644ffc18b1d1.png)
![image](https://user-images.githubusercontent.com/35348648/133211717-76145e5c-b4e8-4141-84b7-564f71910249.png)
![image](https://user-images.githubusercontent.com/35348648/133211747-b41b7911-979b-49c0-8363-aeb768a70102.png)
[flameshot.zip](https://github.com/flameshot-org/flameshot/files/7159564/flameshot.zip)

**Comment by mmahmoudian** [comment] 2021-09-15 17:42
@mindyourlifeguide Considering the version number, I believe for the time being the fastest solution for you is to define some command shortcuts (e.g `flameshot gui`). In the long run, we should see if the newer versions of Flameshot work as expected. For example if you are willing to install the AUR (maintained by us) or alternatively download AppImage of the [latest commit](https://github.com/flameshot-org/flameshot/runs/3612822395?check_suite_focus=true): https://we.tl/t-EO93wdP4ib

**Comment by Nils-Trinity** [comment] 2021-09-16 01:14
I had the same issue earlier and managed to fix it by deleting the "false" in the arguments. I see people above messing with delay settings but I didn't touch those
![image](https://user-images.githubusercontent.com/23055329/133532837-896feb76-926f-42bb-b022-2de7db5af624.png)
instead of 
![image](https://user-images.githubusercontent.com/23055329/133533490-a6ae97ae-a010-4537-b535-c5b0f085f71d.png)

I'm using KDE Plasma with flameshot 0.10.1.
The D-Bus Browser shows the only arguments are path, delay, and id, of which none are bool values.
![image](https://user-images.githubusercontent.com/23055329/133533266-fe837b44-78f7-40f7-ab67-29fa412d8383.png)
It seems that for whatever reason the arguments supplied in the file that was imported do not match the arguments that flameshot actually asks for, causing the screenshot to simply not work.

**Comment by mmahmoudian** [comment] 2021-09-16 07:26
@Nils-Trinity the `false` is a new addition and it should only be used for users with Flameshot >v0.10.1 or those who are using the latest AUR or compile from source. We have added a new flag to DBus recently and it is not in any released version yet but it is merged in the master branch (hence the AUR and compiling from source)

**Comment by mindyourlifeguide** [comment] 2021-09-17 07:03
@mmahmoudian The latest version (r1474.d1428889-1) still does not work via hotkeys. But if you check through a call, then it works. If via d-bus, it does not work.
Also, even if it was possible to call the screenshot window, copying to the clipboard via ctrl + c does not work

![image](https://user-images.githubusercontent.com/35348648/133739119-87ada80a-c07b-4e78-9e88-6ab8d7511261.png)

**Comment by mmahmoudian** [comment] 2021-10-01 13:03
@mindyourlifeguide I have no clue what's happening here. As far as I can understand, if pressing the call button work, it means the DBus call is working just fine and the rest is Plasma detecting the key binding and triggering the call. I cannot reproduce your issue on my KDE Plasma and it work for me.

**Comment by mindyourlifeguide** [comment] 2021-10-05 10:10
@mmahmoudian I completely removed flameshot, cleaned up the configs and tried to install it again.
The problem was solved by the method suggested by @Nils-Trinity .
I just removed the false argument and everything worked, both on the version from the distribution repositories and on yours with git.

**Comment by mmahmoudian** [comment] 2021-10-05 16:57
@mindyourlifeguide I believe if you compile from the git repo (or alternatively install from AUR), the `false` should be there as we have added a new feature to Flameshot which requires that input.

**Comment by Rastem88** [comment] 2022-01-17 01:51
@DifficultDerek You may need to install khotkeys. That should bring back the custom shortcuts menu.

**Comment by mmahmoudian** [comment] 2022-02-06 15:59
@Rastem88 I don't have khotkeys installed and yet mine works fine. I don't know what can be the cause for the issue of @DifficultDerek .

**Comment by mmahmoudian** [comment] 2022-02-07 07:12
In #2383 the documentation is updated to explain the situation.

Going through the whole thread once again, I realized that there are three separate issues discussed here:
- dbus issue (dbus was updated but the shortcuts didn't)
- bad config 
- lacking `khotkeys`

We now do not use dbus for those actions since version 11.0.0 and therefore shortcuts have been migrated to use the commands instead.

**Closed** 2022-02-07 07:12 UTC
Labels: Bug

**Comment by Cloud0310** [comment] 2025-09-02 16:57
This document needs update, since khotkeys **no longer** being **maintained**. And is unavailable to newer versions of KDE6.
Here's the [detailed information](https://github.com/KDE/khotkeys) about this problem.

**Comment by borgmanJeremy** [comment] 2025-09-02 22:59
We do not use that anymore. We use this: https://github.com/Skycoder42/QHotkey
