### ISSUE TITLE
undo/redo break the screenshot on a scaled screen

### ISSUE THREAD

**Issue by All3xJ** [flameshot-org/flameshot#1459] opened 2021-03-13 11:53 UTC
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2 

**Describe the bug**
When using a custom scaling factor in KDE display settings, the undo and redo actions do not work because they replace the modified area with a screen capture of the pixel value, not including the scaling factor.

**To Reproduce**
1)Enable scaling in KDE display settings
2)Do anything in a captured area
3)Press undo/redo

**Expected behavior**
 Flameshot should correctly undo/redo the action, replacing with a screengrab of what was under the modified area before.

**System Information**
Manjaro KDE 5.21.2 with 125% scaling factor.

![immagine](https://user-images.githubusercontent.com/20903913/111029118-296d7000-83fb-11eb-9f65-02230f592f6e.png)

**Comment by mmahmoudian** [comment] 2021-03-13 13:12
Isn't this a duplicate of #760 ?

**Comment by All3xJ** [comment] 2021-03-13 14:27
> Isn't this a duplicate of #760 ?

yes, I think it is

**Comment by mmahmoudian** [comment] 2021-03-13 14:32
I'm closing this one then.

**Closed by mmahmoudian** 2021-03-13 14:32 UTC
