### ISSUE TITLE
Feature: allow disabling the double left click shortcut to copy the image to the keyboard

### ISSUE THREAD

**Issue by ColsonThePCMechanic** [flameshot-org/flameshot#2574] opened 2022-05-01 20:07 UTC
### Feature Description

![image](https://user-images.githubusercontent.com/84006238/166162720-b2668c65-2f73-4807-8bcb-d92bde1a1dc8.png)

This shortcut is a **huge** annoyance when I try to add multiple annotations or text documents to an image, since my image gets randomly saved to the clipboard before it's complete.  Additionally, this shortcut essentially disables the ability to edit text, since you have to double click to edit text, and doing so saves the image.  I absolutely hate having to try and work around this shortcut that cannot be changed - I've often had to use other software such as Krita to annotate images solely because of this shortcut.  A way to modify or disable this shortcut would be extremely helpful and make Flameshot far easier to use.

**Comment by mmahmoudian** [comment] 2022-05-01 21:06
Duplicate of #2374 and #2461 which are already solved by #2432

**Closed** 2022-05-01 21:06 UTC
Labels: Enhancement
