### ISSUE TITLE
Capture an active window

### ISSUE THREAD

**Issue by d4n3sh** [flameshot-org/flameshot#395] opened 2018-11-05 22:38 UTC
Sorry but I could not find the option to capture an active window/app in help.  Is it possible?

**Comment by icf20** [comment] 2018-11-14 15:33
@d4n3sh afaik that option dont exist

**Comment by DanitiKain** [comment] 2018-12-20 15:39
This would be very useful to have is it a planned addition. Like right now I a copying a large amount of files and a screen is popping giving me errors because of some file names being to long for USB. So I need to a quick way to capture which files so I can go back in and edit them later. So like on windows I could hit alt print screen to get the active window.  Please add this feature :)

**Comment by daiaji** [comment] 2019-01-02 10:20
I also need this feature very much.😃

**Comment by azhi** [comment] 2019-01-16 00:55
Leaving a reference to related issues #5 and #334 - seems like this feature is already planned for next release.

**Comment by derek-shnosh** [comment] 2019-10-20 15:43
This is a great suggestion; or something similar to windows ShareX region selection (`ctrl+prnt`) that _best guess_ attempts to selection windows/regions as you mouse over them. But I'm sure that's a whole other challenge.

**Comment by AlexWayfer** [comment] 2020-04-13 12:05
Can this issue be closed as duplicate of #334?

**Comment by Vladimir-csp** [comment] 2020-04-13 15:17
yes, it seems

**Comment by mmahmoudian** [comment] 2021-04-08 15:17
I will close this as to me it seems like duplicate of  #334

**Closed by mmahmoudian** 2021-04-08 15:17 UTC
Labels: Duplicate, Enhancement
