### ISSUE TITLE
[Feature Request] drag shows the width height real time.

### ISSUE THREAD

**Issue by rodnt** [flameshot-org/flameshot#1174] opened 2020-11-29 22:22 UTC
**Is your feature request related to a problem?**

**Comment by mmahmoudian** [comment] 2020-11-30 07:38
@rodnt can you explain your idea a little bit more?

**Comment by rodnt** [comment] 2020-11-30 11:47
hello @mmahmoudian , my feature request is While you drag to take a screenshot the screenshot size is not shown as you drag the selected area, you have to stop and see the size through the tools. What I wanted to have is the possibility to see while I'm dragging to take a screenshot I see the width and size of the image. For example, in the macos screenshot, if I'm going to take a screenshot of a square, while I drag from edge to edge the size in pixels is shown in real time. In the flameshot currently I have to drag stop and check the image size using the tools. It would make it much easier for me to see the size while I'm dragging.

**Comment by borgmanJeremy** [comment] 2021-02-16 18:45
duplicate of #595. It is a good idea and would be a good improvement.

**Closed by borgmanJeremy** 2021-02-16 18:45 UTC
Labels: Enhancement
