### ISSUE TITLE
Amazon S3 bucket option for cloud upload

### ISSUE THREAD

**Issue by erlisdhima** [flameshot-org/flameshot#1734] opened 2021-07-21 12:13 UTC
It would be great if there was an option to change from imgur to a specific Amazon S3 bucket. 
Obviously this might take a lot of effort, but if possible, it would be nice to have it as an option.

And this would be useful for uploading annotated images to the cloud.

**Comment by mmahmoudian** [comment] 2021-07-22 10:10
This is duplicate of #178. 

But for your immediate use-case, you can checkout [one of the comments](https://github.com/flameshot-org/flameshot/issues/178#issuecomment-881959137) there in which @notmeta kindly provided a quick solution:

> I was looking for a solution and ended up adapting a ShareX script someone linked to make it work for an AWS S3 bucket
> https://github.com/notmeta/flameshot-s3-uploader
> 
> Hope this is useful to anyone

**Closed** 2021-07-22 10:10 UTC
Labels: Duplicate

**Comment by erlisdhima** [comment] 2021-07-22 11:14
Thanks a lot for your feedback and suggestion!

I'm working on implementing that script, but was thinking it would be ideal to have it as an option in the settings.
Especially if I want to suggest the tool to someone who's not very technical.

**Comment by mmahmoudian** [comment] 2021-07-22 11:21
@erlisdhima I definitely agree, but we are slightly understaffed as we have basically two main developers. We are working towards setting up  accounts in [BountySource](https://www.bountysource.com/) or [Rysolv](https://rysolv.com/) so that we can lift some of the pressure from main devs and also so that users can financially contribute or technically contribute and financially gain something.

**Comment by erlisdhima** [comment] 2021-07-22 11:26
@mmahmoudian , yes that makes total sense!

I'll be following the updates, and hopefully I'll be able to help as well in the future.

**Comment by danielkrajnik** [comment] 2023-06-16 20:52
sooooo... can we set a default application to Ctrl+O or not?
