### ISSUE TITLE
pressing enter to capture does not work with snap / flathub version 0.9 on KDE

### ISSUE THREAD

**Issue by atomtm** [flameshot-org/flameshot#1527] opened 2021-03-31 20:35 UTC
Using KDE Neon 5.21 (Ubuntu 20.04 based) , I can not capture the display by pressing Enter, nor any other key, by using the snap or flathub version 0.9 . Only thing I can do is press Esc.
Apt version 0.6 works.
Below is my system information:
![image](https://user-images.githubusercontent.com/6628454/113207798-bd538e80-9279-11eb-8dc3-6857f98ab04a.png)

**Comment by mmahmoudian** [comment] 2021-03-31 21:45
Duplicate of #1429.

You can use Ctrl+c to copy the screenshot to clipboard. Also since 0.9.0 you can define your own shortcut keys from the settings menu.

**Closed** 2021-03-31 21:45 UTC
Labels: Duplicate

**Comment by atomtm** [comment] 2021-04-01 06:31
Thank you very much ! 
This solved it.

**Comment by johnjacobkenny** [comment] 2021-08-08 04:50
I think the on screen documentation still says Press Enter. This could be the main confusion, and I had to go through several issues to identify why it was not working. Now I understand that a simple `Ctrl + C` will give me the full screen capture!

**Comment by mmahmoudian** [comment] 2021-08-09 08:28
Thanks @johnjacobkenny for reminding us of this. I created #1813 to address this once and for all
