### ISSUE TITLE
Auto-identify onscreen windows for soft snapping

### ISSUE THREAD

**Issue by spiritually-soup** [flameshot-org/flameshot#3704] opened 2024-08-29 07:41 UTC
### Feature Description

This is a feature in [Xnip](https://xnipapp.com/) that I really like, because it makes getting clean screenshots really easy!

Basically, on mousing over an onscreen window, it soft snaps the selection to the window boundaries (user then clicks to set the selection; there are options to select multiple areas to include + option to add shadow to the screenshot along the window edges).

<img width="1792" alt="autosnap" src="https://github.com/user-attachments/assets/052ad691-ff86-42cb-b054-5eb0719d6cc1">

**Comment by mmahmoudian** [comment] 2024-08-29 15:37
Thanks for the suggestion, but it is a duplicate of many other issues. We strongly suggest searching among open and closed issues before creating a new one.

**Closed by mmahmoudian** 2024-08-29 15:37 UTC
Labels: Enhancement
