### ISSUE TITLE
Flameshot stops after copying screenshot to clipboard

### ISSUE THREAD

**Issue by jamshaid120** [flameshot-org/flameshot#700] opened 2020-03-18 05:32 UTC
**Flameshot version**

Flameshot 0.6.0+git20190714-1(Debian)
Compiled with Qt 5.12.4

**Describe the bug**

I installed the app using sudo apt-get install flameshot. I started the app and when I took a screenshot and copied it to clipboard using Ctrl+C or usnig the copy button, the app stopped and I had to start it again. I tried installing it again after purge but it behaved the same way.
**To Reproduce**

**Expected behavior**

It should have copied the snapshot to clipboard
**System Information**

Ubuntu 19.10

**Comment by CiderAndWhisky** [comment] 2020-06-03 15:07
The same happens to me, too.

Output is: 
`QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
`

**Comment by borgmanJeremy** [comment] 2020-09-10 01:12
It's possible the config option "close after capture" was selected. Could you paste the contents of flameshot.ini?

**Comment by CiderAndWhisky** [comment] 2020-09-10 10:51
This was already several moths ago, but I think this was actually the option I changed to make it work again. Seems "Close after capture" is broken.

**Comment by borgmanJeremy** [comment] 2020-09-16 00:50
Duplicate of #557 . Will track progress on that issue.

**Closed by borgmanJeremy** 2020-09-16 00:50 UTC
