### ISSUE TITLE
Cannot capture the entire screen

### ISSUE THREAD

**Issue by thep0y** [flameshot-org/flameshot#1148] opened 2020-11-09 10:44 UTC
**Flameshot version**
0.8.5

**Describe the bug**
Cannot capture the entire screen.
![2020-11-09 18-41-18 的屏幕截图](https://user-images.githubusercontent.com/51874567/98531384-3ba79800-22bb-11eb-992a-c53ba3d085e8.png)

**To Reproduce**
![2020-11-09 18-42-34 的屏幕截图](https://user-images.githubusercontent.com/51874567/98531485-5da11a80-22bb-11eb-83c8-c1c1b370c2c6.png)
`flameshtop gui`

**Expected behavior**
The screenshot range is the entire screen.

**System Information**
Ubuntu 20.04.1
![2020-11-09 18-43-29 的屏幕截图](https://user-images.githubusercontent.com/51874567/98531576-7e697000-22bb-11eb-9597-aef88102bcc1.png)

**Comment by borgmanJeremy** [comment] 2020-11-09 18:08
This is a duplicate of the fractional scaling bug so I will close it. #748 #564

**Closed by borgmanJeremy** 2020-11-09 18:08 UTC
Labels: Bug, Linux, Wayland
