### ISSUE TITLE
Screen loses focus after a screenshot when using a tiling window manager (i3-gaps for me).

### ISSUE THREAD

**Issue by LiterallyJohnny** [flameshot-org/flameshot#1222] opened 2021-01-04 20:52 UTC
**Flameshot version**

Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**

After taking a screenshot, the screen loses focus when using a tiling window manager. I am using i3-gaps. After every screenshot, I have to press `Alt` + `Space` to focus back onto the window I was taking a screenshot of. It seems to be focusing on a floating window that isn't even there.

[Here is an example of what it looks like before a screenshot.](https://i.imgur.com/Rj73C0w.png) Normal, right?

[This is an example of what it looks like after a screenshot.](https://i.imgur.com/fUPxne4.png) Note the transparency and the blur. This is my compositor (Picom) rendering the blurred + transparent window as not focused. I am still able to interact with the blurred window, but it still isn't focused. If I hit `Alt` + `Space` (i3wm shortcut to toggle focus between focused and tiled windows), it focused back to the regular window, and the compositor's effects go away. It doesn't seem to happen if I press "Upload to Imgur" instead of "Copy to clipboard" and "Save file".

**To Reproduce**

1. Take screenshot using "Copy to clipboard" or "Save file"
2. Compositor's effects remain on the window.

**Expected behavior**

It should focus back on the original window instead of Flameshot's toolkit that isn't even open on that point.

**System Information**

Arch Linux (Rolling release)

**Comment by mmahmoudian** [comment] 2021-01-04 20:54
Possible duplicate of #784

**Comment by LiterallyJohnny** [comment] 2021-01-05 20:05
Yeah, it looks like that is the same issue I am having. Should I close this issue and take it over to #784?

**Closed** 2021-01-05 20:38 UTC
