### ISSUE TITLE
Can't take screenshots i3 Fedora 34

### ISSUE THREAD

**Issue by isaiahtaylor** [flameshot-org/flameshot#2062] opened 2021-11-11 18:47 UTC
**Flameshot version**
Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**
I can't take a screenshot with flameshot, either through `flameshot gui` or by clicking the tray icon. I am able to right click on the tray icon and open the configuration. I can also see a capture when I hit "open launcher" but I am not able to save the image that was captured. 

`flameshot gui` shows no output at all.

When I run `dbus monitor` and then click the icon, I get this:

```
signal time=1636656324.917145 sender=:1.76 -> destination=(null destination) serial=21 path=/; interface=org.flameshot.Flameshot; member=captureFailed
   uint32 0
```

## Other tech I'm using

I'm using i3 and launching it in .xinitrc with `exec dbus-launch --sh-syntax --exit-with-session i3`. I also tried `exec dbus-launch i3`.

I'm using polybar as well. 

**System Information**

```
cat /etc/os-release
NAME=Fedora
VERSION="34 (Workstation Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### Additional info

```
❯ inxi --width 80 --system --graphics
System:
  Host: fed-net Kernel: 5.2.9-200.fc30.x86_64 x86_64 bits: 64 
  Desktop: i3 4.19.1 Distro: Fedora release 34 (Thirty Four) 
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070] driver: nvidia v: 495.44 
  Display: x11 server: X.Org 1.20.11 driver: loaded: nvidia 
  note: n/a (using device driver) - try sudo/root unloaded: nvidia 
  resolution: 1920x1080~60Hz 
  OpenGL: renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 495.44 
```

```
❯ xrandr --listactivemonitors

Monitors: 1
 0: +DP-4 1920/598x1080/336+3840+0  DP-4
```

```
❯ lspci | grep -i 'vga\|3d\|2d'

01:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
```

**Comment by mmahmoudian** [comment] 2021-11-12 07:36
The `flameshot gui` does not produce output. We have had lots of bug fixes since the release of v0.10.1. Would you please try either compiling from source (https://flameshot.org/guide/installation/compilation/), or try installing our latest highlights build (https://flameshot.org/nightly/) and let us know if you still have that issue.

**Comment by xvitaly** [comment] 2021-11-12 13:09
Looks like duplicate of #1910.

**Comment by isaiahtaylor** [comment] 2021-11-12 15:44
@mmahmoudian I followed that nightly link and downloaded, but it looks like 0.10.1 is latest nightly? I already have that rpm installed. I can try installing from source later.

**Comment by isaiahtaylor** [comment] 2021-11-12 15:56
Built from source just now. Same result. Not sure if this is a dupe because I'm on X / i3, rather than wayland /Gnome.

**Comment by mmahmoudian** [comment] 2021-11-13 07:14
@isaiahtaylor 
> I followed that nightly link and downloaded, but it looks like 0.10.1

The nightly builds are having the save version as the latest release, but if you check the version you will see it also contains the git commit hash which makes them unique

> Built from source just now. Same result.

Ok, thanks for trying. Let's see what other devs can think about this issue.

**Comment by veracioux** [comment] 2021-11-13 17:23
@isaiahtaylor I also had (and to this day continue to have) issues with D-Bus on X11, i3wm. I'm on Arch Linux though.

If it's not too much of a hassle, can you try compiling from #2003 and see if the issue persists? This PR removes D-Bus to a large extent, although even then the clipboard and screenshot pinning may not work correctly for you.

**Comment by felubra** [comment] 2021-11-15 16:44
@veracioux I've built flameshot with your branch and was able to start it with `flameshot gui` on Fedora 35. But I've encountered a problem where the copy to clipboard feature no longer works: the copy notification never appers after I click to the copy to clipboard button. The following error was captured from dbus-monitor:

```
error time=1636994514.726608 sender=:1.184 -> destination=:1.191 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=8
   string "No such method 'attachScreenshotToClipboard' in any interface at object path '/' (signature 'ay')"
signal time=1636994514.728877 sender=org.freedesktop.DBus -> destination=:1.191 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.191"
signal time=1636994514.728895 sender=org.freedesktop.DBus -> destination=(null destination) serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.191"
   string ":1.191"
   string ""

```

**Comment by borgmanJeremy** [comment] 2022-05-03 13:30
Closing this as its stale and seems like an i3 integration issue not an issue with flameshot

**Closed by borgmanJeremy** 2022-05-03 13:30 UTC
Labels: Waiting For Info, Unconfirmed Bug
