### ISSUE TITLE
Please allow text rotation

### ISSUE THREAD

**Issue by elad2109** [flameshot-org/flameshot#2216] opened 2021-12-31 23:52 UTC
### Discussed in https://github.com/flameshot-org/flameshot/discussions/2200

<div type='discussions-op-text'>

<sup>Originally posted by **elad2109** December 29, 2021</sup>
![image](https://user-images.githubusercontent.com/1093841/147619599-bd9f9b2b-75b5-4911-98ec-bd67584ad44c.png)

Would be very nice to rotate the text (freehand) so it can aligned to existing image.</div>

**Comment by mmahmoudian** [comment] 2022-01-01 08:17
Duplicate of #1858

@elad2109 please search if your feature request or bug report is already discussed in another issue. Thanks.

**Closed** 2022-01-01 08:17 UTC
Labels: Duplicate, Enhancement
