### ISSUE TITLE
upload not working 

### ISSUE THREAD

**Issue by Cloud-Mak** [flameshot-org/flameshot#3595] opened 2024-05-05 03:49 UTC
### Flameshot Version

v0.12.1.0

### Installation Type

User repository (AUR)

### Operating System type and version

linux mint 21

### Description

`Error transferring https://api.imgur.com/3/image?title=&description=2024-05-05_09-14 - server replied: Too Many Requests`

The image upload to imgur is not working with above error.

### System Information

linux mint vanessa
laptop

**Comment by kayatf** [comment] 2024-05-06 07:22
I'm facing the same issues on random machines without any pattern.

**Comment by mmahmoudian** [comment] 2024-05-06 12:33
@Cloud-Mak @kayatf Duplicate of so many. The latest one being #3535

In short: This is not a bug. You are using our upload quota, and as the error suggests, the quota is full. The solution is to create your own Imgur account and use that. Some explanation in our documentation:

https://flameshot.org/docs/guide/imgur-help/#creating-your-own-custom-client-id

**Closed by mmahmoudian** 2024-05-06 12:33 UTC
Labels: Unconfirmed Bug
