### ISSUE TITLE
No panel icon when flameshot is set to run on boot

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#387] opened 2018-10-25 17:51 UTC
**Flameshot version**
0.6

**Describe the bug**
No panel icon when flameshot is set to run on boot, though flameshot does appear (albeit in a strange way) in the list of applications to run on start,  and flameshot does appear to be running and 

**To Reproduce**
1. Install from .deb, on Mint 19 Cinnamon.
2. Run flameshot and set to run on boot.
3. Reboot.

**Expected behavior**
The icon should appear in my panel (and I thought a window might open automatically too - though I would not want that).

**System Information**
Mint 19 Cinnamon.

**Screenshot**
In the screenshot, please note the following.
* There is no icon in the panel. (The tiny icon is for the program Rainlendar - this is another bug, either with Mint/Cinnamon or with Rainlendar.)
* A flameshot process is reported as running.
* Flameshot appears within the startup manager's list of applications. However, it's icon is extra large. That gigantism affects another application too (as one can half see in the screenshot) and may (or may not) be a Mint bug. Note also that Flameshot appears in the startup list with no delay field - unlike all other applications in the list.

![image](https://user-images.githubusercontent.com/9998846/47519917-a0cff280-d886-11e8-9931-6041c463518f.png)

Also: when I run Flameshot, after it has run/tried to run at boot, this happens: nothing appears in my panel; an icon for Flameshot appears in my dock very briefly - it disappears after a moment. Normal service resumes only after I kill all flameshot processes and then run the program again.

**Comment by PoLoMoTo** [comment] 2018-10-31 15:25
I have the same issue on Arch with Gnome with flameshot from the official repos.  Curiously though it only happens on my laptop, my desktop appear to work perfectly.

**Comment by CottonEaster** [comment] 2018-10-31 15:33
@PoLoMoTo 

Thanks. So the desktop has Arch with Gnome, just as the desktop does? If so, are both computers fully updated, on the same kernel and on the same version of flameshot? If yes, then perhaps screen resolution or size has something to do with the matter.

**Comment by PoLoMoTo** [comment] 2018-10-31 18:00
Nope it has the same issue apparently.  I swear it was working fine the other day.  I guess not.  Sorry for the confusion, it does not work on either.  And yes they are both running Arch with Gnome, probably should've clarified.

**Comment by christianmtr** [comment] 2018-11-22 22:10
I just comment my case in other similar issue.
https://github.com/lupoDharkael/flameshot/issues/403#issuecomment-441126951

**Comment by harkor** [comment] 2018-12-13 07:58
I have the same problem on my desktop with Arch, I can make capture with "flameshot gui".

I found an half solution, execute "flameshot config" and uncheck/check "Show tray icon" and the icon appear.

**Comment by CottonEaster** [comment] 2018-12-13 09:47
The problem could be with Mint (see [this bug report on the Mint tracker](https://github.com/linuxmint/Cinnamon/issues/2846)), and it seems that the new beta of Mint (Mint 19.1 Cinnamon beta) does _not_ have the problem.

**Comment by harkor** [comment] 2018-12-13 09:59
I don't think so, I'm on the basic Arch Linux and I have the problem too.

**Comment by CottonEaster** [comment] 2018-12-13 10:02
Ah well the problem could be with the _Cinnamon_ part of Mint Cinnamon - what DE to you have?

**Comment by harkor** [comment] 2018-12-13 10:58
Gnome 3.30.2

**Comment by yipinghuang1991** [comment] 2019-01-04 13:16
I can confirm this.
Latest Arch, Openbox, Tint2.
Everything as harkor described.

**Comment by PoLoMoTo** [comment] 2019-01-20 05:04
> It's a shame this problem persists. It makes Flameshot unusable for me - and for the others in the thread, I imagine.

It is really disappointing, especially since we don't seem to be getting any dev response or finding a workaround.  However the "flameshot gui" command does still work so for now I just bound that to a keyboard shortcut through Gnome's settings and that works well. (At least until I forget what the shortcut was...)

**Comment by morganchenjp** [comment] 2019-11-22 10:19
Still same issue on Mint 19.1 with kernel 4.15.0-47-generic

Keyboard shortcut is a good alternative :)

**Comment by jrial** [comment] 2019-11-22 10:41
19.2 here, and it looks like it's resolved for me.

**Comment by morganchenjp** [comment] 2019-11-22 11:09
Another laptop, Linuxmint 19.2 with 
Flameshot 0.5.1-1(Debian)
Compiled with QT 5.9.4

Still same issue :(

**Comment by EzraT** [comment] 2020-01-06 10:32
This issue is still present on Linux Mint 19.3 Cinnamon

**Comment by crlsgms** [comment] 2020-01-28 23:22
Im having the same issue with debian 10 cinnamon

added to startup apps, with 100s delay but still wont launch, only when calling the shortcut on the menus.

**Comment by wiserweb** [comment] 2020-02-06 04:21
Issue occurs with Ubuntu with Cinnamon Desktop environment

**Comment by johnzantey** [comment] 2020-03-19 11:34
Same on completely updated Manjaro i3 19.0.2 (Kyria), kernel 5.4.24-1
Obtained flameshot_0.6.0_x86_64.AppImage from git
Checked to see if qt5-svg is installed, and it is

I installed on VM first, which worked and qualified it becoming an app i install, before installing on bare metal
On actual bare metal, I too can't get the icons coming up when taking a screenshot (no resolution as yet)

**Comment by ricardoseriani** [comment] 2020-04-13 12:59
Same here on Ubuntu 18.04.4 with i3-wm 4.17.1-1

**Comment by codiflow** [comment] 2020-08-14 07:57
Same here on Manjaro Linux since about one month, Kernel 5.7.9-1, XFCE 4.14

After closing it and starting `flameshot config` the icon reappears in the tray.

**Comment by CrustyCurmudgeon** [comment] 2020-12-05 16:55
Similar issue with KDE Neon 20.04 focal; (KDE 5.76.0 / Plasma 5.20.4). Slight difference is that flameshot tray icon loads on boot, but then disappears after using the app; In fact, the app literally  terminates and is no longer running. 

Also attempted to use "flameshot-shortcuts-kde" script to assign custom shortcuts to KDE settings. All went as expected and Spectacle shortcuts disabled, but no shortcuts would initiate flameshot, even after reboot and  even  when the flameshot icon was clearly visible.

**Comment by raphapaulino** [comment] 2021-01-05 22:49
> Issue occurs with Ubuntu with Cinnamon Desktop environment
> 
> For some reason the Bionic package manager is not installing the latest 0.6, instead it install 0.5.1.
> 
> Resolved by manually downloading and installing the latest release from [Releases page](https://github.com/lupoDharkael/flameshot/releases).

The @wiserweb  solution has solved the problem here. But I uninstalled the 0.6 version and install v0.8.5

**Comment by adrianvg** [comment] 2021-05-07 06:43
Ran into this problem on Kubuntu 20.04.2 LTS.
Tried some different themes and icon sets to see if it'd show up, but unfortunately no.
Flameshot is usable, but difficult to find as there's no icon in the system tray. See pic!
The red arrow points to where the invisible Flameshot icon is.

![2021-05-07_08-39](https://user-images.githubusercontent.com/15629475/117408426-3648a480-af10-11eb-931b-38c37626620d.png)

$ flameshot --version
Flameshot v0.9.0
Compiled with Qt 5.12.3

**Comment by mmahmoudian** [comment] 2021-05-07 16:45
@adrianvg I think your issue has nothing to do with this issue, but rather #1554 & #1514

**Comment by adrianvg** [comment] 2021-09-14 08:12
> @adrianvg I think your issue has nothing to do with this issue, but rather #1554 & #1514

Will look into those, thanks.

**Comment by adrianvg** [comment] 2021-09-16 17:12
@mmahmoudian 
I seem to somehow have managed to install both the snap and "normal" packaged version of flameshot on my Kubuntu.
I might've forgotten at some point that I already had the snap installed while trying to figure out the icon problem.
After uninstalling both I installed the packaged version from the regular Ubuntu repos to try out, and behold, the icon shows!

Thanks for your assistance! 
All is well. :-)

**Closed** 2022-02-17 03:35 UTC
