### ISSUE TITLE
Problems with the display 3440x1440 when scaling the interface 125%

### ISSUE THREAD

**Issue by chobanyukivan** [flameshot-org/flameshot#2141] opened 2021-12-03 11:23 UTC
### Flameshot Version

0.6.0+git20191001-2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 20.04

### Description

when using a monitor with a resolution of 3440x1440 and scaling the interface of 125%, when I try to take a screenshot, the screen goes blank, then the image appears again, and this continues until you cancel the attempt to take a screenshot. Sometimes, when trying to take a screenshot, there are no problems with screen flickering, but the frame of the screenshot is not the whole screen. When using 100% scaling, everything works as it should.

### Steps to reproduce

1. Display settings - Scaling - set 125%
2. Tray Icon - Take Snapshot

### Screenshots or screen recordings

![Снимок экрана от 2021-12-03 14-02-25](https://user-images.githubusercontent.com/32276334/144592379-eb7d74b9-f497-4643-8bf3-c59e729014ca.png)
Screenshot when the monitor is blank, it looks like an attempt is made to change the screen resolution
![Снимок экрана от 2021-12-03 13-58-40](https://user-images.githubusercontent.com/32276334/144594021-7cc7b488-20be-4dde-89e1-02de01b32d42.png)

### System Information

1. Ubuntu 20.04.3 LTS, 64bit
2. Monitor:  Xiaomi Curved Display 34, 3440x1440, scaling 125%
3. GNOME 3.36.8, X11
![2021-12-03_14-17](https://user-images.githubusercontent.com/32276334/144593944-23882fa4-7698-4b3e-9710-6b06566e51d0.png)
![2021-12-03_14-14_1](https://user-images.githubusercontent.com/32276334/144594208-a896c88d-fd73-4830-8928-2c28ea390399.png)

**Comment by chobanyukivan** [comment] 2021-12-03 11:43
Update: checked for updates and installed the latest version 0.10.2. The first time I started and grabbed a screenshot, the frame covered the entire screen and it looked like it should. When re-capturing a screenshot, the monitor flickers. If I uncapture and recapture, the frame does not cover the entire screen. But if I close flameshot through the tray, and restart the process, the screen capture occurs correctly

**Comment by mmahmoudian** [comment] 2021-12-03 12:21
Isn't this duplicate of #1610 ?

**Comment by chobanyukivan** [comment] 2021-12-03 12:32
> Isn't this duplicate of #1610 ?

yes, the problem is the same, thanks

**Comment by mmahmoudian** [comment] 2021-12-03 12:38
Then I'll mark this as duplicated and close it in favor of #1610

**Closed by mmahmoudian** 2021-12-03 12:38 UTC
Labels: Unconfirmed Bug
