### ISSUE TITLE
  Every time I upload a screenshot with "Copy URL after Upload" enabled I can't do anything on my desktop until it's uploaded

### ISSUE THREAD

**Issue by Toadfield** [flameshot-org/flameshot#1155] opened 2020-11-13 22:15 UTC
**Flameshot version**
0.8.5-1

**Describe the bug**
like in title.

**To Reproduce**
I upload a screenshot and I can't do anything on my desktop like opening shortcuts and stuff like that.

**Expected behavior**
That it just normally uploads and being copied.

**System Information**
Manjaro kde with kernel version 5.9.3-1

**Comment by borgmanJeremy** [comment] 2020-11-14 20:36
Duplicate of #1128  (We solve the issue just need to backport it).

**Closed by borgmanJeremy** 2020-11-14 20:36 UTC

**Comment by Toadfield** [comment] 2020-11-14 21:31
ok
