### ISSUE TITLE
Gnome 42 - Sharing the screenshot causes it to zoom in

### ISSUE THREAD

**Issue by rayzorben** [flameshot-org/flameshot#2614] opened 2022-05-20 16:14 UTC
### Flameshot Version

v11.0.0

### Installation Type

User repository (AUR)

### Operating System type and version

Arch

### Description

In Gnome 42, when using Flameshot, I have to click 'Share' to share the screenshot with Flameshot. Annoying, but I can get past it.

But the issue is that when it is shared, it zooms in and craps about 1/4 of the right and bottom of the screen. I imagine this has to do with my using fractional scaling/display scaling in Wayland?

### Steps to reproduce

1. gnome 42
2. set fractional scaling 125%
3. take screenshot
4. you lose about 1/4 of the screen

### System Information

Arch, 5.17.9.
Single laptop window, 2560x1440, fractional scaling
wayland

**Comment by borgmanJeremy** [comment] 2022-05-21 01:10
Duplicate of #564

**Closed by borgmanJeremy** 2022-05-21 01:10 UTC
Labels: Unconfirmed Bug
