### ISSUE TITLE
Editing text in CLI mode aborts screenshot

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#2641] opened 2022-06-02 18:36 UTC
### Flameshot Version

v11.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux

### Description

If flameshot is started with the cli, click another tool while editing text aborts the screenshot

### Steps to reproduce

1. Run flameshot gui
1. Add text
1. Click another tool

Note: This does not happen if started from the tray. 

### Screenshots or screen recordings

![Peek 2022-06-02 13-35](https://user-images.githubusercontent.com/46930769/171701953-0152f6f7-8ac6-4a5a-92d0-e3590a695437.gif)

### System Information

Tested on Arch, KDE, X11

**Comment by borgmanJeremy** [comment] 2022-06-03 01:02
This is the commit that introduced the bug: 883e55c52db375a77b1343311f0f39a6a78cc600

@veracioux do you have time to dig into this? If not I can.

**Comment by borgmanJeremy** [comment] 2022-06-03 01:17
This is the line that causes the issue. I don't want to add it back in without understanding why it was removed in the first place:

![image](https://user-images.githubusercontent.com/46930769/171768418-1ff82c8e-d02e-4ef6-8408-d3af03e749b6.png)

**Comment by mmahmoudian** [comment] 2022-06-03 06:59
Isn't this the duplicate of #2528 which was fixed in #2369?

**Comment by borgmanJeremy** [comment] 2022-06-03 11:32
Nope multiple bugs apparently.

**Comment by veracioux** [comment] 2022-06-03 13:34
@borgmanJeremy I removed the line because `flameshot launcher` when launched via CLI would not quit after the launcher dialog was closed. And also `flameshot gui` would not close after the upload dialog was closed.

Using the exact same steps you used, I can't reproduce this on the current master (65e3a013605c9aacaecfaffc65423311d41b2a7f)
Tested on Arch, X11, both in i3wm and KDE

But I can reproduce it on v11.0.0.

Can you specify the exact commit you used?

**Comment by borgmanJeremy** [comment] 2022-06-03 14:02
Nevermind, I can do it on master too. However, Must re-edit the text window. See this gif and process:

1. Run flameshot gui
2. Add text
3. Exit text tool
4. Click existing text and start editing
5. Click another tool while the text edit is active. 

I stumbled on this when working on centering the text box

![Peek 2022-06-02 13-35](https://user-images.githubusercontent.com/46930769/171869445-b1f37a5d-da76-4788-97c7-8dcdec3ea82c.gif)

**Comment by mmahmoudian** [comment] 2022-06-03 14:36
> 3. Click existing text and start editing
> 4.Click another tool while the text edit is active.

Based on the screen capture, it seems when you double click, the text tool is not "selected" although you can modify the text. Perhaps the glitch happens then and there

**Comment by veracioux** [comment] 2022-06-03 15:54
I'll look into it.

**Comment by mmahmoudian** [comment] 2022-06-03 17:16
So when the sidebar is open, the first time you edit, it will not change the text, it write "over" it and when you click outside it will not keep the new text, but the second time it will change it. This is interesting

https://user-images.githubusercontent.com/390889/171913694-dbe0aa7e-1ccd-4dc3-b7ce-9af37a53cf81.mp4

**Comment by borgmanJeremy** [comment] 2022-06-03 17:27
> #2645 Seems to fix the issue across the board. The sole cause seems to be this line:
> 
> https://github.com/flameshot-org/flameshot/blob/65e3a013605c9aacaecfaffc65423311d41b2a7f/src/tools/text/texttool.cpp#L122
> 
> For some reason, Qt thinks this is the last window. I have no clue why. Since the `close()` call is followed by a `delete`, it can be replaced with `hide()` with no loss of functionality, so that's what I did and it fixed the issue for me. I went ahead and did the same to all similar calls, so we avoid future surprises.
> 
> An interesting thing is that if the utility panel is open whilst performing [the steps](https://github.com/flameshot-org/flameshot/issues/2641#issuecomment-1145997200), the issue does not manifest.

Awesome thanks. Yeah this was a strange one.

**Closed** 2022-06-03 17:27 UTC
Labels: Unconfirmed Bug
