### ISSUE TITLE
Wrong file extension when saving on MacOS

### ISSUE THREAD

**Issue by SvnH1s** [flameshot-org/flameshot#2544] opened 2022-04-13 06:38 UTC
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 21.4.0
osx: 12.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

macOS 12.3.1

### Description

There is a bug when choosing a file extension. The first two entries work fine (BMP and HEIC) but after that the previous wrong one is chosen. If I select JP2 I get HEIC, if I select PNG I get JPG, if I select TIF I get PNG and so forth. 

### System Information

1. macOS 12.3.1
2. Lenovo L28u-30 with 2560x1440

**Comment by mmahmoudian** [comment] 2022-04-13 06:55
Duplicate of:

- #2270
- #2361

**Closed** 2022-04-13 06:55 UTC
Labels: Bug, Duplicate
