### ISSUE TITLE
print screen shortcut don't work on windows 11 - and cannot be configured to other keystroke.

### ISSUE THREAD

**Issue by zurcacielos** [flameshot-org/flameshot#3554] opened 2024-04-02 08:29 UTC
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 6.2.9200
windows: 8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

windows 11

### Description

print screen shortcut don't work on windows 11 - and cannot be configured to other keystroke.
The printscreen shortcut continues to get assigned to windows regular screenshot tool.
And it cannot be configured to other key stroke, the shortcut for print screen is FIXED.

### Steps to reproduce

1. run flameshot
2. press print screen
3. windows regular print screen appears. 
4. flamshot should appear.

### System Information

windows 11
surface pro 9

**Comment by gamberoillecito** [comment] 2024-04-02 20:58
I'm having the exact same issue, it worked at first but after a couple of minutes it stopped working

**Comment by mmahmoudian** [comment] 2024-04-02 21:24
@zurcacielos @gamberoillecito 
>  it worked at first but after a couple of minutes it stopped working

Please check our documentation. the answer is usually there: https://flameshot.org/docs/guide/windows-help/

Also duplicate of:
#3506
#3325 
#3259
#3234
#3147
#2887
#2261 
#1961 
#1551   <-- main thread

>  and cannot be configured to other keystroke.

No at the current state of Flameshot, this is not possible in Windows. 
Duplicate of:
#3485 
#3292 
#3214 
#2925
#2493 
#2167
#1341  <-- main thread
#1861 
#1054 


Please always search among open and closed issued before creating a new one. This would primarily to save your own time.

**Closed by mmahmoudian** 2024-04-02 21:24 UTC
Labels: Unconfirmed Bug

**Comment by gamberoillecito** [comment] 2024-04-02 21:32
@mmahmoudian thank you for your help, unfortunately I had already checked the documentation and tried the proposed solutions but none of them worked for me. I understand this has to do with Microsoft being Microsoft but being able to change the default shortcut instead of Print Screen could easily solve the issue. The fact that the CLI doesn't work in windows also prevents the use of alternatives such as autohotkey (mapping any key combination to PrintScreen doesn't solve the issue)

**Comment by mmahmoudian** [comment] 2024-04-02 22:35
@gamberoillecito true, the lack of Windows CLI is an issue, but there is an open feature request about it. Please give it an upvote.
