### ISSUE TITLE
unable to save file to any home path [snap]

### ISSUE THREAD

**Issue by alculete** [flameshot-org/flameshot#1494] opened 2021-03-19 07:21 UTC
**Flameshot version**
v0.9.0.rc2+git33.856e08a

**Describe the bug**
When  trying to save a picture to a specific path on the home directory it saves on an unknown temporary path

**To Reproduce**

1. Take a snapshot 
2. click to save
3. the path is strange and cannot be changed, since of you change it will save on this strange path instead
![flameshot](https://user-images.githubusercontent.com/2129497/111744827-7dad9f80-8894-11eb-8f20-750f7b36ca69.png)

**Expected behavior**
Save on any available path (Desktop, Documents, Pictures, etc)

**System Information**
OS: Ubuntu 20.04.2 LTS x86_64 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-4930MX (8) @ 3.900GHz 
GPU: Intel 4th Gen Core Processor 
GPU: NVIDIA Quadro K4100M 
Memory: 11170MiB / 15815MiB

**Comment by mmahmoudian** [comment] 2021-03-19 08:21
Can you post your `~/.config/flameshot/flameshot.ini` here.

**Comment by alculete** [comment] 2021-03-19 16:58
Can't find this file. seems to not be available. I'm running snap version

**Comment by borgmanJeremy** [comment] 2021-03-20 01:51
This is duplicate of #1144 and we are waiting for upstream to fix a QT issue.

**Closed by borgmanJeremy** 2021-03-20 01:51 UTC
Labels: Waiting For Info
