### ISSUE TITLE
Allow to configure/customize global keys

### ISSUE THREAD

**Issue by MagnoAlberto** [flameshot-org/flameshot#3734] opened 2024-09-21 13:58 UTC
### Feature Description

I have a keyboard that does not have a Print-Screen key, and in other applications I can get around this limitation by configuring/custom global keys, such as the Print-Screen key itself, telling the application that it should use another key, such as WIN + ALT + F12. For some time now, I have been using MS PowerToys to remap the keys, however, even using the remap, I cannot get Flameshot to "detect" this remap. If Flameshot allowed me to change these keys, this would be very useful, because currently, every time I have to click on the Flameshot icon, located in the system tray, to be able to take a printscreen.

![Untitled](https://github.com/user-attachments/assets/7f8b78ef-a074-41e2-8cac-5159807ed8e1)

**Comment by mmahmoudian** [comment] 2024-09-26 08:13
Thanks for the feature request, but this is duplicate of #1341 . Please consider searching among open and closed issues before creating a new one. Thanks.

**Closed by mmahmoudian** 2024-09-26 08:13 UTC
Labels: Enhancement
