### ISSUE TITLE
Refresh regularly to detect new monitors while app is already running

### ISSUE THREAD

**Issue by Semnodime** [flameshot-org/flameshot#2128] opened 2021-11-28 18:17 UTC
### Flameshot Version

Flameshot V0.10.1

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10 x64bit

### Description

When connecting a new monitor after flameshot has already been launched, the new monitor won't be captured when issuing a screenshot via `print`-key. Instead the application has to be restarted to properly detect the new monitor.

### Steps to reproduce

1. Run flameshot
2. Connect second monitor
3. Take a screenshot via `print`-key
4. See error (missing screen capture for second monitor)

### System Information

Windows 10 x64bit

**Comment by Eveldee** [comment] 2021-12-04 10:26
Same issue on Windows 10 x64 using flameshot V0.10.2.

If I power on my second screen after Windows (and so flameshot) has already started, it won't be recognized, I need to restart flamshot to take a screen on it

**Comment by dbolton** [comment] 2022-05-20 19:30
Thank you for narrowing down this bug and explaining why Flameshot stopped working for me on the second monitor. 

Workaround: Right click on the Flameshot quick launch icon, choose Quit, then reopen it via the start menu.

**Comment by dbolton** [comment] 2022-05-20 19:31
duplicate of this issue: https://github.com/flameshot-org/flameshot/issues/1506

**Comment by mmahmoudian** [comment] 2022-05-21 09:38
@dbolton you are right, it is the same issue but pitched from the other angle.

**Closed by mmahmoudian** 2022-05-21 09:38 UTC
Labels: Unconfirmed Bug
