### ISSUE TITLE
Suddenly not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by Dylan-86** [flameshot-org/flameshot#2581] opened 2022-05-03 18:38 UTC
Upgraded yesterday to Ubuntu 22.04

Flameshot does not work at all.
The tray icon is there, I can click on it and the menu works.
If I click on Take screenshot (or if I type "`flameshot gui`") in terminal, nothing happens.

Terminal responds with:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

If I run:
`QT_QPA_PLATFORM=wayland flameshot gui`
I get
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

**Comment by mmahmoudian** [comment] 2022-05-03 18:58
It seems like a duplicate of #2199

Also please for the next time try to use the bug report form. Thank you.

I close this as you are most probably lack some packages on your end (without the information we asked for in the bug report form we cannot help you). Try installing the packages that was discussed in #2199 (mainly `xdg-desktop-portal-gnome`)

**Closed by mmahmoudian** 2022-05-03 18:58 UTC
