### ISSUE TITLE
The icon of the application doesn't display correctly on the Gnome Software Center.

### ISSUE THREAD

**Issue by vladspirin** [flameshot-org/flameshot#1200] opened 2020-12-25 13:11 UTC
**Flameshot version**

Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**

The icon of the application doesn't display correctly on the Gnome Software Center.
![2020-12-25_14-42](https://user-images.githubusercontent.com/24988700/103135376-93aa2a80-46c0-11eb-8f64-ae3ae2a65b64.png)
![2020-12-25_14-42_1](https://user-images.githubusercontent.com/24988700/103135380-973db180-46c0-11eb-9722-74b37d89494b.png)

**To Reproduce**

1. Search the Flameshot app in the Gnome Software Center 
2. Install the application via source fedoraproject.org
3. You have a view of the problem with the icon
4. Click on the 'Installed' at the top of the Software Center
5. Scroll down and search the Flameshot app
6. You have a view of the problem with the icon

**Expected behavior**

After installation via source fedoraproject.org in the Gnome Software Center, I have a view of the correctly displayed Flameshot app icon in all parts of the Gnome Software Center. 

**System Information**

_System_:
  Host: fedora Kernel: 5.9.15-200.fc33.x86_64 x86_64 bits: 64 
  Desktop: GNOME 3.38.2 Distro: Fedora release 33 (Thirty Three) 
_Machine_:
  Type: Desktop Mobo: MSI model: H170M PRO-VDH (MS-7982)
_CPU_:
  Info: Quad Core model: Intel Core i7-6700 bits: 64 type: MT MCP 
  L2 cache: 8192 KiB 
  Speed: 800 MHz min/max: 800/4000 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 
_Graphics_:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nouveau v: kernel 
  Display: x11 server: Fedora Project X.org 1.20.10 driver: modesetting 
  OpenGL: renderer: NV136 v: 4.3 Mesa 20.2.6
_Monitors_: 2
 0: +*HDMI-2 1920/477x1080/268+0+0  HDMI-2
 1: +HDMI-1 1920/477x1080/268+1920+0  HDMI-1

Gnome Software: 3.38.0

**Comment by vladspirin** [comment] 2020-12-27 11:05
After the installation of the new system, this bug was reproduced.

**Comment by ZetaoYang** [comment] 2020-12-28 08:58
@vladspirin Did you notice here? 
![image](https://user-images.githubusercontent.com/10769951/103202646-f05e4d00-492d-11eb-82f6-d0b91d31a923.png)
The version and source are unknown.

**Comment by vladspirin** [comment] 2020-12-28 11:16
@ZetaoYang Of course, I noticed it. I'm surprised by this application behavior and that's why I raised the issue.

**Comment by mmahmoudian** [comment] 2020-12-28 20:34
It is a very good point, but to me it seems to me that the issue is with the Fedora repo as we don't upload our rpm builds to their repository. Perhaps the Fedora repository maintainers should be contacted. The "Unknown" parts doesn't help the situation either as we don't know who is the maintainer. Is there any way to figure out where we should contact?

**Comment by borgmanJeremy** [comment] 2020-12-29 01:16
I can track down the Fedora maintainer if we can't figure it out.

**Comment by vladspirin** [comment] 2020-12-31 05:32
Some observations.
At first, when you search the Flameshot app in the Gnome Software you have a view of the icon with all necessary data: 

![02](https://user-images.githubusercontent.com/24988700/103395793-a0070b00-4b38-11eb-964c-f49d8b55d9bc.png)

The next situation (after installation) is more interesting. As I wrote in the steps 'To Reproduce' when you click on the 'Installed' on the top and find the Flameshot app, you have a view of an incorrect icon. 
If click on this app in this part of Gnome Software, the next behavior looks the same as in the first screenshot in the issue.

**Comment by borgmanJeremy** [comment] 2021-12-10 03:03
Im going to close this because its really a downstream packaging bug not handled by us.

**Closed by borgmanJeremy** 2021-12-10 03:03 UTC
Labels: Needs Investigation, Linux
