### ISSUE TITLE
Flameshot snap doesn't start on Kubuntu

### ISSUE THREAD

**Issue by mystiquewolf** [flameshot-org/flameshot#1656] opened 2021-06-06 14:42 UTC
**Flameshot version**

v0.9.0.rc2+git33.856e08a
**Describe the bug**

Flameshot doesn't start after installing it. I try to launch it from KDE's Application Launcher.
I have also edited/added the following lines to the  `/var/lib/snapd/desktop/applications/flameshot_flameshot.desktop` file but it still doesn't start:
```
X-DBUS-StartupType=Unique
X-DBUS-ServiceName=org.flameshot.Flameshot
X-KDE-DBUS-Restricted-Interfaces=org.kde.kwin.Screenshot
```
**System Information**

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.90
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-18-lowlatency (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7,6 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by javierin** [comment] 2021-07-09 07:23
I am running a kubuntu 21.04 set up and it is working just fine. Have you tried running flameshot config and see if that makes a difference?

**Comment by mystiquewolf** [comment] 2021-07-09 07:33
@javierin Are you running in a Wayland session?
`flameshot config` doesn't start anything. Just `flameshot` on the other way gives the following error:
```
Failed to create wl_display (No such file or directory)
Segmentation fault (core dumped)
```

**Comment by NelsonJeppesen** [comment] 2021-07-21 13:04
I just ran into this issue with NixOS unstable

```
% flameshot
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
zsh: segmentation fault (core dumped)  flameshot
```

worked for a very long time then just stopped. I ran `flameshot config` and the window would appear for a half second then close

I then moved my config folder 
```
mv ~/.config/flameshot/ ~/.config/flameshot2
```

and now it works 🤷🏼‍♂️ I didn't change any settings - so not sure what's up

```
% flameshot -v
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

**Comment by NelsonJeppesen** [comment] 2021-07-21 13:09
Some quick digging, on my machine the setting

```
[General]
disabledTrayIcon=true
```

causes the segfault

**Comment by mmahmoudian** [comment] 2021-07-22 09:52
@NelsonJeppesen The segfault has been constantly reported by users for when `disabledTrayIcon` is set to `false`. I will create a new bug report for this.

**Comment by mystiquewolf** [comment] 2021-07-22 12:56
I have no idea what this issue with `disabledTrayIcon` is.
All i know is that i'm with 0.10.0, i did not have the file `/home/username/.config/flameshot/flameshot.ini` so i created it with the following content:
```
[General]
disabledTrayIcon=false
```

This still produced:
```
Failed to create wl_display (No such file or directory)
Segmentation fault (core dumped)
```

Then i tried:
```
[General]
disabledTrayIcon=true
```

Still the same error:
```
Failed to create wl_display (No such file or directory)
Segmentation fault (core dumped)
```
So it seems that this bug and your @NelsonJeppesen one are different ones. Furthermore i believe @NelsonJeppesen is using gnome, while the issue is for Kubuntu with KDE.

Maintainers, if you have some idea where this dump is dumped, mention it. Maybe i could run gdb on it if you have/can provide some debug symbols. Usually Ubuntu has debug symbols with the apt package name suffixed with -dbgsym, no idea how it's done for snap packages. Also i can't find a crash file in /var/crash.

**Comment by mystiquewolf** [comment] 2021-07-22 13:07
I don't have line 49 from [HERE](https://github.com/flameshot-org/flameshot/pull/1603/files#diff-e275014958777cacd01ad35395f0fb254e52fb296262e91ee88ac74de2f581cbL49-R49) inside `/var/lib/snapd/desktop/applications/flameshot_flameshot.desktop`??

**Comment by mystiquewolf** [comment] 2021-07-22 13:15
...And adding the above line to the above file still doesn't fix it.
Running `gtk-launch flameshot_flameshot` gives `Failed to create wl_display (No such file or directory)` and the command stays active indefinitely without further output.

**Comment by mmahmoudian** [comment] 2021-07-22 14:43
@mystiquewolf When you do all these changes to the files, do you make sure to kill Flameshot processes beforehand? Especially when dealing with `disabledTrayIcon`.

**Comment by mystiquewolf** [comment] 2021-07-22 16:19
Тhere are no flameshot processes to begin with.

**Comment by mystiquewolf** [comment] 2021-08-11 14:14
Does this bug have to be reproduced by maintainers before its status can be set to "confirmed"?

**Comment by mmahmoudian** [comment] 2021-08-11 14:29
@mystiquewolf it should be reproduced or reported by at least one other user other than the OP.

**Comment by borgmanJeremy** [comment] 2022-01-15 17:03
Can you try the snap that was released yesterday?

**Comment by mystiquewolf** [comment] 2022-01-15 21:25
Since then i've switched to Arch. Flameshot icon shows when i open it, but trying to take a screenshot doesn't work.

**Comment by mmahmoudian** [comment] 2022-01-15 21:26
@mystiquewolf how have you installed it?

**Comment by mystiquewolf** [comment] 2022-01-15 21:29
See the update above, i edited the comment.


> @mystiquewolf how have you installed it?

sudo snap install flameshot

**Comment by borgmanJeremy** [comment] 2022-01-15 21:30
I did not test the snap on KDE + wayland, I did all the snap testing on Gnome so its probable there is an issue

**Comment by mystiquewolf** [comment] 2022-01-15 21:32
And i haven't tested from the repos...

**Comment by mmahmoudian** [comment] 2022-07-18 13:55
I wonder if this issue still exists. @mystiquewolf are you still facing this issue in version 12.1.0 ?

**Comment by mystiquewolf** [comment] 2022-07-18 15:47
Capturing screenshots with flameshot seems to work now.

**Comment by mystiquewolf** [comment] 2022-07-18 19:04
The keyboard buttons don't work. Also, the images seem to be saved blurry (at least the fonts in the screenshots look blurry). I'm using display scaling of 125% on KDE, but i guess these two are a different issue.

I use KDE's default Spectacle since some time and I'm happy with it.

**Comment by mmahmoudian** [comment] 2022-07-19 06:26
> The keyboard buttons don't work

What do you mean? The keyboard shortcuts for starting flameshot (e.g printscreen), or thr keybindings inside of the application (e.g Ctlr+s to save)??

> the images seem to be saved blurry (at least the fonts in the screenshots look blurry)

Are you saving as JPG or PNG?

**Comment by mystiquewolf** [comment] 2022-07-19 07:49
> What do you mean? The keyboard shortcuts for starting flameshot (e.g printscreen), or thr keybindings inside of the application (e.g Ctlr+s to save)??

Inside the application - `Ctrl + S`, `Ctrl + C`
> Are you saving as JPG or PNG?

PNG, but i think that's not the issue, cause they look blurry even when selecting the region to screenshot.

**Comment by mmahmoudian** [comment] 2022-07-19 08:07
> Inside the application - `Ctrl + S`, `Ctrl + C`

would you please provide your Flameshot config (`~/.config/flameshot/flameshot.ini`)

> they look blurry even when selecting the region to screenshot.

Interesting. This is something that no one have ever reported. I should check and see if I can reproduce this in a clean install VM. Would you please confirm you OS again? Kubuntu seems to only have 22.04, 21.10, and 20.04

**Comment by mmahmoudian** [comment] 2022-07-19 10:23
> It's not Kubuntu, i've switched to Arch Linux since some time

As for Arch/Manjaro I know that Flameshot works just fine with KDE X11 (I myself use it in daily basis on 3 different computers), and for Wayland we need to have proper bug report with all the details.

> I don't have such a directory??

how have you installed Flameshot then?

-------

I close this issue as:
1. this is the only report of this kind
2. we cannot reproduce it
3. the OP's setup has also changed and is not reproducible in their new setup either

**Closed by mmahmoudian** 2022-07-19 10:23 UTC
Labels: Waiting For Info, Unconfirmed Bug, Linux, Wayland

**Comment by mystiquewolf** [comment] 2022-07-19 13:45
> how have you installed Flameshot then?

FWIW, `sudo snap install flameshot`

**Comment by mmahmoudian** [comment] 2022-08-08 11:08
@mystiquewolf It just hit me: what is your locale? (run `locale` in terminal) It might be that you are on some language other than latin characters.

**Comment by mystiquewolf** [comment] 2022-08-10 08:04
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=bg_BG.UTF-8
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=bg_BG.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=bg_BG.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by mmahmoudian** [comment] 2022-08-10 16:37
I'm out of ideas. I really cannot reproduce this. Here are my ultimate suggestions:

- try the AUR since you are on Arch
- from the Configuration window assign other keys  to some actions and see if they work
