### ISSUE TITLE
Flameshot legend pushes screen content to the side, starting with v11.0.0

### ISSUE THREAD

**Issue by dkasak** [flameshot-org/flameshot#2428] opened 2022-02-15 09:49 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux

### Description

With the upgrade to 11.0.0, flameshot displays the legend (the help window) docked to the right of the screen, pushing everything else on that screen leftward and onto my other monitor to the left. Previously (e.g. in 0.10.2), the legend displayed as an overlay on the screen, which worked well.

As I'm trying to take a screenshot of the situation, I now notice that the docked legend cannot be screenshot by flameshot. Attempting to screenshot an area including the legend results in a small screenshot which doesn't include the legend.

### Steps to reproduce

1. `flameshot gui`
2. The screen content is partially pushed to the side, obscuring it. The left monitor now also displays the content of the right screen instead of its own content.

### System Information

I'm using xmonad on Xorg. I have two monitors, output from xrandr below:

```
❯ xrandr
Screen 0: minimum 8 x 8, current 6336 x 2160, maximum 32767 x 32767
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected primary 3840x2160+2496+0 (normal left inverted right x axis y axis) 600mm x 340mm
   3840x2160     60.00*+  59.94    50.00    30.00    29.97    25.00    23.98  
   2560x1440     59.95  
   1920x1080     60.00    59.94    50.00    29.97    23.98  
   1600x900      60.00  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00    59.94  
   1152x864      60.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-3 connected 2496x1404+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  48.00  
DP-4 disconnected (normal left inverted right x axis y axis)
```

**Comment by mmahmoudian** [comment] 2022-02-15 16:11
I don't quite understand the issue. Would you please record a short video (for example using [peek](https://github.com/phw/peek)) to demo the issue

**Comment by dkasak** [comment] 2022-02-22 08:40
I only have a single screen at the moment so I can't reproduce to record. I'll do this ASAP.

**Comment by FischLu** [comment] 2022-03-17 15:49
I have the same problem when this is a external screen connected to my macbook air. I have recorded a video

https://user-images.githubusercontent.com/10261662/158839113-668dc10f-ab54-4aae-bca8-a0c8693f241a.mp4

.

**Comment by mmahmoudian** [comment] 2022-03-18 06:49
@FischLu what you are describing is different from the issue @dkasak has explained. What you have is the animation macOS plays when you close a fullscreen window. The same happens if you make any software fullscreen and then close it. The reason is that basically Flameshot takes a picture from all your screens and open a fullscreen window and then let you annotate it. When you copy or save or cancel, that fullscreen window gets closed. There is no way to bypass that animation as a software, but you as a user can disable that.

**Comment by FischLu** [comment] 2022-03-18 11:15
@mmahmoudian Thank you for the explanation, I switched off the animation via `Preferences > Accessibility > Display and check "Reduce Motion"` The problem is partly solved, although there is still some transition animation from dark to light.

It is interesting to note that some software such as [xnip](https://xnipapp.com/) can take screenshot for the full screen of all monitors and able to make annotation but without any animation at all. Unfortunately it is closed source software, no way to know how it is implemented.

**Comment by dkasak** [comment] 2022-03-29 09:08
Here it is. The thing that's visible in the video initially is the X root window with my background in it. When Flameshot is started, the help menu / legend pushes the right monitor's content halfway leftward, onto the left monitor (which is not visible in the recording). When I press `Esc` to close Flameshot, everything returns back to normal.

This only happens while I'm using more than one monitor.

https://user-images.githubusercontent.com/463342/160575811-addd5d87-67c7-4701-b4d4-8de1c45bd05c.mp4

**Comment by dkasak** [comment] 2022-03-29 09:16
I notice that before 11.0.0 I'm unable to select flameshot's GUI using `xprop` but starting with 11.0.0 I can do so. My guess is the method for spawning the GUI somehow changed between those version and the new one does not agree with my window manager (xmonad).

**Comment by borgmanJeremy** [comment] 2022-04-05 01:00
@dkasak are you using fractional scaling? This looks like the issue that happens with fractional scaling.

**Comment by dkasak** [comment] 2022-04-05 07:43
I'm... *probably* using fractional scaling, depending on how you define it. I'm using `nvidia-settings` to assign a resolution which isn't an integer multiple of the natural resolution, yes.

**Comment by borgmanJeremy** [comment] 2022-04-05 12:56
Ok this is very likely a duplicate of #564

**Closed by borgmanJeremy** 2022-04-05 12:56 UTC
Labels: Waiting For Info, Unconfirmed Bug

**Comment by dkasak** [comment] 2022-04-05 13:07
I'm not sure that it is, given that it worked correctly with 0.10.2 and that issue is from 2019. However, it seems to be a duplicate of https://github.com/flameshot-org/flameshot/issues/1386.

Running `QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="" flameshot gui` works for me as a workaround.

**Comment by borgmanJeremy** [comment] 2022-04-05 14:02
Ok great thanks for reporting back. We have never had a release that consistently worked with fractional scaling. It seems that manually setting the screen factor resolves the issue for most people.
