### ISSUE TITLE
Support ALT+PRINT SCREEN to only capture the active window and open Flameshot GUI

### ISSUE THREAD

**Issue by Hassias** [flameshot-org/flameshot#3636] opened 2024-06-12 14:02 UTC
### Feature Description

Other screenshot tools, and even the build-in support in windows support pressing ALT+PRINT SCREEN. In Flameshot, the GUI does not open when using this combination, only the image is copied to the clipboard.

**Comment by Korb** [comment] 2024-07-12 07:16
@Hassias, apparently, in any case, we will have to wait for the implementation of #334.

**Comment by cspaniard** [comment] 2024-09-21 10:11
Being able to capture and annotate the active window would be of great help.

**Comment by mmahmoudian** [comment] 2024-09-26 08:17
Thanks for the feature request, but this is duplicate of https://github.com/flameshot-org/flameshot/issues/1341 . Please consider searching among open and closed issues before creating a new one. Thanks.

**Closed by mmahmoudian** 2024-09-26 08:17 UTC
Labels: Enhancement
