### ISSUE TITLE
Support gif creation

### ISSUE THREAD

**Issue by maireanu** [flameshot-org/flameshot#670] opened 2019-12-10 11:05 UTC
It will be nice to have the possibility to make gif also

**Comment by lawzava** [comment] 2020-01-22 19:57
Indeed.

**Comment by mmahmoudian** [comment] 2020-09-06 16:12
I think this is out of the scope of this software. You can achieve this using [https://github.com/phw/peek](https://github.com/phw/peek) which is designed for this purpose:

![peek example](https://raw.githubusercontent.com/phw/peek/master/data/screenshots/peek-recording-itself.gif)

**Comment by borgmanJeremy** [comment] 2020-09-10 16:02
Duplicate of #172

**Closed by borgmanJeremy** 2020-09-10 16:02 UTC
Labels: Enhancement, Needs Decision
