### ISSUE TITLE
Severe broken in 4k screen setup

### ISSUE THREAD

**Issue by eerbano** [flameshot-org/flameshot#1983] opened 2021-10-16 18:07 UTC
**Flameshot version**
v0.9.0

**Describe the bug**
I recently added a 4k screen in my setup (I had a 2k screen plus an 1080p screen and I just replaced it to a 4k screen), and when I tried to take a screenshot, it broke everything, it started mixing parts that was in my 2k screen together parts that was in my 4k screen, and scrabled everything, I was able to barely close flameshot, and then, I noticed my gnome panels would not load up, until I ended restarting the system.

**To Reproduce**
Any steps you would normaly take to get a screenshot will trigger what I described.

**Expected behavior**
I just expect it to show the areas of the screen, so I can select what I want to screenshot

**System Information**
Ubuntu 20.04

**Comment by borgmanJeremy** [comment] 2021-10-17 14:35
Okay thanks. I am going to close this as a duplicate of #564 . Unfortunately we have yet to find a workaround for this issue as its a deeply embedded Qt5 bug. We are hoping Qt6 fixes the problem.

**Closed by borgmanJeremy** 2021-10-17 14:35 UTC
