### ISSUE TITLE
Add pixel values for width and height

### ISSUE THREAD

**Issue by code-r-man** [flameshot-org/flameshot#3258] opened 2023-07-04 07:36 UTC
### Feature Description

If possible please add values (in pixels) for the height and width of the screenshot area. OSX has this on their screenshot utility.
This would make the tool just perfect for front-end development.
I would love to contribute my self, but sadly I can't code in "C" :(

**Comment by mmahmoudian** [comment] 2023-07-05 05:33
Duplicate of #3099 which was fixed in #2766

**Closed** 2023-07-05 05:33 UTC
Labels: Enhancement
