### ISSUE TITLE
Part of desktop not covered on MS Windows with 2 screen, mixed-DPI

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#986] opened 2020-09-25 19:41 UTC
**Flameshot version**
git HEAD (2020-09-25, f5d581c89f36c705f65f10193902a2382a5bf595)

**Describe the bug**
With certain 2-screen setup and mixed DPI settings, part of the desktop is not convered when making a screenshot with flameshot.

**To Reproduce**
* Use 2 monitors and use the following setup:
![图片](https://user-images.githubusercontent.com/8443926/94308743-f6b2e680-ff44-11ea-8adf-0a385f8883a5.png)

* Screen 1: 3840 * 2160, 200% scaling
* Screen 2: 1080 * 1920, 100% scaling

* Start flameshot for a capture. The behavior is abnormal. See the attached photo (pay attention to the black part at the top of screen 2 and duplicated parts at the top of screen 1):

![图片](https://user-images.githubusercontent.com/8443926/94309016-69bc5d00-ff45-11ea-80c7-613037cac126.png)

**Expected behavior**
The whole desktop is covered with dark background and can be captured.

**System Information**
Windows 10 x86_64 19041

**Comment by szszoke** [comment] 2020-09-25 22:54
Likely a duplicate of #739

**Comment by borgmanJeremy** [comment] 2020-09-26 01:09
@hosiet maybe this was caused by a result of [this commit](https://github.com/flameshot-org/flameshot/commit/e1214e23e5a2641d585e47aa064cfcbb8a2b6111)

**Comment by hosiet** [comment] 2020-09-26 01:12
This happens on 0.8.1 without the commit so the commit should be unrelated

**Comment by ZetaoYang** [comment] 2020-09-26 02:43
I think it might be related to this https://github.com/flameshot-org/flameshot/issues/932. Maybe your two monitors are running on different graphics cards and the iGPU conflicts with the dGPU.

**Comment by mmahmoudian** [comment] 2020-09-27 11:54
At the moment I don't have access to two monitors to test this on Linux but I would like to see the results of these tests:
1. Does it behave the same on Linux (X11) or is it a Windows thing?
2. Is it related to having monitors connected to different graphic cards?
3. Can the rectangular section get dragged out side of the "dark background" area?
4. Does it get fixed if the height of both monitors are the same?

**Comment by hosiet** [comment] 2020-09-28 02:44
Answers to those questions:

1. I don't have a Linux installation with dual monitor right now so cannot test. Hopefully someone else can take a look with similar setup.
2. Those 2 monitors are connected to the same graphics card (NVIDIA).
3. Yes it can. The screenshot result also contains the "dark background" area. The odd thing is that the bright area in monitor 1 cannot be covered by the rectangular section.
4. If the top of the monitors are kept to be on the same horizontal line, this bug will disappear.

**Comment by mmahmoudian** [comment] 2020-09-28 05:19
@hosiet so it seems the error is in geometry (esp. height) and the position defined for the "dark background".


off-topic: let's call the "dark background" as "curtain" if it doesn't have a designated name yet.

**Comment by 1619513467** [comment] 2020-10-03 15:52
Windows 如何安装这个？

**Comment by borgmanJeremy** [comment] 2020-11-01 00:57
I think this might be fixed with #1126

**Closed** 2020-11-01 01:04 UTC
Labels: Bug, Windows
