### ISSUE TITLE
Pointer/cursor for selecting region is invisible

### ISSUE THREAD

**Issue by luixal** [flameshot-org/flameshot#2396] opened 2022-02-08 21:58 UTC
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
linux: 5.16.5-arch1-1
endeavouros: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

EndeavourOS (Arch Linux) Kernel 5.16.5 x86_64

### Description

Running it from the tray icon or by running the `flameshot gui` command, the dark overlay appears, but the cursor/pointer (with the + shape) just goes invisible.

Having a look at gnome logs, I've just seen this one that could be related:

`journalctl -e /usr/bin/gnome-shell` gives me this message `gnome-shell[3639]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x620000a specified for 0x6200041.`

### Steps to reproduce

1. run `flameshot gui`
2. That's it, cursor is invisible a couple seconds after.

### System Information

- Desktop Environment: Gnome 41
- Xorg and Wayland, have tried both having the same issue.

**Comment by mmahmoudian** [comment] 2022-02-10 07:51
Can be related or even duplicate of #2004

**Comment by borgmanJeremy** [comment] 2022-02-18 17:01
Yeah i think this is a duplicate

**Closed by borgmanJeremy** 2022-02-18 17:01 UTC
Labels: Unconfirmed Bug
