### ISSUE TITLE
Quick Screenshot Feature

### ISSUE THREAD

**Issue by allabright** [flameshot-org/flameshot#1846] opened 2021-08-26 16:49 UTC
I'm not sure if this exists already, but it would be good to have a command line argument to take a quick screenshot, i.e.

- Hit hotkey to run command
- GUI window comes up
- Highlight portion of page required
- Screenshot is automatically copied to clipboard and saved to screenshot directory
- GUI closes

This would be useful for taking many repetitive screenshots that don't require edits, such as figures from textbooks. It's a hassle to have to click the 'Copy' button each time.

I could then have two screenshot hotkeys mapped:

- One for quick screenshot, as above.
- One for normal screenshots, where they may require editing.

**Comment by mmahmoudian** [comment] 2021-08-28 06:02
Just out if curiosity, do you know that you can press <kbd>Ctrl</kbd>+ <kbd>c</kbd> to copy and <kbd>Ctrl</kbd>+ <kbd>s</kbd> to save?

**Comment by mmahmoudian** [comment] 2021-08-28 06:06
Btw, isn't this duplicate of #526?

**Comment by allabright** [comment] 2021-08-28 08:38
Yes, I'm aware of the Ctrl-C and Ctrl-S shortcuts, thanks.

And yes, it looks like that's the same feature being requested, I didn't spot that.

**Comment by mmahmoudian** [comment] 2021-08-28 11:30
@allabright then would you please close this issue and in case your idea is not fully presented there, you add a comment and write a complementary post?

**Closed** 2021-09-26 07:36 UTC
Labels: Duplicate, Enhancement
