### ISSUE TITLE
tools are missing on multi monitors

### ISSUE THREAD

**Issue by LooJee** [flameshot-org/flameshot#1485] opened 2021-03-17 01:52 UTC
![image](https://user-images.githubusercontent.com/13059033/111402523-4f9a5500-8706-11eb-93c5-ea5174840a3c.png)
![image](https://user-images.githubusercontent.com/13059033/111402587-6c368d00-8706-11eb-8308-e9378e1f1554.png)

**Comment by mmahmoudian** [comment] 2021-03-17 08:18
Thanks for reporting this, but without having all the requested information, we cannot investigate this issue. Please edit your original post and add all the requested information including
- Flameshot version
- how have you got Flameshot on your system
- your operating system and its version
- steps to reproduce the bug

**Comment by LooJee** [comment] 2021-03-17 08:52
1. Flameshot version：v0.9.0
2. operating system：win10 pro-10.0.19042
3. install Flameshot via [Flameshot-0.9.0-win64.msi
](https://github.com/flameshot-org/flameshot/releases/download/v0.9.0/Flameshot-0.9.0-win64.msi)
4. I have two monitors , when I press PrtScn to capture the screen on my screen 1, the tools are shown on monitor 2，and some tools are beyond screen.
![image](https://user-images.githubusercontent.com/13059033/111439763-a7ee4880-8740-11eb-99db-6bc431597106.png)

**Comment by WebsiteDeveloper** [comment] 2021-03-17 12:29
I have the same issue although i cant take any screenshots anymore because my middle monitor is not selectable.
Can share some more info if needed

**Comment by borgmanJeremy** [comment] 2021-03-17 13:21
I think this is a duplicate of #1440.

If you can test from the master branch that would be helpful. I believe we have already merged the fix for it.

**Closed by borgmanJeremy** 2021-03-17 13:21 UTC
Labels: Visuals, Windows
