### ISSUE TITLE
Pin tool not pinning to original position on Manjaro

### ISSUE THREAD

**Issue by Alaskra** [flameshot-org/flameshot#2001] opened 2021-10-23 09:02 UTC
**Flameshot version**
v0.10.1

![image](https://user-images.githubusercontent.com/49367127/138550007-cdc2e636-b0a1-4646-a8ab-ea23a2503240.png)

**Describe the bug**

the problem is the same as issue #350

**System Information**

Kernel: 5.4.148-1-MANJARO 
DE: Plasma 
WM: KWin

I tried `yay -S flameshot` and appImage, both have this problem

**Comment by borgmanJeremy** [comment] 2022-06-02 01:27
Closing this as duplicate of the other fracitonal scaling issues.

**Closed by borgmanJeremy** 2022-06-02 01:27 UTC
Labels: Waiting For Info, Unconfirmed Bug, Visuals
