### ISSUE TITLE
editing other images

### ISSUE THREAD

**Issue by dakyskye** [flameshot-org/flameshot#1094] opened 2020-10-23 10:06 UTC
**Is your feature request related to a problem?**

No. Flameshot's in-app editor is goood enough that I'd love to use it on screenshots I took before. It gets job done very quickly. Would be cool if flameshot cli had an option "edit" and it had flags `-p` for path and `-c` for clipboard (so it uses image from clipboard).

**Comment by borgmanJeremy** [comment] 2020-10-23 13:10
This is a great idea and something we are considering. However it is a duplicate of #240 so I am going to close this new issue. Thanks for chiming in.

**Closed by borgmanJeremy** 2020-10-23 13:10 UTC
