### ISSUE TITLE
Built-in crop to content

### ISSUE THREAD

**Issue by daneel6672** [flameshot-org/flameshot#1708] opened 2021-07-15 09:40 UTC
Flameshot is amazing but needs built-in crop to content. My daily use-case is:

- Grab image approximately (has some whitespace)
- Crop to content (preferably with a shortcut key)
- Copy image
- Paste into document / social media...

At the moment I have to have a gimp window open, grab image, paste into gimp, crop to content, copy then paste into the destination document.

**Comment by mmahmoudian** [comment] 2021-07-15 13:13
I think your feature request is a duplicate of #1490 (interestingly enough it was created by me). My use case was also taking a screenshot from Rstudio and paste the "trimmed" version in presentations and reports.

While we are waiting for implementation of this feature, I put together a small script to do this and few other post-capture modifications for me (only three dependencies: bash, ImageMagick and dmenu):
https://codeberg.org/mehrad/dmenu_shot/src/branch/main/docs/actions.md


Anyways, as that feature request (#1490) is open, I suggest closing this one.

**Closed** 2021-07-19 10:29 UTC
Labels: Duplicate
