### ISSUE TITLE
Screenshot Hotkey

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#200] opened 2018-04-24 23:46 UTC
Running Linux Mint, is there a way to either set a hotkey to take a screenshot, or a way to create a custom keyboard shortcut that points to the screenshot function? Sadly any applications that run in fullscreen modes make this application redundant.

**Comment by fschaap** [comment] 2018-05-14 13:10
I'm running Cinnamon on Manjaro, so I hope this applies 100% to Linux Mint.

What I did, because I wanted to use the 'prtscr' key to launch Flameshot is:
1) Open System Settings
2) Open Keyboard Settings (under Hardware)
3) Select the 'Shortcuts' tab
4) Under Categories open System > Screenshots and Recordings
5) Check to which action the 'prtscr' key is bound (likely to Take a screenshot of an area or Take a screenshot... I had messed with this setting before, so I'm not quite sure)
6) Open Custom Shortcuts
7) Click Add custom shortcut
8) Type 'Flameshot' in the Name field and 'flameshot gui' in the Command field (both without the enclosing apostrophies)
9) Click Add
10) That's it, hopefully.

**Comment by yochananmarqos** [comment] 2018-08-12 18:31
I tried the same thing on Manjaro Cinnamon, but it doesn't work for some reason. Running `flameshot gui` from the terminal with or without Flameshot running works,however.

**Comment by luucasalvesss** [comment] 2018-08-13 19:11
@yochananmarqos its cause DE use print screen key for default progam... try change the key printscreen in "global" put something random (link ctrl + 3 +4) , and try make what @fschaap say

**Comment by yochananmarqos** [comment] 2018-08-13 19:34
@luucasalvesss I tried that, but it made no difference. Also I noticed none of the default keyboard shortcuts work; i.e., Alt + Print when Print is assigned to anything other than default.
![screenshot from 2018-08-13-13 32 35](https://user-images.githubusercontent.com/5437803/44053635-84fad146-9efd-11e8-990f-bd5a4ec39002.png)
![screenshot from 2018-08-13-13 32 52](https://user-images.githubusercontent.com/5437803/44053641-88c8e15a-9efd-11e8-96b2-b9b4e8547913.png)

**Comment by fschaap** [comment] 2018-08-27 09:48
I'm not sure why it is not working for you.
I would advise trying the following:
- check if the command for your keyboard shortcut is 'flameshot gui' (without the single quotes)
- add a random unused keyboard binding, like: ctrl+shift+7
- test if Flameshot launches when you use that shortcut
- if not, make the command for the shortcut '/usr/bin/flameshot' (without the single quotes)
- if Flameshot is still not launching from the shortcut, I suppose something else is wrong on your system

However, if Flameshot is properly launching from this before unused shortcut, then you can start to get it connected to the Print-screen key. The point is, this is a bit finicky. What I have done:
- in the above screenshot, under System > Screenshots and Recording remove all the shortcut bindings that have the 'Print' key in it
- you can do this by double-clicking the keyboard binding
- the keyboard-binding is now active and high-lighted
- press the backspace key
- the keyboard-binding now says 'unassigned'
- doublecheck if the 'Print' button is assigned in any of the other categories
- now go back to the Custom shortcut for Flameshot, double-click the keyboard-binding and hit the 'Print' key

I admit it is a bit finicky that you first have to unassign the other keyboard shortcuts, but this is what works for me.

**Comment by maksha** [comment] 2018-11-22 10:58
> I'm running Cinnamon on Manjaro, so I hope this applies 100% to Linux Mint.
> 
> What I did, because I wanted to use the 'prtscr' key to launch Flameshot is:
> 
> 1. Open System Settings
> 2. Open Keyboard Settings (under Hardware)
> 3. Select the 'Shortcuts' tab
> 4. Under Categories open System > Screenshots and Recordings
> 5. Check to which action the 'prtscr' key is bound (likely to Take a screenshot of an area or Take a screenshot... I had messed with this setting before, so I'm not quite sure)
> 6. Open Custom Shortcuts
> 7. Click Add custom shortcut
> 8. Type 'Flameshot' in the Name field and 'flameshot gui' in the Command field (both without the enclosing apostrophies)
> 9. Click Add
> 10. That's it, hopefully.

Following the steps from @fschaap works for me (Linux Mint 19):

![image](https://user-images.githubusercontent.com/305042/48898565-a584c800-ee7f-11e8-9226-ca5aa74ef486.png)

**Comment by Faults** [comment] 2019-04-09 08:21
I have same issue on Ubuntu 19.04 Beta. I tried workaround, but I didn't. 

![google-music](https://user-images.githubusercontent.com/31610325/55784424-3cfa5880-5ab9-11e9-84cf-a736f40de30d.png)

![app indicators](https://user-images.githubusercontent.com/31610325/55784530-7337d800-5ab9-11e9-9155-edc9e1131f7d.png)

**Comment by kamalhm** [comment] 2019-07-11 04:53
fschaap solution works perfectly, thanks!

**Comment by osagga** [comment] 2019-07-30 15:43
If anyone is looking for a way to do this on Ubuntu (tested on Ubuntu 19.04), here's the way that worked for me:

- Release the `PrtScr` binding by this command
    `gsettings set org.gnome.settings-daemon.plugins.media-keys screenshot ''`
- Go to Settings -> Devices -> Keyboard and scroll to the end. Press `+` and you will create custom shortcut.
  + Enter name: "flameshot", command: `/usr/bin/flameshot gui` (or wherever flameshot is, use `which flameshot` to see where it is)
  + Set shortcut to PrtScr (print).

That is it. Next time you push `PrtScr` flameshot will be launched.

Source: https://askubuntu.com/a/1039949

**Comment by LinuxOnTheDesktop** [comment] 2019-11-15 02:48
I am on Mint 19.2 Cinnamon. All that was necessary for me to get Flameshot to take a screenshot, whether Flameshot is running or not, was to tell Cinnamon to bind `flameshot gui` to a key. However, including the 'gui' bit - that is not going to occur to most people.

**Comment by evolutics** [comment] 2019-12-29 22:44
For **Xubuntu** users (Xfce), you can configure the Print Screen key as a Flameshot shortcut like this:

- Via GUI: application "Keyboard" in the main menu, then tab "Application Shortcuts", where you edit the shortcut "Print" to bind it to the command `flameshot gui`.
- Alternatively, via command line:
  ```bash
  xfconf-query --channel xfce4-keyboard-shortcuts \
    --property /commands/custom/Print \
    --create --set 'flameshot gui' --type string
  ```

I use the latter to configure my Xubuntu 18.04.3 LTS machine via Ansible.

**Comment by LinuxOnTheDesktop** [comment] 2020-02-06 02:08
There is a bug in Cinnamon that is causing at least most of the problem here. See [here](https://github.com/linuxmint/cinnamon/issues/7124).

**Comment by riadhtaihi** [comment] 2020-06-15 06:28
Hi, I am using the Snap version of Flameshot, could you please help me find the right command to add  in Keyboards settings?

Thanks!

**Comment by hyuma78** [comment] 2020-06-15 18:42
> I'm running Cinnamon on Manjaro, so I hope this applies 100% to Linux Mint.
> 
> What I did, because I wanted to use the 'prtscr' key to launch Flameshot is:
> 
> 1. Open System Settings
> 2. Open Keyboard Settings (under Hardware)
> 3. Select the 'Shortcuts' tab
> 4. Under Categories open System > Screenshots and Recordings
> 5. Check to which action the 'prtscr' key is bound (likely to Take a screenshot of an area or Take a screenshot... I had messed with this setting before, so I'm not quite sure)
> 6. Open Custom Shortcuts
> 7. Click Add custom shortcut
> 8. Type 'Flameshot' in the Name field and 'flameshot gui' in the Command field (both without the enclosing apostrophies)
> 9. Click Add
> 10. That's it, hopefully.

This worked perfect for me. Is it possible to skip the step where it asks "Select area with the mouse or press exit... " and have immediately the window with the area selected?

**Comment by LinuxOnTheDesktop** [comment] 2020-06-15 19:34
People who have contributed to this thread may want to head over to [the Cinnamon bug report](https://github.com/linuxmint/cinnamon/issues/7124) that I mentioned above and give that issue a '+1'.

**Comment by CowlingBanana** [comment] 2020-08-20 06:31
Guys, any ideas on setting it on lubuntu?!

**Comment by UgoTran** [comment] 2020-11-09 00:54
perfect it work for me
![image](https://user-images.githubusercontent.com/44249146/98489505-d6bf5400-2260-11eb-9b3e-6858ff315f8c.png)

**Comment by Dincer24** [comment] 2020-11-17 17:18
I'm using linux mint and i find a solution by installing flameshot via using terminal (sudo apt install flameshot) now it works properly by using prtsctrn bind

**Comment by vixrodriguez** [comment] 2021-01-02 20:23
> > I'm running Cinnamon on Manjaro, so I hope this applies 100% to Linux Mint.
> > What I did, because I wanted to use the 'prtscr' key to launch Flameshot is:
> > 
> > 1. Open System Settings
> > 2. Open Keyboard Settings (under Hardware)
> > 3. Select the 'Shortcuts' tab
> > 4. Under Categories open System > Screenshots and Recordings
> > 5. Check to which action the 'prtscr' key is bound (likely to Take a screenshot of an area or Take a screenshot... I had messed with this setting before, so I'm not quite sure)
> > 6. Open Custom Shortcuts
> > 7. Click Add custom shortcut
> > 8. Type 'Flameshot' in the Name field and 'flameshot gui' in the Command field (both without the enclosing apostrophies)
> > 9. Click Add
> > 10. That's it, hopefully.
> 
> Following the steps from @fschaap works for me (Linux Mint 19):
> 
> ![image](https://user-images.githubusercontent.com/305042/48898565-a584c800-ee7f-11e8-9226-ca5aa74ef486.png)

It works for Linux Mint MATE 20!

**Closed** 2021-03-04 02:08 UTC

**Comment by mbaev** [comment] 2021-03-21 08:18
For guys who installed the Flameshot using Flatpack the command is
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=flameshot org.flameshot.Flameshot gui --delay 0
```

![image](https://user-images.githubusercontent.com/6450526/111898439-87273b00-8a3f-11eb-8e8b-eb68ec3f2534.png)

**Comment by epsilon42** [comment] 2021-03-23 06:46
Thanks @mbaev. That command also worked for me running PopOS with Flameshot installed via Pop! Shop (Flatpak).

**Comment by Duduxs** [comment] 2021-03-23 22:27
![como-fazer](https://user-images.githubusercontent.com/53549133/112227046-c73c1880-8c0d-11eb-8876-588779cea45a.png)

**Comment by Duduxs** [comment] 2021-03-23 22:28
![como-fazer](https://user-images.githubusercontent.com/53549133/112227151-f2bf0300-8c0d-11eb-8900-fa7e4afd7077.png)

**Comment by mmahmoudian** [comment] 2021-03-24 10:50
@Duduxs Thanks for the visual help. I just wanted to point out that you can also use the counter bubbles to add those numbers easily without typing them manually. 😉 

![image](https://user-images.githubusercontent.com/390889/112298210-7248e280-8c9f-11eb-8562-2229eced2fde.png)

**Comment by tq-bit** [comment] 2021-09-04 08:24
If anyone is looking for a solution on Ubuntu 20.04: This one worked for me

1. System settings -> Shortcuts -> Custom Shortcuts
2. Under KMenuEdit -> Create new entry 
3. Set a trigger ( in my case print button ) and type in `flameshot gui` (just like in the other comments above) 

![image](https://user-images.githubusercontent.com/69204418/132088103-f3f8871b-8977-43a3-9e96-d772b7822403.png)

**Comment by stephenaustin** [comment] 2022-04-01 03:15
Happy to report this works on Pop! 0S. Steps are a bit different but not rocket science to a usual Linux user. 
Keyboard>keyboard shortcuts>Custom shortcut and follow the steps above.

**Comment by vijayrana-99** [comment] 2022-07-15 03:49
> 

I had to remove the old shortcut and reattach the keyboard shortcut after ubuntu upgrade from 21.10 to 22.04

**Comment by Roeefl** [comment] 2022-08-15 04:59
@vijayrana-99 Could you please help me understand exactly what to do ? I can't figure out how to make the keyboard shortcut work.
I'm on ubuntu 22.04 as well.
thank you

**Comment by mmahmoudian** [comment] 2022-08-15 18:39
> @vijayrana-99 Could you please help me understand exactly what to do ? I can't figure out how to make the keyboard shortcut work.
> I'm on ubuntu 22.04 as well.
> thank you

Can you explain what the problem is
