### ISSUE TITLE
Flameshot's window flash after copying screenshot to clipboard

### ISSUE THREAD

**Issue by Pheggas** [flameshot-org/flameshot#2716] opened 2022-06-24 09:28 UTC
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Using the ready-made package from Github Releases

### Operating System type and version

Microsoft Windows, 21H2

### Description

Hello. I recently installed Flameshot v12.0.0 and noticed that after i copy screenshot to clipboard, the Flameshot's window quickly appears and disappears. (See screen recording)

### Steps to reproduce

1. Install Flameshot v12.0.0 from windows installed (.msi)
2. Take screenshot with selected region
3. Ctrl + C
4. See the window quickly flash

### Screenshots or screen recordings

https://streamable.com/z7w3yh

### System Information

1. Already mentioned in Operating System type and version
2. https://i.imgur.com/VJnYKMy.png

**Comment by Alaskra** [comment] 2022-06-25 15:12
This is caused by the hack(which open an empty window and close it) to fix another issue. I have opened this pr #2698 to fix it.

**Comment by Pheggas** [comment] 2022-06-25 16:48
Alright, thanx for reply.

**Comment by borgmanJeremy** [comment] 2022-06-29 23:00
Merged.

**Closed by borgmanJeremy** 2022-06-29 23:00 UTC
Labels: Unconfirmed Bug
