### ISSUE TITLE
Selection of any tool after using text tool closes flameshot

### ISSUE THREAD

**Issue by shivanshu-semwal** [flameshot-org/flameshot#2407] opened 2022-02-10 18:29 UTC
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 20.04.3 LTS x86_64

### Description

After using the text tool in flameshot gui, and then when you select another tool in flameshot gui it closes flameshot.
This happen occasionally, also if text tool is selected and you select another tool without deselecting it, the gui closes.

### Screenshots or screen recordings

https://user-images.githubusercontent.com/53912074/153471730-8c6926ec-f91f-407e-9a2d-a809ebd4309b.mp4

### System Information

- Ubuntu 20.04.3 LTS x86_64
- wm - i3-gaps
- Xorg

**Comment by mmahmoudian** [comment] 2022-02-10 21:38
duplicate of #2283, #2353 and #2402

Please search before posting a bug report or feature request. It would save everyone's time. Thank you.

**Closed** 2022-02-10 21:38 UTC
Labels: Bug, Duplicate
