### ISSUE TITLE
Flameshot creates new, empty virtual desktop when taking screenshot

### ISSUE THREAD

**Issue by theraccoonbear** [flameshot-org/flameshot#2292] opened 2022-01-20 18:09 UTC
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Using the ready-made package from Github Releases

### Operating System type and version

MacOS X 11.6.1

### Description

Once I've installed the newest Flameshot and have it running, I try to take a screenshot.  When the semi-opaque Flameshot overlay appears, it does so on a new virtual desktop, not the one I am working on.  Essentially: I can only take a screenshot of an empty desktop now.

Prior to this update Flameshot was working flawlessly.  I'm extremely appreciative of the work that goes into this, but also equally frustrated that my tooling is now broken.

### Steps to reproduce

1. Install Flameshot on Mac OS (I've tried both `.dmg` and `brew install flameshot`)
2. From the task bar, click the Flameshot icon and choose "Take screenshot"
3. Observe that you're now on a wholly separate, empty Desktop with no option to go back to your original one with Flameshot.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/60887/150396312-a3a33bef-f7bb-4396-b91e-9a13ec0210ff.png)
![image](https://user-images.githubusercontent.com/60887/150396415-04549ca2-60bb-46f0-99cd-6f75a0421a96.png)
![image](https://user-images.githubusercontent.com/60887/150396473-dbd9ffcb-b045-4706-88b5-ace72711ed37.png)
![image](https://user-images.githubusercontent.com/60887/150396515-8191751d-16e7-4f41-a586-1098df718dad.png)

### System Information

MacOS X 10.6.1
Darwin 20.6.0
Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2

**Comment by borgmanJeremy** [comment] 2022-01-20 18:11
You need to remove and re add permissions. It's a macOS thing 😢

**Comment by theraccoonbear** [comment] 2022-01-20 18:15
@borgmanJeremy which permissions?  I just removed the "Screen Recording" option.  It prompted to close and re-open Flameshot.  I did so.  I then re-added the permission, closed, and launched Flameshot again.  Identical behavior: new empty desktop

**Comment by borgmanJeremy** [comment] 2022-01-20 18:16
Try closing flameshot, removing the permission.

Then open flameshot to get the prompt, grant permission, and restart flameshot.

**Comment by theraccoonbear** [comment] 2022-01-20 18:29
> Then open flameshot to get the prompt

This part never occurred.  I closed it, removed the screen recording permission, then reopened it and the icon appeared the the task bar.  Tried to take a screenshot, no permissions prompt, it created a new virtual desktop again, so nothing seems to have changed other than Flameshot no longer has permissions 😢

**Comment by borgmanJeremy** [comment] 2022-01-20 18:31
Ugh, MacOs is a real pain with this. Maybe a reboot or reinstall? I do about 50% of flameshot development on a Mac so i am installing a new version like every other day. Sometimes it gets into a bad state and i just reboot and re-install flameshot. It's always eventually sorted itself out.

**Comment by theraccoonbear** [comment] 2022-01-20 18:37
I did try a uninstall/reinstall (both `.dmg` and `brew`) with no luck.  I'm in the middle of some work right now, but I'll try a reboot later.  I feel your Mac pain.  After main years working in Linux ❤️ I'm back on a Mac and while it's _pretty_ it is an enormous PITA 😢

**Comment by aroute** [comment] 2022-01-25 14:39
I saw the same issue on Mac. The recent update has broken the usage of this software on Mac.

**Comment by borgmanJeremy** [comment] 2022-01-25 14:40
You need to redo permissions and reboot.

**Closed** 2022-01-25 15:55 UTC
Labels: Unconfirmed Bug, MacOS

**Comment by Goralive** [comment] 2022-07-07 04:04
> I saw the same issue on Mac. The recent update has broken the usage of this software on Mac.

If the solution with restart doesn't help you can delete the permision with a minus.
[2721](https://github.com/flameshot-org/flameshot/issues/2721#issuecomment-1166383340)

**Comment by Tiagochicoo** [comment] 2022-08-24 07:48
Restarting it worked for me. Macbook M1 pro

**Comment by krizman** [comment] 2022-09-04 15:40
I have done all of the above: 
- enabled "screen recording" permission,
- restarted,
- installed via brew,
- then via macports using sudo,
- with various combinations of the above with uninstalls and everything

and I **still get the screenshot performed at a new blank virtual screen**.

This happened before and I've resolved it with reinstalling, restarting or updating the permissions. But now with the **upgrade to MacOS Monterey 12.5.1**, I can't get it to work no mater what I do.

The only difference I see is that when enabling the "screen recording" permissions and a "quit and restart" app option, it will again ask me to enable the permissions as though they are not granted. It's like the permission toggle does nothing for the app

![image](https://user-images.githubusercontent.com/4232871/188321563-3323f66f-48ee-4a36-9249-d464c6ddbb77.png)
![image](https://user-images.githubusercontent.com/4232871/188321602-a7bf5c2d-7f1b-48d6-a145-c6ca5c5d3c8e.png)
![image](https://user-images.githubusercontent.com/4232871/188321609-b0846a1f-a176-4b43-b621-7ad5c2e3aec6.png)

Does anyone have any idea on how to make this work on an **M1 MacBook** with MacOS 12.5.1?

**Comment by mmahmoudian** [comment] 2022-09-04 16:30
@krizman 
1. Remove the permission
2. Reboot
3. Add the permission
4. Enjoy

(Step 1 is suuuuuuper crucial )

**Comment by krizman** [comment] 2022-09-05 11:08
@mmahmoudian thank you for your fast reply 🙏

It finally worked but only when **I removed and re-added the app to the permissions list using the "minus" and "plus" signs** (without restarting). 

Before I just toggled enable/disable checkbox 🤦🏻‍♂️ which apparently is not the same thing 😅

**Comment by saeedvaziry** [comment] 2023-04-08 08:20
Hello here,
For me it works but the problem is when I initiate screenshot it takes a screenshot from the current screen and opens that screenshot in a new window in full-screen mode in a new desktop (animating) and after I close the screenshot mode or copy it to clipboard at closes that screenshot window and backs to the original desktop with animating.

https://user-images.githubusercontent.com/61919774/230711429-be9afed7-22e5-4710-9f98-be7e4da52e57.mov

**Comment by hodunov** [comment] 2023-07-16 15:11
is there any way to solve this problem?

**Comment by mmahmoudian** [comment] 2023-07-16 15:17
@hodunov this is not a Flameshot issue. It is about macOS not permitting Flameshot to see anything. As others have said as as we have mentioned in our troubleshooting guide (link below), user have to give the correct permission:

https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection

**Comment by TerrorSquad** [comment] 2023-07-16 20:35
@mmahmoudian I gave the correct permission (screen recording) to Flameshot and restarted my Macbook, but the behaviour is still the same.
Is there anything else I could do to fix this?

**Comment by mmahmoudian** [comment] 2023-07-16 20:37
@TerrorSquad did you delete the permissions and added them again? macOS has an issue that it does not transfer the permission to other versions of the same software. So after updating, you have to delete the permission and add it again and then reboot

**Comment by hodunov** [comment] 2023-07-16 21:27
@mmahmoudian yes I realize it's a macos issue, sorry, I wrote in the hope that someone had a solution. The above methods did not work for me 😞

**Comment by TerrorSquad** [comment] 2023-07-19 23:23
@mmahmoudian  I did. I followed the exact steps you posted above and it didn't work.

**Comment by ddv16111998** [comment] 2024-11-23 03:24
Because it related the security on MacOS system, any screenshot app will default disabled snapshot function and auto open a empty workspace. To fix this issue, please go System Setting --> Privacy and Security --> Screen and System Audio Recording then enable this app. It worked with me.

**Comment by offeex** [comment] 2024-12-23 16:26
didn't work for me as well, no matter what i did

**Comment by saeedvaziry** [comment] 2024-12-25 12:51
So as far as I understood Flameshot goes to full-screen mode to capture the screen on mac which is causing this workspace change.

Is it possible to use this command on MacOS to make the screen capturing?

```sh
/usr/sbin/screencapture -s ~/Desktop/capture.png
```
