### ISSUE TITLE
allow pinned window to be dragged partly outside of the display

### ISSUE THREAD

**Issue by zhangfuwen** [flameshot-org/flameshot#1262] opened 2021-01-29 09:56 UTC
**Is your feature request related to a problem?** No

Currently, a pinned picture can be dragged around on the display but with one limitation: You can't drag part of it outside of the display, the whole picture must be in the display. 

Sometimes, I use this tool to help me remember something that I have to do later. I capture a image and pin it on my display, and I want to drag it to one side of the display and save room for me to do some other work. When I am done with it, I drags the pinned picture back and continue with the original work. For now, the pinned picture takes too much room. I want to hide most part of it outside of the display when I am doing some other work.

**Comment by borgmanJeremy** [comment] 2021-02-03 01:26
This is a good idea but also a duplicate of #984

**Closed by borgmanJeremy** 2021-02-03 01:26 UTC
Labels: Enhancement
