### ISSUE TITLE
Unix Timestamp in the filename pattern: %s

### ISSUE THREAD

**Issue by ExceptionGit** [flameshot-org/flameshot#1900] opened 2021-09-15 10:43 UTC
**Flameshot version**
Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**
Pattern `file%s`, doesn't work now.

**To Reproduce**
1. Set the filename pattern to screenshot: `file%s`
2. Take a screenshot
3. `file%s.png`

**Expected behavior**
Should work.

**System Information**
Arch Linux

**Comment by borgmanJeremy** [comment] 2021-09-15 11:59
We support the format specifiers defined here: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-160

The msvc compiler only supports a subset of the flags that gcc does.

**Comment by mmahmoudian** [comment] 2021-09-15 13:09
@borgmanJeremy is this something that we are planning to solve if the issue is upstream? In other words should I mark it as Enhancement or close the issue?

**Comment by borgmanJeremy** [comment] 2021-09-15 13:34
I would close the issue. MSVC is not planning to change the compiler. 

I specifically added in filters a while back to only support the "intersection" of all the different format specifiers to prevent crashes.

**Closed** 2021-09-15 13:53 UTC
Labels: Won't Fix, Upstream

**Comment by mmahmoudian** [comment] 2021-09-15 13:55
@ExceptionGit Hope this get resolved in upstream so that we can also have this flag

**Comment by ExceptionGit** [comment] 2021-09-16 03:40
@borgmanJeremy In old version `Flameshot v0.9.0` it's work and `%s` used in Spdlog. Can you post a commit where this behavior is changed?

@mmahmoudian I don't think this get resolved in upstream if the MSVC compiler in priority.

**Comment by borgmanJeremy** [comment] 2021-09-16 12:22
I changed the behavior in this PR to commonize the behavior across all platforms: https://github.com/flameshot-org/flameshot/pull/1415

**Comment by ExceptionGit** [comment] 2021-09-16 22:56
Thanks, i will change this behavior for my case and keep it upgradeable.

**Comment by drawanon** [comment] 2021-12-25 01:43
It's a shame it got removed. Luckily it's easy to add back for people, who still want to use it just by adding 's' to [this line](https://github.com/flameshot-org/flameshot/blob/da5d71c23c31e89db59006183a3572d35e3c85d1/src/utils/strfparse.cpp#L25)

i respect the decision to keep it more platform independent - this note is for people who may stumble on this and look for a way to add it back, for their personal use
