### ISSUE TITLE
Upload Screenshots to Third Party Cloud

### ISSUE THREAD

**Issue by itskamzan** [flameshot-org/flameshot#2498] opened 2022-03-21 21:29 UTC
### Feature Description

The application only uploads the contents to Imgur.
It would be better if the same had wide variety of options such as AWS S3, Box, SCP over SSH, FTP, Google Drive, etc.
Then we could configure screenshots on our own custom servers for our personal needs.

**Comment by mmahmoudian** [comment] 2022-03-22 05:55
Is this duplicate of:

- #2332
- #2164
- #1971
- #1931
- #1623
- #1463
- #1190
- #1154
- #750
- #178

And most importantly:

- #955

**Comment by itskamzan** [comment] 2022-03-22 06:37
The thing is I’m using a mac. 
the so called scripts don’t work. 
also kindly include all these in the preferences.

**Comment by mmahmoudian** [comment] 2022-03-22 06:44
> The thing is I’m using a mac.
> the so called scripts don’t work.

macOS supports all the bash scripts in all those threads. Only Windows users don't have proper bash support, which imho should give them more incentive to use a [better] OS (i.e Linux or BSD).

> also kindly include all these in the preferences.

I don't understand what you mean by "include in preferences". Wolf you please elaborate more.

**Comment by itskamzan** [comment] 2022-03-22 07:42
I wanted these settings included in the preference tabs similar to this

https://ibb.co/kcDbH7C
https://ibb.co/TPKMCJL

I guess these will help noob people like me.

**Comment by mmahmoudian** [comment] 2022-03-22 08:33
to reiterate, read #955

**Closed** 2022-03-22 08:33 UTC
Labels: Duplicate, Enhancement
