### ISSUE TITLE
Is there a way to change "quit capture" keys?

### ISSUE THREAD

**Issue by ragnarov** [flameshot-org/flameshot#2916] opened 2022-09-23 01:26 UTC
### Feature Description

The title pretty much says it.

**Comment by mmahmoudian** [comment] 2022-09-23 07:04
Short answer: No, not yet.

Duplicate of:
- #2055
- #2844 (which itself is to some extent duplicate of #2802 )

I close this issue, but you can follow the progress in the aforementioned issues. You can also express your opinion and suggestions there as well. Any suggestion and contributions is most welcome.

**Closed by mmahmoudian** 2022-09-23 07:04 UTC
Labels: question
