### ISSUE TITLE
[Ubuntu 21.04] Qt: Session management error

### ISSUE THREAD

**Issue by asamofal** [flameshot-org/flameshot#1583] opened 2021-04-26 12:14 UTC
**Flameshot version**
Flameshot v0.9.0 _(Compiled with Qt 5.12.8)_

**Describe the bug**
`flameshot gui` doesn't start anything. Doesn't matter how to install. I've tried flatpak, snap, .deb package.

**To Reproduce**
```
$ flameshot gui 
or 
$ flatpak run org.flameshot.Flameshot

// syslog
Apr 26 15:12:05 laptop systemd[2025]: Started app-flatpak-org.flameshot.Flameshot-37050.scope.
Apr 26 15:12:05 laptop org.flameshot.Flameshot[37061]: Qt: Session management error: None of the authentication protocols specified are supported
Apr 26 15:12:05 laptop systemd[2025]: app-flatpak-org.flameshot.Flameshot-37050.scope: Succeeded.
```

**System Information**
Ubuntu 21.04 (5.11.0-16-generic)
GNOME Shell 3.38.4
Wayland

**Comment by borgmanJeremy** [comment] 2021-04-26 18:04
Before flameshot gui will do anything the flameshot daemon needs to be active.

Please start flameshot from the gnome menu before running "flameshot gui" or run simply "flameshot" in another terminal.

**Comment by asamofal** [comment] 2021-04-27 08:41
@borgmanJeremy Thanks, can confirm that it works for .deb package installation version. 
But there's still a problem with flatpak version.

```
$ flatpak run org.flameshot.Flameshot
Qt: Session management error: None of the authentication protocols specified are supported
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed

$ flatpak run org.flameshot.Flameshot gui
```
I get just a notification about the error:
![flameshot-flatpak-issue](https://user-images.githubusercontent.com/2729547/116211742-cdfa0600-a74c-11eb-85c7-ef10f3d97a37.png)

Syslog is clear in this case:
```
Apr 27 11:37:01 laptop systemd[2064]: Started app-flatpak-org.flameshot.Flameshot-18423.scope.
Apr 27 11:37:01 laptop systemd[2064]: app-flatpak-org.flameshot.Flameshot-18423.scope: Succeeded.
```
Are there any other logs somewhere? Or flameshot just catch the errors and show me this sweet notifications?

**Comment by borgmanJeremy** [comment] 2021-04-27 18:39
Ah ok, for flatpaks this is a duplicate of #1560

**Closed by borgmanJeremy** 2021-04-27 18:39 UTC
