### ISSUE TITLE
Ability to set fixed layout for buttons

### ISSUE THREAD

**Issue by xahon** [flameshot-org/flameshot#3195] opened 2023-05-13 10:04 UTC
### Feature Description

Currently, buttons are placed underneath the selection if it's big enough and around the selection otherwise. I often select small regions and buttons are placed in seemingly random order and it's hard enough to find the needed button. May be there should be an option to lay buttons out in a predictable fixed order to be always in one line under the selection rect?

**Comment by mmahmoudian** [comment] 2023-05-15 19:20
Duplicate of #573

Please make sure you have searched among open and closed issued before creating a new one. This would save everyone's time. Thanks.

**Closed** 2023-05-15 19:21 UTC
Labels: Duplicate, Enhancement

**Comment by xahon** [comment] 2023-05-15 19:25
@mmahmoudian well, I'm not sure I was able to find such a duplicate in a very generic issue

**Comment by mmahmoudian** [comment] 2023-05-15 19:48
Of course I don't remember the issue numbers by heart. I just remembered such topic was at some point discussed, and all I did was to search "UI" and open few issues that sounded relevant.

Anyways, you can follow the progress in that issue. You can also up vote comments and ideas if you agree with them.

**Comment by xahon** [comment] 2023-05-15 19:51
I guess a better way is to go from general to specific and fix each problem in separate branches
