### ISSUE TITLE
Flameshot problem on KDE wayland

### ISSUE THREAD

**Issue by Dansito** [flameshot-org/flameshot#2463] opened 2022-02-28 15:28 UTC
### Flameshot Version

flameshot 11.0.0-4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux 

### Description

Well, as I said in the title, I have a problem in KDE with the wayland session, it happens that if I run flameshot there, first there is a kind of weird lag, I get a black screen for 1 second and then the normal flameshot comes out this is one of the problems, the other problem is that normally I save the captures that I make with flameshot in the clipboard, it happens that in the session of wayland worspace-plasma it saves a capture in /tmp/ something  weird, and finally I cancel la capture save the screenshot at the address above,  i don’t want to take 2 captures when I save it to the clipboard with flameshot, I also think it’s the cause of the lag

None of these problems happen to me in the x11 session, if anyone knows how to fix it please tell me, wayland feels a bit better for normal use and xorg is somewhat insecure nowadays.

PD: I have xdg-desktop-portal installed.

### Steps to reproduce

Install flameshot from pacman and run flameshot gui

### Screenshots or screen recordings

![imagen](https://user-images.githubusercontent.com/84112405/156009334-cb1beed3-2811-4e0c-8418-1238ceb1d2c3.png)

### System Information

Arch linux
Kernel : 5.15.25-1 LTS
Wayland
DE: Kde 5.24.2

**Comment by altuhovsu** [comment] 2022-03-06 15:49
For me Screenshot to Clipboard is not working.
I see message "Capture saved to clipboard. ", but nothing in the clipboard (can't paste in Krita for example)

System Information

```
Flameshot v11.0.0 (11.0.rc1-1)
Compiled with Qt 5.12.8
linux: 5.13.0-32-generic
Kubuntu: 21.10
Wayland
KDE 5.24.2
```

**Comment by borgmanJeremy** [comment] 2022-04-05 15:49
This is intended behavior due to the way the KDE Wayland screenshot API worked. We just merged a patch to have kde wayland use XDG-portal so you might want to install flameshot-git from the AUR and see if that helps.

**Closed** 2022-04-06 22:57 UTC
Labels: Unconfirmed Bug, Wayland
