### ISSUE TITLE
Blurring doesn't hide text

### ISSUE THREAD

**Issue by kramer65** [flameshot-org/flameshot#121] opened 2018-02-20 09:54 UTC
I love Flameshot and use it on a daily basis. But one thing is a real problem for me. Blurred sensitive text can still be read. Since I work in the medical industry, blurring patient information is extremely important. Have a look at the screenshot below though. If you look closely, you can still read the first part of the text. 

When I used to work on a mac I used Monosnap, which does an awesome job at blurring. Is it somehow possible to make the blurring resemble that of Monosnap?

Is this blurring a setting somewhere or can this be marked as a bug?

![no secret](https://user-images.githubusercontent.com/596581/36417391-143e72b4-162c-11e8-88f2-b88fa34d335c.png)

**Comment by vendforce** [comment] 2018-02-20 19:47
go over it twice. it will blur it out

**Comment by lupoDharkael** [comment] 2018-02-20 22:07
I've made it more blurry with the last commit. The actual implementation is not ideal as it requires 3 iterations of the Qt's built in blur. The perfect solution would be to implement a specific blur and be able to control the level of blur with the mouse wheel. I think Deepin's screenshot tool has an implementation, I should check it.
I hope the blur is enough with the last change while I investigate the implementation of a specific blur algorithm.

**Comment by kramer65** [comment] 2018-04-09 13:55
Hi @lupoDharkael - Thanks for the extra blur. Unfortunately I don't think it's enough for me. As you already suggest I think you need a different kind of blurring algorithm. I would really suggest to have a look at the blurring of Monosnap. Maybe someone on the interwebs knows what kind of algorithm that is.

**Comment by mbirth** [comment] 2018-06-23 12:32
Could you make the blurring according to the selected pencil width? Because blurring out big headings often needs multiple passes. It would be awesome if we could just crank up the mouse wheel and only blur it once.

**Comment by reitzig** [comment] 2018-10-09 19:39
Seconded. With 0.5.1 (trunk in Ubuntu 18.04 repos):

![image](https://user-images.githubusercontent.com/4246780/46693869-62420300-cc0b-11e8-8ca9-27ba3d345570.png)

### Workaround

Get more area under the blur and/or repeat in different orientations.

Single pass, higher box: 
![image](https://user-images.githubusercontent.com/4246780/46693913-8a316680-cc0b-11e8-883c-cd7db0cc8877.png)

Four passes, once along each diagonal:
![image](https://user-images.githubusercontent.com/4246780/46693942-9caba000-cc0b-11e8-848e-dc361d8cbc33.png)

**Comment by reitzig** [comment] 2018-10-09 19:40
I seem to remember Shutter's blurring tool to be quite effective. I think they averaged color in small segments, and then shuffled those, or something like that.

**Comment by spirituallyinsane** [comment] 2018-11-12 20:46
> I seem to remember Shutter's blurring tool to be quite effective. I think they averaged color in small segments, and then shuffled those, or something like that.

Yes, Shutter uses a "pixelate" or "mosaic" filter instead of a Gaussian blur.  This is particularly useful when blurring high-contrast things like text.

**Comment by RealOrangeOne** [comment] 2019-01-02 16:56
A simple blur like this does have its place. Perhaps an additional tool to pixelate rather than blur would be better. I can imagine using a blur in a high-contrast photo would look much nicer than a pixelation.

Being able to control the blur amount would be quite useful too!

**Comment by reitzig** [comment] 2019-01-02 17:40
A place for artistic effect, maybe. But if it's about obfuscation, it better _obfuscate_.

**Comment by tastytea** [comment] 2019-01-26 03:31
The reason why blurring/pixelation looks better than blackening is that part of the information is kept. This part can always be recovered and the missing information can be extrapolated. This works especially well with text. **Blurring should never be used to obfuscate anything sensitive!**

**Comment by sgbeal** [comment] 2019-04-18 11:11
User version 0.5.1-1 on Mint Linux i'm massively underwhelmed at having to re-blur text/icons multiple times to make them unreadable. As @reitzig points out, the blur that's implemented is fine for artistic effect, but this is *not an artistic tool* - it's one for posting screenshots, and making areas of screenshots unreadable is an *extremely* common operation... which we have to repeat multiple times just to get a blurry-enough effect (making it exceptionally tedious).

This screenshot was just made from this github page, using a single pass of the blur tool:

![image](https://user-images.githubusercontent.com/235303/56357056-d2dd6400-61da-11e9-9f1d-1037414caee9.png)

It clearly (no pun intended) demonstrates that the text below the blur is not obfuscated all that well.

**Comment by Tc-001** [comment] 2020-07-10 16:58
Could it be that the blurring also "feathers" the edges of the blur area adding transparency?

Let's say I have a image that I want to blur
![image](https://user-images.githubusercontent.com/55956895/87177232-fc087980-c2e3-11ea-89e8-3a63bec9b1f9.png)

What I believe is happening is that the selected area get blurred **(while surrounded by transparency)**, cropped, then pasted back
![image](https://user-images.githubusercontent.com/55956895/87178631-1cd1ce80-c2e6-11ea-8f84-6ef62bc5e270.png)

Notice the same thing with the edges of the letters "sticking out" as with a actual use of the tool
![image](https://user-images.githubusercontent.com/55956895/87179047-c87b1e80-c2e6-11ea-9e1b-1c1eab022f1f.png)

Proposed solution:
I think that the easiest way to fix this is to have a larger initial area selected to get blurred, but then the blurred result to get cropped before pasting it back, or some way of removing any alpha transparency before the blurred result gets applied

**Comment by borgmanJeremy** [comment] 2020-07-10 17:31
Check out this for a solution using pixelation https://github.com/lupoDharkael/flameshot/issues/774

**Comment by borgmanJeremy** [comment] 2020-09-04 14:26
This is merged and will be present in the next release.

**Closed by borgmanJeremy** 2020-09-04 14:26 UTC
Labels: 0.6, enhancement

**Comment by mokkin** [comment] 2021-02-16 14:55
On the actual release candidate the issue is still there. I know how to work around this with two or three times blurring, but for users with so many "ideas" this will be difficult.

v0.9.0rc1 on Ubuntu 20.04

![grafik](https://user-images.githubusercontent.com/2938748/108079360-07d4cf00-706f-11eb-8293-4d22a03162d3.png)

**Comment by borgmanJeremy** [comment] 2021-02-16 14:56
@mokkin increase the size to greater than 0 (ie scroll up)
