### ISSUE TITLE
Anchor the toolbar "bubbles" so they don't move around so much

### ISSUE THREAD

**Issue by eamodio** [flameshot-org/flameshot#1412] opened 2021-03-02 04:04 UTC
It's kind of neat looking that the toolbar icons move around the selection based on its size, but I find it hard to use -- as they move around. IMHO, it would be nice to have a set of horizontal buttons anchored to the bottom right and another set of vertical buttons also anchored to the bottom right. These 2 "toolbars" are then located (typically) very close to the mouse cursor, and each toolbar could serve a different function -- e.g. one toolbar is about annotations, and one is about saving/etc or something along those lines.

**Comment by mmahmoudian** [comment] 2021-03-03 13:19
Duplicate of #573

**Comment by mmahmoudian** [comment] 2021-03-03 13:19
might be also related to  #638

**Closed** 2021-03-03 16:56 UTC
