### ISSUE TITLE
Screenshots not saved to Save Path

### ISSUE THREAD

**Issue by slightlyfaulty** [flameshot-org/flameshot#1836] opened 2021-08-22 21:49 UTC
**Flameshot version**
41ca51bc
Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**
Saving a captured area always saves directly in my home folder. It does not use the **Save Path** set in the configuration GUI.

**To Reproduce**
Change **Save Path** to something random. Capture an area of the screen and click save. The screenshot file is saved under `~/`.

**Expected behavior**
Screenshot file should be saved to the specified **Save Path**.

**Additional info**
Using the `-p` cli option works as expected.

**System Information**
Arch Linux
KDE Plasma 5.22.4

**Comment by mmahmoudian** [comment] 2021-08-23 05:04
@slightlyfaulty would you please provide your config file (`~/.config/flameshot/flameshot.ini`)

**Comment by slightlyfaulty** [comment] 2021-08-23 17:37
<details>
<summary>flameshot.ini</summary>

```ini
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\f\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\a\0\0\0\v\0\0\0\xe)
checkForUpdates=false
contastUiColor=#b4001f
contrastOpacity=76
contrastUiColor=#00b0b1
disabledTrayIcon=true
drawColor=#ff3e3e
drawFontSize=8
drawThickness=5
filenamePattern=screenshot-%Y%m%d-%H%M%S
saveAfterCopyPath=/home/saul/Filebin
savePath=/home/saul/Filebin
savePathFixed=false
setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)
showStartupLaunchMessage=false
startupLaunch=false
uiColor=#ff005d
undoLimit=100
uploadHistoryMax=25

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Return
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_MARKER=M
TYPE_MOVESELECTION=
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

</details>

**Comment by veracioux** [comment] 2021-08-23 19:00
@slightlyfaulty When you click save, do you get a file dialog first? Does the dialog open in the configured directory?

Using your config on my system (Arch, i3wm), the save function works correctly. Except for a weird file name showing up in the dialog, but you can fix that:

Just change the config line
`setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)`
to
`setSaveAsFileExtension=.png`

This is a bug that was introduced by a previous version of flameshot and got fixed subsequently, but you were left with an older version of your config.

**Comment by slightlyfaulty** [comment] 2021-08-23 19:17
I changed that setting to `setSaveAsFileExtension=.png` but it hasn't made any difference to the save location. In a previous version I noticed the filename bug, but it seems like it's fixed in the latest commit.

Saving a screenshot does not open a file dialog anymore since updating to the latest commit. Now it saves instantly and shows a nice desktop notification. This is a welcome improvement, if only it saved to the configured Save Path.

**Comment by veracioux** [comment] 2021-08-23 19:44
@slightlyfaulty Can you kill the flameshot daemon (e.g. using `pkill flameshot`) and try that again? Sometimes issues can be caused by a version mismatch between the daemon and the `flameshot gui` command.

**Comment by slightlyfaulty** [comment] 2021-08-23 20:38
@veracioux No change unfortunately.

For reference, this is the desktop notification that pops up after clicking save on a screenshot:

![screenshot-20210823-212057](https://user-images.githubusercontent.com/2036475/130516053-d7e97f6d-cfcf-47cc-b066-f09002ea8d7a.png)

**Comment by veracioux** [comment] 2021-08-23 22:07
@slightlyfaulty I'm sorry, due to my clumsiness I wasn't using the correct flameshot version so I wasn't getting the bug. I have identified the error and fixed it in a pull request. Please install flameshot from the PR and let me know if everything works as expected.

**Comment by slightlyfaulty** [comment] 2021-08-24 00:12
Yup, works perfectly! 🥳

**Comment by slightlyfaulty** [comment] 2021-08-24 00:20
Oops I may have spoken too soon. My cwd was the same as my configured save path, so it looked like it worked. But I'm actually still seeing the same issue.

**Comment by veracioux** [comment] 2021-08-24 00:25
@slightlyfaulty Make sure that both the running daemon and `flameshot gui` use the same flameshot version. If that doesn't work, I'll look into it tomorrow because I have to go sleep now :)

**Comment by slightlyfaulty** [comment] 2021-08-24 00:26
Nope I just cloned the wrong branch. It's working 😆

I did like the dialog-less saving previously. But I guess that wasn't intended...

**Comment by veracioux** [comment] 2021-08-24 00:31
> I did like the dialog-less saving previously. But I guess that wasn't intended...

@slightlyfaulty That's what the `--path` option is for.

**Comment by mmahmoudian** [comment] 2021-08-24 05:32
@slightlyfaulty & @veracioux should we consider this closed as @veracioux was super kind, investigated and created a PR?

**Comment by slightlyfaulty** [comment] 2021-08-24 08:04
Fine by me. #1838 fixes the issue.

**Closed** 2021-08-24 10:17 UTC
Labels: Bug
