### ISSUE TITLE
Flameshot doesnt recognize adding external display

### ISSUE THREAD

**Issue by Claymeister** [flameshot-org/flameshot#3584] opened 2024-04-26 21:22 UTC
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.22631
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11

### Description

Simply put, i need to restart Flameshot for it to recognise i plugged in another display.
Otherwise, using it only puts the overlay on the primary screen. 

### Steps to reproduce

1. Run flameshot gui
2. Plug in another display
3. Try to screenshot
4. Realise the other display doesnt have the flameshot overlay

### System Information

Windows 11 Home Version 23H2
![image](https://github.com/flameshot-org/flameshot/assets/97406383/03b9f0eb-2dbe-46ba-b083-cfb3937cc3f3)

**Comment by mmahmoudian** [comment] 2024-04-27 03:44
Thanks but this is duplicate of an existing open issue. We strongly encourage our users to search among open and closed issues before creating a new one. It would primarily save your own time.

Thanks again for creating this issue.

**Closed** 2024-04-27 03:44 UTC
Labels: Unconfirmed Bug
