### ISSUE TITLE
Intercept active window

### ISSUE THREAD

**Issue by yinxiulong** [flameshot-org/flameshot#1902] opened 2021-09-17 03:55 UTC
How to intercept the active window? Instead of choosing your own area！

**Comment by mmahmoudian** [comment] 2021-09-17 05:08
I assume by "intercept" you mean take a screenshot from. When you run the command `flameshot gui` you will have the option to select the region (of course you can use <kbd>Ctrl</kbd>+ <kbd>a</kbd> to select all of the active monitor), if you want to capture one monitor you can use `flameshot screen` and if you want to capture everything in all monitors you can use `flameshot full`.

**Comment by yinxiulong** [comment] 2021-09-17 05:28
I just want to select a window, not the whole screen.

**Comment by borgmanJeremy** [comment] 2022-07-07 00:54
duplicate of #334

**Closed by borgmanJeremy** 2022-07-07 00:54 UTC
Labels: question
