### ISSUE TITLE
flameshot not usable when fractional scaling is used (Ubuntu)

### ISSUE THREAD

**Issue by crysman** [flameshot-org/flameshot#1296] opened 2021-02-10 02:25 UTC
**Flameshot version**
0.8.5 (Flatpak version
![image](https://user-images.githubusercontent.com/5269350/107455304-e778b200-6b4e-11eb-8826-571cadf8876d.png)

I tried first verbatim apt version (0.8.3-2) which behaves the same. 

**Describe the bug**
flameshot not usable when fractional scaling is used - only part of desktop view is "visible" to flameshot

**To Reproduce**

1. activate fractional scaling, set e.g. 150%
![image](https://user-images.githubusercontent.com/5269350/107455533-4e966680-6b4f-11eb-8a7d-6e53fd69961b.png)
2. try to capture screenshot in bottom-right area - not possible

**Expected behavior**
be able to capture whichever part of the screen

**System Information**
`Ubuntu 20.10, 5.8.0-41-generic #46-Ubuntu SMP`

**Comment by mmahmoudian** [comment] 2021-02-10 10:42
@crysman Are you using Wayland or Xorg?

Also, Possible duplicate of #748,  #724 and  #564.

**Comment by duvh93** [comment] 2021-02-10 19:19
> @crysman Are you using Wayland or Xorg?
> 
> Also, Possible duplicate of #748, #724 and #564.

Is there any work in progress to fix this?

**Comment by borgmanJeremy** [comment] 2021-02-10 20:55
#564 has the latest progress. The root cause is buried deep in qt it seems so progress is slow.

**Closed** 2021-02-10 20:55 UTC

**Comment by tfactor2** [comment] 2021-07-13 10:35
Running the flameshot with `QT_SCALE_FACTOR=0.8` solved my problem on PopOs 21.04 with KDE 5.21.4 on Qt 5.15.2 (XOrg).

**Comment by zhongdongy** [comment] 2023-02-06 13:32
Version v12.1.0 on Zorin OS Pro 16 will flash and the prompt text after running `flameshot gui` keeps changing its size. I  have fractional scaling enabled on my Thinkpad T14 2022, so I tried:

```bash
QT_SCALE_FACTOR=1.5 flameshot gui
```

And it works like a charm!

**Comment by kasie-zhang** [comment] 2023-02-25 03:56
```bash
# start flameshot with parameter
env QT_AUTO_SCREEN_SCALE_FACTOR=1 flameshot

# if command above worked, you can save blow setting to your profile
# then reboot you device
echo "export QT_AUTO_SCREEN_SCALE_FACTOR=1" >> ~/.profile
reboot
```

It worked on ubuntu 22.04.1 LTS, with Fractional Scaling open, Scale set to 125%
