### ISSUE TITLE
Screenshot tools & Sidebar appear on wrong monitor on Windows

### ISSUE THREAD

**Issue by TinyBabyOwl** [flameshot-org/flameshot#1522] opened 2021-03-30 23:07 UTC
**Flameshot version**
0.9.0

**Describe the bug**
When selecting an area for a screenshot the screenshot tools appear on my leftmost monitor.

Here's what it looks like: 
![Problem](https://i.imgur.com/KX0IS2k.png)

Here's my display set up:
![Display Setup](https://i.imgur.com/SfuHgU3.png)

**To Reproduce**
With two monitors hit printscreen and select an area on one monitor of an extended display

**Expected behavior**
Tools should appear below selection window. Sidebar should be on primary monitor.

**System Information**
Windows 10

**Comment by mmahmoudian** [comment] 2021-03-31 05:54
@TinyBabyOwl Isn't this duplicate of #1440?

**Comment by TinyBabyOwl** [comment] 2021-03-31 06:00
> 
> 
> @TinyBabyOwl Isn't this duplicate of #1440?

Ah yes that looks like the same issue. Sorry I searched and couldn't find it. My search skills must be weak.

**Comment by mmahmoudian** [comment] 2021-03-31 06:03
No worries, please close this issue and add some text to #1440 and add the first and second pictures you posted here to that issue as well.

**Closed** 2021-03-31 06:03 UTC
Labels: Waiting For Info
