### ISSUE TITLE
Clicking on "Take Screenshot" does not work

### ISSUE THREAD

**Issue by SavexG** [flameshot-org/flameshot#2966] opened 2022-10-29 05:42 UTC
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

EndeavourOS Linux x86_64

### Description

When starting flameshot it appears in the tray but when I click on "take screenshot" my cursor just shows that something is loading but then returns to normal after a while and nothing happens. 
When I click on "take screenshot" after that nothing happens anymore until I quit and start the application again.

When I press quit there is popup that says "unable to capture screen" and then the tray icon disappears.

typing "flameshot gui" in the terminal give this warning:
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
(no idea what this means)

Here is the terminal output from dbus-monitor --session sender=org.flameshot.Flameshot as described on the website

https://bin.snopyta.org/?94eb3c7b7932d2d4#9SoNGN4Fr4LrHaCjH75sJAxNRUWGdYLkXdweLABeSVAY

all the other buttons except for "open launcher" work as normal (I think).

I also tried installing flameshot-git from AUR and the appimage but both have the same issue for me 

### Steps to reproduce

start flameshot
klick on "take screenshot" 
nothing happens

### System Information

System:
  Host: save-endeavour Kernel: 6.0.5-arch1-1 arch: x86_64 bits: 64
    Desktop: GNOME v: 42.5 Distro: EndeavourOS
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Display: wayland server: X.Org v: 22.1.4 with: Xwayland v: 22.1.4
    compositor: gnome-shell driver: gpu: amdgpu resolution: 2560x1440~165Hz
  OpenGL: renderer: AMD Radeon RX 6600 XT (navi23 LLVM 14.0.6 DRM 3.48
    6.0.5-arch1-1) v: 4.6 Mesa 22.2.1

Screen 0: minimum 16 x 16, current 2560 x 1440, maximum 32767 x 32767
XWAYLAND0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 600mm x 340mm
   2560x1440    164.90*+
   1920x1440    164.87  
   1600x1200    164.88  
   1440x1080    164.85  
   1400x1050    164.88  
   1280x1024    164.93  
   1280x960     164.80  
   1152x864     164.93  
   1024x768     164.99  
   800x600      164.72  
   640x480      164.26  
   320x240      163.69  
   1920x1200    164.87  
   1680x1050    164.82  
   1440x900     164.86  
   1280x800     164.81  
   720x480      164.67  
   640x400      164.67  
   320x200      161.83  
   2048x1152    164.90  
   1920x1080    164.83  
   1600x900     164.77  
   1368x768     164.98  
   1280x720     164.71  
   1024x576     164.94  
   864x486      164.71  
   720x400      164.23  
   640x350      164.46

**Comment by SavexG** [comment] 2022-10-29 05:46
https://bin.snopyta.org/?469d7b90eb83ace4#DHW93z6rYauiXRWV71cv6BFi4BbVQ8vjMoP3uDmT73r6

**Comment by mmahmoudian** [comment] 2022-10-29 06:14
Looks like a duplicate of #2880. Try installing `xdg-desktop-portal-gnome` and see if it works

**Closed** 2022-10-29 06:15 UTC
Labels: Duplicate, Unconfirmed Bug
