### ISSUE TITLE
Re: @mmahmoudian

### ISSUE THREAD

**Issue by alkaris2** [flameshot-org/flameshot#3182] opened 2023-04-30 02:54 UTC
@alkaris2 please mind your language and keep the conversation polite.

Flameshot is a free and Libre OpenSource software, all the discussions and decisions were public and you had every opportunity to express your opinion and participate in the discussions during the development.

If you don't like the change, feel free to use another tool, but never ever complain about changes when you couldn't even be bothered to contribute.

_Originally posted by @mmahmoudian in https://github.com/flameshot-org/flameshot/issues/2275#issuecomment-1039927153_
            

Conversation was polite, and I explicitly expressed my opinion AND participated in the discussions, but you just didn't like what I said because it hurt your feelings.  To say "never complain" is just you who can't take criticisms for your shitty contributions that essentially "downgrades" an existing feature. And hey to delete my comment from that post just goes to show you're afraid of criticisms, but hey you'll also delete this one too which will only further prove my point you're just another shitty dev with a huge ego who _"can't do no wrong"_ despite your words and actions being shitty when someone points out an issue to something you've created and taking it as some personal attack on your work.

**Comment by mmahmoudian** [comment] 2023-04-30 06:55
To others who are reading this:

## Actions taken so far

1. This issue is stored in Archive.org's Wayback Machine [[link](https://web.archive.org/web/20230430060737/https://github.com/flameshot-org/flameshot/issues/3182)]
2. I also submitted the request to the Wayback Machine to also store #2275 [[link](https://web.archive.org/web/20230430060846/https://github.com/flameshot-org/flameshot/issues/2275)]
3. The user is blocked from Flameshot organization with the message "In this repo we strictly believe in polite and civilized conversation"
4. This issue will be closed as I don't see how this thread can lead to improvement of the software
5. This issue will be marked as:
    - "won't fix" because FLOSS due to it's nature and license cannot be changed
    - "Invalid" because they did not follow this repo's guidelines
    - "Duplicate" because this is not the first troll nor the last
    - "Not Reproduced" because I did not delete this thread as he said I would ;)


## Some responses

> hey to delete my comment from that post just goes to show you're afraid of criticisms

This is a screenshot from the said thread (hint: last event in the thread):

![image](https://user-images.githubusercontent.com/390889/235338933-b362c28c-bf77-4909-9b01-ca61f2b90bbf.png)

That said, I 100% support what @borgmanJeremy did, and I most probably would have done the same. Trolls who are scared and are hiding behind pseudonym don't worth the time nor the effort. I'm investing time and effort in this particular comment/post to clarify once and for all what are my stands and why every move I make has a reason behind it.

>  And hey to delete my comment from that post just goes to show you're afraid of criticisms, but hey you'll also delete this one too which will only further prove my point you're just another shitty dev with a huge ego who "can't do no wrong" despite your words and actions being shitty when someone points out an issue to something you've created and taking it as some personal attack on your work.

Few points:
1. You never contributed and committed to the project (code, documentation, costs, negotiations, community, etc) so subsequently your voice has a very very low weight compared to others who have works and helped towards improving the software or experience fr others.
2. No one forced you to use Flameshot. You don't like it in the current state, move on to another software
3. Flameshot is FLOSS, so if you want to change something that the dev team would not like to have in the software, man-up and do it yourself.
4. This whole thread is a personal attack on me. A hilarious one, a petty one, a naive one, but an attack nonetheless.
5. Why do you and others like you think that polite people don't have an extended and enriched plethora of rude words and curses in their arsenal? Don't ever mistake "me being civilized" with "me being weak" kiddo :))
6. grow up

**Closed by mmahmoudian** 2023-04-30 06:55 UTC
