### ISSUE TITLE
Automatically save an in-progress screenshot

### ISSUE THREAD

**Issue by Vandesm14** [flameshot-org/flameshot#2906] opened 2022-09-12 19:18 UTC
### Feature Description

Sometimes I accidentally close the flameshot GUI or forget to hit Ctrl+C or Ctrl+S to copy/save the screenshot. It would be very beneficial to have an option to save the state or screenshot automatically. That way, if any accidents happen, the screenshot is saved somewhere.

The implementation of recovering a save would be a list or gallery of images, which can be opened back up in the GUI for further editing or actions (e.g., copying or saving).

**Comment by mmahmoudian** [comment] 2022-09-13 04:39
Duplicate of #2055.

**Closed** 2022-09-13 04:39 UTC
Labels: Duplicate, Enhancement
