### ISSUE TITLE
Ability to resize the drawn objects

### ISSUE THREAD

**Issue by edeandrea** [flameshot-org/flameshot#1745] opened 2021-07-23 17:44 UTC
Sometimes I'll do something, like draw a box. Then I'll add some text and realize I need to resize or move the box just a little bit. It seems once I'm done drawing an object I can't go back and change it. This would be a nice feature. Just as an example, its something I can do in the native macOS screen grabber/preview app.

**Comment by mmahmoudian** [comment] 2021-07-23 19:42
Already implemented in v0.10.0. Just deselect the tool you are using by clicking again on that tool's button, then click on the object you want to modify to select it and then change anything you want (scroll to change size, rightclick to change color, drag to reposition)

**Comment by edeandrea** [comment] 2021-07-23 19:59
I did all that but I'm not able to resize it. I can move it, change color, etc, but not re-size.

**Comment by mmahmoudian** [comment] 2021-07-25 12:32
@edeandrea Sorry to the delay in responding. You are correct, the resizing capability is not there as far as I can tell. Perhaps @thepurple who have implemented the post-drawing modifications can also confirm if this is not implemented or if it is possible and we should just add the proper documentations for users.

**Comment by borgmanJeremy** [comment] 2021-07-25 15:33
duplicate of #1712

**Closed by borgmanJeremy** 2021-07-25 15:33 UTC
Labels: Enhancement
