### ISSUE TITLE
Clicking on arrow aborts screenshot

### ISSUE THREAD

**Issue by Yajo** [flameshot-org/flameshot#2402] opened 2022-02-10 10:04 UTC
### Flameshot Version

Flameshot v11.0.0 (883e55c)
Compiled with Qt 5.15.3
linux: 5.16.5-200.fc35.x86_64
org.kde.Platform: 5.15

### Installation Type

Flatpak from Flathub

### Operating System type and version

Fedora Silverblue 35

### Description

Clicking on arrow aborts the screenshot.

### Steps to reproduce

1. `flatpak run org.flameshot.Flameshot gui`
2. Write text.
3. Click arrow.
4. Aborted!

### Screenshots or screen recordings

https://user-images.githubusercontent.com/973709/153384127-a0aebfa5-78b4-4224-959b-2a3d70548660.mp4

### System Information

![imagen](https://user-images.githubusercontent.com/973709/153384303-86c67bd9-0afd-484c-8fec-d138c4da910e.png)

GNOME 41, Xorg.

**Comment by mmahmoudian** [comment] 2022-02-10 10:48
duplicate of #2283 and #2353

**Closed** 2022-02-10 10:49 UTC
Labels: Bug, Duplicate
