### ISSUE TITLE
Pinned screenshot on linux can't be moved outside the screen

### ISSUE THREAD

**Issue by elie-g** [flameshot-org/flameshot#1786] opened 2021-07-29 19:53 UTC
**Flameshot version**
Version 0.10.1

**Describe the bug**
On Windows pinned screenshots can be moved outside the screen but on linux they cannot.

**To Reproduce**

1. Take a screenshot
2. Pin the screenshot
3. Try moving the pinned screenshot outside the screen

**Expected behavior**

I expected the same behaviour on linux as on windows.

It would be nice to be able to move a screenshot outside the screen like on Windows so it doesn't obstruct anything while I don't need it but still want to keep it pinned for later use.

**System Information**
Ubuntu 20.10 Groovy

**Comment by mmahmoudian** [comment] 2021-07-30 09:44
@borgmanJeremy I checked with Manjaro KDE and Flameshot v0.10.1 and it does not go out side of the screen. There has been a feature request (#984) for this and [it has been reported that it works on Windows](https://github.com/flameshot-org/flameshot/issues/984#issuecomment-802664458) but back then I tried with Flameshot v0.9.0 and0 [I could not reproduce the behavior on Windows either](https://github.com/flameshot-org/flameshot/issues/984#issuecomment-802761332). At the moment I don't have access to Windows machine to test this, but I wonder if this is something that can be addressed (unified across all platforms we support). I am puzzled to consider this discrepancy a bug or partial feature request 😅

**Comment by borgmanJeremy** [comment] 2021-09-14 02:03
I looked into this and it is not possible to move a widget off screen on X11  :( . https://forum.qt.io/topic/106141/move-qwidget-offscreen-on-linux I also independently tested this by hard coding negative coordinates. 

We can probably do some sort of cropping operation to give the illusion of moving it off the screen, but not sure how complicated that will be yet.

**Comment by borgmanJeremy** [comment] 2021-09-14 02:24
Actually much easier than I thought.... Will get the PR put in tomorrow. 
![Peek 2021-09-13 21-23](https://user-images.githubusercontent.com/46930769/133184266-e5b8eda5-abfa-436a-9f05-e9b2640e77e7.gif)

**Comment by mmahmoudian** [comment] 2021-09-14 06:49
@borgmanJeremy is it intentional to get cropped at a fraction of the rate of mouse movement (the mouse position drastically changes with respect to the pinned image)?

**Comment by borgmanJeremy** [comment] 2021-09-14 13:17
Nope, thats the bug I need to fix before merging :-)

**Comment by borgmanJeremy** [comment] 2021-09-14 16:20
@mmahmoudian what do you think the behavior should be in a multimonitor setup? 

We can either start truncating the pinned image when it moves past the edge of a screen (Easy)
We can move the pinned image to adjacent monitors and only clip when it hits the furthest edge (Harder)

**Comment by mmahmoudian** [comment] 2021-09-14 19:03
@borgmanJeremy at least on Plasma I can already move the pin from one monitor to another and I actually use that alot when I want to have side-by-side comparison. So I think I have missed what you are asking here.

**Comment by borgmanJeremy** [comment] 2021-09-14 19:16
It's okay, I think you answered my question

**Comment by mmahmoudian** [comment] 2021-09-14 19:36
@borgmanJeremy but isn't that managed by the window manager?

**Comment by borgmanJeremy** [comment] 2021-09-14 19:51
So the goal here is to create the illusion that the pinned image is moving off screen. We have to create this as an illusion because on the X11 window manager the widget cannot move outside the screen:
![image](https://user-images.githubusercontent.com/46930769/133323724-15ca20f7-b859-42cd-9d73-8657214fe920.png)



In order to accomplish this, I am cropping the pinned image as it moves "past" the edge of the screen:
![image](https://user-images.githubusercontent.com/46930769/133323810-be1eb916-78c7-4a0e-ba73-52bab06f8105.png)

This is simple for the case where we move below the origin because I just check if the projected coordinates are negative. But this gets pretty complicated for the positive range with multi monitor. The easy case is just to crop the pinned image to the monitor it was taken from. However what I heard from you is this is likely not desired.
![image](https://user-images.githubusercontent.com/46930769/133323973-347feb1d-1c3d-4ff3-9cf7-4d412e7409f8.png)


So what I will do instead is detect if any part of the pinned image will move off screen, and only then crop it. Some examples of how I think it should work. 
![image](https://user-images.githubusercontent.com/46930769/133324373-06049264-5154-469a-886a-e0eb2c9d0df8.png)

**Comment by mmahmoudian** [comment] 2021-09-15 07:04
@borgmanJeremy I'm not aware of the limitations, so here is just my possibly flawed understanding: in X11 all monitors together create a large rectangular "canvas" (showed as light gray dashed lines) and at the moment the pin window can move between monitors and also can practically go outside of the monitor region if and only if another monitor has expanded the "canvas". I think all we need to do is to detect the width and height of the "canvas" and create the illusion only when the pin window is pushed outside of this canvas:

![bitmap](https://user-images.githubusercontent.com/390889/133386473-a7e2f53d-8564-48d2-89da-36f0a21b3586.png)

**Comment by borgmanJeremy** [comment] 2021-09-15 16:12
@mmahmoudian Can you confirm that that is how it works on X11? I dont have a mixed monitor setup.

**Comment by mmahmoudian** [comment] 2021-09-15 16:36
@borgmanJeremy I did that before making the figures. The full pink rectangles are where I can already position the pin (Manjaro KDE Plasma)

**Closed** 2022-04-06 13:45 UTC
Labels: Needs Investigation, discussion
