### ISSUE TITLE
Can't create text with the text tool

### ISSUE THREAD

**Issue by hoschi** [flameshot-org/flameshot#1071] opened 2020-10-15 10:16 UTC
**Flameshot version**

```
~ > flameshot --version
Flameshot v0.8.1
Compiled with Qt 5.15.1
```

**Describe the bug**
Either I miss something completely or it simply doesn't work :sweat_smile: 

**To Reproduce**
Make screenshot, select text tool, cursor changes to crosshair ... nothing happens.

**Expected behavior**

Something should happen when I click, drag or type. How do I create text areas to type text into?

**System Information**

Arch

**Comment by hoschi** [comment] 2020-10-15 10:17
is #811 related? I don't know what "IME" is :(

**Comment by borgmanJeremy** [comment] 2020-10-15 12:53
Can you upload a .gif with a tool like "peek" ?

Once you hit the text button and the cursour chagnes to a crosshair, you must click somewhere on the screen and start typing.

**Comment by hoschi** [comment] 2020-10-15 13:06
![flameshot-text-tool-1071](https://user-images.githubusercontent.com/163128/96130261-f8dee400-0ef7-11eb-9d51-41bdd08bcc1c.gif)

It doesn't do anything on click

**Comment by borgmanJeremy** [comment] 2020-10-15 13:09
Can you ensure your locales are properly configured?

**Comment by hoschi** [comment] 2020-10-15 13:09
Is there a debug log I could paste or something else which brings you more insights?

**Comment by hoschi** [comment] 2020-10-15 16:50
@borgmanJeremy I don't understand what you mean

**Comment by borgmanJeremy** [comment] 2020-10-15 19:10
@hoschi Here are the directions for setting your locales on arch linux: https://wiki.archlinux.org/index.php/locale

**Comment by hoschi** [comment] 2020-10-27 07:05
my setup looks good to me:
```
/etc > locale                                                                                                          root@maxxgubbl 
LANG=de_DE.utf8
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
/etc > ll /home/hoschi/.config/locale.conf                                                                             
ls: Zugriff auf '/home/hoschi/.config/locale.conf' nicht möglich: Datei oder Verzeichnis nicht gefunden
/etc > cat /etc/locale.gen | grep '^[^#]'                                                                              
de_DE.UTF-8 UTF-8  
en_US.UTF-8 UTF-8  
/etc >                                                                                                                 
```

or do you see any problems?

**Comment by borgmanJeremy** [comment] 2020-10-27 12:52
No that looks okay to me.

**Comment by mmahmoudian** [comment] 2020-11-02 07:58
@hoschi I'm still trying to understand what happens. Would you please:
1. completely report your system information. At the moment all I know is that you are using Arch and a dmenu-like application. This page might save you some time: https://flameshot.js.org/#/data/issue-reporting

2. what happens when you select the text tool, click on the screen and just start typing, and while typing scroll to increase the size? I have the following hypotheses:
    - you don't see a textbox appearing and therefore you are not typing anything
    - the text size is super small that it is not rendered on the screen

**Comment by hoschi** [comment] 2020-11-19 07:21
1. the link leads to 404
2. just typing doesn't work either. Scrolling makes the tool size bigger, that works e.g. for rectangle tool, but doesn't bring me text either.

**Comment by mmahmoudian** [comment] 2020-11-19 13:34
@hoschi that message I sent was 17 days ago and during this past 17 days we migrated fully to our .org domain. 😉 
You can find the same page under this address:
https://flameshot.org/issue-reporting/

**Comment by hoschi** [comment] 2020-11-19 14:57
@mmahmoudian sorry, I try to respond faster :disappointed:

**Comment by mmahmoudian** [comment] 2020-11-19 15:17
@hoschi No worries, I just wanted to mention that why you got 404. In such a repo/software that has gained a development momentum recently, such "drastic" changes happen and there is no easy way to avoid that other that the way you did (you reported the error and I provided the update)

Please let me know if the explanation on that webpage is ambiguous or there is something that doesn't work for you.

**Comment by hoschi** [comment] 2020-11-26 07:05
> In such a repo/software that has gained a development momentum recently
wohoo :smiley: It is the best screenshot tool I saw for a long while in the Linux environment!

I use XFCE as base desktop environment and Xmonad as my window manager.

Here is the info from the page:
```
~ > flameshot --version
Flameshot v0.8.1
Compiled with Qt 5.15.1
```

Display Server Protocol: `X11`

```
~ > xrandr --listactivemonitors
Monitors: 1
 0: +*DP-2 3440/800x1440/335+0+0  DP-2
```

```
~ > lspci | grep -i 'vga\|3d\|2d'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)
```

```
~ > sudo lshw -class display
  *-display
       description: VGA compatible controller
       product: GP107 [GeForce GTX 1050 Ti]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nouveau latency=0
       resources: irq:140 memory:ed000000-edffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:ee000000-ee07ffff
  *-display
       description: VGA compatible controller
       product: HD Graphics 630
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:135 memory:ec000000-ecffffff memory:b0000000-bfffffff ioport:f000(size=64) memory:c0000-dffff
```

```
~ > uname -a
Linux maxxgubbl 5.8.10-arch1-1 #1 SMP PREEMPT Thu, 17 Sep 2020 18:01:06 +0000 x86_64 GNU/Linux
```

**Comment by mmahmoudian** [comment] 2020-11-26 11:29
@hoschi Thanks for completing the information. Based on these I realized that you are using an old version. The latest stable version is [0.8.5](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.5) and you are using 0.8.1 .

I wonder what method have you used to install Flameshot. The following are the options you could have used:
- AUR (at the moment is stuck at v0.8.3)
- Arch community repo (it is at the latest version: v0.8.5)
- Snap (v0.8.5)
- Flatpak (v0.8.5)
- AppImage (typically the user is in charge of updating the AppImage)
- built it yourself

I suggest you to update the Flameshot to the [latest version](https://github.com/flameshot-org/flameshot/releases/latest) and see if the issue persists. Please report back if the issue is solved or it is still there with the newest version of Flameshot.

**Comment by hoschi** [comment] 2020-11-26 16:31
It is just that the last system update is a while ago and I can't do one at the moment, because I test the stability of the system after switching from Nividia to Intel graphics. I tested the AppImage with the same result.

**Comment by jchook** [comment] 2020-12-31 01:38
I also have this issue on Flameshot 0.6 through 0.8.5 on Ubuntu 16.04 and 18.04 running Xmonad as the WM. 

I fixed it briefly by starting xmonad via `dbus-launch`, as described [in this comment](https://github.com/lupoDharkael/flameshot/issues/168#issuecomment-377851744), but then it stopped working again.

**Comment by borgmanJeremy** [comment] 2021-03-04 19:11
I wonder if this is related to #651 . Both these issues are the same locale, seems like a good clue.

**Comment by borgmanJeremy** [comment] 2021-03-04 19:15
I notice this looks wrong: https://github.com/flameshot-org/flameshot/blob/bca3c3d669992017c6ec7f9b5a26254738f79799/data/translations/Internationalization_de_DE.ts#L3

I think it should read de_DE

**Comment by borgmanJeremy** [comment] 2021-03-04 19:37
Actually I am unable to replicate this issue at all in a VM.

**Comment by jchook** [comment] 2021-03-06 21:50
@borgmanJeremy I also cannot seem to replicate this in a VM yet, however, I did notice some additional info on my host.

When I have no applications running and take a screenshot of my desktop background, the text input works properly. However, when I have a terminal or firefox open, that active application receives the text input (not flameshot).

For example, if I have my terminal open, invoke flameshot, use the text tool to type "test", it will not work. However, I see the word "test" entered into the terminal after closing flameshot.

**Comment by borgmanJeremy** [comment] 2021-03-19 01:04
Since we can't recreate this in a VM I'm not sure how to chase the problem down.

**Comment by jchook** [comment] 2021-03-19 01:29
Perhaps you could run Xmonad (with a minimal custom config that disables `focusFollowsMouse`) on your host?

I can reliably reproduce the issue without a VM across several OSes.

**Closed** 2021-12-28 18:48 UTC
Labels: Linux

**Comment by jchook** [comment] 2021-12-28 20:56
Still having issues on my end with the latest.

The first time I run `flameshot gui` I can use the type tool, but with subsequent invocations the type tool does not work.

**Comment by borgmanJeremy** [comment] 2021-12-28 21:00
I closed it since no one else can reproduce it in a vm and other xmonad users don't have the issue.

To me it strongly suggests it's an issue on your system, and unless we can replicate the issue there's really nothing that we can do on our end.

**Comment by mmahmoudian** [comment] 2021-12-28 22:16
@jchook can you reproduce it on a VM? It would be essential for us to have an environment that can reproduce this issue. Investigating this blindly is looking for a needle in a haystack. Considering that you are an Xmpnad user, it should be straightforward for you to create a VM, clone/copy your config and etc.

**Comment by jchook** [comment] 2022-03-04 01:18
This is now fixed for me 🎉
