### ISSUE TITLE
Some buttons not available when capturing region using gui -p <path>

### ISSUE THREAD

**Issue by MudcrabDev** [flameshot-org/flameshot#2597] opened 2022-05-11 01:35 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Pop! OS 22.04 5.17.5-76051705-generic

### Description

I have a custom shortcut set to run `flameshot gui -p ~/Pictures/` when I hit Super+Print. Since updating to flameshot 11 the Pin, Copy, and possibly other buttons are not available when capturing a region, not even if it is enabled in config. Config is saved after setting, but buttons still do not appear. I tried disabling all buttons except Copy and Pin Tool and when I tried to capture a region, no buttons are available.

While writing this report I discovered these buttons DO appear if `-p ~/Pictures/` is omitted from the command. It's possible these buttons are disabled by design if `-p` is used because it is implied the image will be saved. If that is the case I will say I consider it inconvenient design, because I have used the command `flameshot gui -p ~/Pictures/` as my catch-all command for snapping parts of the screen, whether I intend to save, copy, or pin the capture, and this behavior would mean I need separate commands (and therefore separate shortcuts) to do what I could previously do with a single command, and that is an unnecessary hassle. If this was intended behavior I kindly ask it to be reverted to its previous behavior that allowed Copy and Pin Tool buttons to appear when `-p` is invoked.

### Steps to reproduce

1. install flameshot: `sudo apt install flameshot`
2. remove/rename config `~/.config/flameshot/flameshot.ini`
3. set configuration in flameshot with `flameshot config`, disable all buttons except Copy and Pin Tool
4. run `flameshot gui -p ~/Pictures/`, no buttons should be available
5. run `flameshot gui`, buttons should now be visible

### Screenshots or screen recordings

Disable all buttons except the following:
![2022-05-10_20-00](https://user-images.githubusercontent.com/77289474/167749729-8763b93f-06c9-4e59-874d-6403c7cbe749.png)

Capturing with `flameshot gui -p ~/Pictures/` looks like this with no buttons available:
![2022-05-10_20-05](https://user-images.githubusercontent.com/77289474/167749788-15d0b52f-048b-4fb4-9d8c-0e23883afe25.png)

Capturing with `flameshot gui` makes them available again:
![2022-05-10_20-27](https://user-images.githubusercontent.com/77289474/167750518-3fa7a022-dd42-4e15-b086-6d03c56afd82.png)

### System Information

 OS: Pop 22.04 jammy
 Kernel: x86_64 Linux 5.17.5-76051705-generic
 Shell: bash 5.1.16
 Resolution: 1920x1080
 DE: GNOME 41.4
 WM: Mutter
 X11

**Comment by mmahmoudian** [comment] 2022-05-11 04:51
@MudcrabDev  

This is not a bug, it is briefly explained in [the release notes](https://github.com/flameshot-org/flameshot/releases/tag/v11.0.0):

> The CLI now supports pinning (`--pin`), uploading (`--upload`), and copying to clipboard (`--clipboard`).
Note that in case one of these options (or `--path`, `--raw` also) is used, an Accept button is shown and the Save, Copy, Upload, Pin, Open With buttons are hidden.

and it has been in detailed explained on our website:

https://flameshot.org/docs/advanced/commandline-options/#final-actions

I encourage you to to have a quick look at the link above to be able to use Flameshot efficiently and enjoy it :)

You can set the path in your config. There is no need to set it in the command itself every time.
-------

Additionally, this issue is duplicate of:

- #2275
- #2362
- #2365
- #2431
- #2399
- #2391
- #2370
- #2477
- #2526
- and potentially many more that I don't have time to search for

So I will close this issue.

**Closed by mmahmoudian** 2022-05-11 04:51 UTC
Labels: Unconfirmed Bug

**Comment by ppwwyyxx** [comment] 2023-12-20 12:56
This feels like an anti-feature to me. When I use `flameshot gui -p some/path`, I would like flameshot to use `some/path` if the screenshot is accepted, but I would still like to be able to copy the screenshot with buttons. I see no reason why this two feature should be exclusive and user has to choose one.

**Comment by mmahmoudian** [comment] 2023-12-20 13:27
@ppwwyyxx 

> would like flameshot to use some/path if the screenshot is accepted, but I would still like to be able to copy the screenshot with buttons. 

Then perhaps you should use the proper use of the CLI and use `--path` and `--clipboard` to achieve that. More information can be found here:

https://flameshot.org/docs/advanced/commandline-options/

> I see no reason why these two features should be exclusive and user has to choose one.

When user explicitly ask for an action (or set of actions), they will only get that/those action. If you want all actions available, you should not explicitly ask anything, but rather use `flameshot gui`.

**Comment by ppwwyyxx** [comment] 2023-12-20 13:48
> If you want all actions available, you should not explicitly ask anything, but rather use `flameshot gui`.

I want both save and copy actions available, but with the "save" action saving to a specific path given in the command line. `flameshot gui` alone cannot achieve this.

On the other hand, keeping the copy buttons when `--path` is given can achieve this. The fact that there are so many issues about it is an indicator of how counter-intuitive it is to remove the copy button in this case.

**Comment by carpii** [comment] 2024-12-29 23:17
I feel like hiding various buttons is a very poor design decision, and makes flameshot a lot less usable. 
The reason being, you have to know what you want to do with the screenshot when you invoke it from the commandline, which often isnt the case

I use a keyboard shortcut which lets me screencap a region, and then hit enter to accept it. From there, my script uploads it to a host, and copies the remote url into the clipboard.

But I dont always want to do this, sometime I just want to screencap it and open in gimp, or copy to clipboard

Now I have to pass --path to tell it Im saving to disk on accept, at which point open and copy buttons are no longer an option.
