### ISSUE TITLE
Does not start when I click on the icon after installation on (Gnome 43.6 / Debian 12 / Wayland )

### ISSUE THREAD

**Issue by MyNameIsTroll** [flameshot-org/flameshot#3248] opened 2023-06-28 19:40 UTC
### Flameshot Version

Flameshot v 12.1.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian 12 / Gnome 43.6 / Wayland

### Description

I install the software on Debian 12 from the appstore (Gnome 43.6 / Wayland), and the installation goes smoothly. 
I click on the software icon and nothing happens ... 
I launch the software from a terminal with the command 
`$ flameshot gui`
and it works. 

<details>
<summary>The dbus-monitor content</summary>

```
$ dbus-monitor --session sender=org.flameshot.Flameshot
signal time=1687980004.556989 sender=org.freedesktop.DBus -> destination=:1.160 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.160"
signal time=1687980004.557015 sender=org.freedesktop.DBus -> destination=:1.160 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.160"
method call time=1687980020.640483 sender=:1.165 -> destination=org.freedesktop.DBus serial=10 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1687980020.640629 sender=:1.165 -> destination=org.freedesktop.DBus serial=11 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameHasOwner
   string "org.a11y.Bus"
method call time=1687980020.640970 sender=:1.165 -> destination=org.freedesktop.DBus serial=12 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0='org.a11y.Bus'"
method call time=1687980020.641067 sender=:1.165 -> destination=org.freedesktop.DBus serial=13 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method call time=1687980020.641228 sender=:1.165 -> destination=org.a11y.Bus serial=14 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "ScreenReaderEnabled"
method call time=1687980020.641616 sender=:1.165 -> destination=org.a11y.Bus serial=15 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "IsEnabled"
```

</details>

### System Information

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8

System:
  Host: tower Kernel: 6.1.0-9-amd64 arch: x86_64 bits: 64 Desktop: GNOME
    v: 43.6 Distro: Debian GNU/Linux 12 (bookworm)
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nouveau v: kernel
  Display: wayland server: X.Org v: 1.22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell driver: dri: nouveau gpu: nouveau resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.3 Mesa 22.3.6 renderer: NV137

Monitors: 2
 0: +*XWAYLAND1 1920/600x1080/340+0+0  XWAYLAND1
 1: +XWAYLAND0 1920/600x1080/340+1920+0  XWAYLAND0

**Comment by mmahmoudian** [comment] 2023-06-28 22:23
Thanks for reporting. I modified your post to adjust the markdown styling.

This seems like a duplicate of the following:
- #3201
- https://github.com/flameshot-org/flameshot/issues/3213#issuecomment-1608238209

I searched "click" among the open issues and found it on the first page of results:

https://github.com/flameshot-org/flameshot/issues?q=is%3Aissue+is%3Aopen+click

Please make sure to search among open and closed issues before creating a new one. Thanks.

**Closed by mmahmoudian** 2023-06-28 22:23 UTC
Labels: Unconfirmed Bug

**Comment by MyNameIsTroll** [comment] 2023-06-29 16:09
Sorry, I looked it up but maybe not with the right words, and my English isn't very good ^^. 
Sorry for the inconvenience.

**Comment by mmahmoudian** [comment] 2023-06-29 18:28
Don't worry. I understand that sometimes finding the correct word to search is not easy. Thank you for investing time in improving Flameshot by reporting potential bugs 👍👍
