### ISSUE TITLE
Color Picker Won't Pick Any Colors

### ISSUE THREAD

**Issue by jetrosut** [flameshot-org/flameshot#1080] opened 2020-10-17 15:24 UTC
**Flameshot version**
Flameshot 0.8.4.

**Describe the bug**
Color picker won't pick any colors.

**To Reproduce**
1. Select a region to capture.
2. Hit spacebar.
3. Click on the button that lets you pick a color.
4. Hover the cursor and click on any color you want to pick (The cursor doesn't change like it does on Linux).

**Expected behavior**
Color picker should pick the color I am trying to pick.

**System Information**
Windows 10 1909

**Comment by Catwaiix** [comment] 2022-01-01 12:47
Thanks for such amazing program!

**Flameshot version:**
Flameshot 0.10.2 (f81a971) compiled with Qt 5.15.2

**Describe the bug:**
Color picker still won't pick any colors from the screen (just the ones from the panel "Active color" label).

**To reproduce:**

1. Select a region to capture.
2. Hit spacebar.
3. Click on the button that lets you pick a color.
4. Hover the cursor and click on any color you want to pick (The cursor doesn't change like it does on Linux).
?. You can try to drag and drop from the color picker button so active color preview will, indeed, change but it won't let you click for confirming

**Expected behavior:**
Cursor should change when using the color picker so it lets me choose the color I'm trying to pick.

**System information:**
Windows 7 (build 7601: Service Pack 1)

**Unrelated question:**
Where's color info (hex value) in the panel?

**Comment by veracioux** [comment] 2022-01-01 14:50
@Catwaiix Can you try the flameshot v11 beta, because we recently reworked the color grabber? Please also check the additional functionality that is explained in the popup box that appears when you click the **Grab color** button. Btw, the hex value is also displayed (and editable) in v11.

**Comment by Catwaiix** [comment] 2022-01-01 16:22
@veracioux
Flameshot v11.0.0 (4680dcd) Compiled with Qt 5.15.2 on winnt 6.1.7601.2.1.0.256.48 windows: 7sp1

The color grabber doesn't work with mouse, it seems like the app misbehaves with the precise color selection (without holding left click) and closes.
Pressing spacebar, holding left click, using left or right click will close post-selection-box, open a new window with the magnified pixels and hang blocking any further interaction until you manually close it.
In order to pick a color I need to click the `Grab color` button, hover the cursor and hit Enter. This is very inconvenient because the Enter key is too far and there's no way to remap it.
btw, hex value is correct, thanks for that!

**Comment by veracioux** [comment] 2022-01-01 17:06
@Catwaiix Thanks for the insight. I will investigate this in a Windows VM.

**Comment by veracioux** [comment] 2022-01-07 23:07
@Catwaiix Please check if pull request #2226 fixes the issue for you. You can conveniently download a pre-built binary by clicking "Artifacts" [here](https://github.com/flameshot-org/flameshot/runs/4744412123).

**Comment by Catwaiix** [comment] 2022-01-09 04:05
Flameshot v11.0.0 (9fe0690) compiled with Qt 5.15.2 running on windows 7sp1 (winnt 6.1.7601)

Indeed, the color grabber works now, I can pick a color successfully and the magnifier works properly allowing me to choose precisely any pixel. Idk if you may close this issue now.

I'm pretty happy, thanks for everything!!

**Comment by veracioux** [comment] 2022-01-09 07:42
@Catwaiix You're very welcome!

**Closed by veracioux** 2022-01-09 07:42 UTC
Labels: Bug, Windows
