### ISSUE TITLE
flameshot gui doesn't work

### ISSUE THREAD

**Issue by timsofteng** [flameshot-org/flameshot#1195] opened 2020-12-19 17:36 UTC
Hello. 
`flameshot gui` doesn't launch flameshot on freebsd. However flameshot work if i click on icon in tray when flameshot is running.

xorg
Freebsd 12.2
Quarterly repo

**Comment by mmahmoudian** [comment] 2020-12-20 11:18
Please report the Flameshot version.

**Comment by timsofteng** [comment] 2020-12-20 20:10
> Please report the Flameshot version.

0.8.3

**Comment by mmahmoudian** [comment] 2020-12-20 20:17
May I suggest to update your Flameshot first and see if the issue persists? Your version is already two versions behind (latest is 0.8.5). We don't have a large user-base in /.+BSD/ but as always we would like to improve Flameshot. It would be nice if we can know whether the latest version works or it also has the bug.

**Comment by timsofteng** [comment] 2020-12-21 22:33
@mmahmoudian 
Unfortunately 0.8.3 it latest version which I can get.

https://www.freshports.org/deskutils/flameshot/

**Comment by mmahmoudian** [comment] 2020-12-22 07:31
How about compiling it? The dependencies are listed on the freshports.org . Install those dependencies and then follow these instructions:

https://github.com/flameshot-org/flameshot#build

**Comment by malagacj** [comment] 2020-12-23 06:19
Hello, I have tried compiling it in Debian 10.7. I used Flameshot v0.8.5

The "flameshot gui" command doesn't launch anything.

I had previously installed Flameshot v0.6.0 (which is in the stable Debian Repository) and that one works fine when you launch it from the Terminal. The Icons don't work

**Comment by mmahmoudian** [comment] 2020-12-23 12:17
@malagacj I think I know what the issue is. Flameshot uses DBUS, therefore the flameshot should be running in the background (showing in the tray bar)  when you initiate the `flameshot gui`.
Try `( flameshot &; ) && ( sleep 0.5s && flameshot gui )` and please report back.

**Comment by malagacj** [comment] 2020-12-23 13:16
@mmahmoudian I tried this command as I didn't run `make install`:
`~/flameshot/build/src/flameshot &) && (sleep 0.5s && ~/flameshot/build/src/flameshot gui`

I made an Alias called flameshot instead. I also didn't type ";" after the first "&" of the command as it was giving me an error.

It did work! but it did something weird the first time I ran the command. At least on the terminal I called the command First.

![Flameshot_After_First_Close](https://user-images.githubusercontent.com/29704009/102999378-2e700100-4529-11eb-98b8-17d50169561e.png)

After I closed the GUI it took control over that First terminal and showed me this:

![Flameshot_After_First_Close](https://user-images.githubusercontent.com/29704009/102998908-67f43c80-4528-11eb-8d69-e726c447853d.png)

That behaviour didn't occur if I ran the command on a different Terminal instance. Just to let you know :)

**Comment by mmahmoudian** [comment] 2020-12-23 13:27
@malagacj that is because in the first half of the command (the one ending with `&`) is running the flameshot and sending it to background process. Then it waits for half a second in case loading flameshot on your system is slow, and ultimately it runs the `flameshot gui`. What you can do is to put flameshot in your autostart so what when you login to your computer, it runs in the background and from there onwards you just need to call `flameshot gui` (possibly through a keyboard shortcut like <kbd>prntscrn</kbd>)

As a small tip: for such applications that I don't need them immediately when I start my computer, I have a small script with timer that load them one by one with some time interval to distribute the load. Things like CopyQ, Flameshot, cloud sync, ... .

**Comment by dennisleexyz** [comment] 2020-12-24 03:11
I'm having the same issue even with Flameshot running in the background. (Arch Linux)
```
$ flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

**Comment by mmahmoudian** [comment] 2020-12-24 09:59
@dennisleexyz please report your system information, esp. whether or not you are on Wayland.

**Comment by dennisleexyz** [comment] 2020-12-24 19:29
X.org
Arch Linux (latest)
i3-wm
(Anything else?)

BTW, I found `flameshot gui` works fine if run from the shell where `flameshot` was launched, but anywhere else it doesn't.
```sh
$ flameshot gui # hangs with no output
$ time flameshot gui
flameshot gui  0.01s user 0.00s system 0% cpu 25.242 total
```

**Comment by mmahmoudian** [comment] 2020-12-24 20:31
@dennisleexyz out of curiosity, do you have notification daemon and a systray in your i3bar?

**Comment by dennisleexyz** [comment] 2020-12-25 03:24
i3bar builtin tray && deadd-notification-center

**Comment by borgmanJeremy** [comment] 2021-01-05 01:47
@dennisleexyz To make sure I understand. If you follow the process below you have an issue?

1. Open terminal and run ```./flameshot```
2. Open a new terminal and run ```./flameshot gui```

**Comment by dennisleexyz** [comment] 2021-01-05 03:32
Yes.

**Comment by dennisleexyz** [comment] 2021-01-07 04:05
I deleted the config, restarted Flameshot, and nothing changes. For reference, is what I get by default:
```ini
[General]
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
```

**Comment by borgmanJeremy** [comment] 2021-01-08 14:50
@dennisleexyz Sorry I am not able to help more. I created a clean Endeavor I3 install this morning, did pacman updates, and installed flameshot. I am not able to replicate the issue on this setup. This leads me to believe it is an issue with your setup. 

Maybe try installing endeavor i3 in a VM and comparing differences to your setup?

**Comment by mmahmoudian** [comment] 2021-01-08 15:26
I have a suggestion. How about if @dennisleexyz makes a VM that has the same issue and upload it for us to see and investigate?

**Comment by borgmanJeremy** [comment] 2021-01-08 15:47
@mmahmoudian a bash script or ansible playbook that configures a VM would be better so I don't have to download a 10GB+ image.

**Comment by borgmanJeremy** [comment] 2021-01-23 01:38
Closing this since we cannot come up with a way to replicate the issue.

**Closed by borgmanJeremy** 2021-01-23 01:38 UTC

**Comment by hubyhuby** [comment] 2021-04-16 16:29
I had the same problem on Ubuntu Mate 18.
Before launching with gui option, you need to have flamshot already launched in your notification bar...

**Comment by blinry** [comment] 2021-07-23 09:18
I have the same problem as @hubyhuby on Arch Linux, Xorg, and i3, using both the *flameshot* package, as well as the *flameshot-git* package. `flameshot gui` only works if the tray applet is running. For me, it doesn't matter in which terminal I run `flameshot gui` after that, it works everywhere.

**Comment by mmahmoudian** [comment] 2021-07-23 10:21
@blinry Do you have [dbus](https://dbus.freedesktop.org/doc/dbus-launch.1.html) running when you start your i3?

Basically you should have `exec dbus-launch --sh-syntax --exit-with-session i3` to start your [dbus](https://wiki.archlinux.org/title/D-Bus) daemon as Flameshot subcommands use dbus to communicate with the main Flameshot process. I have a hunch that you don't have dbus daemon running in your setup
