### ISSUE TITLE
Dropdown menu appears in screenshots

### ISSUE THREAD

**Issue by sporkfighter** [flameshot-org/flameshot#337] opened 2018-09-05 04:53 UTC
Flameshote 0.5.1-1(Debian)

I seldom want the Flameshot dropdown menu in my capture, but it shows up with a double-click to take a screenshot and doesn't go away until after the screenshot.

Ubuntu 18:04 
Gnome 3.28.2

![tuesday-sep-04-2018 09 42](https://user-images.githubusercontent.com/22015033/45071806-e80ee380-b08c-11e8-91fd-5bd84d17fc7e.png)

**Comment by AlfredoRamos** [comment] 2018-09-05 20:49
I'm not sure I understand what you're reporting.

If you want to show the menu, you can use the terminal as it's the only way right now to set a delay. For example:

```shell
flameshot gui -d 5000
```

It will take an screenshot after 5 seconds, time that you can use to show the menu.

If you do **not** want to show the menu, check if you can reduce the fade-out animation time in Gnome or in your compositor settings, which I think is the issue.

> doesn't go away until after the screenshot

You can't interact with the screen once you start the capture, if that's what you meant.

Also try to update to the latest stable version (currently 0.6.0).

**Comment by wesinator** [comment] 2018-10-30 14:40
@AlfredoRamos the issue is that double clicking the icon to take a screenshot will reopen the menu right before the screenshot window appears, causing the Flameshot menu to be captured over anything in that area of the screen.

This is a problem for screenshots because it blocks/overlays whatever is in that top right part of the screen with the Flameshot menu.

**Expected:** If possible, don't show the menu on double click
User should not have to change global GNOME animation settings to fix this.

**Comment by AlfredoRamos** [comment] 2018-10-30 18:08
@wesinator The system tray icon triggers the screen capture with just one click, it does not (at least for me) show the menu with double click but with a right click.

>  User should not have to change global GNOME animation settings to fix this.

Some issues depend on the user system, which is not something that can be fixed within the application.

Can you reproduce that issue using another DE that is not GNOME? because (using version 0.6.0) I can't.

**Comment by borgmanJeremy** [comment] 2020-10-14 02:35
This can also now be solved using the "launcher" feature in 0.8.x

**Closed by borgmanJeremy** 2020-10-14 02:35 UTC

**Comment by w3lifer** [comment] 2021-05-02 17:28
> This can also now be solved using the "launcher" feature in 0.8.x

How? This is really annoying. I'm using v0.9.0 (Qt 5.12.3).

**Comment by borgmanJeremy** [comment] 2021-05-02 17:35
Right click the icon and hit "open launcher ". Then add a delay

**Comment by w3lifer** [comment] 2021-05-05 12:49
When I double clicked the tray icon:

![Screencast 1](https://user-images.githubusercontent.com/14075412/117142462-67ae5c80-adb8-11eb-8850-fe85afcfa768.gif)

> Right click the icon and hit "open launcher ". Then add a delay

It is not comfortable.
For now, it's easier to right-click on the icon and select "Take screenshot" to solve this problem:

![Screencast 2](https://user-images.githubusercontent.com/14075412/117143371-6d587200-adb9-11eb-9734-adcd678aaba4.gif)

**Comment by mmahmoudian** [comment] 2021-05-05 15:18
@w3lifer alternatively you can have a keyboard shortcut for it.

**Comment by w3lifer** [comment] 2021-05-05 18:53
@mmahmoudian, maybe I don't understand, but what do you mean?: I can't find the keyboard shortcut.

**Comment by mmahmoudian** [comment] 2021-05-06 02:52
I meant add a keyboard shortcut to your Gnome to start taking screenshot with Flameshot using a keyboard shortcut usually people use the <kbd>PrintScreen</kbd> button:

As explained [here](https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en) you can modify Gnome shortcuts by:

1. Open the Activities overview and start typing Settings.
2. Click on Settings.
3. Click Keyboard Shortcuts in the sidebar to open the panel.
4. Click the row for the desired action. The Set shortcut window will be shown.
5. Hold down the desired key combination, or press <kbd>Backspace</kbd> to reset, or press <kbd>Esc</kbd> to cancel.

**Comment by w3lifer** [comment] 2021-05-06 08:47
@mmahmoudian, thank you.

![1](https://user-images.githubusercontent.com/14075412/117269283-d34c0480-ae60-11eb-8ece-a3f0f64a2f8c.png)

**Comment by w3lifer** [comment] 2021-09-27 09:40
> @mmahmoudian, thank you.
> 
> ![1](https://user-images.githubusercontent.com/14075412/117269283-d34c0480-ae60-11eb-8ece-a3f0f64a2f8c.png)

NOTE that in the "Command" field we must enter `flameshot gui`, not just `flameshot`)
