### ISSUE TITLE
Invert color

### ISSUE THREAD

**Issue by pedroflor** [flameshot-org/flameshot#1323] opened 2021-02-15 01:37 UTC
**Invert color feature**

A new option to allow "invert the color" of captured image.

![image](https://user-images.githubusercontent.com/3332674/107896601-1b682480-6f0d-11eb-8863-c0d687dd8b2d.png)

**Comment by borgmanJeremy** [comment] 2021-02-15 01:49
Good idea, but a duplicate of #689

**Closed by borgmanJeremy** 2021-02-15 01:49 UTC
