### ISSUE TITLE
Add automatic shading

### ISSUE THREAD

**Issue by dsirov** [flameshot-org/flameshot#2624] opened 2022-05-24 14:46 UTC
### Feature Description

I think it could be great to add automatic (no user control what-so-ever) shading.
This adds immediate "professional" feel.

Examples:
![image](https://user-images.githubusercontent.com/25965216/170063780-fd2f39bf-75bd-43c3-9a19-5367f54514e3.png)
![image](https://user-images.githubusercontent.com/25965216/170063875-2bb27f06-6a3c-49a1-96ff-5e3299d0a8ce.png)

Keeping doing great job!

[Idea taken from [ksnip](https://github.com/ksnip/ksnip)]

**Comment by mmahmoudian** [comment] 2022-05-25 12:29
Isn't this duplicate of #313 ?

**Closed as completed** 2022-06-01 13:29 UTC
Labels: Duplicate, Enhancement
