### ISSUE TITLE
Window of choosing an app to open pops out and disappears immediately

### ISSUE THREAD

**Issue by choyy** [flameshot-org/flameshot#2469] opened 2022-03-04 05:53 UTC
### Flameshot Version

```
$ flameshot -v 
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

OS: Manjaro 21.2.4 Qonos

### Description

When choosing an app to open, the window pops out and then disappears immediately. As the video shows.

### Screenshots or screen recordings

https://user-images.githubusercontent.com/68107073/156706946-d35f8231-f22c-45d2-b5df-2e5e0de8b383.mp4

### System Information

```
$ inxi --width 80 --system --graphics
System:
  Host: user Kernel: 5.16.11-2-MANJARO x86_64 bits: 64
    Desktop: KDE Plasma 5.24.2 Distro: Manjaro Linux
Use of uninitialized value in concatenation (.) or string at /usr/bin/inxi line 13826.
Graphics:
  Device-1: Intel CoffeeLake-S GT1 [UHD Graphics 610] driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX150] driver: nvidia v: 510.54
  Device-3: Chicony USB2.0 Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia gpu: i915 s-res: 1920x1080~Hz
    resolution: 1920x1080
  OpenGL: renderer: Mesa Intel UHD Graphics 610 (CFL GT1) v: 4.6 Mesa 21.3.7
```
I'm using Xorg.

**Comment by lilalkor** [comment] 2022-03-04 23:34
Can confirm. Have the same issue lately on Arch.

**Comment by mmahmoudian** [comment] 2022-03-05 18:25
Duplicate of #2342

**Closed** 2022-03-05 18:25 UTC
Labels: Unconfirmed Bug
