### ISSUE TITLE
Text annotations are not saving

### ISSUE THREAD

**Issue by danielrosehilljlm** [flameshot-org/flameshot#778] opened 2020-06-21 07:42 UTC
**Flameshot version**

Installed it through the repos. Running Ubuntu 20.04. Not sure how to check the current version.

**Describe the bug**

When I add text, the text does not save with the other layers added to the screenshot.

Screencast demonstration:

https://www.youtube.com/watch?v=e96rp1MrS2s

**To Reproduce**

1. Take screenshot.

2. Add text. 

3. Text does not render. I experienced this behavior both while attempting to apply other effects and while just attempting to add text to the file.

**Expected behavior**

**System Information**

Ubuntu 20.04 LTS with LXDE

**Comment by mmahmoudian** [comment] 2020-09-04 22:19
Nice demonstration 👍 can you check the flameshot version you have:
1. Open terminal
2. `flameshot --version`

**Comment by danielrosehilljlm** [comment] 2020-09-10 07:58
@mmahmoudian 

Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5

**Comment by mmahmoudian** [comment] 2020-09-10 08:06
out of curiosity, can you do something else after writing the text and before pressing enter to save? For example draw an arrow. I suspect that you are still in "edit" mode and the text it not finally applied to the screenshot when you save it. If my hypothesis is correct, we can quickly fix it, otherwise it needs few more back and forth to know how it happens.


P.s. a new version will be released very very soon with some fixes and improvements. If you don't want to wait, you can compile from the Git and have the changes right away 😉

**Comment by danielrosehilljlm** [comment] 2020-09-13 12:16
![demonstration](blob:https://imgur.com/1a9a5c07-3fa7-4994-a944-f77d0545b997)

Yes!

**Comment by mmahmoudian** [comment] 2020-09-13 15:55
@danielrosehilljlm seems my hypothesis was correct. Thanks for providing feedback.

**Comment by mmahmoudian** [comment] 2020-09-20 10:51
@danielrosehilljlm There is a [new stable version out](https://github.com/flameshot-org/flameshot/releases/tag/v0.8.0). Would you please confirm if the issue persists in the new version as well?

**Comment by danielrosehilljlm** [comment] 2020-09-24 18:54
@mmahmoudian Installed the new version and the issue persists. Also: when I add text but then try to copy the image to the clipboard, I cannot do so.

**Comment by mmahmoudian** [comment] 2020-09-24 18:59
@danielrosehilljlm as one more text, if you add more than one text, would texts other than the last one get saved?

**Comment by danielrosehilljlm** [comment] 2020-09-26 16:37
@mmahmoudian Interesting. If I add multiple layers of text, as you said, those before the last one are saved and rendered.

**Comment by borgmanJeremy** [comment] 2020-09-27 23:47
The issue is the hot keys essential act as interrupts. When ctrl+s is hit, the program instantly save the existing image. Tools do not commit any data to the image until another tool button is pressed. 

The fix is to process any in process tools before saving or copying. I **think** this is the behavior we want. An alternative is to only process certain tools. For example:

If you click to draw a line, and never "unclick" then hit ctrl+s should that in process line be saved? The consistent answer is yes, all tools are committed if in process.

**Closed** 2020-09-28 13:53 UTC
Labels: Bug
