### ISSUE TITLE
MacOS Catalina "Current master" . Builded App closing when open "Configuration menu".

### ISSUE THREAD

**Issue by cryerenable** [flameshot-org/flameshot#2050] opened 2021-11-06 18:54 UTC
Hello Again.
Catalina 10.15.0 - Catalina  10.15.7
Xcode 11-12.4
cmake 3.21.4
qt 5.15.2
**Current master**
The assembly of the project goes without problems on BigSure / Monterey and configuration menu working properly.
On Catalina, the project builds without problems, starts up, takes screenshots.
But when you try to enter the configuration menu, the application crashes.
in QTcreator on Catalina with **current master**  have error ` **no member named "MacOsBigSur" in "QOperatingSystem version"**`.
Minimal OS for current master is bigsur?Builded **current master** project on Monterey not support older version macOS(
How build project on bigsur/monterey for old macOS OS?

On Catalina src with tag v0.10.1 have no problem with  configuration menu.(with fix to images in /src/cmakelists..)

**Comment by mmahmoudian** [comment] 2021-11-07 09:26
@cryerenable thanks for the report, but please also mention the commit that you used for compiling. The "HEAD" or "current master" are not enough simply because they change as new commits are made.

**Comment by cryerenable** [comment] 2021-11-07 09:48
I took the last commits :
`Commits on Nov 5, 2021 445a4c68e81e876dbec78e53deaef4b5c3bac291`
and
`Commits on Nov 4, 2021 2c98fc6cfe3b7a589aec40caa5886cf76c325959`

**Comment by cryerenable** [comment] 2021-11-07 17:57
I decided to make a [video ](https://youtu.be/2QU4f9GkkQQ)confirmation of the bug with the Configuration Menu, but now even the build does not start from the last commit.

no problems with v0.10.1.  first build on video.
Weird.

**Comment by borgmanJeremy** [comment] 2021-11-07 18:38
Can you try starting from the terminal to see if there is an error printed? I have seen an issue on MacOs where something with Qt Single Application gets messed up.

**Comment by ks698** [comment] 2021-11-08 02:55
Building latest master (445a4c68e81e876dbec78e53deaef4b5c3bac291) on an M1 macbook air running big sur crashes for me when opening the config menu or taking a screenshot.

Here's my output from lldb:

```
2021-11-07 21:51:27.157683-0500 flameshot[50671:4236071] [qt.qpa.fonts] Populating font family aliases took 239 ms. Replace uses of missing font family "Sans-serif" with one that exists to avoid this cost.
flameshot was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 50671 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000100038dbc flameshot`ConfigHandler::value(this=0x000000016fdfd6e0, key=<unavailable>) const at confighandler.cpp:459:25 [opt]
   456 	        setErrorState(true);
   457 	    }
   458 	    if (m_hasError) {
-> 459 	        return handler->fallback();
   460 	    }
   461 	
   462 	    return handler->value(val);
Target 0: (flameshot) stopped.
```

**Comment by borgmanJeremy** [comment] 2021-11-10 00:26
I confirmed this and bisected with git. The offending commit was d142888

I will get a debugger on it in the next day or so and find the problem. This is the exact error:
```
libc++.abi.dylib: ____cxa_guard_acquire detected recursive initialization
```

**Comment by borgmanJeremy** [comment] 2021-11-10 00:48
Here is the backtrace 
![image](https://user-images.githubusercontent.com/46930769/141029166-e7370b4e-b4c6-4102-8e28-61cd217613a5.png)

**Comment by borgmanJeremy** [comment] 2021-11-10 00:50
Okay this seems to be caused if there is an error in the config file. Removing the config file at ~/.config/flameshot/flameshot.ini "fixes" the problem.

I'll spend some time figuring out why an invalid config crashes it.

**Comment by borgmanJeremy** [comment] 2021-11-15 17:39
Okay this is fixed on the master branch. The issue was we were #ifdef'ing out  a config parameter that is not displayed for Macos, but not every reference was compiled out so it was seg faulting.

**Closed by borgmanJeremy** 2021-11-15 17:39 UTC
Labels: Bug, MacOS
