### ISSUE TITLE
Flameshot not opening on Wayland

### ISSUE THREAD

**Issue by cfsmp3** [flameshot-org/flameshot#2996] opened 2022-11-29 05:18 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.11.3

### Installation Type

Linux .deb file just downloaded from your releases page

### Operating System type and version

Ubuntu 22.04.1 + Regolith + Wayland

### Description

Running flameshot gui doesn't open the usual area selection window.
This started happening after updating my Ubuntu 22.04.1 (Regolith flavor) to Wayland

https://bin.snopyta.org/?19ef8c6f1569e021#3Zq5wVJvnvkdj9KgX4Wse1EEAJetci6LhbwAW2YrvQYE

Interestingly, 
flameshot config

Seems to work fine.
I also have the tray icon.

I followed the 3 terminal instructions. The second one (plain flameshot) is the one that triggers D-Bus activity. However, flameshot gui does nothing - except show this message:

✦ ❯ flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

I tried setting that as an env variable with no luck.

### Steps to reproduce

run flameshot gui
Nothing happens

### System Information

1 - Ubuntu 22.04.1 with regolith (that's an collection if preconfigured i3 packages) with Wayland
2 - 
```
✦ ❯ swaymsg -t get_outputs
Output DP-3 'Dell Inc. Dell U4919DW GPDPXH3' (focused)
  Current mode: 5120x1440 @ 59.977 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    5120x1440 @ 59.977 Hz
    5120x1440 @ 29.978 Hz
    3840x1080 @ 59.968 Hz
    2560x1080 @ 60.000 Hz
    2560x1080 @ 59.940 Hz
    2560x1080 @ 59.978 Hz
    1920x1080 @ 60.000 Hz
    1920x1080 @ 60.000 Hz
    1920x1080 @ 59.940 Hz
    1920x1080 @ 50.000 Hz
    1600x1200 @ 60.000 Hz
    1280x1024 @ 75.025 Hz
    1280x1024 @ 60.020 Hz
    1280x800 @ 59.910 Hz
    1152x864 @ 75.000 Hz
    1280x720 @ 60.000 Hz
    1280x720 @ 59.940 Hz
    1280x720 @ 50.000 Hz
    1024x768 @ 75.029 Hz
    1024x768 @ 60.004 Hz
    800x600 @ 75.000 Hz
    800x600 @ 60.317 Hz
    720x576 @ 50.000 Hz
    720x480 @ 60.000 Hz
    720x480 @ 60.000 Hz
    720x480 @ 59.940 Hz
    720x480 @ 59.940 Hz
    640x480 @ 75.000 Hz
    640x480 @ 60.000 Hz
    640x480 @ 59.940 Hz
    640x480 @ 59.940 Hz
    720x400 @ 70.082 Hz

Output eDP-1 'Unknown 0x095F 0x00000000' (inactive)
  Available modes:
    2256x1504 @ 59.999 Hz
    2256x1504 @ 47.998 Hz
``

**Comment by mmahmoudian** [comment] 2022-11-29 06:12
@cfsmp3 Have you carefully followed this:
https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

**Comment by elwynelwyn** [comment] 2022-11-30 23:22
I'm getting the exact same behaviour (`flameshot config` works, tray icon visible, but `flameshot gui` prints `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` and then does nothing / exits immediately).

Vanilla Ubuntu 22.04, not running sway or anything wlroots
```
echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
```

**Comment by mmahmoudian** [comment] 2022-12-01 06:00
I'll close this. it seem like a duplicate of Gnome issues. that permission thing is also a Gnome thing which is explained on our website:
https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

**Closed by mmahmoudian** 2022-12-01 06:00 UTC
Labels: Unconfirmed Bug
