### ISSUE TITLE
Custom number Start number

### ISSUE THREAD

**Issue by Ericwln** [flameshot-org/flameshot#3314] opened 2023-08-22 07:59 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.11.3

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

ubuntu20.04

### Description

Start numbering when I need a custom serial number: say I want to start with 5, the next one with 6, and so on. Then end the current numbering function, select the input text, after completing the input text, I want to start numbering again, the default start from 1, or you can customize the restart label start; Does it have this function? Or how do I open this feature, thank you

### System Information

ubuntu20.04

**Comment by mmahmoudian** [comment] 2023-08-22 12:18
Duplicate of #2620

Although this is not possible at the moment, there is a **very easy trick** to pull it off as I explained here:

https://github.com/flameshot-org/flameshot/issues/2620#issuecomment-1133936985

**Closed by mmahmoudian** 2023-08-22 12:18 UTC
Labels: Unconfirmed Bug
