### ISSUE TITLE
Doesn't work on sway

### ISSUE THREAD

**Issue by fabifont** [flameshot-org/flameshot#1356] opened 2021-02-18 19:16 UTC
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.15.1

**Describe the bug**
Instant crash. This is the log:
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

**To Reproduce**
Type `flameshot` in your terminal.

**Expected behavior**
Launch `flameshot`.

**System Information**
Linux arch 5.10.16-arch1-1

**Comment by borgmanJeremy** [comment] 2021-02-18 19:18
What windows manager are you using

**Comment by fabifont** [comment] 2021-02-18 19:22
> What windows manager are you using

Sway

**Comment by borgmanJeremy** [comment] 2021-02-18 19:27
Do you have qt5-wayland installed? 

We use xcb on the backend so I suspect you are missing something to enable that.

**Comment by fabifont** [comment] 2021-02-18 19:29
> Do you have qt5-wayland installed?
> 
> We use xcb on the backend so I suspect you are missing something to enable that.

Now yes, flameshot doesn't crash anymore but clicking on the icon it does nothing. The log says: `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

**Comment by borgmanJeremy** [comment] 2021-02-19 01:17
Checkout this thread: https://github.com/flameshot-org/flameshot/pull/1272

Specifically:

>Yay! It works after properly starting xdg-desktop-portal!

**Comment by tinywrkb** [comment] 2021-03-01 16:52
It works for me with 0.9.0 but only once and after that it fails.  

I'm using the Flatpak from here https://github.com/flathub/org.flameshot.Flameshot but building it myself as Flathub is not updated.  

Flameshot doesn't do a good job handling `XDG_CURRENT_DESKTOP` it should split on `:` and try the first sub-string instead of the current randomly chosen order by the developer, [this is wrong](https://github.com/flameshot-org/flameshot/blob/5b0bb501dc513f16e93a6d72e06a222a2da6c404/src/utils/desktopinfo.cpp#L29).  
I don't remember where it's documented but the split in on colon.  
This is what I have in my system `XDG_CURRENT_DESKTOP="sway:GNOME:Unity:"`. This way I have OBS using the ScreenCast portal from the wlroots implementation, Gnome/GTK for the other desktop portals (except Screenshot), and Unity for the StatusNotifier protocol for the system tray instead XEMBED.

So currently we need to override `XDG_CURRENT_DESKTOP=sway` to make Flameshot work with Sway.

Successive captures fail with the error `org.freedesktop.DBus.Error.NoMemory` and argument `Cannot allocate memory` on dbus from `org.freedesktop.impl.portal.Screenshot.Screenshot`.  
I'm not sure if the fault is with Flameshot or xdg-desktop-portal-wlr.

**Comment by jokeyrhyme** [comment] 2021-03-02 04:17
I tried running the flatpak version in sway, but it wouldn't capture at all, not even the first time

Then I tried running the non-flatpak version in sway (0.9.0-1 in archlinux) and it worked exactly two times and then stopped working

The stdout/err looks like:

```
❯ flameshot
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
```

**Comment by tinywrkb** [comment] 2021-03-02 13:23
> Successive captures fail with the error org.freedesktop.DBus.Error.NoMemory and argument Cannot allocate memory on dbus from org.freedesktop.impl.portal.Screenshot.Screenshot

Looking at this again, it seems like the Close method call is failing and Flameshot is reusing the previous handle/object path.  
The request handle is even kept after closing Flameshot and not being cleaned and can be seen under `org.freedesktop.impl.portal.desktop.wlr`.  

Here's a pcap log displaying the issue, you can use Bustle and I guess also Wireshark to read it.  
[2021-03-02_145629.pcap.tar.gz](https://github.com/flameshot-org/flameshot/files/6068854/2021-03-02_145629.pcap.tar.gz)

**Comment by borgmanJeremy** [comment] 2021-03-02 17:31
Thanks for the detailed log, this will be much easier to investigate with this info.

**Comment by nullobsi** [comment] 2021-03-04 23:23
Hi,

Yes, currently there is an issue with trying to take multiple screenshots (unless you use the patched xdg-desktop-portal-wlr.) While I am not sure about what the proper solution is, the [documentation](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-Request.Close) specifies that when calling the Close() method:
> A Response signal will not be emitted in this case. 

This is the same implementation that xdg-desktop-portal-gtk uses. While this seems racy (and it is,) the proper way is to use the handle from "/org/freedesktop/portal/desktop/request/SENDER/TOKEN" to subscribe to the event before requesting. I don't think the WLR portal properly implements this, however (I faintly remember trying.)

The D-Bus flow right now works like this:

```
// flameshot calls Screenshot
method call sender=flameshot -> destination=org.freedesktop.portal.Desktop path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.Screenshot; member=Screenshot
   string "" // no token (todo?)
   array [
   ] // no options

<xdg-desktop-portal retrieves PID and UID of flameshot>

<xdg-desktop-portal adds watches to the expected object path "/org/freedesktop/portal/desktop/request/1_141/t" on the WLR portal>

<xdg-desktop-portal obtains DBus connection info for wlr portal>

// xdg-desktop-portal checks if a request object exists
method call sender=xdg-desktop-portal -> destination=xdg-desktop-portal-wlr path=/org/freedesktop/portal/desktop/request/1_141/t; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.impl.portal.Request"
error sender=xdg-desktop-portal-wlr -> destination=xdg-desktop-portal "Unknown object '/org/freedesktop/portal/desktop/request/1_141/t'."

// xdg-desktop-portal calls the WLR portal with the expected object path
method call sender=xdg-desktop-portal -> destination=xdg-desktop-portal-wlr path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.Screenshot; member=Screenshot
   object path "/org/freedesktop/portal/desktop/request/1_141/t"
   string "" //app ID
   string "" // window ID
   array [
   ] // no options

// object path is returned to flameshot
method return sender=xdg-desktop-portal -> destination=flameshot
   object path "/org/freedesktop/portal/desktop/request/1_141/t"

<flameshot adds watches to object path on xdg-desktop-portal>

// xdg-desktop-portal-wlr returns the Screenshot call of xdg-desktop-portal with no error
method return sender=xdg-desktop-portal-wlr -> destination=xdg-desktop-portal
   uint32 0
   array [
      dict entry(
         string "uri"
         variant             string "file:///tmp/out.png"
      )
   ]

// signal is sent by the portal
signal sender=xdg-desktop-portal -> destination=flameshot path=/org/freedesktop/portal/desktop/request/1_141/t; interface=org.freedesktop.portal.Request; member=Response
   uint32 0
   array [
      dict entry(
         string "uri"
         variant             string "file:///tmp/out.png"
      )
   ]

<xdg-desktop-portal removes watches>

// flameshot attempts to call Close() which results in an UnknownMethod error (expected)
method call sender=flameshot -> destination=xdg-desktop-portal path=/org/freedesktop/portal/desktop/request/1_141/t; interface=org.freedesktop.portal.Request; member=Close
error time=1614898286.171544 sender=xdg-desktop-portal -> destination=flameshot error_name=org.freedesktop.DBus.Error.UnknownMethod

<flameshot removes watches>
```
It is important to note that flameshot has no knowledge of the wlr portal- all requests are forwarded by xdg-desktop-portal. After this sequence, the object path on the implementation (wlr portal) is never cleared. This can be verified with qdbusviewer. Attempting to take a screenshot results in the following exchange:
```
<sequence follows above until xdg-desktop-portal checks for the object path (which is the same)>
method call sender=xdg-desktop-portal -> destination=xdg-desktop-portal-wlr path=/org/freedesktop/portal/desktop/request/1_141/t; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.freedesktop.impl.portal.Request"
method return sender=xdg-desktop-portal-wlr -> destination=xdg-desktop-portal
   array [
   ] // method returns OK
   
<xdg-desktop-portal calls impl WLR portal with same object path>
// This call results in the impl WLR portal attempting to create another object at the same location:
// 2021/03/04 15:15:18 [ERROR] - dbus: sd_bus_add_object_vtable failed: Unknown error -11

<xdg-desktop-portal returns object path like before>

// xdg-desktop-portal-wlr returns error
error  sender=xdg-desktop-portal-wlr -> destination=xdg-desktop-portal error_name=org.freedesktop.DBus.Error.NoMemory
   string "Cannot allocate memory"
```
I think there are two issues here:
- Flameshot should use a unique token on the call to Screenshot()
- xdg-desktop-portal-wlr should free Request objects when they are no longer in use.

Later, I will do some testing to see if a unique token fixes the issue. :)

**Comment by yuja** [comment] 2021-03-06 06:51
Hi, I'm not sure if this is related, but installing `grim` made flameshot work on Debian sid.
xdg-desktop-portal-wlr executes grim under the hood. If grim isn't installed, execvp would fail and dbus request would end with status=2.
```
Mar  6 15:32:57 lemosa xdg-desktop-portal-wlr[7021]: execvp: No such file or directory
```

Also, launching `flameshot gui` directly didn't work for some reason. Once `flameshot` started in background, `flameshot gui` worked fine.

**Comment by rgrunbla** [comment] 2021-03-13 14:14
Hey, I also have a similar problem. The screenshot only works when flameshot is launched for the first time, and then, if flameshot is already launched, it fails. Here are the messages I get:

```
[remy@typhoon:~]$ flameshot
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()     <- First click, it manages to take a screenshot
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()       <- Later mouse click on the flameshot logo, failures
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by nullobsi** [comment] 2021-03-13 17:27
You will either need to build latest master or use the patched xdpw.

**Comment by tinywrkb** [comment] 2021-03-14 20:10
@nullobsi great work! It is working for me extremely well with an updated Flatpak built from git master.  
Thank you also for the `XDG_CURRENT_DESKTOP` fix, it's also working perfectly.  
I haven't noticed any issue.

**Comment by dmayle** [comment] 2021-03-17 18:15
+subscribe

**Comment by borgmanJeremy** [comment] 2021-03-17 18:18
@dmayle  I think all the work is done if you build from source. It will be released in 0.9.1 this weekend

**Comment by dmayle** [comment] 2021-03-17 18:58
@borgmanJeremy I've just switched to nixos from chromeos and am still learning how to do my own packaging.  (I used to be a longtime Gentoo user, and knew how to build new packages for that, but I've been using a mix of OSX, ChromeOS, and some ubuntu and debian for the last 10 years.)  Once 0.9.1 is picked up, I'll just override my config with that.

**Comment by zajca** [comment] 2021-04-01 13:20
Cheers guys,
I'm having same issue with Sway.
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
I have compile today latest versions from AUR
```
xdg-desktop-portal-wlr 
sway
flameshot
```
But same issue preserve, also try different values for XDG_CURRENT_DESKTOP without luck.

**Comment by nullobsi** [comment] 2021-04-01 15:02
@zajca please read the xdpw wiki page here: https://github.com/emersion/xdg-desktop-portal-wlr/wiki/systemd-user-services,-pam,-and-environment-variables

you need to make sure that when the portal is activated, it gets the wayland display variable and the XDG_CURRENT_DESKTOP variable in its environment

**Comment by zajca** [comment] 2021-04-12 12:04
> @zajca please read the xdpw wiki page here: https://github.com/emersion/xdg-desktop-portal-wlr/wiki/systemd-user-services,-pam,-and-environment-variables
> 
> you need to make sure that when the portal is activated, it gets the wayland display variable and the XDG_CURRENT_DESKTOP variable in its environment

Thanks I did change `Exec=env XDG_CURRENT_DESKTOP=sway sway` it was not working at first, Flameshot did not complain but was stuck, but today I compile latest git and it's working.

**Comment by nagisa** [comment] 2021-04-27 15:24
Somebody mentioned that it doesn't work after the first screenshot. I can reproduce it. I see something along the lines of:

```
2021/04/27 18:20:03 [ERROR] - dbus: sd_bus_add_object_vtable failed: Unknown error -11
```

in the logs of `xdg-desktop-portal-wlr`. Once `flameshot` daemon is restarted I'm allowed to take another screenshot, and after that screenshot I see the error repeat again.

**Comment by nullobsi** [comment] 2021-04-27 15:26
@nagisa , please read the other comments, either use latest flameshot master or use the patched xdpw

**Closed** 2021-09-13 15:43 UTC
Labels: Bug, Linux, Wayland
