### ISSUE TITLE
Flameshot CLI subcommands does not work

### ISSUE THREAD

**Issue by archiif** [flameshot-org/flameshot#2561] opened 2022-04-24 23:04 UTC
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 10.0.19043.1645

### Description

Executing `flameshot` without any arguments works just fine, launching the program. But none of the command line options listed in https://flameshot.org/docs/advanced/commandline-options/ works.
Running `flameshot gui` or any other subcommands simply does nothing, returning a `0` error code.
Even if `flameshot` is not running yet, `flameshot gui` also does nothing.
`flameshot --help` also does nothing.

### Steps to reproduce

1. Run `flameshot`
2. Flameshot launches just fine
3. Run `flameshot gui`
4. Nothing happens

### System Information

Windows 10.0.19043.1645

**Comment by mmahmoudian** [comment] 2022-04-25 04:52
Isn't this duplicate of the following??

- #2554
- #2118

**Comment by borgmanJeremy** [comment] 2022-05-03 02:16
Yes

**Closed by borgmanJeremy** 2022-05-03 02:16 UTC
Labels: Unconfirmed Bug
