### ISSUE TITLE
Upload targets

### ISSUE THREAD

**Issue by theonlydoo** [flameshot-org/flameshot#1288] opened 2021-02-08 09:28 UTC
# This feature request is not related to a problem

Related to https://github.com/flameshot-org/flameshot/issues/45, it'd be nice to have "more than imgur/nextcloud", like dropbox/googledrive/sftp

# Secondary request
Also, an url shortener like bitly/yourls would be nice to make URLs nice again :-)

**Comment by borgmanJeremy** [comment] 2021-02-09 17:40
Close as duplicate of #955

**Closed by borgmanJeremy** 2021-02-09 17:40 UTC
