### ISSUE TITLE
Enter to save image to disk

### ISSUE THREAD

**Issue by madprops** [flameshot-org/flameshot#991] opened 2020-09-26 21:25 UTC
Just an idea: I always want to save the capture to the predefined disk path, I never use the clipboard for this stuff, and I intuitively press Enter expecting it will save it to disk, but I realized I needed ctrl+s. Enter is a lot easier than ctrl+s. Do many people copy captures to clipboard? My suggestion is simply: Maybe Enter should save to disk.

**Comment by borgmanJeremy** [comment] 2020-09-27 00:21
Thanks for the good suggestion. This is a duplicate of #480 . 

I think a rework of the hotkey / config system will be worked on after some other new features. It's not scheduled yet but its on our radar.

**Closed by borgmanJeremy** 2020-09-27 00:21 UTC
