### ISSUE TITLE
Ability to capture full websites/pages or screenshot by scrolling

### ISSUE THREAD

**Issue by erlisdhima** [flameshot-org/flameshot#1735] opened 2021-07-21 12:30 UTC
As far as I know, this is not possible as flameshot would capture the entire screen, and maybe this will need a browser plugin, but wanted to mention what would be the possibilities.

Currently there's an option to capture the entire screen or a selection.
It would be great if you could be able to capture the visible browser windows, or select and scroll, or automatically scroll and capture.

If its not possible to interact with the browser, this would be useful in other scenarios, like if you have a PDF document, and you want to scroll to capture 2 pages for example.

**Comment by mmahmoudian** [comment] 2021-07-22 10:15
Duplicate of #1130

For your immediate use-case, Firefox (fully OpenSource) an Vivaldi (mostly OpenSource) both have the capability of taking screenshot from the full webpage. They are not great, but they are handy enough for the time being until we implement this feature in Flameshot 😃

**Closed** 2021-07-22 10:15 UTC
Labels: Duplicate

**Comment by erlisdhima** [comment] 2021-07-22 11:11
Apologies as I couldn't find the other issue!

Thanks a lot for your feedback! 
I'm using that feature on Firefox for now, but definitely would be wonderful if it was part of Flameshot. :)
