### ISSUE TITLE
Self hosted server for upload screenshot

### ISSUE THREAD

**Issue by mabed-fr** [flameshot-org/flameshot#2960] opened 2022-10-22 10:14 UTC
### Feature Description

Hello,

thank you for your work, this tool makes me much more productive.

Today it is possible to record on its local storage and upload to IMGUR.

Is it possible to add on the roadmap a possibility to overload this destination to send the screens on its own server (lutim, Cherevto, Pictschare)

Thank you for your reply

**Comment by mmahmoudian** [comment] 2022-10-22 15:44
duplicate of all the following:
- #750
- #175
- #45

**Closed by mmahmoudian** 2022-10-22 15:44 UTC
Labels: Enhancement
