### ISSUE TITLE
Could you add the automatic checking windows's box feature

### ISSUE THREAD

**Issue by Jamie-obj** [flameshot-org/flameshot#1814] opened 2021-08-09 09:11 UTC
Just like the Snipaste apps, windows's box automatically detected when press the button of shotcut.

**Comment by mmahmoudian** [comment] 2021-08-09 14:11
Hi @Jamie-obj, thanks for creating this feature request. I didn't understood your feature request. Feel free to also use your own language, as I think some sentences were not translated properly.

**Comment by ZetaoYang** [comment] 2021-08-10 01:31
@mmahmoudian I believe he means automatic window detection. 

This feature has been initially implemented by the original author @lupoDharkael with opencv and has been in the [opencv](https://github.com/flameshot-org/flameshot/tree/opencv) branch, BTW, I tried it on Linux before, it works well. flameshot is a cross-platform application and automatic window detection can be implemented by some features of the platform, such as the win32 API, or by a general-purpose computer vision library, such as opencv. But currently there is no unified top-level design for this yet.

**Comment by borgmanJeremy** [comment] 2021-08-10 20:49
I'd like to implement this with the openCV method rather than native window management. OpenCV will work much better for cross platform.

**Comment by Semnodime** [comment] 2022-01-12 20:28
I just made a quick test myself, using opencv 4.5.5.62 and quick'n'dirty rectangle detection.
I turns out, detecting rectangles is quite easy when they are large, fully observed and also provide plenty of contrast to their background.
As soon as I use dark-themed window managers, choose not to use window borders, disable window shadows etc, the results are poor and algorithmic complexity (and probably resources) to still detect all windows is quite high.

That's why (as much as I love opencv) I recommend the use of external information to cut out the region of interest.
Also, specifying the area to capture beforehand might reduce overhead (relative to capturing the whole screen).

**Comment by Semnodime** [comment] 2022-01-12 20:40
Additionally, making the solution pixel-precise is close to impossible without spending plenty of time working on the algorithm.

**Comment by borgmanJeremy** [comment] 2022-01-12 21:23
My thought was we could use opencv to like help "snap" to the corners. I'm not sure there is any other option unless qt implements it under the hood.

It's not going to be feasible to support this without a platform independent solution.

**Comment by borgmanJeremy** [comment] 2022-07-07 00:56
This is basically a duplicate of #5 and #334

**Closed by borgmanJeremy** 2022-07-07 00:56 UTC
Labels: Enhancement
