### ISSUE TITLE
An option to select capture area across multiple screens on MacOS

### ISSUE THREAD

**Issue by jasonycw** [flameshot-org/flameshot#2779] opened 2022-07-11 03:06 UTC
### Feature Description

On MacOS, when triggering Flameshot, only the screen with mouse on it will be able to be captured, this is not helpful when what I want to screen cap is something on the non active screen.

Also, if something is across multiple screen, there is no way to capture across that.
e.g. Left screen is showing some UI, right screen is showing some debug log
![image](https://user-images.githubusercontent.com/4518597/178181126-88bac6a3-ba0b-4e10-9b96-96bd06037cbf.png)

Ref: https://github.com/flameshot-org/flameshot/issues/2328#issuecomment-1024950462

**Comment by mmahmoudian** [comment] 2022-07-11 03:53
How is this different from #2771 ?

**Comment by jasonycw** [comment] 2022-07-11 04:34
One for the command `flameshot full`
This is for the UX with mouse and shortcut

**Comment by mmahmoudian** [comment] 2022-07-11 04:36
> This is for the UX with mouse and shortcut

Do you mean the `flameshot gui`?

**Comment by jasonycw** [comment] 2022-07-11 04:38
> > This is for the UX with mouse and shortcut
> 
> Do you mean the `flameshot gui`?

Not related to command line

**Comment by mmahmoudian** [comment] 2022-07-11 04:42
Then I'm confused. Please explain more. As far as I can understand this is duplicate of #2771

**Comment by jasonycw** [comment] 2022-07-11 05:21
> Then I'm confused. Please explain more. As far as I can understand this is duplicate of #2771

From https://flameshot.org/docs/advanced/commandline-options/
```
flameshot full
```
This command should do fullscreen capture (no select capture area)
And #2771 is about this command not actually doing fullscreen capture, only single screen with the terminal windows.

This issue on the other hand is not related to any command line or doing fullscreen capture

It's about not able to select capture area across difference screens

**Comment by mmahmoudian** [comment] 2022-07-11 06:34
@jasonycw 

in #2771 it is written:

> The point is not "capturing all screens" but to be able to drag a selected area across all screens.
> e.g. capture like the red section

and in this issue (#2779) you have wrote:

> Also, if something is across multiple screen, there is no way to capture across that.

and to me both of these are exactly the same issue.

**Comment by jasonycw** [comment] 2022-07-11 06:59
> @jasonycw
> 
> in #2771 it is written:
> 
> > The point is not "capturing all screens" but to be able to drag a selected area across all screens.
> > e.g. capture like the red section
> 
> and in this issue (#2779) you have wrote:

Because that's copied from another comment, not the one I originally wrote

> > Also, if something is across multiple screen, there is no way to capture across that.
> 
> and to me both of these are exactly the same issue.

I think #2771 has 2 issues mixed up after editing, I'll help update the original post

**Comment by borgmanJeremy** [comment] 2022-07-12 01:03
I dont think this is possible with the way MacOS handles a full screen application. Even if we capture more than one screen, we cannot display full screen across both monitors.

**Closed by borgmanJeremy** 2022-07-12 01:03 UTC
Labels: Enhancement, Waiting For Info

**Comment by jasonycw** [comment] 2022-07-12 01:47
> I dont think this is possible with the way MacOS handles a full screen application. Even if we capture more than one screen, we cannot display full screen across both monitors.

What about activate flameshot fullscreen on all screens as a start first?

e.g. when activate flameshot capture, all screen will open fullscreen flameshot instead of just the one with the cursor on it

I tried enable "Allow multiple flameshot GUI instances simultaneously"
![image](https://user-images.githubusercontent.com/4518597/178388128-96a8c647-a5e6-41f6-83de-376f97276423.png)
and it seems that still only one screen can open flameshot fullscreen app at a time.
If trigger flameshot on one screen and then trigger flameshot on another screen, the 1st flameshot instance will be turned off.
