### ISSUE TITLE
Populate filename when saving to file

### ISSUE THREAD

**Issue by NukeManDan** [flameshot-org/flameshot#2936] opened 2022-10-05 01:13 UTC
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
linux: 5.19.0-76051900-generic
org.kde.Platform: 5.15-21.08

### Installation Type

Flatpak from Flathub

### Operating System type and version

Pop!_OS 22.04 LTS

### Description

The save modal should be populated with the setting in the gui `Filename Editor` but for me (on Pop!_OS, using the flatpak app) I always must fully specify the name. 

Specifying that a file should be `use fixed path for screenshots to save` does use the right file name, but I cannot have the chance to edit it.

### Steps to reproduce

1. run gui
2. select region
3. `ctrl+s`
4. opens save modal with no name in input field (empty)

### System Information

Pop!_OS 22.04 LTS

**Comment by mmahmoudian** [comment] 2022-10-05 06:14
Would you please provide the content of your config file (`~/.config/flameshot/flameshot.ini`)? I wonder if the issue is due to misconfiguration.

**Comment by borgmanJeremy** [comment] 2022-10-05 19:29
I think this is a duplicate of #2455

**Comment by NukeManDan** [comment] 2022-10-05 20:39
This is a flatpak, so I think you mean `~/.var/app/org.flameshot.Flameshot/config/flameshot.ini` ?

```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x17\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x16\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\x17\0\0\0\xe\0\0\0\f\0\0\0\x11\0\0\0\x14\0\0\0\x15)
contrastOpacity=188
contrastUiColor=#dd2c82
copyAndCloseAfterUpload=false
drawColor=#008000
drawThickness=7
filenamePattern=%F_%I-%M-%S
saveAsFileExtension=png
saveLastRegion=true
savePath={omitted}
savePathFixed=true
showDesktopNotification=false
showSidePanelButton=false
showStartupLaunchMessage=false
uiColor=#a1ea06
uploadClientSecret={omitted}

[Shortcuts]
TYPE_ACCEPT=Return
```

**Comment by mmahmoudian** [comment] 2022-10-06 05:43
I close this in favor of #2455

**Closed** 2022-10-06 05:43 UTC
Labels: Waiting For Info, Unconfirmed Bug
