### ISSUE TITLE
Lost focus selection area while switching tools

### ISSUE THREAD

**Issue by pqnhan** [flameshot-org/flameshot#2468] opened 2022-03-04 03:44 UTC
### Flameshot Version

V11.0.0

### Installation Type

From deb package

### Operating System type and version

Ubuntu Xfce 18.04

### Description

Sometime I've miss out of selection mode while editing, annotating text and moving to another tools with the cursor on the screenshot area.
Maybe by this shortcut?
Please show me how to disable this shortcut option, because as far as I can see it is default and cannot be changed.
Thank you so much!

### Steps to reproduce

1. run flameshot-gui
2. select a region on the primary monitor (i have only one primary monitor)
3. click to add some text to screen capture, and type something, move to another tools and miss out of selection mode.
4. repeat 1 to 3 so many time :| 

### Screenshots or screen recordings

![2022-03-04](https://user-images.githubusercontent.com/24197589/156696575-618a9961-6d29-4a03-b1da-8a17f73333be.gif)
![image](https://user-images.githubusercontent.com/24197589/156695478-b3388bba-13f5-4691-a09e-8fb050450ab0.png)

### System Information

1. Ubuntu Xfce 18.04.
3. I'm using Xorg.

**Comment by mmahmoudian** [comment] 2022-03-04 20:07
About the double click, it is duplicate of #2374 and #2427 which is already solved by #2432

The other one (switching from text tool) is duplicate of all the following
- #2283
- #2353
- #2402
- #2407
- #2429
- #2434
- #2454
- #2458


I would be thankful if you search in issues before creating one. Thank you.

**Closed** 2022-05-01 14:22 UTC
Labels: Bug, Duplicate
