### ISSUE TITLE
Flameshot Interface no longer opening?

### ISSUE THREAD

**Issue by wosym** [flameshot-org/flameshot#3506] opened 2024-02-21 21:49 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 6.5.0-18-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

ubuntu: 22.04

### Description

Normally Clicking "Take Screenshot" allows you to select an area, which then opens an interface that allows modifying or storing the screenshot. This no longer happens. Instead it immediately takes the screenshot. Same happens when clicking "Open launcher".

After the screenshot has been taken, you get the option to select an Area to be screenshotted. However, after selecting, the interface is still not shown.

Is this a deliberate change? Because that would mean a great and unique screenshotting tool has been degraded to what Gnome Screenshot or MS Snipping tool does...

### Steps to reproduce

Try to take screenshot with Flameshot

### System Information

Ubuntu 22.04

dbus-monitor --session sender=org.flameshot.Flameshot
signal time=1708552097.394394 sender=org.freedesktop.DBus -> destination=:1.311 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.311"
signal time=1708552097.394407 sender=org.freedesktop.DBus -> destination=:1.311 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.311"

  *-display                 
       description: VGA compatible controller
       product: NVIDIA Corporation
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: iomemory:fa0-f9f iomemory:fc0-fbf irq:124 memory:fb000000-fbffffff memory:fa00000000-fbffffffff memory:fc00000000-fc01ffffff ioport:f000(size=128) memory:fc000000-fc07ffff
  *-graphics
       product: EFI VGA
       physical id: 1
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=1920,1080

**Comment by mmahmoudian** [comment] 2024-02-21 23:35
Thanks for opening this issue. It would be highly appreciated if next time you provide all the information that is asked from you in the form to avoid guess work. In this particular case, I guess you are new to using GNOME Wayland.


> This no longer happens. Instead it immediately takes the screenshot. Same happens when clicking "Open launcher".

This is explained in our documentation:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

> Is this a deliberate change? Because that would mean a great and unique screenshotting tool has been degraded to what Gnome Screenshot or MS Snipping tool does...

No, this is terrible one-sided sudden decision by Gnome  developers to change their API for Wayland. Personal suggestion: Use a better Desktop Environment like KDE Plasma.


This issue is duplicate of [many issues](https://github.com/flameshot-org/flameshot/issues?q=i-am-asked-to-share-my-screen-every-time). It is also pinned on top of our issue page:

![image](https://github.com/flameshot-org/flameshot/assets/390889/ef9cd1d1-efbb-4f72-bad6-aabf2f21b844)

**Closed by mmahmoudian** 2024-02-21 23:35 UTC
Labels: Unconfirmed Bug

**Comment by wosym** [comment] 2024-02-22 18:53
@mmahmoudian I tried to provide all the information that was asked. Apologies if I failed to do so. I wouldn't say I'm new to Gnome, but it's true that most of the time I work in i3 exclusively. 
However, I've been using this particular (Gnome) machine for the past 2 months, and haven't had any issues. Flameshot works the same as in any other environment I've used it in. What's even more interesting is that today, everything works as before again? I haven't changed any settings nor have I updated Gnome or Flameshot. 

Curious...

Anyways, my appologies for wasting your time. (As it says in the docs)
