### ISSUE TITLE
Suggested enhancements

### ISSUE THREAD

**Issue by Mayurifag** [flameshot-org/flameshot#43] opened 2018-01-03 04:56 UTC
My huge thanks for your development, its super application that works super awesome on my multi-monitor configuration (that was the reason to migrate from screencloud).

However, I'm missing some features:
1) Authorized imgur, — sometimes you want to hide some private screenshots from the internet
2) Would be nice to have configurable hotkeys for making:
- Select area screenshot
- Selected window screenshot
- All the area screenshot (and, maybe, screenshot of monitor where is the active window now)
3) Configurable default delay: sometimes you need it for making screenshot. Simple way here is just a setting in configuration window. But if we would be able to have also duplicated hotkeys to make all the screenshots with delay — that would be very nice. E.g.: selected  area screenshot with `PrntScreen` button and selected area screenshot with configured delay = `Ctrl+PrntScreen` .
4) Next thing is a bit more configurated hotkeys so with a single hotkey and no more clicks you would be able to make a screenshot; have it uploaded to imgur and have an already copied link in your buffer to share it with your friend by pasting it in chat.

Thanks in advance! English is not my native language, so I'm sorry for mistakes done in this text. Hoping everything is understandable 😺

**Comment by ZetaoYang** [comment] 2018-01-04 01:26
global shortcuts/hotkeys @lupoDharkael is processing.
For third one, I add `delay capture and countdown display`.

**Comment by lupoDharkael** [comment] 2018-01-04 15:19
1. I plan to rework the upload tool in future versions as a simple public upload to Imgur is too simple.
2. It will be implemented in 0.7.0 but it could be done before as I did with the support of Windows.
3. in GNU/Linux you can use your desktop to define shortcuts and launch a command, I'd like to make a GUI to generate those commands for non technical users. For windows I want to implement custom global shortcuts inside the app.
4. Sounds interesting. I'll revisit the Idea when I have shortcuts implemented.

**Comment by Mayurifag** [comment] 2018-01-05 12:22
Thanks a lot!

**Comment by Mayurifag** [comment] 2018-01-15 10:56
@lupoDharkael about upload tool to imgur (and possible other services?) — there is no error handeling now. For example, if api server of imgur said that's an internal error somewhere on their side, I have no ability to even retry to upload same picture once again or save it locally to upload in future.

**Comment by averrin** [comment] 2018-01-15 16:09
1. Option for autosave screenshots even it was copy to clipboard
2. Add some "new contributor friendly" issues. Maybe somebody want to help you :wink:

**Comment by victorhck** [comment] 2018-02-13 11:19
+1 to Delay capture settings (very needed IMHO)

**Comment by pboserup** [comment] 2018-02-14 19:36
I would also like to see an autosave function added. Thx.

**Comment by thanhnha1103** [comment] 2018-05-11 09:51
How to input text on the screen shot bros ? I really really want this feature.

**Comment by tuxflo** [comment] 2019-02-15 08:18
Autosave to clipboard would be nice, so that one can bind a shortcut to directly create a screenshot that could be pasted somewhere else.

**Comment by martinandersen3d** [comment] 2019-12-07 14:36
+autosave 

i like to have a folder on the desktop called "screenshots" where images get autosaved to

**Comment by thiemo-taken** [comment] 2020-09-29 22:43
+1 delay on gui (I need to do it with spectale now)

**Comment by borgmanJeremy** [comment] 2020-09-29 23:01
Delay is in the new launcher gui as of 0.8.x.

**Comment by thiemo-taken** [comment] 2020-11-04 12:42
> Delay is in the new launcher gui as of 0.8.x.

thanks

**Comment by mmahmoudian** [comment] 2022-06-12 17:26
I believe all the requested features here are implemented except the following which is duplicate of #334

> Selected window screenshot

@borgmanJeremy shall we close this issue?

**Closed** 2024-04-04 17:26 UTC
Labels: Enhancement
