### ISSUE TITLE
Inapropriate icon on snap

### ISSUE THREAD

**Issue by vozdeckyl** [flameshot-org/flameshot#2568] opened 2022-04-27 20:08 UTC
### Flameshot Version

Flameshot v11.0.0 (03af9d8)
Compiled with Qt 5.12.8

### Installation Type

Compiled from source

### Operating System type and version

Linux

### Description

After saving the screenshot, the information bar that pops up seems to have an inapropriate (missing?) icon.

### Steps to reproduce

1. run `./flameshot gui`
2. select area
3. save screenshot to desktop

### Screenshots or screen recordings

![bug](https://user-images.githubusercontent.com/55758629/165621384-70359566-964c-4684-bdca-8f15dac27b8d.png)

### System Information

1. Ubuntu 20.04.4 x86
2. resolution 1920x1080
3. X11

**Comment by vozdeckyl** [comment] 2022-05-01 00:05
If this argument is replaced with an _absolate_ path to the icon, it will work.
https://github.com/flameshot-org/flameshot/blob/54690d5be8d8b23ff4736bda553e99de1a8bc9a7/src/utils/systemnotification.cpp#L66

**Comment by mmahmoudian** [comment] 2022-05-01 10:06
As far as I know, it should not be replaced with absolute path as many use custom icons, for instance for dark mode.

I have these on my system:
![image](https://user-images.githubusercontent.com/390889/166141282-90dfa3f4-c496-4872-a37e-f5eaf2f8b0a1.png)

I think for some reason you don't have icon packs. I don't know if this is something that can/should be solved by Flameshot. Perhaps @borgmanJeremy and @veracioux have a solution to this.

**Comment by borgmanJeremy** [comment] 2022-05-01 14:18
Yes I agree with @mmahmoudian  especially because you have compiled from source but not run "make install" or installed any other way to the system. The notification is handled by the system, not flameshot, so if the icon is not installed in the notification daemon search path it will not be found.

**Comment by vozdeckyl** [comment] 2022-05-01 15:33
Hi @borgmanJeremy,
I thought that running flameshot that was compiled from a source could be the issue, so I tried installing it via Snap and it has the same issue:

```bash
$ flameshot --version
Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
```

However, when installing the older version via `apt` it the icon is there and it works fine:
```bash
$ flameshot --version
Flameshot 0.6.0+git20191001-2(Debian)
Compiled with Qt 5.12.5
```

Maybe there is something wrong with the snap?

**Comment by vozdeckyl** [comment] 2022-05-01 17:32
Hi @borgmanJeremy, @mmahmoudian,
So to me this looks like snap doesn't install the icons correctly:

1. `sudo apt install flameshot`
2. verify icons installed:
```bash
$ find /usr/share/icons -name flameshot.* -type f
/usr/share/icons/hicolor/48x48/apps/flameshot.png
/usr/share/icons/hicolor/128x128/apps/flameshot.png
/usr/share/icons/hicolor/scalable/apps/flameshot.svg
```
3. and they work:
```bash
$ notify-send -u normal "TEST" "Test" -i flameshot
```

4. `sudo apt remove flameshot`

However, with snap:


6. `snap install flameshot`
7.  icons are missing:
```bash
find /usr/share/icons -name flameshot.* -type f
```
8. and also don't work
```bash
notify-send -u normal "TEST" "Test" -i flameshot
```

Should I create a separate issue for this? Thanks.

**Comment by mmahmoudian** [comment] 2022-05-01 20:57
Seems like compelling evidence. Thank you. I'll reopen this and assign it to myself to see if I can reproduce it in a clean VM.

**Comment by borgmanJeremy** [comment] 2022-05-03 14:30
So snap's CANNOT install the icons outside the confinement, thats the whole purpose of a snap. After some research I'm not sure this is fixable without reworking the notification system to not use d-bus. I'm likely to close this as "won't fix" unless someone can turn up a way to fix resolve this.

**Comment by borgmanJeremy** [comment] 2022-05-03 14:43
My understanding is it is not fixable without reworking our notifications completely.

**Comment by vozdeckyl** [comment] 2022-05-03 14:47
@borgmanJeremy  What about using snap [layouts](https://forum.snapcraft.io/t/snap-layouts/7207)? They can be used to map system folders into the snap folders. Maybe if we map `/usr/share/icons/..` into `$SNAP/usr/share/icons/..` somehow, it might work? Let me investigate.

**Comment by borgmanJeremy** [comment] 2022-05-03 14:58
I think we need to do the opposite. Map the icon from inside the snap to the system.

**Comment by vozdeckyl** [comment] 2022-05-19 20:21
Hi @borgmanJeremy,
I looked into this and you were right: this won't work. The problem is that it's not the application accessing the icon, but the operating system, which gets a message from the application. If it were the app trying to access the icon in `/usr/share/icons/...`, the snap layouts could map this into `$SNAP/usr/share/icons/..`, where the icon could be saved and it would work ok. However, since it's the system and it expects the icon to be in `/usr/share/icons/...`, we'd need to move the icon there, which I believe is not possible in the snap installation as it doesn't have writing permission for system folders.

The only quick work-around I could think of is to replace `flameshot` in the system notification by the absolute path to `$SNAP/usr/share/icons/../flameshot.svg` if the application is run via snap. This is something I mentioned above, but I'm not sure if this solution would be ideal.

**Comment by borgmanJeremy** [comment] 2022-05-19 23:57
What if we make it a compile time string and pass in the alternate value in the snapcraft CI only

**Comment by vozdeckyl** [comment] 2022-05-20 22:38
Hi @borgmanJeremy,
Yes, that would be even better! Let me tackle this.

**Comment by borgmanJeremy** [comment] 2022-05-20 23:19
Will do, let me know if you hit any roadblocks. Always happy to have more contributors :)

**Comment by vozdeckyl** [comment] 2022-05-21 01:16
I tested it and it seems to be working. When testing snapcraft locally, don't forget to change `source` in `snapcraft.yaml` from the github link to ".", otherwise it will just pull the master branch during the build. I spent quite a while on this...

**Closed** 2022-05-23 15:06 UTC
Labels: Bug, Snap
