### ISSUE TITLE
Incorrect position of the magnifier.

### ISSUE THREAD

**Issue by koliberek** [flameshot-org/flameshot#2730] opened 2022-06-29 09:40 UTC
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 10

### Description

With two monitors, the cursor (cross) is on the main screen, and the magnifying glass appears on the other (and magnifies the image from the second screen).

### Steps to reproduce

Setup two monitors on computer with Windows 10
Run Flameshot.
On my setup cross and magnifying glass appear on different montors.

### Screenshots or screen recordings

![1656495313428](https://user-images.githubusercontent.com/4681734/176405024-546e650e-f404-4b28-84c8-a210702aeafb.jpg)

### System Information

![w](https://user-images.githubusercontent.com/4681734/176405360-a4e43992-9d14-4841-9869-f479d837c73c.png)

**Comment by borgmanJeremy** [comment] 2022-06-30 00:30
Duplicate of #2700

**Closed by borgmanJeremy** 2022-06-30 00:30 UTC
Labels: Unconfirmed Bug
