### ISSUE TITLE
Enable command line options in Windows build

### ISSUE THREAD

**Issue by shitchell** [flameshot-org/flameshot#2658] opened 2022-06-12 10:14 UTC
### Feature Description

The Windows *.exe* version of Flameshot doesn't seem to support command line arguments. I use a script in linux for taking an area selection screenshot and then opening it in `feh`. Stupidly simple, but it's one of my most used scripts. I'd _love_ to be able to write something similar for Windows!

**Comment by borgmanJeremy** [comment] 2022-06-13 14:14
Duplicate of #2118

**Closed by borgmanJeremy** 2022-06-13 14:14 UTC
Labels: Enhancement
