### ISSUE TITLE
Location of tool buttons in vertical monitor

### ISSUE THREAD

**Issue by iwijaya2** [flameshot-org/flameshot#1803] opened 2021-08-05 16:44 UTC
Thank you for developing flameshot. It has been my first choice for screenshot tools. There is only a slight inconvenience regarding location of tool buttons in vertical monitor when using rectangular selection. 

**Flameshot version:**
Flameshot v0.8.5-4(Debian)
Compiled with Qt 5.15.2

**Describe the bug:**
When using rectangular selection in vertical monitor, sometime the tool buttons are located inside the selection and block part of the screen we want to capture. The screen resolution is 1920x1080. 

I made a video demonstrating this:
https://youtu.be/jBCl3h3cNpg

**To Reproduce:**
Run flameshot by using `flameshot gui`, then select some area around the middle of 1920x1080 screen.

**Expected behavior:**
Tool buttons are always located outside the selection.

**System Information:**
Distro: Pop!_OS 21.04 (Hirsute) 
Window tiling manager: Xmonad 0.15

**Comment by mmahmoudian** [comment] 2021-08-06 06:49
Duplicate of #1070

**Comment by mmahmoudian** [comment] 2021-08-06 06:51
@iwijaya2 just to make sure, you have more than one monitor and one is vertical and one is horizontal and this only happens on the vertical one. Right?

**Comment by iwijaya2** [comment] 2021-08-06 16:22
Yes, but this does not happen on the first monitor which has resolution of 1600x900.

**Comment by mmahmoudian** [comment] 2021-08-07 16:10
Yes, it always happens on the vertical monitor (check the photos in #1070).

I'll close this now in favour of #1070.

**Closed** 2021-08-07 16:10 UTC
Labels: Duplicate
