### ISSUE TITLE
Duas Telas

### ISSUE THREAD

**Issue by Cleversonchile2018** [flameshot-org/flameshot#1698] opened 2021-07-07 19:41 UTC
Boa tarde equipe, venho utilizando o Flameshot tem um bom tempo é uma ferramenta excelente, mas ao atualizar para versão 0.9.0, notei que ao efetuar um print utilizando dois monitores ele se perde em exibir as ferramentas no momento da captura, na versão anterior 0.8.4 isso não acontece, estou utilizando o Windows 10 Build 19043.1052.

**Comment by mmahmoudian** [comment] 2021-07-07 19:59
English Google translation:

> Good afternoon team, I've been using Flameshot for a long time, it's an excellent tool, but when upgrading to version 0.9.0, I noticed that when performing a print using two monitors, it gets lost in displaying the tools at the time of capture, in the previous version 0.8.4 this does not happen, I am using Windows 10 Build 19043.1052.

**Comment by mmahmoudian** [comment] 2021-07-07 20:10
Is it similar to the pictures in #1522? If so it is a duplicate of #1440

**Comment by Cleversonchile2018** [comment] 2021-07-08 02:53
Yes, it's the same issue the picture.


De: Mehrad Mahmoudian ***@***.***>
Enviada em: quarta-feira, 7 de julho de 2021 17:11
Para: flameshot-org/flameshot ***@***.***>
Cc: Cleversonchile2018 ***@***.***>; Author ***@***.***>
Assunto: Re: [flameshot-org/flameshot] Duas Telas (#1698)


Is it similar to the pictures in #1522<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflameshot-org%2Fflameshot%2Fissues%2F1522&data=04%7C01%7C%7C7d816ef7bb444a00c31408d9418349ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637612854400282950%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7kWVBDdLyyPtRPBmn%2BTDvLocUbDmor52t%2Bd%2BQU6H5kQ%3D&reserved=0>? If so it is a duplicate of #1440<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflameshot-org%2Fflameshot%2Fissues%2F1440&data=04%7C01%7C%7C7d816ef7bb444a00c31408d9418349ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637612854400292938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8fJLcRVntuKBUf9v%2BIPWR85JzGTLukI7HyOWWdX9JT4%3D&reserved=0>

-

**Comment by mmahmoudian** [comment] 2021-07-08 08:23
I close this issue then as it is duplicate of #1440

**Closed by mmahmoudian** 2021-07-08 08:23 UTC
Labels: Duplicate, Unconfirmed Bug, Waiting For Info, Windows
