### ISSUE TITLE
Flameshot not working in Ubuntu 22.04 Wayland

### ISSUE THREAD

**Issue by anandananda** [flameshot-org/flameshot#2659] opened 2022-06-12 11:44 UTC
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-37-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04 with Wayland

### Description

 Here's what happens: * I go to the Gnome "search" screen, type in "flame", the large Flameshot icon appears, I click on it and a very small Flameshot icon appears in my dock, I click on the tiny Flameshot icon and a menu appears, one of the menu items is "Take a Screenshot"", I click on this and nothing happens. How to fix this? Thanks. PS: I do a Ubuntu software update everyday. PS: Flameshot worked fine in 21.10, I didn't have to do anything special for it to work great.

### Steps to reproduce

1. I go to the Gnome "search" screen, 
2. type in "flame", 
3. the large Flameshot icon appears, I click on it and a very small Flameshot icon appears in my dock, 
4. I click on the tiny Flameshot icon and a menu appears, one of the menu items is "Take a Screenshot"", 
5. I click on this and nothing happens.

### System Information

Ubuntu 22.04 
Gnome DE with Wayland
Single monitor on an AMD Ryzen 7 laptop. 1920 * 1080, 144Hz
Frac scaling off

**Comment by mmahmoudian** [comment] 2022-06-12 17:16
Sorry, I answered you [on the other thread](https://github.com/flameshot-org/flameshot/issues/2590#issuecomment-1153235754), but let's continue this issue in this thread that is dedicated to your specific issue. Thank you for filling the details for this bug report.

Please make sure you have installed `xdg-desktop-portal-gnome`:

```sh
sudo apt install xdg-desktop-portal-gnome
```

For the sake of uniformity with other threads, let's have some of the terminology in place (hopefully other users also read this and get their terminology more accurate and we can help them faster):

> a very small Flameshot icon appears in my dock

That area is callsed "system tray" or "systray". It is removed from Gnome for many versions now, but a Gnome shell extension is available to add this feature back. Ubuntu people are including this extension automatically.

> I click on the tiny Flameshot icon and a menu appears

I assume you were right-clicking on the tray icon. Because clicking should trigger taking screenshot

**Comment by mmahmoudian** [comment] 2022-06-14 10:14
@Lathanao I assume you are also so on Ubuntu 22.04

Please make sure you have installed `xdg-desktop-portal-gnome`:

```sh
sudo apt install xdg-desktop-portal-gnome
```

It can be a duplicate of https://github.com/flameshot-org/flameshot/issues/2199

**Comment by Lathanao** [comment] 2022-06-14 12:26
Good! 
Thank you.

**Comment by mmahmoudian** [comment] 2022-06-14 14:59
@Lathanao Do you mean that installing `xdg-desktop-portal-gnome` solved the issue for you?

**Comment by mmahmoudian** [comment] 2022-06-14 15:44
@Lathanao 

> I have the modal with the share button, but don't matter, Flameshot is working well for me.

That is gnome Wayland thing and has nothing to do with flameshot. We have explained it in details on our website. Feel free to take your complaints to Gnome devs as they have forced it to all softwares that is not developed by themselves:

https://flameshot.org/docs/guide/wayland-help/

**Comment by anandananda** [comment] 2022-06-19 00:57
> Please make sure you have installed `xdg-desktop-portal-gnome`:
> It can be a duplicate of #2199

OK, it's now installed. Thanks.

**Comment by mmahmoudian** [comment] 2022-06-19 07:33
@anandananda so does it work now? Is the issue resolved?

**Comment by anandananda** [comment] 2022-06-19 08:35
> @anandananda so does it work now? Is the issue resolved?

Yeah, kinda. I hit 'Take Screenshot' and a window pops up asking if I want to share it with Flameshot. I hit OK and then the Flameshot screenshot tools appear. So it's working, but I have to go thru some extra steps, which is ok.

If it can be made to operate as it did before, that would be great. But for now it's usable. Thanks for the guidance. And thanks for making a really cool app. Flameshot is great. Cheers!

**Comment by mmahmoudian** [comment] 2022-06-19 11:55
> I hit 'Take Screenshot' and a window pops up asking if I want to share it with Flameshot.

That has nothing to do with us. That is a thing that Gnome people forced to all their users. You can read more about it here:
https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

> So it's working, but I have to go thru some extra steps ...
> If it can be made to operate as it did before, that would be great

Please take your rightful complaints to Gnome developers. This is what they decided to do. In linux users have the freedom to choose their software stack. If you don't like that thing in Gnome, you can switch to other Desktop Environments like KDE, Mate, Solus, lxQt, Xfce, ....

> Flameshot is great. Cheers!

We are glad that you are enjoying Flameshot. Thanks for your kind words and thanks for using Flameshot.

**Closed by mmahmoudian** 2022-06-19 11:55 UTC
Labels: Waiting For Info, Unconfirmed Bug

**Comment by D3vil0p3r** [comment] 2022-12-23 01:33
@mmahmoudian I have the same issue on Arch Linux (latest) with GNOME 43 and Wayland (and I use LightDM as Login Manager), but when I click on "Take Screenshot" on the taskbar icon of Flameshot, still nothing happened. I installed `xdg-desktop-portal-gnome` by:
```
sudo pacman -S xdg-desktop-portal-gnome
```
then I logout and login but still not working.

If I run `flameshot gui` I get only:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
I installed Flameshot by `sudo pacman -S flameshot` and its version is:
```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```

**Comment by mmahmoudian** [comment] 2022-12-23 09:02
@D3vil0p3r have you read our Wayland help page?
https://flameshot.org/docs/guide/wayland-help/#can-t-screen-anything-on-wayland-gnome

**Comment by D3vil0p3r** [comment] 2022-12-24 13:37
> @D3vil0p3r have you read our Wayland help page? https://flameshot.org/docs/guide/wayland-help/#can-t-screen-anything-on-wayland-gnome

Hey, by installing `xdg-desktop-portal-gnome` and `xdg-desktop-portal`, it works only if I run `flameshot gui` or other CLI commands. If I click on "Take Screenshot" on top-right tray icon of Flameshot, nothing happens.

**Comment by Lathanao** [comment] 2022-12-26 06:53
One way to solve your problem could be to set this working CLI on a key shortcut.
This is what I did.

![image](https://user-images.githubusercontent.com/6756795/209514331-807a0d2b-9e1a-4c12-8daa-f27e20f9813b.png)

Hope that can help you.

**Comment by D3vil0p3r** [comment] 2022-12-26 12:17
Thank you @Lathanao thank you. Your proposal is a workaround but I reported this last issue for fixing it in case @mmahmoudian confirms and reproduces this issue.

**Comment by mmahmoudian** [comment] 2022-12-30 17:09
@D3vil0p3r I just made a clean install of Arch Gnome (using archinstall and Gnome profile) and then:

```sh
sudo pacman -Syyu
sudo pacman -S flameshot
killall flameshot #just illustrate the daemon is not running
flameshot gui
```

![image](https://user-images.githubusercontent.com/390889/210095561-ea2feb96-719c-48f1-9de1-071d5ad4ce6c.png)

**Comment by D3vil0p3r** [comment] 2022-12-30 17:22
All commands I give by CLI (as `flameshot gui`) are working correctly. I think I see the systray icon because in my GNOME environment I installed AppIndicator Gnome extension: https://extensions.gnome.org/extension/615/appindicator-support/

Maybe it could be worth for investigating for people using Flameshot systray icon by AppIndicator like extensions? What do you think @mmahmoudian ?

**Comment by mmahmoudian** [comment] 2022-12-30 18:19
@D3vil0p3r let me try to give the appindicator a shot and see. Can you also try to create a VM and check it out as well?

**Comment by D3vil0p3r** [comment] 2022-12-30 18:30
> @D3vil0p3r let me try to give the appindicator a shot and see. Can you also try to create a VM and check it out as well?

I have my VM ready. What you need, ask me and I will do.

**Comment by mmahmoudian** [comment] 2023-01-03 15:09
@D3vil0p3r Sorry for the delay in replying, I've been very busy lately. Can you reproduce this issue you have in you VM?

**Comment by D3vil0p3r** [comment] 2023-01-03 17:05
Ok. I installed `flameshot` by pacman in a new and clean Arch Linux VM with GNOME 43.
During the installation, I see this string:
```
Optional dependencies for flameshot
    gnome-shell-extension-appindicator: for system tray icon if you are using Gnome
```
So I think you updated the PKGBUILD by adding `gnome-shell-extension-appindicator` as optional dependency.

After the installation, if I go to the application list and I click on Flameshot icon, then the systray icon appears, I click there with right-click, then I click on "Take Screenshot", nothing happens, then I quit the application from the systray icon, and I get the same I shown here: https://github.com/flameshot-org/flameshot/issues/2659#issuecomment-1364531745

**Comment by mmahmoudian** [comment] 2023-01-09 10:37
@D3vil0p3r 
> So I think you updated the PKGBUILD by adding `gnome-shell-extension-appindicator` as optional dependency.

Well, we do not maintain [the Flameshot package on Arch Community repo](https://archlinux.org/packages/community/x86_64/flameshot/). We only maintain [the AUR package](https://aur.archlinux.org/packages/flameshot-git/).

I also tried and could **not** replicate this issue

[Peek 2023-01-09 12-36.webm](https://user-images.githubusercontent.com/390889/211289180-20847cf8-49ae-4632-84d0-14e63a68af67.webm)

**Comment by D3vil0p3r** [comment] 2023-01-09 10:50
Thank you for the video. I will investigate more

**Comment by D3vil0p3r** [comment] 2023-01-09 14:46
@mmahmoudian ok I did my tests. The issue must not be reproduced as you did in the video. In that way it works correctly.

The issue is then when you enter in Arch Linux, then open the application menu and click on Flameshot icon, like here (I'm using a theme in Arch Linux so the view is different from pure Arch):
![image](https://user-images.githubusercontent.com/83867734/211335009-e4cde0eb-f50f-4597-b575-a79ef68d7e22.png)

If you click in this icon, then you will get a systray icon (as in your video), but it should not work. Indeed, as I explained above, if you open Flameshot by the app icon in my screenshot, the you right-click on the systray icon, and click on Take Screenshot, nothing happens, and if you right-click again on the systray icon and click on Quit, you will get popup errors as desktop notifications.

Let me know if you can reproduce it.
