### ISSUE TITLE
Add Transparency feature to pinned image

### ISSUE THREAD

**Issue by kopach** [flameshot-org/flameshot#2943] opened 2022-10-10 12:01 UTC
### Feature Description

I often use "pin image" functionality to compare things. E.g. web page before and after change. It would be a really great feature to be able to change the transparency level of a pinned image. This way it would be possible to not only compare things side by side, but also by overlaying pinned image over current state and change transparency of pinned image

**Comment by borgmanJeremy** [comment] 2022-10-10 15:04
I like this idea. I have it working mostly but need to add hotkey support. 

Check out this PR if you want to play with it early: https://github.com/flameshot-org/flameshot/pull/2944

**Comment by kopach** [comment] 2022-10-10 20:22
Cool. Awesome. As one of control options, I would recommend holding down some key (e.g. Meta or Control) and use mouse scroll.

**Comment by mmahmoudian** [comment] 2022-10-11 08:01
Duplicate of #2251, but I closed that in favor of this issue to keep the PR number in the same issue.

Also this fits well under the #954 .

> As one of control options, I would recommend holding down some key (e.g. Meta or Control) and use mouse scroll.

In #954 it was suggested by @aurirjr that "Wheel: Zooming. Ctrl+Wheel: Rotation.". I think we should be very careful about choosing the keybinding, because changing it later would cause a lot of backlash, understandably.

We can use
- one or a combination of these modifier keys along with mouse wheel: <kbd>Ctrl</kbd>, <kbd>Alt</kbd>, <kbd>Shift</kbd>
- these keys alone or in combination with the aforementioned modifier keys: <kbd>Tab</kbd>, <kbd>Space</kbd>, <kbd>Enter</kbd>, number keys (risky due to locale settings), letters (risky due to locale settings), <kbd>+</kbd>, and <kbd>-</kbd>

It is ideal to use <kbd>+</kbd> and <kbd>-</kbd> as alternative to scrolling in general. The only drawback is that unlike ISO layout, on the ANSI keyboard layout the <kbd>+</kbd> is triggered with <kbd>Shift</kbd><kbd>=</kbd>. This is the issue regardless of using the QWERTY, Dvorak, or Colemak. To mitigate this, we can accept both <kbd>+</kbd> and <kbd>Shift</kbd><kbd>=</kbd> at the same time.

![image](https://user-images.githubusercontent.com/390889/195031152-83d2cac0-b9f3-4679-85e5-e69395230c7f.png)
<sub>(source: https://commons.wikimedia.org/wiki/File:Qwerty.svg)</sub>

I have no preference on the keybindings.

**Comment by eazyAlf** [comment] 2022-10-11 11:41
Snappy on macos has a feature of pinning screenshots and lowering the opacity via numbers (e.g. 2=20%, 3=30%)

**Comment by borgmanJeremy** [comment] 2022-10-11 20:29
@mmahmoudian  I kind of like the idea of using numbers, what are your thoughts?

**Comment by mmahmoudian** [comment] 2022-10-11 20:43
> @mmahmoudian  I kind of like the idea of using numbers, what are your thoughts?

I actually like the idea and I thought about a version of it before @eazyAlf mentioned it. What I initially thought about was something similar to what we do for tool size (accept a number typed by user in a limited time frame). But then after reading the @eazyAlf comment I thought of a mixed solution:
1. If the user press [0-9] then we multiply that by 10 and set that as opacity percentage (not transparency). With the exception of 0 which will directly translates to 100% opacity.
2. If user wants a fine-grained control, then use a leader key/combination (e.g <kbd>Ctrl</kbd><kbd>u</kbd>), then type the number. This is somewhat Emacs style.

This second point above can be used for resizing, rotating, opacity, and any other modification that might come in the future.

I think the method @eazyAlf mentioned is good for quick use and I very much like it, but not granular enough. What do you think?

**Comment by eazyAlf** [comment] 2022-10-12 10:35
Not sure whats @kopach original use case is 
never needed it more granular than 10% steps and i've been working daily with image comparisons

But I like the way you would solve it @mmahmoudian

**Comment by kopach** [comment] 2022-10-12 17:47
For me personally, `10%` steps should be more than enough.
And as for point `#2` from @mmahmoudian [suggestion](https://github.com/flameshot-org/flameshot/issues/2943#issuecomment-1275253871), I would instead recommend using context menu (right mouse click). Key/combination is hard to discover for new users. And as for context menu - there are already some options. So, we can add one more for transparency and then let user type number (as per @mmahmoudian's suggestion) or even use a slider or both.

Here is a screenshot of current context menu options
![image](https://user-images.githubusercontent.com/8749624/195411511-d87bbbf7-6763-4fc1-9ca6-d742cee8ba18.png)

**Comment by borgmanJeremy** [comment] 2022-10-13 01:08
added 10% hotkeys and 10% to the context menu. I also agree that 10% is reasonable and we don't need anything more granular than that.

**Comment by kopach** [comment] 2022-10-13 08:59
Just tested the feature from a branch - I like it a lot, works like a charm, thanks a lot @borgmanJeremy 
Can't wait for this to be released

**Closed** 2022-10-13 13:19 UTC
Labels: Enhancement
