### ISSUE TITLE
Screenshot copy to clipboard with shortcut not working

### ISSUE THREAD

**Issue by hihabib** [flameshot-org/flameshot#2526] opened 2022-04-05 23:57 UTC
### Flameshot Version

Flameshot v11.0.0

### Installation Type

Flatpak from Github

### Operating System type and version

Zorin OS pro 16.1

### Description

after selecting on screen for taking a screenshot with this command "flameshot gui -p /home/habib/Pictures/screenshots", the keyboard shortcut Ctrl + C for copying screenshot on clipboard is not working. 

### Steps to reproduce

1. run this command "flameshot gui -p /home/$USER/Pictures/"
2. select a region on the monitor
3. press Ctrl + C
and now nothing happend!

### Screenshots or screen recordings

But after pressing Ctrl + C, it should be copy the selected region on clipboard. because by default there is a configuration setting with it.
![image](https://user-images.githubusercontent.com/63936164/161869319-2392753c-ab09-4cd8-92ed-ef187d3aaf3d.png)

### System Information

1. Zorin OS pro 16.1
2.  
![image](https://user-images.githubusercontent.com/63936164/161869425-d629cbb3-9ca7-4846-9ecd-10e9eaa1f211.png)
3. 
![image](https://user-images.githubusercontent.com/63936164/161869642-2335e8b8-54c5-49b2-8343-00b3d6996821.png)
![image](https://user-images.githubusercontent.com/63936164/161869852-46530cc1-6ef4-45f8-b7f4-60ddd16791eb.png)

**Comment by pigsbeforeswine** [comment] 2022-04-06 09:16
FWIW, I had this same issue and was able to resolve it by setting Flameshot to start automatically on startup.

**Comment by veracioux** [comment] 2022-04-06 16:01
@hihabib When you specify an action via the CLI (in your case the `--path` option), the only action you have available in the GUI is "Accept" which is bound to "Enter" by default.

@pigsbeforeswine Flameshot currently requires the daemon to run in order for the clipboard to work on X11. But if dbus is set up properly on your system, the daemon should be launched automatically when you copy to clipboard if it's not running and automatically closed after the clipboard is no longer necessary. The reason why the clipboard doesn't work is probably because the auto-launch mechanism doesn't work on your system.

**Comment by mmahmoudian** [comment] 2022-04-11 09:21
@hihabib @pigsbeforeswine 

This is not a bug, it is briefly explained in the release notes:

> The CLI now supports pinning (`--pin`), uploading (`--upload`), and copying to clipboard (`--clipboard`).
Note that in case one of these options (or `--path`, `--raw` also) is used, an Accept button is shown and the Save, Copy, Upload, Pin, Open With buttons are hidden.

and it has been in detailed explained on our website:

https://flameshot.org/docs/advanced/commandline-options/#final-actions

I encourage you to to have a quick look at the link above to be able to use Flameshot efficiently and enjoy it :)

-------

Additionally, this issue is duplicate of:

- #2275
- #2362
- #2365
- #2431
- #2399
- #2391
- #2370
- #2477
- and potentially many more that I don't have time to search for

So I will close this issue.

**Closed by mmahmoudian** 2022-04-11 09:21 UTC
Labels: question

**Comment by daroczig** [comment] 2022-04-11 09:31
I understand that this new functionality is really powerful, and I welcome that :bow: 

But unfortunately, the old behavior cannot be replicated now, although it has been useful as well. E.g. I have a keyboard shortcut set up to start `flameshot` and I can decide if I want to copy to clipboard (with Ctr+c) or save to disk (with Enter) after adding annotations etc.

Now I need to either define two keyboard shortcuts (one for clipboard, one for file save) and use different shortcuts before adding annotations, or always doing both actions -- which is not ideal (e.g. I have other things in my clipboard and explicitly want to save to file).

I ended up pinning the version of `flameshot` to be `<11.0.0` for now, but I hope this to be a short-term "solution" :) Any chance that the old behavior could be replicated somehow in the new design?

**Comment by mmahmoudian** [comment] 2022-04-11 10:14
@daroczig I don't think this would change anytime soon. But I wonder why don't you use the `flameshot gui` and set the path in your config file? It does **EXACTLY** what you want it to do. the whole point of `--path` is to define a path that is not regularly used for screenshots. if you have a regular place to save your screenshots (e.g for me it is `~/Pictures`), then just set this regular path in your config (`~/.config/flameshot/flameshot.ini`). For example: `savePath=/home/mehrad/Pictures`.

**Comment by daroczig** [comment] 2022-04-11 11:04
Indeed, thank you! The only downside of that (and why I have been using the `-p` flag on the command-line) is that you need to confirm the file name in the destination folder when using the GUI without the `-p` flag. With `-p`, it was saved in that folder in an auto-generated filename. I can live with pressing an extra Enter, though :)

**Comment by daroczig** [comment] 2022-04-11 11:12
How did I miss that? :open_mouth: 

Thank you so much, @mmahmoudian :bow: :100:

**Comment by mmahmoudian** [comment] 2022-04-11 11:16
@daroczig Enjoy taking the screenshots. Perhaps even add some cool screenshot of your [logger](https://cran.r-project.org/web/packages/logger/index.html) from your vignettes (esp. the benchmarks) to your Github repo 😃

**Comment by Atreyagaurav** [comment] 2022-04-18 21:01
@veracioux 

> Flameshot currently requires the daemon to run in order for the clipboard to work on X11. But if dbus is set up properly on your system, the daemon should be launched automatically when you copy to clipboard if it's not running and automatically closed after the clipboard is no longer necessary. The reason why the clipboard doesn't work is probably because the auto-launch mechanism doesn't work on your system.

Would it be possible for it to be added to the readme? Coz it doesn't work on Arch Linux (flameshot installed from pacman) by default, the copy to clipboard does run if the flameshot daemon is run manually.

**Comment by mmahmoudian** [comment] 2022-04-19 04:54
@Atreyagaurav 
> Coz it doesn't work on Arch Linux (flameshot installed from pacman) by default

As far as my tests goes, this is a wrong statement. Have you been able to reproduce this on a clean VM of Arch with a DE?

**Comment by veracioux** [comment] 2022-04-19 08:24
@Atreyagaurav @mmahmoudian If you are running a tiling window manager without a desktop environment, this could be the cause. For example dbus autolaunch doesn't work with i3wm. All the desktop environments I tested with don't have this issue (GNOME, Plasma, Xfce).

**Comment by Atreyagaurav** [comment] 2022-04-19 13:20
Sorry I didn't think about that, yes I do use i3wm without a desktop environment. I still think many people use arch this way so this can be considered something that should be added in the readme, or instructions on Arch linux part though.

**Comment by AndrewVos** [comment] 2022-06-09 07:49
I've been using flameshot for many years without issue. I've used it on bspwm and qtile and i3 and others. All on X. This is definitely something new.

**Comment by mmahmoudian** [comment] 2022-06-09 11:08
@AndrewVos have your read this:
https://flameshot.org/docs/guide/troubleshooting/#in-tiling-window-managers-e-g-i3wm-dwm-bspwm-flameshot-does-not-pin-the-screenshot

**Comment by AndrewVos** [comment] 2022-06-09 14:08
For anyone struggling with this, the only workaround I have found is to do this:

```
flameshot gui --raw | xclip -selection clipboard -target image/png
```

Which of course doesn't show the clipboard/save button anymore...

**Comment by mmahmoudian** [comment] 2022-06-09 16:48
> Which of course doesn't show the clipboard/save button anymore...

That is [intended behavior](https://flameshot.org/docs/advanced/commandline-options/#final-actions).

**Comment by Atreyagaurav** [comment] 2022-06-10 04:04
@AndrewVos 

> flameshot gui --raw | xclip -selection clipboard -target image/png

This is actually a great workaround thank you. I didn't know about the raw option before. 
Before flameshot, I was using this command (using imagemagick) to get the screenshot into clipboard so I could paste it in social media. Since I need most screenshots just to send it immediately.

    import png:- | xclip -selection c -t image/png

I also have a way to save it from the screenshot in clipboard to a file. basically,

    xclip -selection clipboard -type image/png -o > test.png

Will save that image to `test.png` file, I just tested it also works with the clipboard content from ` flameshot gui --raw `, so you could use it if you decide to save it later.

Here is the full script to save screenshot in clipboard if you want:

https://github.com/Atreyagaurav/scripts/blob/main/save-screenshot
