### ISSUE TITLE
[BUG] TLS initialization failed on Windows

### ISSUE THREAD

**Issue by VuzzyM** [flameshot-org/flameshot#1187] opened 2020-12-16 11:33 UTC
I use: Version 0.8.4 - Windows 10.

If I want to load something to imgur, I get this error, please fix.
![image](https://user-images.githubusercontent.com/66425682/102343430-379a2480-3fa3-11eb-8959-c04cd6755189.png)

**Comment by Lontron** [comment] 2020-12-16 11:50
@flameshot-org I solved this problem with the openssl installation here: https://slproweb.com/products/Win32OpenSSL.html

**Comment by Lontron** [comment] 2020-12-16 11:51
@flameshot-org 
The openssl package should be integrated in the next flameshot update, thanks.

**Comment by musm** [comment] 2021-03-10 23:03
Also having this issue

**Comment by mmahmoudian** [comment] 2021-03-11 06:51
@musm  which Flameshot version?

**Comment by musm** [comment] 2021-03-11 07:08
Latest version 0.9.0. I installedn OpenSSL as linked above and it started to work 👍

**Comment by musm** [comment] 2021-03-11 07:10
Sounds like it will be integrated in the next release? That sounds like a good long-term solution to close this out.

**Comment by mmahmoudian** [comment] 2021-03-11 07:11
@ZetaoYang do you think adding this is a good option and straightforward?

**Comment by ZetaoYang** [comment] 2021-03-11 07:21
> @ZetaoYang do you think adding this is a good option and straightforward?

https://github.com/flameshot-org/flameshot/blob/master/src/CMakeLists.txt#L289 The packaging of openssl dlls is already included within CPack.

**Comment by mmahmoudian** [comment] 2021-03-11 07:24
@ZetaoYang then what do you think can cause this problem that is then solved by installing openssl?

**Comment by ZetaoYang** [comment] 2021-03-11 07:41
> @ZetaoYang then what do you think can cause this problem that is then solved by installing openssl?

I tried to download Windows .zip from github release.
v0.8.4 release the win version, v0.8.5 does not(as you know, because of signed certificates problem). Then, we release 0.9.0 Windows version with SignPath digital signature using appveyor CI.

![image](https://user-images.githubusercontent.com/10769951/110751793-539a2300-827f-11eb-8755-ef0706907041.png)

![image](https://user-images.githubusercontent.com/10769951/110751739-3c5b3580-827f-11eb-9234-4e58c253bffb.png)

So, I think this problem has been solved in 0.9.0 and later versions.

**Comment by ZetaoYang** [comment] 2021-03-11 07:48
@mmahmoudian But After install Flameshot-0.9.0-win64.msi, there are still no openssl dlls.  The portable zip includes openssl dlls.

**Comment by ZetaoYang** [comment] 2021-03-11 07:58
0.8.4 .zip doesn't include openssl dlls.
0.8.4 .msi doesn't include openssl dlls.
0.9.0 .zip includes openssl dlls.
0.9.0 .msi doesn't include openssl dlls.

**Comment by ZetaoYang** [comment] 2021-03-11 08:10
@mmahmoudian Starting with 0.9.0, the windows version(.msi and .zip) on the github release now are all packaged from appveyor. I think you should ask @borgmanJeremy for help, I'm not able to check the logs of the packages on flameshot appveyor.

**Comment by borgmanJeremy** [comment] 2021-03-11 14:30
I'll fix this for the patch release 0.9.1 this weekend. Seems that appveyor is not picking up openssl properly.

**Comment by borgmanJeremy** [comment] 2021-03-11 14:31
@ZetaoYang and @mmahmoudian if you PM me your email addresses on the slack I will get you added to the appveyor team.

**Comment by jc-vgermanov** [comment] 2021-04-29 16:06
Still not working!

**Comment by NightMean** [comment] 2021-05-16 21:43
Can confirm, I have the same issue with 0.9.0. Installed **Win64 OpenSSL v1.1.1k Light** version and it started working perfectly.

**Comment by mmahmoudian** [comment] 2021-07-07 20:06
Can this be duplicate of #1031?

**Comment by VuzzyM** [comment] 2021-07-07 21:03
> Can this be duplicate of #1031?

Yes

**Comment by mmahmoudian** [comment] 2021-07-07 22:24
I close this in favour of #1031 then. I also added a note there pointing out that this thread contains some good info.

**Closed by mmahmoudian** 2021-07-07 22:24 UTC
Labels: Bug, Duplicate, Good first issue, Help Wanted, Windows

**Comment by AndreyTka4uk** [comment] 2021-07-14 08:26
> I use: Version 0.8.4 - Windows 10.
> 
> If I want to load something to imgur, I get this error, please fix.
> ![image](https://user-images.githubusercontent.com/66425682/102343430-379a2480-3fa3-11eb-8959-c04cd6755189.png)

2021-07-14 bug still exist
