### ISSUE TITLE
PrtSc button does not work

### ISSUE THREAD

**Issue by DR-3araby** [flameshot-org/flameshot#2611] opened 2022-05-17 18:17 UTC
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

windows: 10

### Description

I've already downloaded the app, it works when clicking on small icon but does not work when I press PrtSc on my keyboard

### System Information

windows: 10

**Comment by mmahmoudian** [comment] 2022-05-17 20:58
Duplicate of #1551

**Closed by mmahmoudian** 2022-05-17 20:58 UTC
Labels: Unconfirmed Bug
