### ISSUE TITLE
Flameshot moves all windows to the centre between monitors when taking a screenshot

### ISSUE THREAD

**Issue by paul9115** [flameshot-org/flameshot#2761] opened 2022-07-04 21:13 UTC
### Flameshot Version

Flameshot v11.0.0 (Qt 5.15.3)

### Installation Type

User repository (AUR)

### Operating System type and version

Arch 5.18.9-arch-1

### Description

When attempting to take a screenshot with the GUI on a multi monitor system, all open windows (and the taskbar) are moved to the centre of the available space (placing them between the two monitors in my case).

The update message and  info panel are placed to the far left monitor going offscreen by approximately 50% 

### Steps to reproduce

1. run flameshot gui 
2. click the taskbar icon to initiate screenshot capture 

### System Information

OS: Arch Linux x86_64 
Resolution: 3840x2160, 3840x2160 
DE: Plasma 5.25.2 
WM: KWin 
GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate 
Xorg

**Comment by paul9115** [comment] 2022-07-04 21:26
I also compiled v12.1.0 and am still seeing the same issue

**Comment by mmahmoudian** [comment] 2022-07-04 22:21
Based on the version number, you didn't install from AUR.

Please provide your monitors arrangements and if you have fractional scaling enabled on any of your monitors.

In general, without proper and correct information, we cannot address the issue.

**Comment by paul9115** [comment] 2022-07-05 17:45
it was installed through AUR via yay. as I mentioned I also compiled the binary directly from the master branch here and experienced the same issues.
On second inspection, it looks like its not pushing everything to the centre, but rather around half a monitor to the left 
https://drive.google.com/file/d/17OjzonaK-yudxVryuFnEh0ex5bTiX7zs/view?usp=sharing

not 100% sure what information you are looking for, but here's the output of xrandr and a screenshot of the settings, I would be happy to provide any additional information you need 
```
xrandr --listactivemonitors
Monitors: 2
 0: +*DP-2 3840/600x2160/340+0+0  DP-2
 1: +DP-0 3840/600x2160/340+3840+0  DP-0
```
![image](https://user-images.githubusercontent.com/32612194/177385850-390c2fa4-e937-4c64-8404-dd8ad99a7915.png)

**Comment by borgmanJeremy** [comment] 2022-07-05 21:48
!fractionalscaling

**Comment by borgmanJeremy** [comment] 2022-07-05 21:49
duplicate of #564

**Closed by borgmanJeremy** 2022-07-05 21:49 UTC
Labels: Waiting For Info, Unconfirmed Bug

**Comment by Soulsender** [comment] 2022-10-26 04:47
just got the same thing on debian, the env variable worked

**Comment by Steppe-Mammoth** [comment] 2024-04-20 22:02
> Flameshot sometimes behaves poorly when systems have fractional scaling set. Some users have reported that setting an environmental variable can help:`export QT_SCREEN_SCALE_FACTORS="1;1"`

dude you best. thx
