### ISSUE TITLE
Hidden first desktop when flameshot started

### ISSUE THREAD

**Issue by nikkorejz** [flameshot-org/flameshot#2924] opened 2022-09-28 14:55 UTC
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)

### Installation Type

Flatpak from Github

### Operating System type and version

macOS 12.3

### Description

Flameshot switch on other desktop when it starts. Couldn't take a screenshot work area

### Steps to reproduce

run flameshot

### Screenshots or screen recordings

Video: https://disk.yandex.ru/i/ZTs3n6I3pkxS1w

### System Information

Apple M1, macOS 12.3
2 External Monitors (2560 * 1440) (Laptop closed)

**Comment by mmahmoudian** [comment] 2022-09-28 18:43
Duplicate of many. Please search closed and open issues before creating a new one. Thanks

Follow the instructions here:

https://flameshot.org/docs/guide/troubleshooting/#all-opened-applications-go-away-and-only-the-blank-desktop-is-visible-for-selection

**Closed by mmahmoudian** 2022-09-28 18:43 UTC
Labels: Unconfirmed Bug
