### ISSUE TITLE
Feature Request: Make text in the «About» window copy-paste-able 

### ISSUE THREAD

**Issue by Semnodime** [flameshot-org/flameshot#2340] opened 2022-01-29 22:38 UTC
### Feature Description

Make text in the About window copy-paste-able to ease submitting bug reports.
![image](https://user-images.githubusercontent.com/19511852/151679805-84876da2-e385-4b7a-8a16-7918e1894ebf.png)

**Comment by borgmanJeremy** [comment] 2022-01-29 22:39
It should be in version 11.

**Comment by mmahmoudian** [comment] 2022-01-30 08:52
Duplicate of #1732

It is already implemented in the latest version of Flameshot

**Closed** 2022-01-30 08:52 UTC
Labels: Enhancement
