### ISSUE TITLE
Region rescaling isn't happening when monitor resolution changes

### ISSUE THREAD

**Issue by opbod** [flameshot-org/flameshot#3179] opened 2023-04-25 16:58 UTC
### Flameshot Version

From the about box:

> Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.22621
windows: 10

In fact it's running on Windows 11.

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11

### Description

Flameshot isn't rescaling the screenshot region when an external monitor is plugged. This happens frequently for mobile/fixed users working with a laptop on various locations (e.g. work and home).

### Steps to reproduce

1. Run flameshot on a laptop with 1920x1080 resolution
2. Plug in external monitor with higher resolution, e.g. 3840x2160, (display #2) set as 'main display'
3. Try to take a screenshot on the main display
4. Observe the presented region on the main display is 1920x1080 which is 4 times too small.
5. Restart flameshot (menu -> quit and then start again)
6. Try to take a screenshot on the main display
7. Observe that the region now is properly set to the main display's resolution

### Screenshots or screen recordings

<img width="740" alt="flameshot1" src="https://user-images.githubusercontent.com/5190820/234348761-e9112c2f-d218-42b7-9878-8f5a37684ae7.png">

### System Information

Windows 11
External Samsung 4K monitor connected via HDMI

**Comment by mmahmoudian** [comment] 2023-04-26 05:22
Duplicate of #2610

**Closed by mmahmoudian** 2023-04-26 05:22 UTC
Labels: Unconfirmed Bug
