### ISSUE TITLE
Pixelate can be read in screenshot when pixelating a single line

### ISSUE THREAD

**Issue by tonytonyistony** [flameshot-org/flameshot#3045] opened 2023-01-05 05:27 UTC
### Flameshot Version

v11.0.0

### Installation Type

apt

### Operating System type and version

Pop_OS 22.04 LTS

### Description

When pixelating a single line of text you can read the text and have to do it twice

### Steps to reproduce

1. Take screenshot
2. pixelate one terminal line
3. You can see the text

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/53504611/210707706-d772e34b-bbfb-4d00-a6f5-e80f1539e8a3.png)

### System Information

1. Pop_OS 22.04 LTS

![image](https://user-images.githubusercontent.com/53504611/210707972-c282b5e5-e855-4f60-9883-e6d9c984745d.png)

2. Gnome, Xorg

**Comment by mmahmoudian** [comment] 2023-01-07 07:50
Well, first thank you for spending time and filling a bug report.

Now, to main business. You are showing blur and not pixelation. Almost every tool in Flameshot has size attribute that use change change it. For example in arrows, you can change the size to make it larger. In square, you can use it to round the corners, and in pixelation tool, you can define how large each pixel should be. You can change the sizes either by scrolling while the tool is selected (when while you are holding down the left click and are in the middle of drawing), or you can select the tool, type the number with your keyboard relatively fast, and then the size indicator will show you that the size is set.

I hope these explanation helps in using Flameshot.

I'm closing this issue now because it is not a bug

**Closed by mmahmoudian** 2023-01-07 07:50 UTC
Labels: Unconfirmed Bug

**Comment by tonytonyistony** [comment] 2023-01-07 07:55
You are absolutely right! Thanks for the clarification, never knew about these settings.

![image](https://user-images.githubusercontent.com/53504611/211140316-8dd17621-5a5d-48ec-8083-d91b0a008bdb.png)

**Comment by mmahmoudian** [comment] 2023-01-07 07:59
@tonytonyistony Flameshot has a very minimal user interface by design, but it is packed with features. Perhaps you will find this link interesting:

https://flameshot.org/docs/guide/key-bindings/

If you like to, you can help us improve the documentation on our website. The repository for our website is in this address:

https://github.com/flameshot-org/flameshot-org.github.io
