### ISSUE TITLE
Flameshot causing total system-freeze on KDE if a Notification Widget is not present

### ISSUE THREAD

**Issue by Gimzie** [flameshot-org/flameshot#723] opened 2020-04-16 08:55 UTC
**Flameshot version**
0.6.0-4 / Latest

**Describe the bug**
When trying to copy a selection to the clipboard, the system completely freezes except for the mouse cursor, which is infinitely stuck trying to make a selection. I'm forced to switch to another TTY shell, from which I have to reboot. (as restarting my display manager proves to not work)

**To Reproduce**
Launch flameshot w/ `flameshot gui`, make a selection, and hit Ctrl + C.

**Expected behavior**
Flameshot copies the selection to the clipboard, as usual.

**System Information**
Manjaro 5.7.0-1 w/ KDE

**Comment by Gimzie** [comment] 2020-04-16 09:05
Update; it seems this only happens if you don't have a notification widget present anywhere in KDE, probably because Flameshot tries to send a notification and ends up hanging. Updated title to reflect this.

**Comment by avindra** [comment] 2020-06-07 21:26
Likely a duplicate of #635

**Comment by borgmanJeremy** [comment] 2021-02-06 01:29
Closed as duplicate. Also a notification widget is a hard requirement at this time.

**Closed** 2021-02-06 01:29 UTC
Labels: Bug, Duplicate
