### ISSUE TITLE
[Debian testing] flameshot: error: The configuration contains an error. Falling back to default.

### ISSUE THREAD

**Issue by darxmurf** [flameshot-org/flameshot#2232] opened 2022-01-06 08:04 UTC
### Flameshot Version

Flameshot 11.0~rc1+ds1-2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux Debian testing - bookworm/sid

### Description

Minor bug after debian update this morning (flameshot:amd64 (0.10.2+ds1-3, 11.0~rc1+ds1-2))
Launching flameshot was throwing: flameshot: error: The configuration contains an error. Falling back to default.
- The process was running
- no icon in panel
- "flameshot gui" was working.

Removing ~/.config/flameshot/flameshot.ini fixed the issue.

### Steps to reproduce

upgrade package from 0.10.2+ds1-3 to 11.0~rc1+ds1-2
launch flameshot (see the error message)
kill the process
remove flameshot.ini file from config dir (ie ~/.config/flameshot/flameshot.ini)
launch flameshot

### System Information

Linux Debian testing (bookworm/sid)
XFCE - Xorg

**Comment by veracioux** [comment] 2022-01-06 13:13
You can open the configuration menu and you'll see a "Show errors" button. Clicking on this button will show you exactly what the error is. Alternatively, you can run `flameshot config --check` for the same effect.

**Comment by darxmurf** [comment] 2022-01-06 13:23
Good to know thanks ! 2 errors then.

> $ flameshot config --check
> flameshot: error: Semantic error in 'drawThickness'. Expected: number >= 1
> flameshot: error: Semantic error in 'setSaveAsFileExtension'. Expected: supported image extension

$ grep -Ei "drawThickness|setSaveAsFileExtension" flameshot.ini
drawThickness=0
setSaveAsFileExtension=JPEG file (*.jpg)

replaced by
drawThickness=1
setSaveAsFileExtension=.jpg

and it works

**Comment by rockstorm101** [comment] 2022-01-06 19:14
Had a very similar issue. I run Debian GNU/Linux bookworm/sid. Flameshot version 11.0~rc1.
```
$ flameshot config --check
flameshot: error: Semantic error in 'setSaveAsFileExtension'. Expected: supported image extension

$ cat .config/flameshot/flameshot.ini | grep 'setSave'
setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)
```
As suggested by @darxmurf, the following change in `flameshot.ini` does the trick:
```
-setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)
+setSaveAsFileExtension=.png
```

**Comment by mmahmoudian** [comment] 2022-01-07 07:37
@darxmurf shall we close this issue?

**Comment by rockstorm101** [comment] 2022-01-07 14:49
> @darxmurf shall we close this issue?

IMHO the issue persists and would require investigating before being formally closed. Please forgive my ignorance of the software but I did not deliberately write "Portable Network Graphic file (PNG) (*.png)" for the `setSaveAsFileExtension` option in the configuration file. However, between flameshot versions 0.10.2 and 0.11.0.rc1 something in the code has changed that triggers the  "The configuration contains an error. Falling back to default." message.

If the option `setSaveAsFileExtension` is new in 11.0.rc1, the code that writes the options and the code that reads them don't agree on what's expected.

If the option `setSaveAsFileExtension` was there in version 0.10.2 and a value such as "Portable Network Graphic file (PNG) (*.png)" was acceptable. This is a regression issue in version 11.0.rc1 cause that value is no longer acceptable.

**Comment by darxmurf** [comment] 2022-01-07 16:35
> > @darxmurf shall we close this issue?
> 
> IMHO the issue persists and would require investigating before being formally closed. Please forgive my ignorance of the software but I did not deliberately write "Portable Network Graphic file (PNG) (*.png)" for the `setSaveAsFileExtension` option in the configuration file. However, between flameshot versions 0.10.2 and 0.11.0.rc1 something in the code has changed that triggers the "The configuration contains an error. Falling back to default." message.
> 
> If the option `setSaveAsFileExtension` is new in 11.0.rc1, the code that writes the options and the code that reads them don't agree on what's expected.
> 
> If the option `setSaveAsFileExtension` was there in version 0.10.2 and a value such as "Portable Network Graphic file (PNG) (*.png)" was acceptable. This is a regression issue in version 11.0.rc1 cause that value is no longer acceptable.

I quite agree.
It looks like there is something wrong in the updater or something changed in the new version.
It should automatically correct the conf file during the update as we did not change anything by hand in there.

**Comment by borgmanJeremy** [comment] 2022-01-07 16:37
I don't like the idea of it "fixing" the issue. The reason is we will forever need to maintain that in the code, and add to it everytime we make a breaking change.

Instead I think we should simply remove the offending line. Thoughts?

**Comment by mmahmoudian** [comment] 2022-01-07 16:57
@rockstorm101  That wrongful png part was added in version 0.10.0 due to a mistake and now in v11 that is is fixed. This **was** (past tense) a bug. Not anymore.

@borgmanJeremy I don't know how comfortable are you with this, but we can add a temporary code to fix this particular issue if it happens. Once we release the v12 we can remove that temp code.

**Comment by borgmanJeremy** [comment] 2022-01-07 17:11
@mmahmoudian i don't think that will be sufficient because many distros skip releases

**Comment by hosiet** [comment] 2022-01-07 17:13
I am wondering whether we should provide a button to **nuke** the user configuration file whenever a config error is detected. This is simple, effective and does not add history extra burden. User may lose their custom config, but this can be made optional (ask before deleting user config file) so they have the choice and do not need to bother with manually fixing the config file.

**Comment by mmahmoudian** [comment] 2022-01-07 17:22
@hosiet that is not necessary as Flameshot already loads with a fallback config which essentially does what you suggest.

**Comment by hosiet** [comment] 2022-01-07 17:25
@mmahmoudian The key issue is that this error keeps showing up unless manually fixed. This will definitely bother users, especially those who have no idea about how to fix the problem.

**Comment by veracioux** [comment] 2022-01-07 19:25
@borgmanJeremy @mmahmoudian @hosiet Currently if the config contains an error we just fall back to defaults across the board. How about we modify the "Config Window -> Show errors" function such that it displays a list of offenders with a checkbox next to each one that says "Reset to default value" (currently it just prints a list of offenders in plain text). Also add a nuke button here as @hosiet suggested.

We should also make the "Show errors/Fix errors" feature more discoverable, because some issues proved that isn't completely the case. I have the following ideas, all of them (potentially) flawed:
- Make the notification say "The configuration contains errors. Click here to see them.". When clicking the notification, open the same dialog that opens when you press "Show errors" in the config window. I don't know if that is possible, because my knowledge is limited about how notifications work. Another problem is, at least on my system (Arch, i3wm, X11), that the flameshot gui obstructs the notification. Does that happen on other systems?
- Make the bottom-right error text that appears when the gui is launched say the same thing and behave the same as the notification. Here the problem is also that the gui might obstruct the dialog that would be launched.
- Make the dialog appear every time the flameshot gui is launched if the config is faulty. This forces the user to fix the config, either manually or by GUI. This is by far the easiest to implement, but it might be annoying to users - though probably less annoying than the alternatives.

**Comment by mmahmoudian** [comment] 2022-01-07 19:59
> How about we modify the "Config Window -> Show errors" function such that it displays a list of offenders with a checkbox next to each one that says "Reset to default value" (currently it just prints a list of offenders in plain text). Also add a nuke button here as @hosiet suggested.

Sounds awesome imho. This would still give enough space to user to learn and also provide fast and quick solution

**Comment by borgmanJeremy** [comment] 2022-01-07 20:12
In my experience so far, we are going to get a billion issues submitted if there is user intervention. Why not just delete the offending line?

**Comment by mmahmoudian** [comment] 2022-01-07 20:16
@borgmanJeremy probably then we will get some bug reports titled "why every time I set this setting it vanishes" 😉

I think part of solution is also in education and documentation.

**Comment by borgmanJeremy** [comment] 2022-01-07 20:21
Well it wont vanish everytime they set it, just once in the migration.

**Comment by veracioux** [comment] 2022-01-07 21:24
@borgmanJeremy 
> In my experience so far, we are going to get a billion issues submitted if there is user intervention. Why not just delete the offending line?

I don't think we will get issues submitted if we tell the user exactly what they have to do, by displaying the popup immediately before the GUI is launched, blocking any features until the user confirms that they want to reset the offending options.

I don't like deleting the offending line because:
1. With the way QSettings works, I don't think it is possible
2. Doing any config-fiddling automatically will annoy users who want to know exactly what is going on with their configs like @mmahmoudian and myself (mainly because of version control but also out of principle)
3. I think it's better to explicitly leave the option explicitly set in the config file. That allows the user to distinguish a truly default option (one that doesn't show up in the config file at all) from one that was defaulted because it contained the error, which is useful if the user wants to change the option to a non-default value afterwards.

**Comment by borgmanJeremy** [comment] 2022-01-08 15:05
Okay, @veracioux sounds like your plan has the best consensus and I support it too.

**Comment by veracioux** [comment] 2022-01-08 15:43
@borgmanJeremy Are we going to include it in the v11 release?

**Comment by borgmanJeremy** [comment] 2022-01-08 15:47
Yeah I think as is we are going to get lots of negative feedback

**Comment by veracioux** [comment] 2022-01-13 15:12
Please test the #2244 pull request with a config that contains an error and tell me if you find the behavior satisfactory.

**Closed** 2022-01-13 22:01 UTC
Labels: Unconfirmed Bug
