### ISSUE TITLE
Unable to use flameshot in Gentoo's Wayland

### ISSUE THREAD

**Issue by jack9603301** [flameshot-org/flameshot#3014] opened 2022-12-11 12:45 UTC
### Flameshot Version

git master

### Installation Type

Compiled from source

### Operating System type and version

gentoo

### Description

Unable to use flameshot in Gentoo's Wayland

output:

```
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.
```

### Steps to reproduce

XDG_CURRENT_DESKTOP=sway flameshot gui

### System Information

OS: Gentoo
WM: Hyprland

**Comment by jack9603301** [comment] 2022-12-11 16:49
It seems to be solved. I have a suggestion. Is it better if the software can directly support wayland protocol screenshot instead of dbus protocol?

**Comment by mmahmoudian** [comment] 2022-12-11 18:51
Duplicate of #2987

**Closed** 2022-12-11 18:52 UTC
Labels: Duplicate, Unconfirmed Bug

**Comment by jack9603301** [comment] 2022-12-12 02:31
@mmahmoudian I will implement wayland adapter
