### ISSUE TITLE
Ctrl+Click on save icon doesn't open save dialog, but it does when the program is activated from tray

### ISSUE THREAD

**Issue by floppy-engineer** [flameshot-org/flameshot#1196] opened 2020-12-22 20:45 UTC
Flameshot process Ctrl+Click on "save" icon differently starting by PrtScr and by clicking on the tray icon.

**Flameshot version**
0.6.0

**Describe the bug**
When I start Flameshot with PrtScr I can't open Save As dialog - Ctrl+Click on save icon just save file to default location without asking.
When I start Flameshot by clicking on its icon in tray, then Ctrl+Click on save icon - I see "Save As" dialog

**To Reproduce**
1. Open flameshot with PrtScr (flameshot call is registered as d-bus call see attach)
2. Ctrl + L.Click on save Icon
3. The sceenshot is saved to a default place

**Expected behavior**
1. Open flameshot with PrtScr 
2. Ctrl + L.Click on save Icon
3. "Save As" dialog is opened

**System Information**
OS: openSUSE 15.1
Plasma version: 5.12.8
KDE Framework: 5.55.0
Qt: 5.9.7
![2020-12-22_23-40](https://user-images.githubusercontent.com/53353094/102932178-d5648680-44b0-11eb-97c0-d31aaf8b8a26.png)

**Comment by floppy-engineer** [comment] 2020-12-22 20:52
Sorry, forget the attachment.
![2020-12-22_23-40](https://user-images.githubusercontent.com/53353094/102932067-ac43f600-44b0-11eb-95d3-59f8e13e020c.png)

**Comment by mmahmoudian** [comment] 2020-12-23 19:18
Would you pleAse try the latest Flameshot version 0.8.5 (or at least a more recent version 0.8.x) and report back if the issue is also there.

You can download the `.rpm` file from [release page](https://github.com/flameshot-org/flameshot/releases/latest)

Alternatively you can get Flameshot through Snap or Flatpak.

**Comment by floppy-engineer** [comment] 2020-12-25 13:27
Sorry, but can't check it properly.
I don't have a clean VM for playing with latest release and Flatpak is not integrated into the system properly (hence I can't check PrtScr behavior)

**Comment by borgmanJeremy** [comment] 2020-12-30 16:57
We are not able to support version 0.6.x any longer so I am going to close this issue for now until it is replication on a release from the 0.8.x series.

**Closed by borgmanJeremy** 2020-12-30 16:57 UTC

**Comment by mmahmoudian** [comment] 2020-12-30 17:06
@floppy-engineer use AppImage. This way you don't need to install anything and not dependent on Flatpak or Snap.
