### ISSUE TITLE
25 second delay between taking a screenshot and being able to use flameshot again or paste the screenshot somewhere

### ISSUE THREAD

**Issue by LeoKira997** [flameshot-org/flameshot#2425] opened 2022-02-15 01:14 UTC
### Version
11.0.0

### Installation Type
flameshot-11.0.0-1.ubuntu-20.04.amd64.deb

### Operating System
Ubuntu 20.04 (Using KDE)

### Description
Regardless of how I use flameshot to take a screenshot (whether it's through a custom shortcut, cli or right clicking the tray icon) there is a 25 second delay between being able to do anything else with flameshot including pasting the copied image. When I run `flameshot gui` in a terminal I noticed it spits out the following.

> QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active

And the cursor is just blinking waiting for whatever to happen before allowing me to run other commands at the end of the 25 seconds.

If I don't take a screenshot at all by pressing the escape key then it will say this at the end of the 25 seconds before allowing me to run other commands.
> flameshot: info: Screenshot aborted.

I noticed this #2398 is actually quite similar to mine except I can still use everything just fine, nothing is locking up, and I noticed the time it was taking for them was roughly the same as mine so I ran `time flameshot gui --clipboard --accept-on-select` myself and this was the output

> real	0m27.084s
user	0m0.370s
sys	0m0.151s

Something is most certainly wrong here. I decided to try closing the terminal to end the program because maybe forcing it to end early will make the problem go away. And it does, sort of. I still can't paste it until the 25 seconds are over but I can take another screenshot...except it has to wait until those 25 seconds are up before it will actually take the screenshot.

Using the previous version, 0.10.2, seems to have a similar issue where saving a screenshot is causing some sort of ~10 second hang where all I can do is move my mouse, the flameshot gui is still up on the screen but unresponsive. I have not used my PC for the last few months until just the other day but I was not having this problem when I was using it so I am pretty sure some update to something is the problem.

Just for the sake of having the information here I also ran `time flameshot gui` while using 0.10.2.

> real	0m0.250s
user	0m0.007s
sys	0m0.000s

The only problem I have with 0.10.2 is the gui hanging for ~10 seconds which based off the time reported I don't think is what's actually happening, unless the time spent hanging somehow isn't factored in. I also tested 11.0.0s AppImage and I have the same problems.

### System Information
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.15.22-xanmod1

**Comment by borgmanJeremy** [comment] 2022-02-15 01:23
Can you please post your screen configuration and resolutions? Can you please also upload your config file?

My two theories are:
1.) Another race condition between notifications and clipboard interactions causing dbus to hang.
2.) A very high resolution is causing a performance issue.

**Comment by LeoKira997** [comment] 2022-02-15 01:36
I am not exactly sure what to post in regards to screen configuration but as for resolutions KInfoCenter says 5760x2160. I have 4 1080p monitors.

Flameshot config file is

> [General]
antialiasingPinZoom=false
contrastOpacity=188
copyAndCloseAfterUpload=false
saveAfterCopy=true
savePath=/home/leokira/Pictures/Screenshots
showDesktopNotification=false
showHelp=false
showSidePanelButton=false
showStartupLaunchMessage=false
startupLaunch=false

**Comment by borgmanJeremy** [comment] 2022-02-15 01:42
Does the performance change if you disable 3 monitors?

**Comment by LeoKira997** [comment] 2022-02-15 01:49
No it does not.

**Comment by mmahmoudian** [comment] 2022-02-15 07:18
I also have one theory: IO traffic 

@LeoKira997 said that they have not used that computer for a while, so something like timeshift or baloo (KDE file indexer) can be running in the background and using a lot if diskIO.

I suggest running `iotop` (a software similar to `top` and `htop` but to monitor the IO) before Flameshot and see if anything is using having a big IO, then run Flameshot and see if the IO changes

**Comment by LeoKira997** [comment] 2022-02-15 08:19
I don't see anything that seems something out of the ordinary. I tried taking a screenshot with Spectacle which comes with KDE and it works perfectly fine but Spectacle doesn't seem to have all the features I need.

**Comment by LeoKira997** [comment] 2022-02-15 08:33
I seem to have fixed it but I don't understand why it's fixed. I had the notifications tray icon set to disabled, I changed it to always shown and flameshot is working normally again. I set it back to disabled and flameshot is still working normally. If you have any idea why this fixed it and why it was a problem I would love to know, if not just close this issue I guess.

**Comment by mmahmoudian** [comment] 2022-02-15 08:52
It seems like an IO problem to me and it getting magically fixed can be because the whatever process was taking a lot of IO is now done doing its job.

Let's do it this way, I close this issue for the time being, but please bookmark the issue and reopen it whenever it comes back. And also please remember to check the IO as it will give us more information of the root cause.

**Closed** 2022-02-15 08:52 UTC

**Comment by MathieuMoalic** [comment] 2022-05-25 13:32
Exact same issue here, and it's not an IO problem. Any other clue ?
Manjaro + KDE as well

**Comment by mmahmoudian** [comment] 2022-05-26 07:15
@MathieuMoalic how many monitors do you have? Are they all connected to the same graphics card? Is your graphics card Nvidia? Are you using a proprietary driver or opensource?

**Comment by MathieuMoalic** [comment] 2022-05-26 07:30
2 monitors, both 1920x1200 (16:10), connected to the same graphics card, an NVIDIA GeForce RTX 3080 Ti. I am using the proprietary Driver Version: 510.73.05.
