### ISSUE TITLE
Gnome41/Wayland, failed to take screenshot

### ISSUE THREAD

**Issue by fovendor** [flameshot-org/flameshot#2049] opened 2021-11-06 12:48 UTC
**Flameshot version**
0.10.1

**Describe the bug**
When trying to take a screenshot, the error "Failed to capture the screen" appears. This error is repeated when changing the keys, when clicking on the program icon in the tray, as well as when calling the flameshot gui command from the terminal.

**To Reproduce**
Calling the program in any way fails on Fedora 35 / Gnome 41 / Wayland.

**Expected behavior**
It is expected that it will be possible to use the program :)

**System Information**
* Installing packages ...
LSB version :: core-4.1-amd64: core-4.1-noarch
Distributor ID: Fedora
Description: Fedora Release 35 (Thirty-five)
Release: 35
Codename: ThirtyFive

****
[Link to bin.snopyta.org](https://bin.snopyta.org/?5bb98e1d11a9f034#Fb4ypusaCPLyYST2f6rdoBe7UgBCy4SKL3M4FJVyohQJ)

**Comment by borgmanJeremy** [comment] 2021-11-06 13:09
Duplicate of #1910

You can test out the nightly builds or wait for version 11 to release.

**Closed by borgmanJeremy** 2021-11-06 13:09 UTC
