### ISSUE TITLE
Freeze after clipboard copy

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#896] opened 2020-09-12 20:26 UTC
**Flameshot version**
master branch

**Describe the bug**
When the Copy tool is clicked the UI freezes for about 1 min

This issue was introduced in #878 

Initial debugging shows it gets stuck in /src/utils/screenshotsaver.cpp Line 49:

```
    SystemNotification().sendMessage(QObject::tr("Capture saved to clipboard"));
```
If the notification is sent BEFORE copying the pixmap it doesn't freeze. If the clipboard copy is commented out, there is no issue. It does not seem to be specifically related to just a delay as I played with QSleep. There seems to be a specific interaction between QClipboard and QDbusInterface.

Another thing to note is BOTH the QDbusInterface constructor and the callWithArgumentList() function are taking a long time. I am running a proper DBus and libnotify service because if the clipboard code is commented out it functions properly. Additionally even though the GUI freezes for a period of time, I eventually get the copied to clipboard notification. 

Probably the same root cause as #635

**Comment by borgmanJeremy** [comment] 2020-09-12 20:33
Initial debugging shows it gets stuck in /src/utils/screenshotsaver.cpp Line 49:

```
    SystemNotification().sendMessage(QObject::tr("Capture saved to clipboard"));
```

**Comment by borgmanJeremy** [comment] 2020-09-12 20:37
If the notification is sent BEFORE copying the pixmap it doesn't freeze

**Comment by borgmanJeremy** [comment] 2020-09-12 20:48
Probably the same root cause as #635

**Comment by borgmanJeremy** [comment] 2020-09-13 01:21
@hosiet Let me know if you can think of any other debugging steps. As a quick fix for 0.8 we can just re-order the function calls, but it makes me uneasy to not understand the root cause of the issue.

**Comment by hosiet** [comment] 2020-09-13 01:27
It's really an interesting bug. Though I don't know the root cause, I am curious about what would happen if those 2 lines are run in different threads (i.e. not blocking the main/UI thread).

**Comment by borgmanJeremy** [comment] 2020-09-13 15:08
#900 fixes the "symptom" but I want to leave this bug open until I can figure out the root cause. #900 is good enough to make a better user experience for the 0.8 release, but I hate these type of unsolved mysteries. 

Running in a different thread is a good idea, I'll try that out when I dig into this again. Clang's thread sanitizer is very unhappy with this application, but that might be a general interaction between thread sanitizer and Qt signals.

**Comment by Toadfield** [comment] 2020-11-07 23:00
I have the same problem.
It worked for me some moths ago,the only really thing I updated was the kernel to 5.9.3-1.
I use Manjaro and installed flameshot from the official repository (flameshot version 0.9.5-1).
@borgmanJeremy In thttps://github.com/flameshot-org/flameshot/pull/900 is that a script that I have to run once and then I can use flameshot normally and being able to update it without using the script everytime,or is it different?

**Comment by borgmanJeremy** [comment] 2020-11-07 23:02
Can you double check your flameshot version? We have never released a 0.9.x

Can you also check if you have close after capture enabled in the configuration?

**Comment by Toadfield** [comment] 2020-11-07 23:29
> Can you double check your flameshot version? We have never released a 0.9.x
Oh,I have 0.8.5-1.
> Can you also check if you have close after capture enabled in the configuration?
I don't have that enabled.

**Comment by Toadfield** [comment] 2020-11-07 23:36
Btw it doesn't work with this fork either:https://github.com/33kk/flameshot

**Comment by borgmanJeremy** [comment] 2020-11-08 02:18
What DE are you using?

**Comment by Toadfield** [comment] 2020-11-08 09:57
kde

**Comment by borgmanJeremy** [comment] 2020-11-12 13:57
@Toadfield Can you open a new issue for your observation? The problem we were discussing seems solved if not understood.

**Comment by Toadfield** [comment] 2020-11-12 19:35
@borgmanJeremy Where is the problem solved?
I mean was there an update or something that fixes that or is the fix to use an older version?

**Comment by borgmanJeremy** [comment] 2020-11-12 20:49
In 0.8.5 I believe it is fixed. The issue was related to the order of the functions.

**Comment by Toadfield** [comment] 2020-11-12 21:05
nice

**Comment by CocaineJohnsson** [comment] 2021-01-12 16:28
At least on my end it is not fixed in version 0.8.5

$ flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.15.1

Running on arch Linux (Kernel 5.10.5-arch1-1, Nvidia proprietary 460.32.03)

`Flameshot gui` followed by a ctrl+c on the selected region freezes for approximately 60 seconds if I don't have a notification daemon running. It completes instantly if I do.

`flameshot screen -c` and `flameshot full -c` work as expected.

**Comment by 33kk** [comment] 2021-03-21 21:07
Guess what i just spent a hour on lol https://github.com/33kk/flameshot/commit/40702e8e351dd2321a9078ee5c70d971003691a8

**Comment by ZerominerBR** [comment] 2021-06-28 14:56
I was having this exact problem of freezing the screen after copying to clipboard.
I have just installed `flameshot-git` from the AUR on Arch Linux and I still suffer from the same issue.

My `flameshot --version`:
```
Flameshot v0.10.0
Compiled with Qt 5.15.2
```

**Comment by jolars** [comment] 2021-11-30 06:49
I have this problem too, on Fedora 35 + i3wm.

**Comment by jolars** [comment] 2021-11-30 06:52
I just figured out this. I was incorrectly running mako as a notification service. Switching to dunst, the problem is now gone.

**Closed** 2021-12-28 18:49 UTC
Labels: Bug, Needs Investigation, Low Priority

**Comment by duongdominhchau** [comment] 2024-06-12 15:54
I got into this same problem today on Arch, flameshot just hangs after capturing when notification daemon is not running. Can we have an error here to guide the user to take correct action? Just a suggestion, I'm not demanding anything.

```plain
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10
```
