### ISSUE TITLE
Select active window?

### ISSUE THREAD

**Issue by soviet-man** [flameshot-org/flameshot#2901] opened 2022-09-06 02:25 UTC
How to make a shot of active window only? Most of times I want to share the view of window of specific app, not full desktop.

`scrot` has corresponding flag and it's a usefull feature.

**Comment by mmahmoudian** [comment] 2022-09-06 04:46
Duplicate of #334

If you are on Xorg you can easily script it yourself. For example I have made a dmenu script to do many things including this one:

https://codeberg.org/mehrad/dmenu_shot

**Closed** 2022-09-06 04:46 UTC
Labels: Duplicate
